/* generated by tur (phase 2) */
#include "tidal__notation.h"

static int64_t nil_hyvalue();
static bool list_hynil_qu(int64_t);
static int64_t cons(int64_t, int64_t);
static int64_t head(int64_t);
static int64_t tail(int64_t);
static void * tidal_hyok(int64_t);
static void * tidal_hyerr(int64_t);
static bool tidal_hyok_qu(void *);
static bool tidal_hyerr_qu(void *);
static int64_t tidal_hyok_hyval(void *);
static int64_t tidal_hyerr_hyval(void *);
static void tidal_hyvoid();
static int64_t tidal_hycstr_hyas_hyint(const char *);
static bool tidal_hycstr_hyeq_qu(const char *, const char *);
static bool tidal_hycstr_hyis_hyrest_qu(const char *);
static double tidal_hyint_hyto_hyfloat(int64_t);
static int64_t tidal_hyfloat_hyto_hyint(double);
static int64_t tidal_hyint_hydiv(int64_t, int64_t);
static int64_t tidal_hyint_hymod(int64_t, int64_t);
static int64_t tidal_hyint_hymax(int64_t, int64_t);
static int64_t tidal_hypat_hyalloc(int64_t);
static void tidal_hypat_hyadd_hychild(int64_t, int64_t, double);
static int64_t tidal_hypat_hykind(int64_t);
static const char * tidal_hypat_hyvalue(int64_t);
static void tidal_hypat_hyset_hyvalue(int64_t, const char *);
static int64_t tidal_hypat_hycount(int64_t);
static int64_t tidal_hypat_hychild(int64_t, int64_t);
static double tidal_hypat_hyweight(int64_t, int64_t);
static double tidal_hypat_hyparam_hyf(int64_t);
static int64_t tidal_hypat_hyparam_hyn(int64_t);
static int64_t tidal_hypat_hyparam_hyk(int64_t);
static void tidal_hypat_hyset_hyparam_hyf(int64_t, double);
static void tidal_hypat_hyset_hyparam_hyn(int64_t, int64_t);
static void tidal_hypat_hyset_hyparam_hyk(int64_t, int64_t);
static double tidal_hypat_hytotal_hyweight(int64_t);
static void tidal_hypat_hyfree_hyraw(int64_t);
static int64_t tidal_hytokenize(const char *);
static int64_t tidal_hytok_hycount(int64_t);
static int64_t tidal_hytok_hytype(int64_t, int64_t);
static const char * tidal_hyttidal_hyok_hyvalue(int64_t, int64_t);
static void tidal_hytok_hyfree(int64_t);
static const char * tidal_hyatom_hybase(const char *);
static int64_t tidal_hyatom_hymod_hytype(const char *);
static int64_t tidal_hyatom_hymod_hyn(const char *);
static int64_t tidal_hyatom_hymod_hyk(const char *);
static double tidal_hyatom_hymod_hyf(const char *);
static void * tidal_hyparse_hyelement(int64_t, int64_t);
static void * tidal_hyparse_hyseq_hybody(int64_t, int64_t, int64_t);
static void * tidal_hyparse_hyalt_hybody(int64_t, int64_t, int64_t);
static void * tidal_hyparse_hyseq(const char *);
static int64_t tidal_hyel_hynew();
static void tidal_hyel_hypush(int64_t, double, double, const char *);
static int64_t tidal_hyel_hycount(int64_t);
static int64_t tidal_hyel_hyget(int64_t, int64_t);
static int64_t tidal_hyel_hyto_hycons(int64_t);
static void tidal_hyel_hyfree_hyall(int64_t);
static void tidal_hyel_hyfree_hystruct(int64_t);
static double tidal_hyev_hyonset(int64_t);
static double tidal_hyev_hydur(int64_t);
static const char * tidal_hyev_hyvalue(int64_t);
static int64_t tidal_hybjorklund(int64_t, int64_t);
static int64_t tidal_hybjorklund_hyget(int64_t, int64_t);
static void tidal_hybjorklund_hyfree(int64_t);
static double tidal_hyrand();
static void tidal_hyeval(int64_t, int64_t, double, double, int64_t);
static double tidal_hychild_hydur(double, double, double);
static double tidal_hyslow_hyfrac(double, double);
static void tidal_hyeval_hyseq_hychildren(int64_t, int64_t, int64_t, double, double, int64_t, int64_t, double);
static void tidal_hyeval_hyrepeat_hysteps(int64_t, int64_t, int64_t, double, double, int64_t, int64_t);
static void tidal_hyeval_hyfast_hysteps(int64_t, int64_t, int64_t, double, double, int64_t, int64_t);
static void tidal_hyeval_hystack_hychildren(int64_t, int64_t, int64_t, double, double, int64_t, int64_t);
static void tidal_hyeval_hyeuclid_hysteps(int64_t, int64_t, int64_t, int64_t, double, double, int64_t, int64_t);
static void tidal_hyeval_hyslow_hyfilter(int64_t, int64_t, double, double, double, double, double, int64_t);
static void tidal_hyeval_hyslow(int64_t, int64_t, double, double, int64_t);
static void tidal_hyeval_hyrev_hybuild(int64_t, int64_t, int64_t, double, double, int64_t);
static void tidal_hyeval_hydegrade_hyfilter(int64_t, int64_t, int64_t, double, int64_t);
static void tur_tidal_eval_impl(int64_t, int64_t, double, double, int64_t);
static int64_t tidal_hyeval_hyto_hycons(int64_t, int64_t);
static void * parse_hynotation(const char *);
static void notation_hyfree(int64_t);
static int64_t pattern_hyevents(int64_t, int64_t);

static int64_t nil_hyvalue() {
        return 0;
  
}

static bool list_hynil_qu(int64_t lst) {
        return lst == 0;
  
}

static int64_t cons(int64_t value, int64_t next) {
        struct { int64_t value; int64_t next; } *cell = malloc(sizeof(*cell));
  cell->value = value; cell->next = next;
  return (int64_t)(intptr_t)cell;
  
}

static int64_t head(int64_t lst) {
        struct { int64_t value; int64_t next; } *cell = (void*)(intptr_t)lst;
  if (!cell) { fprintf(stderr, "head: empty list\n"); exit(1); }
  return cell->value;
  
}

static int64_t tail(int64_t lst) {
        struct { int64_t value; int64_t next; } *cell = (void*)(intptr_t)lst;
  if (!cell) { fprintf(stderr, "tail: empty list\n"); exit(1); }
  return cell->next;
  
}

static void * tidal_hyok(int64_t x) {
        struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = true; r->ok_val = x; r->err_val = 0;
  return (void*)r;
  
}

static void * tidal_hyerr(int64_t e) {
        struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = false; r->ok_val = 0; r->err_val = e;
  return (void*)r;
  
}

static bool tidal_hyok_qu(void * r) {
        struct { bool is_ok; int64_t ok_val; int64_t err_val; } *res = (void*)r;
  return res != NULL && res->is_ok;
  
}

static bool tidal_hyerr_qu(void * r) {
        struct { bool is_ok; int64_t ok_val; int64_t err_val; } *res = (void*)r;
  return res == NULL || !res->is_ok;
  
}

static int64_t tidal_hyok_hyval(void * r) {
        struct { bool is_ok; int64_t ok_val; int64_t err_val; } *res = (void*)r;
  return res->ok_val;
  
}

static int64_t tidal_hyerr_hyval(void * r) {
        struct { bool is_ok; int64_t ok_val; int64_t err_val; } *res = (void*)r;
  return res->err_val;
  
}

static void tidal_hyvoid() {
        return;
  
}

static int64_t tidal_hycstr_hyas_hyint(const char * s) {
        return (int64_t)(intptr_t)s;
  
}

static bool tidal_hycstr_hyeq_qu(const char * a, const char * b) {
        const char *ca = (const char*)(intptr_t)a;
  const char *cb = (const char*)(intptr_t)b;
  if (!ca || !cb) return ca == cb;
  return strcmp(ca, cb) == 0;
  
}

static bool tidal_hycstr_hyis_hyrest_qu(const char * s) {
        const char *str = (const char*)(intptr_t)s;
  return str && strcmp(str, "~") == 0;
  
}

static double tidal_hyint_hyto_hyfloat(int64_t n) {
        return (float)(int)n;
  
}

static int64_t tidal_hyfloat_hyto_hyint(double f) {
        return (int64_t)(int)(double)f;
  
}

static int64_t tidal_hyint_hydiv(int64_t a, int64_t b) {
        if (b <= 0) return 0;
  return (int64_t)((int)a / (int)b);
  
}

static int64_t tidal_hyint_hymod(int64_t a, int64_t b) {
        if (b <= 0) return 0;
  return (int64_t)((int)a % (int)b);
  
}

static int64_t tidal_hyint_hymax(int64_t a, int64_t b) {
        return a > b ? a : b;
  
}

static int64_t tidal_hypat_hyalloc(int64_t kind) {
        typedef struct PatNode {
    int kind; char *value; double param_f; int param_n; int param_k;
    double *weights; struct PatNode **children; int child_count; int child_cap;
  } PatNode;
  PatNode *n = calloc(1, sizeof(PatNode));
  n->kind    = (int)kind;
  n->param_f = 1.0;
  n->child_cap = 4;
  n->children = malloc(4 * sizeof(PatNode*));
  n->weights  = malloc(4 * sizeof(double));
  return (int64_t)(intptr_t)n;
  
}

static void tidal_hypat_hyadd_hychild(int64_t pat, int64_t child, double w) {
        typedef struct PatNode {
    int kind; char *value; double param_f; int param_n; int param_k;
    double *weights; struct PatNode **children; int child_count; int child_cap;
  } PatNode;
  PatNode *n = (PatNode*)(intptr_t)pat;
  if (!n) return;
  if (n->child_count >= n->child_cap) {
    n->child_cap *= 2;
    n->children = realloc(n->children, n->child_cap * sizeof(PatNode*));
    n->weights  = realloc(n->weights,  n->child_cap * sizeof(double));
  }
  n->children[n->child_count] = (PatNode*)(intptr_t)child;
  n->weights[n->child_count]  = (double)w;
  n->child_count++;
  
}

static int64_t tidal_hypat_hykind(int64_t pat) {
        typedef struct { int kind; char *value; double param_f; int param_n; int param_k;
                   double *weights; void **children; int child_count; int child_cap; } PatNode;
  PatNode *n = (PatNode*)(intptr_t)pat;
  return n ? (int64_t)n->kind : 0;
  
}

static const char * tidal_hypat_hyvalue(int64_t pat) {
        typedef struct { int kind; char *value; double param_f; int param_n; int param_k;
                   double *weights; void **children; int child_count; int child_cap; } PatNode;
  PatNode *n = (PatNode*)(intptr_t)pat;
  return (n && n->value) ? n->value : "";
  
}

static void tidal_hypat_hyset_hyvalue(int64_t pat, const char * v) {
        typedef struct { int kind; char *value; double param_f; int param_n; int param_k;
                   double *weights; void **children; int child_count; int child_cap; } PatNode;
  PatNode *n = (PatNode*)(intptr_t)pat;
  if (!n) return;
  free(n->value);
  n->value = v ? strdup((const char*)(intptr_t)v) : NULL;
  
}

static int64_t tidal_hypat_hycount(int64_t pat) {
        typedef struct { int kind; char *value; double param_f; int param_n; int param_k;
                   double *weights; void **children; int child_count; int child_cap; } PatNode;
  PatNode *n = (PatNode*)(intptr_t)pat;
  return n ? (int64_t)n->child_count : 0;
  
}

static int64_t tidal_hypat_hychild(int64_t pat, int64_t i) {
        typedef struct { int kind; char *value; double param_f; int param_n; int param_k;
                   double *weights; void **children; int child_count; int child_cap; } PatNode;
  PatNode *n = (PatNode*)(intptr_t)pat;
  if (!n || (int)i < 0 || (int)i >= n->child_count) return 0;
  return (int64_t)(intptr_t)n->children[(int)i];
  
}

static double tidal_hypat_hyweight(int64_t pat, int64_t i) {
        typedef struct { int kind; char *value; double param_f; int param_n; int param_k;
                   double *weights; void **children; int child_count; int child_cap; } PatNode;
  PatNode *n = (PatNode*)(intptr_t)pat;
  if (!n || (int)i < 0 || (int)i >= n->child_count) return 1.0f;
  return (float)n->weights[(int)i];
  
}

static double tidal_hypat_hyparam_hyf(int64_t pat) {
        typedef struct { int kind; char *value; double param_f; int param_n; int param_k;
                   double *weights; void **children; int child_count; int child_cap; } PatNode;
  PatNode *n = (PatNode*)(intptr_t)pat;
  return n ? (float)n->param_f : 1.0f;
  
}

static int64_t tidal_hypat_hyparam_hyn(int64_t pat) {
        typedef struct { int kind; char *value; double param_f; int param_n; int param_k;
                   double *weights; void **children; int child_count; int child_cap; } PatNode;
  PatNode *n = (PatNode*)(intptr_t)pat;
  return n ? (int64_t)n->param_n : 0;
  
}

static int64_t tidal_hypat_hyparam_hyk(int64_t pat) {
        typedef struct { int kind; char *value; double param_f; int param_n; int param_k;
                   double *weights; void **children; int child_count; int child_cap; } PatNode;
  PatNode *n = (PatNode*)(intptr_t)pat;
  return n ? (int64_t)n->param_k : 0;
  
}

static void tidal_hypat_hyset_hyparam_hyf(int64_t pat, double f) {
        typedef struct { int kind; char *value; double param_f; int param_n; int param_k;
                   double *weights; void **children; int child_count; int child_cap; } PatNode;
  PatNode *n = (PatNode*)(intptr_t)pat;
  if (n) n->param_f = (double)f;
  
}

static void tidal_hypat_hyset_hyparam_hyn(int64_t pat, int64_t v) {
        typedef struct { int kind; char *value; double param_f; int param_n; int param_k;
                   double *weights; void **children; int child_count; int child_cap; } PatNode;
  PatNode *n = (PatNode*)(intptr_t)pat;
  if (n) n->param_n = (int)v;
  
}

static void tidal_hypat_hyset_hyparam_hyk(int64_t pat, int64_t v) {
        typedef struct { int kind; char *value; double param_f; int param_n; int param_k;
                   double *weights; void **children; int child_count; int child_cap; } PatNode;
  PatNode *n = (PatNode*)(intptr_t)pat;
  if (n) n->param_k = (int)v;
  
}

static double tidal_hypat_hytotal_hyweight(int64_t pat) {
        typedef struct { int kind; char *value; double param_f; int param_n; int param_k;
                   double *weights; void **children; int child_count; int child_cap; } PatNode;
  PatNode *n = (PatNode*)(intptr_t)pat;
  if (!n || n->child_count == 0) return 1.0f;
  double total = 0.0;
  for (int i = 0; i < n->child_count; i++) total += n->weights[i];
  return total > 0.0 ? (float)total : (float)n->child_count;
  
}

static void tidal_hypat_hyfree_hyraw(int64_t pat) {
        typedef struct { int kind; char *value; double param_f; int param_n; int param_k;
                   double *weights; void **children; int child_count; int child_cap; } PatNode;
  if (!pat) return;
  struct { int64_t *buf; int len; int cap; } stk;
  stk.cap = 16; stk.len = 0;
  stk.buf = malloc(stk.cap * sizeof(int64_t));
  stk.buf[stk.len++] = (int64_t)pat;
  while (stk.len > 0) {
    int64_t cur = stk.buf[--stk.len];
    PatNode *n = (PatNode*)(intptr_t)cur;
    if (!n) continue;
    for (int i = 0; i < n->child_count; i++) {
      if (stk.len >= stk.cap) {
        stk.cap *= 2;
        stk.buf = realloc(stk.buf, stk.cap * sizeof(int64_t));
      }
      stk.buf[stk.len++] = (int64_t)(intptr_t)n->children[i];
    }
    free(n->value);
    free(n->children);
    free(n->weights);
    free(n);
  }
  free(stk.buf);
  
}

static int64_t tidal_hytokenize(const char * text) {
        typedef struct { int type; char *value; } TidalTok;
  typedef struct { TidalTok *items; int count; int cap; } TokArr;
  const char *src = (const char*)(intptr_t)text;
  if (!src) src = "";
  TokArr *ta = malloc(sizeof(TokArr));
  ta->cap = 16; ta->count = 0;
  ta->items = malloc(ta->cap * sizeof(TidalTok));
  int pos = 0, len = (int)strlen(src);
  while (pos < len) {
    while (pos < len && (src[pos]==' '||src[pos]=='\t'||src[pos]=='\r'||src[pos]=='\n'))
      pos++;
    if (pos >= len) break;
    if (ta->count >= ta->cap) {
      ta->cap *= 2;
      ta->items = realloc(ta->items, ta->cap * sizeof(TidalTok));
    }
    TidalTok *tok = &ta->items[ta->count++];
    char c = src[pos];
    if      (c == '[') { tok->type = 1; tok->value = strdup("["); pos++; }
    else if (c == ']') { tok->type = 2; tok->value = strdup("]"); pos++; }
    else if (c == '<') { tok->type = 3; tok->value = strdup("<"); pos++; }
    else if (c == '>') { tok->type = 4; tok->value = strdup(">"); pos++; }
    else {
      int start = pos;
      while (pos < len && src[pos]!=' ' && src[pos]!='\t' &&
             src[pos]!='\r' && src[pos]!='\n' &&
             src[pos]!='[' && src[pos]!=']' &&
             src[pos]!='<' && src[pos]!='>')
        pos++;
      int n = pos - start;
      tok->type  = 0;
      tok->value = malloc(n + 1);
      memcpy(tok->value, src + start, n);
      tok->value[n] = '\0';
    }
  }
  return (int64_t)(intptr_t)ta;
  
}

static int64_t tidal_hytok_hycount(int64_t ta) {
        typedef struct { void *items; int count; int cap; } TokArr;
  TokArr *t = (TokArr*)(intptr_t)ta;
  return t ? (int64_t)t->count : 0;
  
}

static int64_t tidal_hytok_hytype(int64_t ta, int64_t i) {
        typedef struct { int type; char *value; } TidalTok;
  typedef struct { TidalTok *items; int count; int cap; } TokArr;
  TokArr *t = (TokArr*)(intptr_t)ta;
  if (!t || (int)i < 0 || (int)i >= t->count) return -1;
  return (int64_t)t->items[(int)i].type;
  
}

static const char * tidal_hyttidal_hyok_hyvalue(int64_t ta, int64_t i) {
        typedef struct { int type; char *value; } TidalTok;
  typedef struct { TidalTok *items; int count; int cap; } TokArr;
  TokArr *t = (TokArr*)(intptr_t)ta;
  if (!t || (int)i < 0 || (int)i >= t->count) return "";
  return t->items[(int)i].value ? t->items[(int)i].value : "";
  
}

static void tidal_hytok_hyfree(int64_t ta) {
        typedef struct { int type; char *value; } TidalTok;
  typedef struct { TidalTok *items; int count; int cap; } TokArr;
  TokArr *t = (TokArr*)(intptr_t)ta;
  if (!t) return;
  for (int i = 0; i < t->count; i++) free(t->items[i].value);
  free(t->items);
  free(t);
  
}

static const char * tidal_hyatom_hybase(const char * s) {
        const char *src = (const char*)(intptr_t)s;
  if (!src) return strdup("");
  int i = 0;
  while (src[i] && src[i]!='*' && src[i]!='/' && src[i]!='(' && src[i]!='@') i++;
  char *out = malloc(i + 1);
  memcpy(out, src, i);
  out[i] = '\0';
  return out;
  
}

static int64_t tidal_hyatom_hymod_hytype(const char * s) {
        const char *src = (const char*)(intptr_t)s;
  if (!src) return 0;
  while (*src && *src!='*' && *src!='/' && *src!='(' && *src!='@') src++;
  if (!*src) return 0;
  if (*src == '*') return 1;
  if (*src == '/') return 2;
  if (*src == '(') return 3;
  if (*src == '@') return 4;
  return 0;
  
}

static int64_t tidal_hyatom_hymod_hyn(const char * s) {
        /* For *n: return n. For (n,k): return n. */
  const char *src = (const char*)(intptr_t)s;
  if (!src) return 1;
  while (*src && *src!='*' && *src!='(' ) src++;
  if (!*src) return 1;
  src++;
  return (int64_t)atoi(src);
  
}

static int64_t tidal_hyatom_hymod_hyk(const char * s) {
        /* For (n,k): return k. */
  const char *src = (const char*)(intptr_t)s;
  if (!src) return 1;
  while (*src && *src!='(') src++;
  if (!*src) return 1;
  src++;
  while (*src && *src!=',') src++;
  if (!*src) return 1;
  src++;
  int k = atoi(src);
  return k < 1 ? 1 : (int64_t)k;
  
}

static double tidal_hyatom_hymod_hyf(const char * s) {
        /* For /n: return n as float. For @w: return w. */
  const char *src = (const char*)(intptr_t)s;
  if (!src) return 1.0f;
  while (*src && *src!='/' && *src!='@') src++;
  if (!*src) return 1.0f;
  src++;
  double f = atof(src);
  return f > 0.0 ? (float)f : 1.0f;
  
}

static void * tidal_hyparse_hyelement(int64_t ta, int64_t i) {
        void * __t0;
        if ((i) >= (tidal_hytok_hycount(ta))) {
            __t0 = tidal_hyerr(INT64_C(0));
        } else {
            void * __t1;
            {
                int64_t ttype_143 = tidal_hytok_hytype(ta, i);
                (void)ttype_143;
                void * __t2;
                if ((ttype_143) == (INT64_C(1))) {
                    void * __t3;
                    {
                        int64_t subnode_144 = tidal_hypat_hyalloc(INT64_C(2));
                        (void)subnode_144;
                        void * r_145 = tidal_hyparse_hyseq_hybody(ta, (i) + (INT64_C(1)), subnode_144);
                        (void)r_145;
                        void * __t4;
                        if (tidal_hyerr_qu((void *)(intptr_t)(r_145))) {
                            __t4 = r_145;
                        } else {
                            void * __t5;
                            {
                                int64_t pair_146 = tidal_hyok_hyval((void *)(intptr_t)(r_145));
                                (void)pair_146;
                                int64_t seq_147 = head(pair_146);
                                (void)seq_147;
                                int64_t end_hyi_148 = tail(pair_146);
                                (void)end_hyi_148;
                                int64_t __t6;
                                if ((end_hyi_148) < (tidal_hytok_hycount(ta))) {
                                    int64_t __t7;
                                    if ((tidal_hytok_hytype(ta, end_hyi_148)) == (INT64_C(2))) {
                                        __t7 = (end_hyi_148) + (INT64_C(1));
                                    } else {
                                        __t7 = end_hyi_148;
                                    }
                                    __t6 = __t7;
                                } else {
                                    __t6 = end_hyi_148;
                                }
                                int64_t next_hyi_149 = __t6;
                                (void)next_hyi_149;
                                __t5 = tidal_hyok(cons(seq_147, next_hyi_149));
                            }
                            __t4 = __t5;
                        }
                        __t3 = __t4;
                    }
                    __t2 = __t3;
                } else {
                    void * __t8;
                    if ((ttype_143) == (INT64_C(3))) {
                        void * __t9;
                        {
                            int64_t altnode_150 = tidal_hypat_hyalloc(INT64_C(3));
                            (void)altnode_150;
                            void * r_151 = tidal_hyparse_hyalt_hybody(ta, (i) + (INT64_C(1)), altnode_150);
                            (void)r_151;
                            __t9 = r_151;
                        }
                        __t8 = __t9;
                    } else {
                        void * __t10;
                        {
                            const char * val_152 = tidal_hyttidal_hyok_hyvalue(ta, i);
                            (void)val_152;
                            const char * base_153 = tidal_hyatom_hybase(val_152);
                            (void)base_153;
                            int64_t leaf_154 = tidal_hypat_hyalloc(INT64_C(0));
                            (void)leaf_154;
                            tidal_hypat_hyset_hyvalue(leaf_154, base_153);
                            void * __t11;
                            void * __t12;
                            {
                                int64_t mt_155 = tidal_hyatom_hymod_hytype(val_152);
                                (void)mt_155;
                                void * __t13;
                                if ((mt_155) == (INT64_C(0))) {
                                    __t13 = tidal_hyok(cons(leaf_154, (i) + (INT64_C(1))));
                                } else {
                                    void * __t14;
                                    if ((mt_155) == (INT64_C(1))) {
                                        void * __t15;
                                        {
                                            int64_t n_156 = tidal_hyatom_hymod_hyn(val_152);
                                            (void)n_156;
                                            int64_t rep_157 = tidal_hypat_hyalloc(INT64_C(4));
                                            (void)rep_157;
                                            tidal_hypat_hyset_hyparam_hyn(rep_157, n_156);
                                            tidal_hypat_hyadd_hychild(rep_157, leaf_154, 1.0);
                                            void * __t16;
                                            __t16 = tidal_hyok(cons(rep_157, (i) + (INT64_C(1))));
                                            __t15 = __t16;
                                        }
                                        __t14 = __t15;
                                    } else {
                                        void * __t17;
                                        if ((mt_155) == (INT64_C(2))) {
                                            void * __t18;
                                            {
                                                double f_158 = tidal_hyatom_hymod_hyf(val_152);
                                                (void)f_158;
                                                int64_t sl_159 = tidal_hypat_hyalloc(INT64_C(5));
                                                (void)sl_159;
                                                tidal_hypat_hyset_hyparam_hyf(sl_159, f_158);
                                                tidal_hypat_hyadd_hychild(sl_159, leaf_154, 1.0);
                                                void * __t19;
                                                __t19 = tidal_hyok(cons(sl_159, (i) + (INT64_C(1))));
                                                __t18 = __t19;
                                            }
                                            __t17 = __t18;
                                        } else {
                                            void * __t20;
                                            if ((mt_155) == (INT64_C(3))) {
                                                void * __t21;
                                                {
                                                    int64_t n_160 = tidal_hyatom_hymod_hyn(val_152);
                                                    (void)n_160;
                                                    int64_t k_161 = tidal_hyatom_hymod_hyk(val_152);
                                                    (void)k_161;
                                                    int64_t eu_162 = tidal_hypat_hyalloc(INT64_C(6));
                                                    (void)eu_162;
                                                    tidal_hypat_hyset_hyparam_hyn(eu_162, n_160);
                                                    tidal_hypat_hyset_hyparam_hyk(eu_162, k_161);
                                                    tidal_hypat_hyadd_hychild(eu_162, leaf_154, 1.0);
                                                    void * __t22;
                                                    __t22 = tidal_hyok(cons(eu_162, (i) + (INT64_C(1))));
                                                    __t21 = __t22;
                                                }
                                                __t20 = __t21;
                                            } else {
                                                void * __t23;
                                                {
                                                    double w_163 = tidal_hyatom_hymod_hyf(val_152);
                                                    (void)w_163;
                                                    tidal_hypat_hyset_hyparam_hyf(leaf_154, w_163);
                                                    void * __t24;
                                                    __t24 = tidal_hyok(cons(leaf_154, (i) + (INT64_C(1))));
                                                    __t23 = __t24;
                                                }
                                                __t20 = __t23;
                                            }
                                            __t17 = __t20;
                                        }
                                        __t14 = __t17;
                                    }
                                    __t13 = __t14;
                                }
                                __t12 = __t13;
                            }
                            __t11 = __t12;
                            __t10 = __t11;
                        }
                        __t8 = __t10;
                    }
                    __t2 = __t8;
                }
                __t1 = __t2;
            }
            __t0 = __t1;
        }
        return __t0;
}

static void * tidal_hyparse_hyseq_hybody(int64_t ta, int64_t i, int64_t node) {
        __tur_tailcall:;
        if ((i) >= (tidal_hytok_hycount(ta))) {
            return tidal_hyok(cons(node, i));
        } else {
            {
                int64_t ttype_167 = tidal_hytok_hytype(ta, i);
                (void)ttype_167;
                if ((ttype_167) == (INT64_C(2))) {
                    return tidal_hyok(cons(node, i));
                } else {
                    if ((ttype_167) == (INT64_C(4))) {
                        return tidal_hyok(cons(node, i));
                    } else {
                        {
                            void * r_168 = tidal_hyparse_hyelement(ta, i);
                            (void)r_168;
                            if (tidal_hyerr_qu((void *)(intptr_t)(r_168))) {
                                return r_168;
                            } else {
                                {
                                    int64_t pair_169 = tidal_hyok_hyval((void *)(intptr_t)(r_168));
                                    (void)pair_169;
                                    int64_t child_170 = head(pair_169);
                                    (void)child_170;
                                    int64_t new_hyi_171 = tail(pair_169);
                                    (void)new_hyi_171;
                                    double __t25;
                                    if ((tidal_hypat_hykind(child_170)) == (INT64_C(0))) {
                                        __t25 = tidal_hypat_hyparam_hyf(child_170);
                                    } else {
                                        __t25 = 1.0;
                                    }
                                    double w_172 = __t25;
                                    (void)w_172;
                                    tidal_hypat_hyadd_hychild(node, child_170, w_172);
                                    int64_t __t26 = ta;
                                    int64_t __t27 = new_hyi_171;
                                    int64_t __t28 = node;
                                    ta = __t26;
                                    i = __t27;
                                    node = __t28;
                                    goto __tur_tailcall;
                                }
                            }
                        }
                    }
                }
            }
        }
}

static void * tidal_hyparse_hyalt_hybody(int64_t ta, int64_t i, int64_t node) {
        __tur_tailcall:;
        if ((i) >= (tidal_hytok_hycount(ta))) {
            return tidal_hyok(cons(node, i));
        } else {
            {
                int64_t ttype_176 = tidal_hytok_hytype(ta, i);
                (void)ttype_176;
                if ((ttype_176) == (INT64_C(4))) {
                    return tidal_hyok(cons(node, (i) + (INT64_C(1))));
                } else {
                    {
                        void * r_177 = tidal_hyparse_hyelement(ta, i);
                        (void)r_177;
                        if (tidal_hyerr_qu((void *)(intptr_t)(r_177))) {
                            return r_177;
                        } else {
                            {
                                int64_t pair_178 = tidal_hyok_hyval((void *)(intptr_t)(r_177));
                                (void)pair_178;
                                int64_t child_179 = head(pair_178);
                                (void)child_179;
                                int64_t new_hyi_180 = tail(pair_178);
                                (void)new_hyi_180;
                                tidal_hypat_hyadd_hychild(node, child_179, 1.0);
                                int64_t __t29 = ta;
                                int64_t __t30 = new_hyi_180;
                                int64_t __t31 = node;
                                ta = __t29;
                                i = __t30;
                                node = __t31;
                                goto __tur_tailcall;
                            }
                        }
                    }
                }
            }
        }
}

static void * tidal_hyparse_hyseq(const char * text) {
        void * __t32;
        {
            int64_t ta_182 = tidal_hytokenize(text);
            (void)ta_182;
            int64_t root_183 = tidal_hypat_hyalloc(INT64_C(1));
            (void)root_183;
            void * r_184 = tidal_hyparse_hyseq_hybody(ta_182, INT64_C(0), root_183);
            (void)r_184;
            tidal_hytok_hyfree(ta_182);
            void * __t33;
            void * __t34;
            if (tidal_hyerr_qu((void *)(intptr_t)(r_184))) {
                __t34 = r_184;
            } else {
                __t34 = tidal_hyok(head(tidal_hyok_hyval((void *)(intptr_t)(r_184))));
            }
            __t33 = __t34;
            __t32 = __t33;
        }
        return __t32;
}

static int64_t tidal_hyel_hynew() {
        typedef struct { void **items; int count; int cap; } EventList;
  EventList *el = malloc(sizeof(EventList));
  el->cap = 16; el->count = 0;
  el->items = malloc(16 * sizeof(void*));
  return (int64_t)(intptr_t)el;
  
}

static void tidal_hyel_hypush(int64_t el, double onset, double dur, const char * value) {
        typedef struct { double onset; double dur; char *value; } TidalEvent;
  typedef struct { void **items; int count; int cap; } EventList;
  EventList *e = (EventList*)(intptr_t)el;
  if (!e) return;
  if (e->count >= e->cap) {
    e->cap *= 2;
    e->items = realloc(e->items, e->cap * sizeof(void*));
  }
  TidalEvent *ev = malloc(sizeof(TidalEvent));
  ev->onset = (double)onset;
  ev->dur   = (double)dur;
  const char *v = (const char*)(intptr_t)value;
  ev->value = v ? strdup(v) : strdup("");
  e->items[e->count++] = ev;
  
}

static int64_t tidal_hyel_hycount(int64_t el) {
        typedef struct { void **items; int count; int cap; } EventList;
  EventList *e = (EventList*)(intptr_t)el;
  return e ? (int64_t)e->count : 0;
  
}

static int64_t tidal_hyel_hyget(int64_t el, int64_t i) {
        typedef struct { void **items; int count; int cap; } EventList;
  EventList *e = (EventList*)(intptr_t)el;
  if (!e || (int)i < 0 || (int)i >= e->count) return 0;
  return (int64_t)(intptr_t)e->items[(int)i];
  
}

static int64_t tidal_hyel_hyto_hycons(int64_t el) {
        typedef struct { void **items; int count; int cap; } EventList;
  typedef struct { int64_t value; int64_t next; } ConsCell;
  EventList *e = (EventList*)(intptr_t)el;
  if (!e) return 0;
  int64_t lst = 0;
  for (int i = e->count - 1; i >= 0; i--) {
    ConsCell *cell = malloc(sizeof(ConsCell));
    cell->value = (int64_t)(intptr_t)e->items[i];
    cell->next  = lst;
    lst = (int64_t)(intptr_t)cell;
  }
  return lst;
  
}

static void tidal_hyel_hyfree_hyall(int64_t el) {
        typedef struct { double onset; double dur; char *value; } TidalEvent;
  typedef struct { void **items; int count; int cap; } EventList;
  EventList *e = (EventList*)(intptr_t)el;
  if (!e) return;
  for (int i = 0; i < e->count; i++) {
    TidalEvent *ev = (TidalEvent*)e->items[i];
    if (ev) { free(ev->value); free(ev); }
  }
  free(e->items);
  free(e);
  
}

static void tidal_hyel_hyfree_hystruct(int64_t el) {
        typedef struct { void **items; int count; int cap; } EventList;
  EventList *e = (EventList*)(intptr_t)el;
  if (!e) return;
  free(e->items);
  free(e);
  
}

static double tidal_hyev_hyonset(int64_t e) {
        typedef struct { double onset; double dur; char *value; } TidalEvent;
  TidalEvent *ev = (TidalEvent*)(intptr_t)e;
  return ev ? (float)ev->onset : 0.0f;
  
}

static double tidal_hyev_hydur(int64_t e) {
        typedef struct { double onset; double dur; char *value; } TidalEvent;
  TidalEvent *ev = (TidalEvent*)(intptr_t)e;
  return ev ? (float)ev->dur : 0.0f;
  
}

static const char * tidal_hyev_hyvalue(int64_t e) {
        typedef struct { double onset; double dur; char *value; } TidalEvent;
  TidalEvent *ev = (TidalEvent*)(intptr_t)e;
  return (ev && ev->value) ? ev->value : "";
  
}

static int64_t tidal_hybjorklund(int64_t n, int64_t k) {
        int ni = (int)n, ki = (int)k;
  if (ki <= 0) ki = 1;
  int *out = calloc(ki, sizeof(int));
  if (ni <= 0) return (int64_t)(intptr_t)out;
  if (ni >= ki) { for (int i = 0; i < ki; i++) out[i] = 1; return (int64_t)(intptr_t)out; }
  /* Bresenham-style Euclidean distribution */
  int error = 0;
  for (int i = 0; i < ki; i++) {
    error += ni;
    if (error >= ki) { out[i] = 1; error -= ki; }
  }
  return (int64_t)(intptr_t)out;
  
}

static int64_t tidal_hybjorklund_hyget(int64_t arr, int64_t i) {
        int *a = (int*)(intptr_t)arr;
  return a ? (int64_t)a[(int)i] : 0;
  
}

static void tidal_hybjorklund_hyfree(int64_t arr) {
        free((void*)(intptr_t)arr);
  
}

static double tidal_hyrand() {
        return (float)rand() / (float)(RAND_MAX > 0 ? RAND_MAX : 1);
  
}

static void tidal_hyeval(int64_t pat, int64_t cycle, double onset, double dur, int64_t el) {
        tur_tidal_eval_impl(pat, cycle, onset, dur, el);
  
}

static double tidal_hychild_hydur(double dur, double w, double total_w) {
        return (float)((double)dur * ((double)w / (double)total_w));
  
}

static double tidal_hyslow_hyfrac(double r, double fa) {
        return (float)((double)r / (double)fa);
  
}

static void tidal_hyeval_hyseq_hychildren(int64_t pat, int64_t n, int64_t cycle, double onset, double dur, int64_t i, int64_t el, double total_w) {
        if ((i) >= (n)) {
            tidal_hyvoid();
        } else {
            {
                int64_t child_221 = tidal_hypat_hychild(pat, i);
                (void)child_221;
                double w_222 = tidal_hypat_hyweight(pat, i);
                (void)w_222;
                double child_hydur_223 = tidal_hychild_hydur(dur, w_222, total_w);
                (void)child_hydur_223;
                tidal_hyeval(child_221, cycle, onset, child_hydur_223, el);
                tidal_hyeval_hyseq_hychildren(pat, n, cycle, (onset) + (child_hydur_223), dur, (i) + (INT64_C(1)), el, total_w);
            }
        }
}

static void tidal_hyeval_hyrepeat_hysteps(int64_t child, int64_t n, int64_t cycle, double onset, double step_dur, int64_t i, int64_t el) {
        if ((i) >= (n)) {
            tidal_hyvoid();
        } else {
            tidal_hyeval(child, cycle, onset, step_dur, el);
            tidal_hyeval_hyrepeat_hysteps(child, n, cycle, (onset) + (step_dur), step_dur, (i) + (INT64_C(1)), el);
        }
}

static void tidal_hyeval_hyfast_hysteps(int64_t child, int64_t fi, int64_t cycle, double onset, double step_dur, int64_t i, int64_t el) {
        if ((i) >= (fi)) {
            tidal_hyvoid();
        } else {
            tidal_hyeval(child, ((cycle) * (fi)) + (i), onset, step_dur, el);
            tidal_hyeval_hyfast_hysteps(child, fi, cycle, (onset) + (step_dur), step_dur, (i) + (INT64_C(1)), el);
        }
}

static void tidal_hyeval_hystack_hychildren(int64_t pat, int64_t n, int64_t cycle, double onset, double dur, int64_t i, int64_t el) {
        if ((i) >= (n)) {
            tidal_hyvoid();
        } else {
            tidal_hyeval(tidal_hypat_hychild(pat, i), cycle, onset, dur, el);
            tidal_hyeval_hystack_hychildren(pat, n, cycle, onset, dur, (i) + (INT64_C(1)), el);
        }
}

static void tidal_hyeval_hyeuclid_hysteps(int64_t child, int64_t pulses, int64_t k, int64_t cycle, double onset, double step_dur, int64_t i, int64_t el) {
        if ((i) >= (k)) {
            tidal_hybjorklund_hyfree(pulses);
        } else {
            if ((tidal_hybjorklund_hyget(pulses, i)) == (INT64_C(1))) {
                tidal_hyeval(child, cycle, onset, step_dur, el);
            } else {
                tidal_hyvoid();
            }
            tidal_hyeval_hyeuclid_hysteps(child, pulses, k, cycle, (onset) + (step_dur), step_dur, (i) + (INT64_C(1)), el);
        }
}

static void tidal_hyeval_hyslow_hyfilter(int64_t temp_el, int64_t i, double frac, double frac_end, double onset, double dur, double factor, int64_t el) {
        if ((i) >= (tidal_hyel_hycount(temp_el))) {
            tidal_hyvoid();
        } else {
            {
                int64_t ev_261 = tidal_hyel_hyget(temp_el, i);
                (void)ev_261;
                double eo_262 = tidal_hyev_hyonset(ev_261);
                (void)eo_262;
                double ed_263 = tidal_hyev_hydur(ev_261);
                (void)ed_263;
                const char * val_264 = tidal_hyev_hyvalue(ev_261);
                (void)val_264;
                bool __t35;
                if ((eo_262) >= (frac)) {
                    __t35 = (eo_262) < (frac_end);
                } else {
                    __t35 = false;
                }
                bool in_hywin_265 = __t35;
                (void)in_hywin_265;
                if (in_hywin_265) {
                    {
                        double rel_hystart_266 = ((eo_262) - (frac)) * (factor);
                        (void)rel_hystart_266;
                        double rel_hydur_267 = (ed_263) * (factor);
                        (void)rel_hydur_267;
                        tidal_hyel_hypush(el, (onset) + ((rel_hystart_266) * (dur)), (rel_hydur_267) * (dur), val_264);
                    }
                } else {
                    tidal_hyvoid();
                }
                tidal_hyeval_hyslow_hyfilter(temp_el, (i) + (INT64_C(1)), frac, frac_end, onset, dur, factor, el);
            }
        }
}

static void tidal_hyeval_hyslow(int64_t pat, int64_t cycle, double onset, double dur, int64_t el) {
        {
            double f_273 = tidal_hypat_hyparam_hyf(pat);
            (void)f_273;
            int64_t fi_274 = tidal_hyint_hymax(tidal_hyfloat_hyto_hyint(f_273), INT64_C(1));
            (void)fi_274;
            double fac_275 = tidal_hyint_hyto_hyfloat(fi_274);
            (void)fac_275;
            int64_t rem_276 = tidal_hyint_hymod(cycle, fi_274);
            (void)rem_276;
            int64_t child_277 = tidal_hypat_hychild(pat, INT64_C(0));
            (void)child_277;
            double frac_278 = tidal_hyslow_hyfrac(tidal_hyint_hyto_hyfloat(rem_276), fac_275);
            (void)frac_278;
            double frac_hyend_279 = (frac_278) + (((fac_275) ? ((1.0) / (fac_275)) : (fprintf(stderr, "division by zero\n"), abort(), 0)));
            (void)frac_hyend_279;
            int64_t temp_hyel_280 = tidal_hyel_hynew();
            (void)temp_hyel_280;
            tidal_hyeval(child_277, tidal_hyint_hydiv(cycle, fi_274), 0.0, 1.0, temp_hyel_280);
            tidal_hyeval_hyslow_hyfilter(temp_hyel_280, INT64_C(0), frac_278, frac_hyend_279, onset, dur, fac_275, el);
            tidal_hyel_hyfree_hyall(temp_hyel_280);
        }
}

static void tidal_hyeval_hyrev_hybuild(int64_t temp_el, int64_t n, int64_t i, double onset, double dur, int64_t el) {
        if ((i) >= (n)) {
            tidal_hyvoid();
        } else {
            {
                int64_t ev_287 = tidal_hyel_hyget(temp_el, i);
                (void)ev_287;
                double eo_288 = tidal_hyev_hyonset(ev_287);
                (void)eo_288;
                double ed_289 = tidal_hyev_hydur(ev_287);
                (void)ed_289;
                const char * val_290 = tidal_hyev_hyvalue(ev_287);
                (void)val_290;
                double new_hyonset_291 = (((onset) + (dur)) - ((eo_288) - (onset))) - (ed_289);
                (void)new_hyonset_291;
                tidal_hyel_hypush(el, new_hyonset_291, ed_289, val_290);
                tidal_hyeval_hyrev_hybuild(temp_el, n, (i) + (INT64_C(1)), onset, dur, el);
            }
        }
}

static void tidal_hyeval_hydegrade_hyfilter(int64_t temp_el, int64_t n, int64_t i, double prob, int64_t el) {
        if ((i) >= (n)) {
            tidal_hyvoid();
        } else {
            {
                int64_t ev_297 = tidal_hyel_hyget(temp_el, i);
                (void)ev_297;
                double r_298 = tidal_hyrand();
                (void)r_298;
                if ((r_298) >= (prob)) {
                    tidal_hyel_hypush(el, tidal_hyev_hyonset(ev_297), tidal_hyev_hydur(ev_297), tidal_hyev_hyvalue(ev_297));
                } else {
                    tidal_hyvoid();
                }
                tidal_hyeval_hydegrade_hyfilter(temp_el, n, (i) + (INT64_C(1)), prob, el);
            }
        }
}

static void tur_tidal_eval_impl(int64_t pat, int64_t cycle, double onset, double dur, int64_t el) {
        {
            int64_t kind_304 = tidal_hypat_hykind(pat);
            (void)kind_304;
            if ((kind_304) == (INT64_C(0))) {
                {
                    const char * val_305 = tidal_hypat_hyvalue(pat);
                    (void)val_305;
                    if (tidal_hycstr_hyis_hyrest_qu(val_305)) {
                        tidal_hyvoid();
                    } else {
                        tidal_hyel_hypush(el, onset, dur, val_305);
                    }
                }
            } else {
                if ((kind_304) == (INT64_C(1))) {
                    tidal_hyeval_hyseq_hychildren(pat, tidal_hypat_hycount(pat), cycle, onset, dur, INT64_C(0), el, tidal_hypat_hytotal_hyweight(pat));
                } else {
                    if ((kind_304) == (INT64_C(2))) {
                        tidal_hyeval_hyseq_hychildren(pat, tidal_hypat_hycount(pat), cycle, onset, dur, INT64_C(0), el, tidal_hypat_hytotal_hyweight(pat));
                    } else {
                        if ((kind_304) == (INT64_C(3))) {
                            {
                                int64_t n_306 = tidal_hypat_hycount(pat);
                                (void)n_306;
                                int64_t idx_307 = tidal_hyint_hymod(cycle, tidal_hyint_hymax(n_306, INT64_C(1)));
                                (void)idx_307;
                                tidal_hyeval(tidal_hypat_hychild(pat, idx_307), cycle, onset, dur, el);
                            }
                        } else {
                            if ((kind_304) == (INT64_C(4))) {
                                {
                                    int64_t n_308 = tidal_hypat_hyparam_hyn(pat);
                                    (void)n_308;
                                    int64_t ni_309 = tidal_hyint_hymax(n_308, INT64_C(1));
                                    (void)ni_309;
                                    int64_t child_310 = tidal_hypat_hychild(pat, INT64_C(0));
                                    (void)child_310;
                                    double step_hydur_311 = ((tidal_hyint_hyto_hyfloat(ni_309)) ? ((dur) / (tidal_hyint_hyto_hyfloat(ni_309))) : (fprintf(stderr, "division by zero\n"), abort(), 0));
                                    (void)step_hydur_311;
                                    tidal_hyeval_hyrepeat_hysteps(child_310, ni_309, cycle, onset, step_hydur_311, INT64_C(0), el);
                                }
                            } else {
                                if ((kind_304) == (INT64_C(5))) {
                                    tidal_hyeval_hyslow(pat, cycle, onset, dur, el);
                                } else {
                                    if ((kind_304) == (INT64_C(6))) {
                                        {
                                            int64_t n_312 = tidal_hypat_hyparam_hyn(pat);
                                            (void)n_312;
                                            int64_t k_313 = tidal_hyint_hymax(tidal_hypat_hyparam_hyk(pat), INT64_C(1));
                                            (void)k_313;
                                            int64_t child_314 = tidal_hypat_hychild(pat, INT64_C(0));
                                            (void)child_314;
                                            double step_hydur_315 = ((tidal_hyint_hyto_hyfloat(k_313)) ? ((dur) / (tidal_hyint_hyto_hyfloat(k_313))) : (fprintf(stderr, "division by zero\n"), abort(), 0));
                                            (void)step_hydur_315;
                                            int64_t pulses_316 = tidal_hybjorklund(n_312, k_313);
                                            (void)pulses_316;
                                            tidal_hyeval_hyeuclid_hysteps(child_314, pulses_316, k_313, cycle, onset, step_hydur_315, INT64_C(0), el);
                                        }
                                    } else {
                                        if ((kind_304) == (INT64_C(7))) {
                                            tidal_hyeval_hystack_hychildren(pat, tidal_hypat_hycount(pat), cycle, onset, dur, INT64_C(0), el);
                                        } else {
                                            if ((kind_304) == (INT64_C(8))) {
                                                {
                                                    int64_t n_317 = tidal_hypat_hycount(pat);
                                                    (void)n_317;
                                                    int64_t idx_318 = tidal_hyint_hymod(cycle, tidal_hyint_hymax(n_317, INT64_C(1)));
                                                    (void)idx_318;
                                                    tidal_hyeval(tidal_hypat_hychild(pat, idx_318), cycle, onset, dur, el);
                                                }
                                            } else {
                                                if ((kind_304) == (INT64_C(9))) {
                                                    {
                                                        int64_t child_319 = tidal_hypat_hychild(pat, INT64_C(0));
                                                        (void)child_319;
                                                        int64_t temp_hyel_320 = tidal_hyel_hynew();
                                                        (void)temp_hyel_320;
                                                        tidal_hyeval(child_319, cycle, onset, dur, temp_hyel_320);
                                                        tidal_hyeval_hyrev_hybuild(temp_hyel_320, tidal_hyel_hycount(temp_hyel_320), INT64_C(0), onset, dur, el);
                                                        tidal_hyel_hyfree_hyall(temp_hyel_320);
                                                    }
                                                } else {
                                                    if ((kind_304) == (INT64_C(10))) {
                                                        {
                                                            double f_321 = tidal_hypat_hyparam_hyf(pat);
                                                            (void)f_321;
                                                            int64_t fi_322 = tidal_hyint_hymax(tidal_hyfloat_hyto_hyint(f_321), INT64_C(1));
                                                            (void)fi_322;
                                                            int64_t child_323 = tidal_hypat_hychild(pat, INT64_C(0));
                                                            (void)child_323;
                                                            double step_hydur_324 = ((tidal_hyint_hyto_hyfloat(fi_322)) ? ((dur) / (tidal_hyint_hyto_hyfloat(fi_322))) : (fprintf(stderr, "division by zero\n"), abort(), 0));
                                                            (void)step_hydur_324;
                                                            tidal_hyeval_hyfast_hysteps(child_323, fi_322, cycle, onset, step_hydur_324, INT64_C(0), el);
                                                        }
                                                    } else {
                                                        if ((kind_304) == (INT64_C(11))) {
                                                            {
                                                                int64_t n_325 = tidal_hypat_hyparam_hyn(pat);
                                                                (void)n_325;
                                                                int64_t ni_326 = tidal_hyint_hymax(n_325, INT64_C(1));
                                                                (void)ni_326;
                                                                int64_t cnt_327 = tidal_hypat_hycount(pat);
                                                                (void)cnt_327;
                                                                int64_t rem_328 = tidal_hyint_hymod(cycle, ni_326);
                                                                (void)rem_328;
                                                                int64_t __t36;
                                                                bool __t37;
                                                                if ((rem_328) == (INT64_C(0))) {
                                                                    __t37 = (cnt_327) >= (INT64_C(2));
                                                                } else {
                                                                    __t37 = false;
                                                                }
                                                                if (__t37) {
                                                                    __t36 = tidal_hypat_hychild(pat, INT64_C(1));
                                                                } else {
                                                                    __t36 = tidal_hypat_hychild(pat, INT64_C(0));
                                                                }
                                                                int64_t child_329 = __t36;
                                                                (void)child_329;
                                                                tidal_hyeval(child_329, cycle, onset, dur, el);
                                                            }
                                                        } else {
                                                            if ((kind_304) == (INT64_C(12))) {
                                                                {
                                                                    double prob_330 = tidal_hypat_hyparam_hyf(pat);
                                                                    (void)prob_330;
                                                                    int64_t child_331 = tidal_hypat_hychild(pat, INT64_C(0));
                                                                    (void)child_331;
                                                                    int64_t temp_hyel_332 = tidal_hyel_hynew();
                                                                    (void)temp_hyel_332;
                                                                    tidal_hyeval(child_331, cycle, onset, dur, temp_hyel_332);
                                                                    tidal_hyeval_hydegrade_hyfilter(temp_hyel_332, tidal_hyel_hycount(temp_hyel_332), INT64_C(0), prob_330, el);
                                                                    tidal_hyel_hyfree_hyall(temp_hyel_332);
                                                                }
                                                            } else {
                                                                tidal_hyvoid();
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
}

static int64_t tidal_hyeval_hyto_hycons(int64_t pat, int64_t cycle) {
        int64_t __t38;
        {
            int64_t el_335 = tidal_hyel_hynew();
            (void)el_335;
            tidal_hyeval(pat, cycle, 0.0, 1.0, el_335);
            int64_t __t39;
            int64_t __t40;
            {
                int64_t lst_336 = tidal_hyel_hyto_hycons(el_335);
                (void)lst_336;
                tidal_hyel_hyfree_hystruct(el_335);
                int64_t __t41;
                __t41 = lst_336;
                __t40 = __t41;
            }
            __t39 = __t40;
            __t38 = __t39;
        }
        return __t38;
}

static void * parse_hynotation(const char * text) {
        void * __t42;
        {
            void * r_338 = tidal_hyparse_hyseq(text);
            (void)r_338;
            void * __t43;
            if (tidal_hyerr_qu((void *)(intptr_t)(r_338))) {
                __t43 = tidal_hyerr(INT64_C(0));
            } else {
                __t43 = r_338;
            }
            __t42 = __t43;
        }
        return __t42;
}

static void notation_hyfree(int64_t p) {
        tidal_hypat_hyfree_hyraw(p);
}

static int64_t pattern_hyevents(int64_t p, int64_t cycle) {
        return tidal_hyeval_hyto_hycons(p, cycle);
}


