/* generated by tur (phase 2) */
#include "tidal__event.h"

static int64_t nil_hyvalue();
static bool list_hynil_qu(int64_t);
static int64_t cons(int64_t, int64_t);
static int64_t head(int64_t);
static int64_t tail(int64_t);
static void * tidal_hyok(int64_t);
static void * tidal_hyerr(int64_t);
static bool tidal_hyok_qu(void *);
static bool tidal_hyerr_qu(void *);
static int64_t tidal_hyok_hyval(void *);
static int64_t tidal_hyerr_hyval(void *);
static void tidal_hyvoid();
static int64_t event_hynew(double, double, const char *);
static double event_hyonset(int64_t);
static double event_hydur(int64_t);
static const char * event_hyvalue(int64_t);
static void event_hyfree(int64_t);
static int64_t note_hy_gtmidi(const char *);

static int64_t nil_hyvalue() {
        return 0;
  
}

static bool list_hynil_qu(int64_t lst) {
        return lst == 0;
  
}

static int64_t cons(int64_t value, int64_t next) {
        struct { int64_t value; int64_t next; } *cell = malloc(sizeof(*cell));
  cell->value = value; cell->next = next;
  return (int64_t)(intptr_t)cell;
  
}

static int64_t head(int64_t lst) {
        struct { int64_t value; int64_t next; } *cell = (void*)(intptr_t)lst;
  if (!cell) { fprintf(stderr, "head: empty list\n"); exit(1); }
  return cell->value;
  
}

static int64_t tail(int64_t lst) {
        struct { int64_t value; int64_t next; } *cell = (void*)(intptr_t)lst;
  if (!cell) { fprintf(stderr, "tail: empty list\n"); exit(1); }
  return cell->next;
  
}

static void * tidal_hyok(int64_t x) {
        struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = true; r->ok_val = x; r->err_val = 0;
  return (void*)r;
  
}

static void * tidal_hyerr(int64_t e) {
        struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = false; r->ok_val = 0; r->err_val = e;
  return (void*)r;
  
}

static bool tidal_hyok_qu(void * r) {
        struct { bool is_ok; int64_t ok_val; int64_t err_val; } *res = (void*)r;
  return res != NULL && res->is_ok;
  
}

static bool tidal_hyerr_qu(void * r) {
        struct { bool is_ok; int64_t ok_val; int64_t err_val; } *res = (void*)r;
  return res == NULL || !res->is_ok;
  
}

static int64_t tidal_hyok_hyval(void * r) {
        struct { bool is_ok; int64_t ok_val; int64_t err_val; } *res = (void*)r;
  return res->ok_val;
  
}

static int64_t tidal_hyerr_hyval(void * r) {
        struct { bool is_ok; int64_t ok_val; int64_t err_val; } *res = (void*)r;
  return res->err_val;
  
}

static void tidal_hyvoid() {
        return;
  
}

static int64_t event_hynew(double onset, double dur, const char * value) {
        typedef struct { double onset; double dur; char *value; } TidalEvent;
  TidalEvent *e = malloc(sizeof(TidalEvent));
  e->onset = (double)onset;
  e->dur   = (double)dur;
  e->value = value ? strdup((const char*)(intptr_t)value) : strdup("");
  return (int64_t)(intptr_t)e;
  
}

static double event_hyonset(int64_t e) {
        typedef struct { double onset; double dur; char *value; } TidalEvent;
  TidalEvent *ev = (TidalEvent*)(intptr_t)e;
  return ev ? (float)ev->onset : 0.0f;
  
}

static double event_hydur(int64_t e) {
        typedef struct { double onset; double dur; char *value; } TidalEvent;
  TidalEvent *ev = (TidalEvent*)(intptr_t)e;
  return ev ? (float)ev->dur : 0.0f;
  
}

static const char * event_hyvalue(int64_t e) {
        typedef struct { double onset; double dur; char *value; } TidalEvent;
  TidalEvent *ev = (TidalEvent*)(intptr_t)e;
  return ev && ev->value ? ev->value : "";
  
}

static void event_hyfree(int64_t e) {
        typedef struct { double onset; double dur; char *value; } TidalEvent;
  TidalEvent *ev = (TidalEvent*)(intptr_t)e;
  if (ev) { free(ev->value); free(ev); }
  
}

static int64_t note_hy_gtmidi(const char * value) {
        const char *s = (const char*)(intptr_t)value;
  if (!s || !*s) return -1;
  /* rest */
  if (strcmp(s, "~") == 0) return -1;
  /* try numeric */
  int all_digits = 1;
  int si = 0;
  if (s[0] == '-') si = 1;
  for (int i = si; s[i]; i++) {
    if (s[i] < '0' || s[i] > '9') { all_digits = 0; break; }
  }
  if (all_digits && s[si] != '\0') return (int)atoi(s);
  /* parse note name: letter [accidental] digit */
  char ch = s[0];
  if (ch >= 'A' && ch <= 'Z') ch = ch - 'A' + 'a';
  int pitch_class = -1;
  switch (ch) {
    case 'c': pitch_class = 0;  break;
    case 'd': pitch_class = 2;  break;
    case 'e': pitch_class = 4;  break;
    case 'f': pitch_class = 5;  break;
    case 'g': pitch_class = 7;  break;
    case 'a': pitch_class = 9;  break;
    case 'b': pitch_class = 11; break;
    default: return -1;
  }
  int pos = 1;
  /* accidentals: # or b; support bb (double flat) */
  int accidental = 0;
  while (s[pos] == '#' || s[pos] == 'b') {
    if (s[pos] == '#') accidental++;
    else               accidental--;
    pos++;
  }
  /* octave digit */
  if (s[pos] < '0' || s[pos] > '9') return -1;
  int octave = s[pos] - '0';
  /* middle C = c4 = 60; formula: (octave+1)*12 + pitch_class */
  int midi = (octave + 1) * 12 + pitch_class + accidental;
  if (midi < 0 || midi > 127) return -1;
  return midi;
  
}


