/* generated by tur (phase 2) */
#ifndef TUR_tidal__pattern_H
#define TUR_tidal__pattern_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#endif /* TUR_tidal__pattern_H */
