/* generated by tur (phase 2) */
#include "tidal__pattern.h"

static int64_t nil_hyvalue();
static bool list_hynil_qu(int64_t);
static int64_t cons(int64_t, int64_t);
static int64_t head(int64_t);
static int64_t tail(int64_t);
static void * tidal_hyok(int64_t);
static void * tidal_hyerr(int64_t);
static bool tidal_hyok_qu(void *);
static bool tidal_hyerr_qu(void *);
static int64_t tidal_hyok_hyval(void *);
static int64_t tidal_hyerr_hyval(void *);
static void tidal_hyvoid();
static int64_t tidal_hypat_hynew1(int64_t, int64_t);
static int64_t tidal_hypat_hynew2(int64_t, int64_t, int64_t);
static void tidal_hypat_hyset_hyf(int64_t, double);
static void tidal_hypat_hyset_hyn(int64_t, int64_t);
static void tidal_hypat_hyfree_hyraw(int64_t);
static int64_t pattern_hyfast(int64_t, double);
static int64_t pattern_hyslow(int64_t, double);
static int64_t pattern_hystack(int64_t, int64_t);
static int64_t pattern_hycat(int64_t, int64_t);
static int64_t pattern_hyrev(int64_t);
static int64_t pattern_hyevery(int64_t, int64_t, int64_t);
static int64_t pattern_hydegrade(int64_t, double);
static void pattern_hyfree(int64_t);

static int64_t nil_hyvalue() {
        return 0;
  
}

static bool list_hynil_qu(int64_t lst) {
        return lst == 0;
  
}

static int64_t cons(int64_t value, int64_t next) {
        struct { int64_t value; int64_t next; } *cell = malloc(sizeof(*cell));
  cell->value = value; cell->next = next;
  return (int64_t)(intptr_t)cell;
  
}

static int64_t head(int64_t lst) {
        struct { int64_t value; int64_t next; } *cell = (void*)(intptr_t)lst;
  if (!cell) { fprintf(stderr, "head: empty list\n"); exit(1); }
  return cell->value;
  
}

static int64_t tail(int64_t lst) {
        struct { int64_t value; int64_t next; } *cell = (void*)(intptr_t)lst;
  if (!cell) { fprintf(stderr, "tail: empty list\n"); exit(1); }
  return cell->next;
  
}

static void * tidal_hyok(int64_t x) {
        struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = true; r->ok_val = x; r->err_val = 0;
  return (void*)r;
  
}

static void * tidal_hyerr(int64_t e) {
        struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = false; r->ok_val = 0; r->err_val = e;
  return (void*)r;
  
}

static bool tidal_hyok_qu(void * r) {
        struct { bool is_ok; int64_t ok_val; int64_t err_val; } *res = (void*)r;
  return res != NULL && res->is_ok;
  
}

static bool tidal_hyerr_qu(void * r) {
        struct { bool is_ok; int64_t ok_val; int64_t err_val; } *res = (void*)r;
  return res == NULL || !res->is_ok;
  
}

static int64_t tidal_hyok_hyval(void * r) {
        struct { bool is_ok; int64_t ok_val; int64_t err_val; } *res = (void*)r;
  return res->ok_val;
  
}

static int64_t tidal_hyerr_hyval(void * r) {
        struct { bool is_ok; int64_t ok_val; int64_t err_val; } *res = (void*)r;
  return res->err_val;
  
}

static void tidal_hyvoid() {
        return;
  
}

static int64_t tidal_hypat_hynew1(int64_t kind, int64_t child) {
        typedef enum {
    PAT_LEAF=0, PAT_SEQ=1, PAT_SUBSEQ=2, PAT_ALT=3, PAT_REPEAT=4,
    PAT_SLOW=5, PAT_EUCLID=6, PAT_STACK=7, PAT_CAT=8, PAT_REV=9,
    PAT_FAST=10, PAT_EVERY=11, PAT_DEGRADE=12
  } PatKind;
  typedef struct PatNode {
    PatKind kind; char *value; double param_f; int param_n; int param_k;
    double *weights; struct PatNode **children; int child_count; int child_cap;
  } PatNode;

  PatNode *n = calloc(1, sizeof(PatNode));
  n->kind = (PatKind)kind;
  n->param_f = 1.0;
  n->child_cap = 2;
  n->children = malloc(2 * sizeof(PatNode*));
  n->weights  = malloc(2 * sizeof(double));
  n->children[0] = (PatNode*)(intptr_t)child;
  n->weights[0]  = 1.0;
  n->child_count = 1;
  return (int64_t)(intptr_t)n;
  
}

static int64_t tidal_hypat_hynew2(int64_t kind, int64_t c1, int64_t c2) {
        typedef enum {
    PAT_LEAF=0, PAT_SEQ=1, PAT_SUBSEQ=2, PAT_ALT=3, PAT_REPEAT=4,
    PAT_SLOW=5, PAT_EUCLID=6, PAT_STACK=7, PAT_CAT=8, PAT_REV=9,
    PAT_FAST=10, PAT_EVERY=11, PAT_DEGRADE=12
  } PatKind;
  typedef struct PatNode {
    PatKind kind; char *value; double param_f; int param_n; int param_k;
    double *weights; struct PatNode **children; int child_count; int child_cap;
  } PatNode;

  PatNode *n = calloc(1, sizeof(PatNode));
  n->kind = (PatKind)kind;
  n->param_f = 1.0;
  n->child_cap = 4;
  n->children = malloc(4 * sizeof(PatNode*));
  n->weights  = malloc(4 * sizeof(double));
  n->children[0] = (PatNode*)(intptr_t)c1;
  n->weights[0]  = 1.0;
  n->children[1] = (PatNode*)(intptr_t)c2;
  n->weights[1]  = 1.0;
  n->child_count = 2;
  return (int64_t)(intptr_t)n;
  
}

static void tidal_hypat_hyset_hyf(int64_t pat, double f) {
        typedef struct { int kind; char *value; double param_f; int param_n; int param_k;
                   double *weights; void **children; int child_count; int child_cap;
  } PatNode;
  PatNode *n = (PatNode*)(intptr_t)pat;
  if (n) n->param_f = (double)f;
  
}

static void tidal_hypat_hyset_hyn(int64_t pat, int64_t n) {
        typedef struct { int kind; char *value; double param_f; int param_n; int param_k;
                   double *weights; void **children; int child_count; int child_cap;
  } PatNode;
  PatNode *p = (PatNode*)(intptr_t)pat;
  if (p) p->param_n = (int)n;
  
}

static void tidal_hypat_hyfree_hyraw(int64_t pat) {
        typedef struct { int kind; char *value; double param_f; int param_n; int param_k;
                   double *weights; void **children; int child_count; int child_cap; } PatNode;
  if (!pat) return;
  struct { int64_t *buf; int len; int cap; } stk;
  stk.cap = 16; stk.len = 0;
  stk.buf = malloc(stk.cap * sizeof(int64_t));
  stk.buf[stk.len++] = (int64_t)pat;
  while (stk.len > 0) {
    int64_t cur = stk.buf[--stk.len];
    PatNode *n = (PatNode*)(intptr_t)cur;
    if (!n) continue;
    for (int i = 0; i < n->child_count; i++) {
      if (stk.len >= stk.cap) {
        stk.cap *= 2;
        stk.buf = realloc(stk.buf, stk.cap * sizeof(int64_t));
      }
      stk.buf[stk.len++] = (int64_t)(intptr_t)n->children[i];
    }
    free(n->value); free(n->children); free(n->weights); free(n);
  }
  free(stk.buf);
  
}

static int64_t pattern_hyfast(int64_t p, double n) {
        int64_t __t0;
        {
            int64_t node_49 = tidal_hypat_hynew1(INT64_C(10), p);
            (void)node_49;
            tidal_hypat_hyset_hyf(node_49, n);
            int64_t __t1;
            __t1 = node_49;
            __t0 = __t1;
        }
        return __t0;
}

static int64_t pattern_hyslow(int64_t p, double n) {
        int64_t __t2;
        {
            int64_t node_52 = tidal_hypat_hynew1(INT64_C(5), p);
            (void)node_52;
            tidal_hypat_hyset_hyf(node_52, n);
            int64_t __t3;
            __t3 = node_52;
            __t2 = __t3;
        }
        return __t2;
}

static int64_t pattern_hystack(int64_t p1, int64_t p2) {
        return tidal_hypat_hynew2(INT64_C(7), p1, p2);
}

static int64_t pattern_hycat(int64_t p1, int64_t p2) {
        return tidal_hypat_hynew2(INT64_C(8), p1, p2);
}

static int64_t pattern_hyrev(int64_t p) {
        return tidal_hypat_hynew1(INT64_C(9), p);
}

static int64_t pattern_hyevery(int64_t n, int64_t f, int64_t p) {
        int64_t __t4;
        {
            int64_t node_61 = tidal_hypat_hynew2(INT64_C(11), p, f);
            (void)node_61;
            tidal_hypat_hyset_hyn(node_61, n);
            int64_t __t5;
            __t5 = node_61;
            __t4 = __t5;
        }
        return __t4;
}

static int64_t pattern_hydegrade(int64_t p, double prob) {
        int64_t __t6;
        {
            int64_t node_64 = tidal_hypat_hynew1(INT64_C(12), p);
            (void)node_64;
            tidal_hypat_hyset_hyf(node_64, prob);
            int64_t __t7;
            __t7 = node_64;
            __t6 = __t7;
        }
        return __t6;
}

static void pattern_hyfree(int64_t p) {
        tidal_hypat_hyfree_hyraw(p);
}


