/* generated by tur (phase 2) */
#include "tidal__render.h"

static int64_t nil_hyvalue();
static bool list_hynil_qu(int64_t);
static int64_t cons(int64_t, int64_t);
static int64_t head(int64_t);
static int64_t tail(int64_t);
static void * tidal_hyok(int64_t);
static void * tidal_hyerr(int64_t);
static bool tidal_hyok_qu(void *);
static bool tidal_hyerr_qu(void *);
static int64_t tidal_hyok_hyval(void *);
static int64_t tidal_hyerr_hyval(void *);
static void tidal_hyvoid();
static int64_t tidal_hyeval_hyto_hycons(int64_t, int64_t);
static int64_t note_hy_gtmidi(const char *);
static const char * tidal_hyconcat(const char *, const char *);
static const char * tidal_hyfloat_hystr(double);
static const char * tidal_hyint_hystr(int64_t);
static double tidal_hyev_hyonset(int64_t);
static double tidal_hyev_hydur(int64_t);
static const char * tidal_hyev_hyvalue(int64_t);
static void tidal_hyev_hyfree(int64_t);
static const char * render_hyevents_hyloop(int64_t, const char *);
static const char * render_hyevents(int64_t, int64_t);
static const char * render_hymidi_hycsv(int64_t, bool);
static const char * render_hydur_hycsv(int64_t, bool);
static const char * render_hymidi_hysp(int64_t, bool);
static const char * render_hydur_hysp(int64_t, bool);
static const char * render_hysclang(int64_t, const char *);
static const char * render_hypbind(int64_t, const char *);

static int64_t nil_hyvalue() {
        return 0;
  
}

static bool list_hynil_qu(int64_t lst) {
        return lst == 0;
  
}

static int64_t cons(int64_t value, int64_t next) {
        struct { int64_t value; int64_t next; } *cell = malloc(sizeof(*cell));
  cell->value = value; cell->next = next;
  return (int64_t)(intptr_t)cell;
  
}

static int64_t head(int64_t lst) {
        struct { int64_t value; int64_t next; } *cell = (void*)(intptr_t)lst;
  if (!cell) { fprintf(stderr, "head: empty list\n"); exit(1); }
  return cell->value;
  
}

static int64_t tail(int64_t lst) {
        struct { int64_t value; int64_t next; } *cell = (void*)(intptr_t)lst;
  if (!cell) { fprintf(stderr, "tail: empty list\n"); exit(1); }
  return cell->next;
  
}

static void * tidal_hyok(int64_t x) {
        struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = true; r->ok_val = x; r->err_val = 0;
  return (void*)r;
  
}

static void * tidal_hyerr(int64_t e) {
        struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = false; r->ok_val = 0; r->err_val = e;
  return (void*)r;
  
}

static bool tidal_hyok_qu(void * r) {
        struct { bool is_ok; int64_t ok_val; int64_t err_val; } *res = (void*)r;
  return res != NULL && res->is_ok;
  
}

static bool tidal_hyerr_qu(void * r) {
        struct { bool is_ok; int64_t ok_val; int64_t err_val; } *res = (void*)r;
  return res == NULL || !res->is_ok;
  
}

static int64_t tidal_hyok_hyval(void * r) {
        struct { bool is_ok; int64_t ok_val; int64_t err_val; } *res = (void*)r;
  return res->ok_val;
  
}

static int64_t tidal_hyerr_hyval(void * r) {
        struct { bool is_ok; int64_t ok_val; int64_t err_val; } *res = (void*)r;
  return res->err_val;
  
}

static void tidal_hyvoid() {
        return;
  
}

static int64_t tidal_hyeval_hyto_hycons(int64_t pat, int64_t cycle) {
        /* This stub is replaced by the full implementation in notation.tur
   * when used in a combined build.  As a standalone file it returns
   * an empty list (0) so render functions degrade gracefully. */
  return 0;
  
}

static int64_t note_hy_gtmidi(const char * value) {
        const char *s = (const char*)(intptr_t)value;
  if (!s || !*s) return -1;
  if (strcmp(s, "~") == 0) return -1;
  int si = 0;
  if (s[0] == '-') si = 1;
  int all_digits = 1;
  for (int i = si; s[i]; i++) { if (s[i]<'0'||s[i]>'9') { all_digits=0; break; } }
  if (all_digits && s[si]!='\0') return atoi(s);
  char ch = s[0]; if (ch>='A'&&ch<='Z') ch=ch-'A'+'a';
  int pc=-1;
  switch(ch){case 'c':pc=0;break;case 'd':pc=2;break;case 'e':pc=4;break;
             case 'f':pc=5;break;case 'g':pc=7;break;case 'a':pc=9;break;
             case 'b':pc=11;break;default:return -1;}
  int pos=1, acc=0;
  while(s[pos]=='#'||s[pos]=='b'){if(s[pos]=='#')acc++;else acc--;pos++;}
  if(s[pos]<'0'||s[pos]>'9') return -1;
  int octave=s[pos]-'0';
  int midi=(octave+1)*12+pc+acc;
  return (midi>=0&&midi<=127)?midi:-1;
  
}

static const char * tidal_hyconcat(const char * a, const char * b) {
        const char *sa = (const char*)(intptr_t)a;
  const char *sb = (const char*)(intptr_t)b;
  if (!sa) sa = ""; if (!sb) sb = "";
  size_t la = strlen(sa), lb = strlen(sb);
  char *out = malloc(la + lb + 1);
  memcpy(out, sa, la); memcpy(out + la, sb, lb);
  out[la + lb] = '\0';
  return out;
  
}

static const char * tidal_hyfloat_hystr(double f) {
        char *buf = malloc(32);
  snprintf(buf, 32, "%.3f", (double)f);
  return buf;
  
}

static const char * tidal_hyint_hystr(int64_t n) {
        char *buf = malloc(24);
  snprintf(buf, 24, "%d", (int)n);
  return buf;
  
}

static double tidal_hyev_hyonset(int64_t e) {
        typedef struct { double onset; double dur; char *value; } TidalEvent;
  TidalEvent *ev = (TidalEvent*)(intptr_t)e;
  return ev ? (float)ev->onset : 0.0f;
  
}

static double tidal_hyev_hydur(int64_t e) {
        typedef struct { double onset; double dur; char *value; } TidalEvent;
  TidalEvent *ev = (TidalEvent*)(intptr_t)e;
  return ev ? (float)ev->dur : 0.0f;
  
}

static const char * tidal_hyev_hyvalue(int64_t e) {
        typedef struct { double onset; double dur; char *value; } TidalEvent;
  TidalEvent *ev = (TidalEvent*)(intptr_t)e;
  return ev && ev->value ? ev->value : "";
  
}

static void tidal_hyev_hyfree(int64_t e) {
        typedef struct { double onset; double dur; char *value; } TidalEvent;
  TidalEvent *ev = (TidalEvent*)(intptr_t)e;
  if (ev) { free(ev->value); free(ev); }
  
}

static const char * render_hyevents_hyloop(int64_t evts, const char * acc) {
        __tur_tailcall:;
        if (list_hynil_qu(evts)) {
            return acc;
        } else {
            {
                int64_t e_54 = head(evts);
                (void)e_54;
                double onset_55 = tidal_hyev_hyonset(e_54);
                (void)onset_55;
                double dur_56 = tidal_hyev_hydur(e_54);
                (void)dur_56;
                const char * value_57 = tidal_hyev_hyvalue(e_54);
                (void)value_57;
                const char * line_58 = tidal_hyconcat(tidal_hyfloat_hystr(onset_55), tidal_hyconcat("  ", tidal_hyconcat(tidal_hyfloat_hystr(dur_56), tidal_hyconcat("  ", tidal_hyconcat(value_57, "\n")))));
                (void)line_58;
                int64_t __t0 = tail(evts);
                const char * __t1 = tidal_hyconcat(acc, line_58);
                evts = __t0;
                acc = __t1;
                goto __tur_tailcall;
            }
        }
}

static const char * render_hyevents(int64_t p, int64_t cycle) {
        const char * __t2;
        {
            int64_t evts_61 = tidal_hyeval_hyto_hycons(p, cycle);
            (void)evts_61;
            __t2 = render_hyevents_hyloop(evts_61, "");
        }
        return __t2;
}

static const char * render_hymidi_hycsv(int64_t evts, bool first_qu) {
        __tur_tailcall:;
        if (list_hynil_qu(evts)) {
            return "";
        } else {
            {
                int64_t ev_64 = head(evts);
                (void)ev_64;
                int64_t midi_65 = note_hy_gtmidi(tidal_hyev_hyvalue(ev_64));
                (void)midi_65;
                const char * rest_66 = render_hymidi_hycsv(tail(evts), false);
                (void)rest_66;
                if ((midi_65) < (INT64_C(0))) {
                    int64_t __t3 = tail(evts);
                    bool __t4 = first_qu;
                    evts = __t3;
                    first_qu = __t4;
                    goto __tur_tailcall;
                } else {
                    if (first_qu) {
                        return tidal_hyconcat(tidal_hyint_hystr(midi_65), rest_66);
                    } else {
                        return tidal_hyconcat(",", tidal_hyconcat(tidal_hyint_hystr(midi_65), rest_66));
                    }
                }
            }
        }
}

static const char * render_hydur_hycsv(int64_t evts, bool first_qu) {
        __tur_tailcall:;
        if (list_hynil_qu(evts)) {
            return "";
        } else {
            {
                int64_t ev_69 = head(evts);
                (void)ev_69;
                int64_t midi_70 = note_hy_gtmidi(tidal_hyev_hyvalue(ev_69));
                (void)midi_70;
                const char * rest_71 = render_hydur_hycsv(tail(evts), false);
                (void)rest_71;
                if ((midi_70) < (INT64_C(0))) {
                    int64_t __t5 = tail(evts);
                    bool __t6 = first_qu;
                    evts = __t5;
                    first_qu = __t6;
                    goto __tur_tailcall;
                } else {
                    if (first_qu) {
                        return tidal_hyconcat(tidal_hyfloat_hystr(tidal_hyev_hydur(ev_69)), rest_71);
                    } else {
                        return tidal_hyconcat(",", tidal_hyconcat(tidal_hyfloat_hystr(tidal_hyev_hydur(ev_69)), rest_71));
                    }
                }
            }
        }
}

static const char * render_hymidi_hysp(int64_t evts, bool first_qu) {
        __tur_tailcall:;
        if (list_hynil_qu(evts)) {
            return "";
        } else {
            {
                int64_t ev_74 = head(evts);
                (void)ev_74;
                int64_t midi_75 = note_hy_gtmidi(tidal_hyev_hyvalue(ev_74));
                (void)midi_75;
                const char * rest_76 = render_hymidi_hysp(tail(evts), false);
                (void)rest_76;
                if ((midi_75) < (INT64_C(0))) {
                    int64_t __t7 = tail(evts);
                    bool __t8 = first_qu;
                    evts = __t7;
                    first_qu = __t8;
                    goto __tur_tailcall;
                } else {
                    if (first_qu) {
                        return tidal_hyconcat(tidal_hyint_hystr(midi_75), rest_76);
                    } else {
                        return tidal_hyconcat(" ", tidal_hyconcat(tidal_hyint_hystr(midi_75), rest_76));
                    }
                }
            }
        }
}

static const char * render_hydur_hysp(int64_t evts, bool first_qu) {
        __tur_tailcall:;
        if (list_hynil_qu(evts)) {
            return "";
        } else {
            {
                int64_t ev_79 = head(evts);
                (void)ev_79;
                int64_t midi_80 = note_hy_gtmidi(tidal_hyev_hyvalue(ev_79));
                (void)midi_80;
                const char * rest_81 = render_hydur_hysp(tail(evts), false);
                (void)rest_81;
                if ((midi_80) < (INT64_C(0))) {
                    int64_t __t9 = tail(evts);
                    bool __t10 = first_qu;
                    evts = __t9;
                    first_qu = __t10;
                    goto __tur_tailcall;
                } else {
                    if (first_qu) {
                        return tidal_hyconcat(tidal_hyfloat_hystr(tidal_hyev_hydur(ev_79)), rest_81);
                    } else {
                        return tidal_hyconcat(" ", tidal_hyconcat(tidal_hyfloat_hystr(tidal_hyev_hydur(ev_79)), rest_81));
                    }
                }
            }
        }
}

static const char * render_hysclang(int64_t p, const char * instrument) {
        const char * __t11;
        {
            int64_t evts_84 = tidal_hyeval_hyto_hycons(p, INT64_C(0));
            (void)evts_84;
            const char * midi_hystr_85 = render_hymidi_hycsv(evts_84, true);
            (void)midi_hystr_85;
            const char * dur_hystr_86 = render_hydur_hycsv(evts_84, true);
            (void)dur_hystr_86;
            __t11 = tidal_hyconcat("(Pbind.new([\\instrument, \"", tidal_hyconcat(instrument, tidal_hyconcat("\", \\midinote, Pseq.new([", tidal_hyconcat(midi_hystr_85, tidal_hyconcat("],inf), \\dur, Pseq.new([", tidal_hyconcat(dur_hystr_86, "],inf)])).play;"))))));
        }
        return __t11;
}

static const char * render_hypbind(int64_t p, const char * instrument) {
        const char * __t12;
        {
            int64_t evts_89 = tidal_hyeval_hyto_hycons(p, INT64_C(0));
            (void)evts_89;
            const char * midi_hystr_90 = render_hymidi_hysp(evts_89, true);
            (void)midi_hystr_90;
            const char * dur_hystr_91 = render_hydur_hysp(evts_89, true);
            (void)dur_hystr_91;
            __t12 = tidal_hyconcat("(. (pbind :instrument \"", tidal_hyconcat(instrument, tidal_hyconcat("\" :midinote (pseq [", tidal_hyconcat(midi_hystr_90, tidal_hyconcat("] inf) :dur (pseq [", tidal_hyconcat(dur_hystr_91, "] inf)) play)"))))));
        }
        return __t12;
}


