/* generated by tur (phase 2) */
#include "tur__zlib.h"

void * tur__zlib__gzip_hyencode(void *, int64_t);
void * tur__zlib__gzip_hydecode(void *, int64_t);
void * tur__zlib__deflate_hyraw(void *, int64_t);
void * tur__zlib__inflate_hyraw(void *, int64_t);
void * tur__zlib__gzip_hybuf_hydata(void *);
int64_t tur__zlib__gzip_hybuf_hylen(void *);
void tur__zlib__gzip_hybuf_hyfree(void *);

void * tur__zlib__gzip_hyencode(void * data, int64_t data_len) {
        #include <stdlib.h>
  #include <string.h>
  #include <zlib.h>
  struct __gzbuf { int64_t len; unsigned char data[1]; };
  if (data_len < 0) return NULL;
  uLong src_len = (uLong)data_len;
  /* deflateBound is an upper bound on the raw deflate output; the gzip
     wrapper adds at most 18 bytes of header/trailer plus a few for the
     extra fields.  +64 is plenty of slack. */
  uLong bound = deflateBound(NULL, src_len) + 64;
  z_stream zs;
  memset(&zs, 0, sizeof(zs));
  /* windowBits = 15 + 16 selects the gzip wrapper. */
  if (deflateInit2(&zs, Z_DEFAULT_COMPRESSION, Z_DEFLATED,
                   15 + 16, 8, Z_DEFAULT_STRATEGY) != Z_OK)
    return NULL;
  unsigned char *out = (unsigned char *)malloc((size_t)bound);
  if (!out) { deflateEnd(&zs); return NULL; }
  zs.next_in   = (Bytef *)data;
  zs.avail_in  = (uInt)src_len;
  zs.next_out  = (Bytef *)out;
  zs.avail_out = (uInt)bound;
  int rc = deflate(&zs, Z_FINISH);
  if (rc != Z_STREAM_END) { free(out); deflateEnd(&zs); return NULL; }
  size_t produced = (size_t)zs.total_out;
  deflateEnd(&zs);
  struct __gzbuf *b = (struct __gzbuf *)malloc(sizeof(int64_t) + produced);
  if (!b) { free(out); return NULL; }
  b->len = (int64_t)produced;
  memcpy(b->data, out, produced);
  free(out);
  return b;
  
}

void * tur__zlib__gzip_hydecode(void * data, int64_t data_len) {
        #include <stdlib.h>
  #include <string.h>
  #include <zlib.h>
  struct __gzbuf { int64_t len; unsigned char data[1]; };
  if (data_len < 0) return NULL;
  z_stream zs;
  memset(&zs, 0, sizeof(zs));
  /* windowBits = 15 + 32 enables automatic gzip/zlib header detection. */
  if (inflateInit2(&zs, 15 + 32) != Z_OK) return NULL;
  zs.next_in  = (Bytef *)data;
  zs.avail_in = (uInt)data_len;
  size_t cap = (size_t)data_len * 4 + 64;
  unsigned char *out = (unsigned char *)malloc(cap);
  if (!out) { inflateEnd(&zs); return NULL; }
  size_t produced = 0;
  for (;;) {
    if (produced == cap) {
      size_t new_cap = cap * 2;
      unsigned char *new_out = (unsigned char *)realloc(out, new_cap);
      if (!new_out) { free(out); inflateEnd(&zs); return NULL; }
      out = new_out; cap = new_cap;
    }
    zs.next_out  = (Bytef *)(out + produced);
    zs.avail_out = (uInt)(cap - produced);
    int rc = inflate(&zs, Z_NO_FLUSH);
    produced = cap - zs.avail_out;
    if (rc == Z_STREAM_END) break;
    if (rc != Z_OK)        { free(out); inflateEnd(&zs); return NULL; }
    if (zs.avail_in == 0 && zs.avail_out > 0) {
      free(out); inflateEnd(&zs); return NULL;
    }
  }
  inflateEnd(&zs);
  struct __gzbuf *b = (struct __gzbuf *)malloc(sizeof(int64_t) + produced);
  if (!b) { free(out); return NULL; }
  b->len = (int64_t)produced;
  memcpy(b->data, out, produced);
  free(out);
  return b;
  
}

void * tur__zlib__deflate_hyraw(void * data, int64_t data_len) {
        #include <stdlib.h>
  #include <string.h>
  #include <zlib.h>
  struct __gzbuf { int64_t len; unsigned char data[1]; };
  if (data_len < 0) return NULL;
  uLong src_len = (uLong)data_len;
  uLong bound = deflateBound(NULL, src_len) + 64;
  z_stream zs;
  memset(&zs, 0, sizeof(zs));
  /* Negative windowBits selects raw deflate (no wrapper). */
  if (deflateInit2(&zs, Z_DEFAULT_COMPRESSION, Z_DEFLATED,
                   -15, 8, Z_DEFAULT_STRATEGY) != Z_OK)
    return NULL;
  unsigned char *out = (unsigned char *)malloc((size_t)bound);
  if (!out) { deflateEnd(&zs); return NULL; }
  zs.next_in   = (Bytef *)data;
  zs.avail_in  = (uInt)src_len;
  zs.next_out  = (Bytef *)out;
  zs.avail_out = (uInt)bound;
  int rc = deflate(&zs, Z_FINISH);
  if (rc != Z_STREAM_END) { free(out); deflateEnd(&zs); return NULL; }
  size_t produced = (size_t)zs.total_out;
  deflateEnd(&zs);
  struct __gzbuf *b = (struct __gzbuf *)malloc(sizeof(int64_t) + produced);
  if (!b) { free(out); return NULL; }
  b->len = (int64_t)produced;
  memcpy(b->data, out, produced);
  free(out);
  return b;
  
}

void * tur__zlib__inflate_hyraw(void * data, int64_t data_len) {
        #include <stdlib.h>
  #include <string.h>
  #include <zlib.h>
  struct __gzbuf { int64_t len; unsigned char data[1]; };
  if (data_len < 0) return NULL;
  z_stream zs;
  memset(&zs, 0, sizeof(zs));
  if (inflateInit2(&zs, -15) != Z_OK) return NULL;
  zs.next_in  = (Bytef *)data;
  zs.avail_in = (uInt)data_len;
  size_t cap = (size_t)data_len * 4 + 64;
  unsigned char *out = (unsigned char *)malloc(cap);
  if (!out) { inflateEnd(&zs); return NULL; }
  size_t produced = 0;
  for (;;) {
    if (produced == cap) {
      size_t new_cap = cap * 2;
      unsigned char *new_out = (unsigned char *)realloc(out, new_cap);
      if (!new_out) { free(out); inflateEnd(&zs); return NULL; }
      out = new_out; cap = new_cap;
    }
    zs.next_out  = (Bytef *)(out + produced);
    zs.avail_out = (uInt)(cap - produced);
    int rc = inflate(&zs, Z_NO_FLUSH);
    produced = cap - zs.avail_out;
    if (rc == Z_STREAM_END) break;
    if (rc != Z_OK)        { free(out); inflateEnd(&zs); return NULL; }
    if (zs.avail_in == 0 && zs.avail_out > 0) {
      free(out); inflateEnd(&zs); return NULL;
    }
  }
  inflateEnd(&zs);
  struct __gzbuf *b = (struct __gzbuf *)malloc(sizeof(int64_t) + produced);
  if (!b) { free(out); return NULL; }
  b->len = (int64_t)produced;
  memcpy(b->data, out, produced);
  free(out);
  return b;
  
}

void * tur__zlib__gzip_hybuf_hydata(void * b) {
        struct __gzbuf { int64_t len; unsigned char data[1]; };
  struct __gzbuf *p = (struct __gzbuf *)b;
  if (!p) return NULL;
  return (void *)p->data;
  
}

int64_t tur__zlib__gzip_hybuf_hylen(void * b) {
        struct __gzbuf { int64_t len; unsigned char data[1]; };
  struct __gzbuf *p = (struct __gzbuf *)b;
  if (!p) return 0;
  return (int64_t)p->len;
  
}

void tur__zlib__gzip_hybuf_hyfree(void * b) {
        #include <stdlib.h>
  if (b) free(b);
  
}


