/* generated by tur (phase 2) */
#ifndef TUR_tur__zlib_H
#define TUR_tur__zlib_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void * tur__zlib__gzip_hyencode(void *, int64_t);
void * tur__zlib__gzip_hydecode(void *, int64_t);
void * tur__zlib__deflate_hyraw(void *, int64_t);
void * tur__zlib__inflate_hyraw(void *, int64_t);
void * tur__zlib__gzip_hybuf_hydata(void *);
int64_t tur__zlib__gzip_hybuf_hylen(void *);
void tur__zlib__gzip_hybuf_hyfree(void *);
#endif /* TUR_tur__zlib_H */
