/* generated by tur (phase 2) */
#include "raylib__textures.h"

int64_t raylib__textures__load_hytexture(const char *);
void raylib__textures__unload_hytexture(int64_t);
void raylib__textures__draw_hytexture(int64_t, int64_t, int64_t, int64_t);
void raylib__textures__draw_hytexture_hyv(int64_t, int64_t, int64_t);
void raylib__textures__draw_hytexture_hyex(int64_t, int64_t, double, double, int64_t);

int64_t raylib__textures__load_hytexture(const char * path) {
        #include <raylib.h>
  Texture2D *tex = malloc(sizeof(Texture2D));
  *tex = LoadTexture((const char *)path);
  return (int64_t)(intptr_t)tex;
  
}

void raylib__textures__unload_hytexture(int64_t tex) {
        #include <raylib.h>
  Texture2D *t = (Texture2D *)(intptr_t)tex;
  UnloadTexture(*t);
  free(t);
  
}

void raylib__textures__draw_hytexture(int64_t tex, int64_t x, int64_t y, int64_t tint) {
        #include <raylib.h>
  Texture2D *t = (Texture2D *)(intptr_t)tex;
  Color     *c = (Color     *)(intptr_t)tint;
  DrawTexture(*t, (int)x, (int)y, *c);
  
}

void raylib__textures__draw_hytexture_hyv(int64_t tex, int64_t pos, int64_t tint) {
        #include <raylib.h>
  Texture2D *t = (Texture2D *)(intptr_t)tex;
  Vector2   *p = (Vector2   *)(intptr_t)pos;
  Color     *c = (Color     *)(intptr_t)tint;
  DrawTextureV(*t, *p, *c);
  
}

void raylib__textures__draw_hytexture_hyex(int64_t tex, int64_t pos, double rotation, double scale, int64_t tint) {
        #include <raylib.h>
  Texture2D *t = (Texture2D *)(intptr_t)tex;
  Vector2   *p = (Vector2   *)(intptr_t)pos;
  Color     *c = (Color     *)(intptr_t)tint;
  DrawTextureEx(*t, *p, (float)rotation, (float)scale, *c);
  
}


