/* generated by tur (phase 2) */
#ifndef TUR_raylib__models_H
#define TUR_raylib__models_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int64_t raylib__models__load_hymodel(const char *);
void raylib__models__unload_hymodel(int64_t);
void raylib__models__draw_hymodel(int64_t, double, double, double, double, int64_t);
void raylib__models__draw_hymodel_hyex(int64_t, double, double, double, double, double, double, double, double, double, double, int64_t);
int64_t raylib__models__load_hymesh(double, double, double);
void raylib__models__draw_hymesh(int64_t, int64_t, int64_t);
#endif /* TUR_raylib__models_H */
