/* generated by tur (phase 2) */
#include "raylib__shapes.h"

static int64_t raylib__shapes___un_unmake_hyvec2(double, double);
void raylib__shapes__draw_hycircle(int64_t, int64_t, double, int64_t);
void raylib__shapes__draw_hycircle_hyv(int64_t, double, int64_t);
void raylib__shapes__draw_hyrectangle(int64_t, int64_t, int64_t, int64_t, int64_t);
void raylib__shapes__draw_hyrectangle_hyrec(int64_t, int64_t);
void raylib__shapes__draw_hyline(int64_t, int64_t, int64_t, int64_t, int64_t);
void raylib__shapes__draw_hyline_hyv(int64_t, int64_t, int64_t);
void raylib__shapes__draw_hytriangle(int64_t, int64_t, int64_t, int64_t);

static int64_t raylib__shapes___un_unmake_hyvec2(double x, double y) {
        #include <raylib.h>
  Vector2 *v = malloc(sizeof(Vector2)); v->x = (float)x; v->y = (float)y;
  return (int64_t)(intptr_t)v;
  
}

void raylib__shapes__draw_hycircle(int64_t cx, int64_t cy, double radius, int64_t col) {
        #include <raylib.h>
  Color *c = (Color *)(intptr_t)col;
  DrawCircle((int)cx, (int)cy, (float)radius, *c);
  
}

void raylib__shapes__draw_hycircle_hyv(int64_t center, double radius, int64_t col) {
        #include <raylib.h>
  Vector2 *v = (Vector2 *)(intptr_t)center;
  Color   *c = (Color   *)(intptr_t)col;
  DrawCircleV(*v, (float)radius, *c);
  
}

void raylib__shapes__draw_hyrectangle(int64_t x, int64_t y, int64_t w, int64_t h, int64_t col) {
        #include <raylib.h>
  Color *c = (Color *)(intptr_t)col;
  DrawRectangle((int)x, (int)y, (int)w, (int)h, *c);
  
}

void raylib__shapes__draw_hyrectangle_hyrec(int64_t rec, int64_t col) {
        #include <raylib.h>
  Rectangle *r = (Rectangle *)(intptr_t)rec;
  Color     *c = (Color     *)(intptr_t)col;
  DrawRectangleRec(*r, *c);
  
}

void raylib__shapes__draw_hyline(int64_t x1, int64_t y1, int64_t x2, int64_t y2, int64_t col) {
        #include <raylib.h>
  Color *c = (Color *)(intptr_t)col;
  DrawLine((int)x1, (int)y1, (int)x2, (int)y2, *c);
  
}

void raylib__shapes__draw_hyline_hyv(int64_t start, int64_t end, int64_t col) {
        #include <raylib.h>
  Vector2 *s = (Vector2 *)(intptr_t)start;
  Vector2 *e = (Vector2 *)(intptr_t)end;
  Color   *c = (Color   *)(intptr_t)col;
  DrawLineV(*s, *e, *c);
  
}

void raylib__shapes__draw_hytriangle(int64_t v1, int64_t v2, int64_t v3, int64_t col) {
        #include <raylib.h>
  Vector2 *a = (Vector2 *)(intptr_t)v1;
  Vector2 *b = (Vector2 *)(intptr_t)v2;
  Vector2 *c_v = (Vector2 *)(intptr_t)v3;
  Color   *c = (Color   *)(intptr_t)col;
  DrawTriangle(*a, *b, *c_v, *c);
  
}


