/* generated by tur (phase 2) */
#include "raylib__models.h"

int64_t raylib__models__load_hymodel(const char *);
void raylib__models__unload_hymodel(int64_t);
void raylib__models__draw_hymodel(int64_t, double, double, double, double, int64_t);
void raylib__models__draw_hymodel_hyex(int64_t, double, double, double, double, double, double, double, double, double, double, int64_t);
int64_t raylib__models__load_hymesh(double, double, double);
void raylib__models__draw_hymesh(int64_t, int64_t, int64_t);

int64_t raylib__models__load_hymodel(const char * path) {
        #include <raylib.h>
  Model *m = malloc(sizeof(Model));
  *m = LoadModel((const char *)path);
  return (int64_t)(intptr_t)m;
  
}

void raylib__models__unload_hymodel(int64_t model) {
        #include <raylib.h>
  Model *m = (Model *)(intptr_t)model;
  UnloadModel(*m);
  free(m);
  
}

void raylib__models__draw_hymodel(int64_t model, double px, double py, double pz, double scale, int64_t tint) {
        #include <raylib.h>
  Model *m = (Model *)(intptr_t)model;
  Color *c = (Color *)(intptr_t)tint;
  DrawModel(*m, (Vector3){ (float)px, (float)py, (float)pz }, (float)scale, *c);
  
}

void raylib__models__draw_hymodel_hyex(int64_t model, double px, double py, double pz, double ax, double ay, double az, double angle, double sx, double sy, double sz, int64_t tint) {
        #include <raylib.h>
  Model  *m = (Model  *)(intptr_t)model;
  Color  *c = (Color  *)(intptr_t)tint;
  Vector3 pos   = { (float)px, (float)py, (float)pz };
  Vector3 axis  = { (float)ax, (float)ay, (float)az };
  Vector3 scale = { (float)sx, (float)sy, (float)sz };
  DrawModelEx(*m, pos, axis, (float)angle, scale, *c);
  
}

int64_t raylib__models__load_hymesh(double w, double h, double d) {
        #include <raylib.h>
  Mesh *mesh = malloc(sizeof(Mesh));
  *mesh = GenMeshCube((float)w, (float)h, (float)d);
  UploadMesh(mesh, false);
  return (int64_t)(intptr_t)mesh;
  
}

void raylib__models__draw_hymesh(int64_t mesh, int64_t material, int64_t transform) {
        #include <raylib.h>
  Mesh     *me = (Mesh     *)(intptr_t)mesh;
  Material *ma = (Material *)(intptr_t)material;
  Matrix   *mx = (Matrix   *)(intptr_t)transform;
  DrawMesh(*me, *ma, *mx);
  
}


