/* generated by tur (phase 2) */
#ifndef TUR_raylib__color_H
#define TUR_raylib__color_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int64_t raylib__color__color(int64_t, int64_t, int64_t, int64_t);
int64_t raylib__color__red();
int64_t raylib__color__green();
int64_t raylib__color__blue();
int64_t raylib__color__white();
int64_t raylib__color__black();
int64_t raylib__color__gray();
int64_t raylib__color__yellow();
int64_t raylib__color__orange();
int64_t raylib__color__purple();
int64_t raylib__color__pink();
int64_t raylib__color__skyblue();
int64_t raylib__color__raywhite();
int64_t raylib__color__fade(int64_t, double);
int64_t raylib__color__color_hylerp(int64_t, int64_t, double);
#endif /* TUR_raylib__color_H */
