/* generated by tur (phase 2) */
#include "raylib__audio.h"

void raylib__audio__init_hyaudio_hydevice();
void raylib__audio__close_hyaudio_hydevice();
int64_t raylib__audio__load_hysound(const char *);
void raylib__audio__unload_hysound(int64_t);
void raylib__audio__play_hysound(int64_t);
int64_t raylib__audio__load_hymusic_hystream(const char *);
void raylib__audio__unload_hymusic_hystream(int64_t);
void raylib__audio__play_hymusic_hystream(int64_t);
void raylib__audio__update_hymusic_hystream(int64_t);

void raylib__audio__init_hyaudio_hydevice() {
        #include <raylib.h>
  InitAudioDevice();
  
}

void raylib__audio__close_hyaudio_hydevice() {
        #include <raylib.h>
  CloseAudioDevice();
  
}

int64_t raylib__audio__load_hysound(const char * path) {
        #include <raylib.h>
  Sound *s = malloc(sizeof(Sound));
  *s = LoadSound((const char *)path);
  return (int64_t)(intptr_t)s;
  
}

void raylib__audio__unload_hysound(int64_t sound) {
        #include <raylib.h>
  Sound *s = (Sound *)(intptr_t)sound;
  UnloadSound(*s);
  free(s);
  
}

void raylib__audio__play_hysound(int64_t sound) {
        #include <raylib.h>
  Sound *s = (Sound *)(intptr_t)sound;
  PlaySound(*s);
  
}

int64_t raylib__audio__load_hymusic_hystream(const char * path) {
        #include <raylib.h>
  Music *m = malloc(sizeof(Music));
  *m = LoadMusicStream((const char *)path);
  return (int64_t)(intptr_t)m;
  
}

void raylib__audio__unload_hymusic_hystream(int64_t music) {
        #include <raylib.h>
  Music *m = (Music *)(intptr_t)music;
  UnloadMusicStream(*m);
  free(m);
  
}

void raylib__audio__play_hymusic_hystream(int64_t music) {
        #include <raylib.h>
  Music *m = (Music *)(intptr_t)music;
  PlayMusicStream(*m);
  
}

void raylib__audio__update_hymusic_hystream(int64_t music) {
        #include <raylib.h>
  Music *m = (Music *)(intptr_t)music;
  UpdateMusicStream(*m);
  
}


