/* generated by tur (phase 2) */
#include "raylib__core.h"

void raylib__core__init_hywindow(int64_t, int64_t, const char *);
void raylib__core__close_hywindow();
bool raylib__core__window_hyshould_hyclose();
void raylib__core__begin_hydrawing();
void raylib__core__end_hydrawing();
void raylib__core__begin_hymode_hy3d(int64_t);
void raylib__core__end_hymode_hy3d();
void raylib__core__clear_hybackground(int64_t);
void raylib__core__set_hytarget_hyfps(int64_t);
double raylib__core__get_hyframe_hytime();

void raylib__core__init_hywindow(int64_t width, int64_t height, const char * title) {
        #include <raylib.h>
  InitWindow((int)width, (int)height, (const char *)title);
  
}

void raylib__core__close_hywindow() {
        #include <raylib.h>
  CloseWindow();
  
}

bool raylib__core__window_hyshould_hyclose() {
        #include <raylib.h>
  return WindowShouldClose();
  
}

void raylib__core__begin_hydrawing() {
        #include <raylib.h>
  BeginDrawing();
  
}

void raylib__core__end_hydrawing() {
        #include <raylib.h>
  EndDrawing();
  
}

void raylib__core__begin_hymode_hy3d(int64_t camera) {
        #include <raylib.h>
  Camera3D *cam = (Camera3D *)(intptr_t)camera;
  BeginMode3D(*cam);
  
}

void raylib__core__end_hymode_hy3d() {
        #include <raylib.h>
  EndMode3D();
  
}

void raylib__core__clear_hybackground(int64_t col) {
        #include <raylib.h>
  Color *c = (Color *)(intptr_t)col;
  ClearBackground(*c);
  
}

void raylib__core__set_hytarget_hyfps(int64_t fps) {
        #include <raylib.h>
  SetTargetFPS((int)fps);
  
}

double raylib__core__get_hyframe_hytime() {
        #include <raylib.h>
  return (double)GetFrameTime();
  
}


