/* generated by tur (phase 2) */
#ifndef TUR_raylib__input_H
#define TUR_raylib__input_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

bool raylib__input__is_hykey_hydown(int64_t);
bool raylib__input__is_hykey_hypressed(int64_t);
bool raylib__input__is_hykey_hyreleased(int64_t);
bool raylib__input__is_hymouse_hybutton_hydown(int64_t);
bool raylib__input__is_hymouse_hybutton_hypressed(int64_t);
int64_t raylib__input__get_hymouse_hyposition();
int64_t raylib__input__get_hymouse_hydelta();
double raylib__input__get_hymouse_hywheel_hymove();
#endif /* TUR_raylib__input_H */
