/* generated by tur (phase 2) */
#ifndef TUR_raylib__camera_H
#define TUR_raylib__camera_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int64_t raylib__camera__camera_hy3d(double, double, double, double, double, double, double, double, double, double, int64_t);
int64_t raylib__camera__camera_hy2d(double, double, double, double, double, double);
void raylib__camera__update_hycamera(int64_t, int64_t);
#endif /* TUR_raylib__camera_H */
