/* generated by tur (phase 2) */
#ifndef TUR_raylib__audio_H
#define TUR_raylib__audio_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void raylib__audio__init_hyaudio_hydevice();
void raylib__audio__close_hyaudio_hydevice();
int64_t raylib__audio__load_hysound(const char *);
void raylib__audio__unload_hysound(int64_t);
void raylib__audio__play_hysound(int64_t);
int64_t raylib__audio__load_hymusic_hystream(const char *);
void raylib__audio__unload_hymusic_hystream(int64_t);
void raylib__audio__play_hymusic_hystream(int64_t);
void raylib__audio__update_hymusic_hystream(int64_t);
#endif /* TUR_raylib__audio_H */
