/* generated by tur (phase 2) */
#ifndef TUR_osc__msg_H
#define TUR_osc__msg_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int64_t osc__msg__msg_hynew(const char *);
void osc__msg__msg_hyadd_hyfloat(int64_t, double);
void osc__msg__msg_hyadd_hyint(int64_t, int64_t);
void osc__msg__msg_hyadd_hystring(int64_t, const char *);
void osc__msg__msg_hyfree(int64_t);
const char * osc__msg__msg_hypath(int64_t);
int64_t osc__msg__msg_hyarg_hycount(int64_t);
const char * osc__msg__msg_hyarg_hytype(int64_t, int64_t);
double osc__msg__msg_hyarg_hyfloat(int64_t, int64_t);
int64_t osc__msg__msg_hyarg_hyint(int64_t, int64_t);
const char * osc__msg__msg_hyarg_hystring(int64_t, int64_t);
#endif /* TUR_osc__msg_H */
