/* generated by tur (phase 2) */
#include "osc__msg.h"

int64_t osc__msg__msg_hynew(const char *);
void osc__msg__msg_hyadd_hyfloat(int64_t, double);
void osc__msg__msg_hyadd_hyint(int64_t, int64_t);
void osc__msg__msg_hyadd_hystring(int64_t, const char *);
void osc__msg__msg_hyfree(int64_t);
const char * osc__msg__msg_hypath(int64_t);
int64_t osc__msg__msg_hyarg_hycount(int64_t);
const char * osc__msg__msg_hyarg_hytype(int64_t, int64_t);
double osc__msg__msg_hyarg_hyfloat(int64_t, int64_t);
int64_t osc__msg__msg_hyarg_hyint(int64_t, int64_t);
const char * osc__msg__msg_hyarg_hystring(int64_t, int64_t);

int64_t osc__msg__msg_hynew(const char * path) {
        #include <stdlib.h>
  #include <string.h>
  #include <lo/lo.h>
  struct __msg_wrapper { char *path; lo_message msg; };
  struct __msg_wrapper *w = malloc(sizeof(*w));
  w->path = strdup((const char *)path);
  w->msg  = lo_message_new();
  return (int64_t)(intptr_t)w;
  
}

void osc__msg__msg_hyadd_hyfloat(int64_t m, double f) {
        #include <lo/lo.h>
  struct __msg_wrapper { char *path; lo_message msg; };
  struct __msg_wrapper *w = (struct __msg_wrapper *)(intptr_t)m;
  lo_message_add_float(w->msg, (float)f);
  
}

void osc__msg__msg_hyadd_hyint(int64_t m, int64_t i) {
        #include <lo/lo.h>
  struct __msg_wrapper { char *path; lo_message msg; };
  struct __msg_wrapper *w = (struct __msg_wrapper *)(intptr_t)m;
  lo_message_add_int32(w->msg, (int32_t)i);
  
}

void osc__msg__msg_hyadd_hystring(int64_t m, const char * s) {
        #include <lo/lo.h>
  struct __msg_wrapper { char *path; lo_message msg; };
  struct __msg_wrapper *w = (struct __msg_wrapper *)(intptr_t)m;
  lo_message_add_string(w->msg, (const char *)s);
  
}

void osc__msg__msg_hyfree(int64_t m) {
        #include <stdlib.h>
  #include <lo/lo.h>
  struct __msg_wrapper { char *path; lo_message msg; };
  struct __msg_wrapper *w = (struct __msg_wrapper *)(intptr_t)m;
  lo_message_free(w->msg);
  free(w->path);
  free(w);
  
}

const char * osc__msg__msg_hypath(int64_t m) {
        struct __msg_wrapper { char *path; void *msg; };
  return ((struct __msg_wrapper *)(intptr_t)m)->path;
  
}

int64_t osc__msg__msg_hyarg_hycount(int64_t m) {
        #include <lo/lo.h>
  struct __msg_wrapper { char *path; lo_message msg; };
  struct __msg_wrapper *w = (struct __msg_wrapper *)(intptr_t)m;
  return (int64_t)lo_message_get_argc(w->msg);
  
}

const char * osc__msg__msg_hyarg_hytype(int64_t m, int64_t i) {
        #include <stdlib.h>
  #include <lo/lo.h>
  struct __msg_wrapper { char *path; lo_message msg; };
  struct __msg_wrapper *w = (struct __msg_wrapper *)(intptr_t)m;
  const char *types = lo_message_get_types(w->msg);
  static char buf[2];
  buf[0] = types ? types[i] : '?';
  buf[1] = '\0';
  return buf;
  
}

double osc__msg__msg_hyarg_hyfloat(int64_t m, int64_t i) {
        #include <lo/lo.h>
  struct __msg_wrapper { char *path; lo_message msg; };
  struct __msg_wrapper *w = (struct __msg_wrapper *)(intptr_t)m;
  lo_arg **argv = lo_message_get_argv(w->msg);
  return (double)argv[i]->f;
  
}

int64_t osc__msg__msg_hyarg_hyint(int64_t m, int64_t i) {
        #include <lo/lo.h>
  struct __msg_wrapper { char *path; lo_message msg; };
  struct __msg_wrapper *w = (struct __msg_wrapper *)(intptr_t)m;
  lo_arg **argv = lo_message_get_argv(w->msg);
  return (int64_t)argv[i]->i32;
  
}

const char * osc__msg__msg_hyarg_hystring(int64_t m, int64_t i) {
        #include <lo/lo.h>
  struct __msg_wrapper { char *path; lo_message msg; };
  struct __msg_wrapper *w = (struct __msg_wrapper *)(intptr_t)m;
  lo_arg **argv = lo_message_get_argv(w->msg);
  return (char *)&argv[i]->s;
  
}


