/* generated by tur (phase 2) */
#include "osc__client.h"

static void * osc__client____ok(int64_t);
static void * osc__client____err(int64_t);
void * osc__client__client_hynew(const char *, const char *, const char *);
void osc__client__client_hyfree(int64_t);
void * osc__client__client_hysend(int64_t, int64_t);
void * osc__client__client_hysend_hybundle(int64_t, int64_t);

static void * osc__client____ok(int64_t v) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = true; r->ok_val = v; r->err_val = 0; return r;
  
}

static void * osc__client____err(int64_t e) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = false; r->ok_val = 0; r->err_val = e; return r;
  
}

void * osc__client__client_hynew(const char * host, const char * port, const char * proto) {
        #include <stdlib.h>
  #include <lo/lo.h>
  (void)proto; /* lo_address_new always uses UDP; proto reserved */
  lo_address addr = lo_address_new((const char *)host, (const char *)port);
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  if (!addr) {
    r->is_ok = false; r->ok_val = 0; r->err_val = 0;
  } else {
    r->is_ok = true; r->ok_val = (int64_t)(intptr_t)addr; r->err_val = 0;
  }
  return r;
  
}

void osc__client__client_hyfree(int64_t c) {
        #include <lo/lo.h>
  lo_address_free((lo_address)(intptr_t)c);
  
}

void * osc__client__client_hysend(int64_t c, int64_t m) {
        #include <stdlib.h>
  #include <lo/lo.h>
  struct __msg_wrapper { char *path; lo_message msg; };
  lo_address addr = (lo_address)(intptr_t)c;
  struct __msg_wrapper *w = (struct __msg_wrapper *)(intptr_t)m;
  int rc = lo_send_message(addr, w->path, w->msg);
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  if (rc < 0) {
    r->is_ok = false; r->ok_val = 0; r->err_val = (int64_t)rc;
  } else {
    r->is_ok = true; r->ok_val = 0; r->err_val = 0;
  }
  return r;
  
}

void * osc__client__client_hysend_hybundle(int64_t c, int64_t bundle) {
        #include <stdlib.h>
  #include <lo/lo.h>
  lo_address addr = (lo_address)(intptr_t)c;
  int rc = lo_send_bundle(addr, (lo_bundle)(intptr_t)bundle);
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  if (rc < 0) {
    r->is_ok = false; r->ok_val = 0; r->err_val = (int64_t)rc;
  } else {
    r->is_ok = true; r->ok_val = 0; r->err_val = 0;
  }
  return r;
  
}


