/* generated by tur (phase 2) */
#ifndef TUR_osc__server_H
#define TUR_osc__server_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void * osc__server__server_hynew(const char *, const char *);
void * osc__server__server_hynew_hytcp(const char *);
void osc__server__server_hyfree(int64_t);
void osc__server__server_hyadd_hymethod(int64_t, const char *, const char *, int64_t);
int64_t osc__server__server_hyrecv(int64_t, int64_t);
int64_t osc__server__server_hyrecv_hynoblock(int64_t);
#endif /* TUR_osc__server_H */
