/* generated by tur (phase 2) */
#ifndef TUR_osc__client_H
#define TUR_osc__client_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void * osc__client__client_hynew(const char *, const char *, const char *);
void osc__client__client_hyfree(int64_t);
void * osc__client__client_hysend(int64_t, int64_t);
void * osc__client__client_hysend_hybundle(int64_t, int64_t);
#endif /* TUR_osc__client_H */
