/* generated by tur (phase 2) */
#ifndef TUR_signal__compose_H
#define TUR_signal__compose_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void * signal__compose__effects_hychain(int64_t, double);
#endif /* TUR_signal__compose_H */
