/* generated by tur (phase 2) */
#include "signal__envelope.h"

typedef double (*tur_thunk_double_double_t)(void *, double);

static double signal__envelope____fn_25(void *, double);
static void * signal__envelope____fn_30(void *, void *);
static double signal__envelope____adsr_attack(int64_t);
static double signal__envelope____adsr_decay(int64_t);
static double signal__envelope____adsr_sustain(int64_t);
static double signal__envelope____adsr_release(int64_t);
static double signal__envelope____adsr_fixed_sample(double, double, double, double, double, double);
void * signal__envelope__adsr_hyfixed(int64_t, double);
void * signal__envelope__adsr_hygen(int64_t);

struct __env_27 { tur_thunk_double_double_t __fn; int64_t pv; double gd; };
static double signal__envelope____fn_25(void * __env_p_28, double t) {
        struct __env_27 *__env___env_27 = (struct __env_27 *)__env_p_28;
        return signal__envelope____adsr_fixed_sample(signal__envelope____adsr_attack(__env___env_27->pv), signal__envelope____adsr_decay(__env___env_27->pv), signal__envelope____adsr_sustain(__env___env_27->pv), signal__envelope____adsr_release(__env___env_27->pv), __env___env_27->gd, t);
}

struct __env_32 { int64_t __fn; int64_t pv; double gd; };
static void * signal__envelope____fn_30(void * __env_p_33, void * _sig) {
        struct __env_32 *__env___env_32 = (struct __env_32 *)__env_p_33;
        struct __env_27 *__t0 = (struct __env_27 *)malloc(sizeof(struct __env_27));
        __t0->__fn = (tur_thunk_double_double_t)signal__envelope____fn_25;
        __t0->pv = __env___env_32->pv;
        __t0->gd = __env___env_32->gd;
        void *__t1 = __t0;
        return __t1;
}

static double signal__envelope____adsr_attack(int64_t p) {
        typedef struct { double attack; double decay; double sustain; double release; } ADSRParams_;
  return ((ADSRParams_ *)(intptr_t)p)->attack;
  
}

static double signal__envelope____adsr_decay(int64_t p) {
        typedef struct { double attack; double decay; double sustain; double release; } ADSRParams_;
  return ((ADSRParams_ *)(intptr_t)p)->decay;
  
}

static double signal__envelope____adsr_sustain(int64_t p) {
        typedef struct { double attack; double decay; double sustain; double release; } ADSRParams_;
  return ((ADSRParams_ *)(intptr_t)p)->sustain;
  
}

static double signal__envelope____adsr_release(int64_t p) {
        typedef struct { double attack; double decay; double sustain; double release; } ADSRParams_;
  return ((ADSRParams_ *)(intptr_t)p)->release;
  
}

static double signal__envelope____adsr_fixed_sample(double attack, double decay, double sustain, double release, double gate_dur, double t) {
        double a = attack, dc = decay, s = sustain, r = release, gd = gate_dur, tv = t;
  if (tv <= a)
    return (a > 0.0) ? (tv / a) : 1.0;
  if (tv <= a + dc) {
    double decay_t = tv - a;
    return 1.0 + (s - 1.0) * ((dc > 0.0) ? (decay_t / dc) : 1.0);
  }
  if (tv <= gd) return s;
  if (tv <= gd + r) {
    double rel_t = tv - gd;
    double v = s * (1.0 - ((r > 0.0) ? (rel_t / r) : 1.0));
    return (v < 0.0) ? 0.0 : v;
  }
  return 0.0;
  
}

void * signal__envelope__adsr_hyfixed(int64_t params, double gate_duration) {
        void * __t2;
        {
            int64_t pv_21 = params;
            (void)pv_21;
            double gd_22 = gate_duration;
            (void)gd_22;
            struct __env_32 *__t3 = (struct __env_32 *)malloc(sizeof(struct __env_32));
            __t3->__fn = (int64_t)(intptr_t)signal__envelope____fn_30;
            __t3->pv = pv_21;
            __t3->gd = gd_22;
            void *__t4 = __t3;
            __t2 = __t4;
        }
        return __t2;
}

void * signal__envelope__adsr_hygen(int64_t params) {
        return signal__envelope__adsr_hyfixed(params, 1.0);
}


