/* generated by tur (phase 2) */
#ifndef TUR_signal__osc_H
#define TUR_signal__osc_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void * signal__osc__sine(double, double);
void * signal__osc__square(double, double);
void * signal__osc__sawtooth(double);
void * signal__osc__triangle(double);
#endif /* TUR_signal__osc_H */
