/* generated by tur (phase 2) */
#include "signal__filter.h"

typedef double (*tur_thunk_double_double_t)(void *, double);

static double signal__filter____fn_17(void *, double);
static void * signal__filter____fn_22(void *, int64_t);
static double signal__filter____fn_32(void *, double);
static void * signal__filter____fn_37(void *, int64_t);
static int64_t signal__filter____filter_alloc_state();
static double signal__filter____filter_lp_step(int64_t, double, double);
static double signal__filter____filter_hp_step(int64_t, double, double);
void * signal__filter__low_hypass(double);
void * signal__filter__high_hypass(double);

struct __env_19 { tur_thunk_double_double_t __fn; int64_t state; double av; int64_t sig; };
static double signal__filter____fn_17(void * __env_p_20, double t) {
        struct __env_19 *__env___env_19 = (struct __env_19 *)__env_p_20;
        return signal__filter____filter_lp_step(__env___env_19->state, __env___env_19->av, (*( tur_thunk_double_double_t *)((void *)(intptr_t)(__env___env_19->sig)))((void *)(intptr_t)(__env___env_19->sig), t));
}

struct __env_24 { int64_t __fn; double av; };
static void * signal__filter____fn_22(void * __env_p_25, int64_t sig) {
        struct __env_24 *__env___env_24 = (struct __env_24 *)__env_p_25;
        void * __t0;
        {
            int64_t state_15 = signal__filter____filter_alloc_state();
            (void)state_15;
            struct __env_19 *__t1 = (struct __env_19 *)malloc(sizeof(struct __env_19));
            __t1->__fn = (tur_thunk_double_double_t)signal__filter____fn_17;
            __t1->state = state_15;
            __t1->av = __env___env_24->av;
            __t1->sig = sig;
            void *__t2 = __t1;
            __t0 = __t2;
        }
        return __t0;
}

struct __env_34 { tur_thunk_double_double_t __fn; int64_t state; double av; int64_t sig; };
static double signal__filter____fn_32(void * __env_p_35, double t) {
        struct __env_34 *__env___env_34 = (struct __env_34 *)__env_p_35;
        return signal__filter____filter_hp_step(__env___env_34->state, __env___env_34->av, (*( tur_thunk_double_double_t *)((void *)(intptr_t)(__env___env_34->sig)))((void *)(intptr_t)(__env___env_34->sig), t));
}

struct __env_39 { int64_t __fn; double av; };
static void * signal__filter____fn_37(void * __env_p_40, int64_t sig) {
        struct __env_39 *__env___env_39 = (struct __env_39 *)__env_p_40;
        void * __t3;
        {
            int64_t state_30 = signal__filter____filter_alloc_state();
            (void)state_30;
            struct __env_34 *__t4 = (struct __env_34 *)malloc(sizeof(struct __env_34));
            __t4->__fn = (tur_thunk_double_double_t)signal__filter____fn_32;
            __t4->state = state_30;
            __t4->av = __env___env_39->av;
            __t4->sig = sig;
            void *__t5 = __t4;
            __t3 = __t5;
        }
        return __t3;
}

static int64_t signal__filter____filter_alloc_state() {
        double *p = (double *)calloc(1, sizeof(double));
  if (!p) { fprintf(stderr, "filter: state alloc failed\n"); abort(); }
  return (int64_t)(intptr_t)p;
  
}

static double signal__filter____filter_lp_step(int64_t state, double alpha, double x) {
        double *prev = (double *)(intptr_t)state;
  double y = alpha * x + (1.0 - alpha) * (*prev);
  *prev = y;
  return y;
  
}

static double signal__filter____filter_hp_step(int64_t state, double alpha, double x) {
        double *prev_lp = (double *)(intptr_t)state;
  double lp = alpha * x + (1.0 - alpha) * (*prev_lp);
  *prev_lp = lp;
  return x - lp;
  
}

void * signal__filter__low_hypass(double alpha) {
        void * __t6;
        {
            double av_13 = alpha;
            (void)av_13;
            struct __env_24 *__t7 = (struct __env_24 *)malloc(sizeof(struct __env_24));
            __t7->__fn = (int64_t)(intptr_t)signal__filter____fn_22;
            __t7->av = av_13;
            void *__t8 = __t7;
            __t6 = __t8;
        }
        return __t6;
}

void * signal__filter__high_hypass(double alpha) {
        void * __t9;
        {
            double av_28 = alpha;
            (void)av_28;
            struct __env_39 *__t10 = (struct __env_39 *)malloc(sizeof(struct __env_39));
            __t10->__fn = (int64_t)(intptr_t)signal__filter____fn_37;
            __t10->av = av_28;
            void *__t11 = __t10;
            __t9 = __t11;
        }
        return __t9;
}


