/* generated by tur (phase 2) */
#ifndef TUR_signal__core_H
#define TUR_signal__core_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void * signal__core__constant(double);
double signal__core__time_hysignal(double);
double signal__core__sample(int64_t, double);
int64_t signal__core__map_hysignal(int64_t, int64_t);
void * signal__core__pair_hysignals(int64_t, int64_t);
#endif /* TUR_signal__core_H */
