/* generated by tur (phase 2) */
#include "signal__shaper.h"

typedef double (*tur_thunk_double_double_t)(void *, double);
typedef void * (*tur_thunk_void___double_t)(void *, double);

static double signal__shaper____fn_24(void *, double);
static void * signal__shaper____fn_29(void *, int64_t);
static double signal__shaper____fn_38(void *, double);
static void * signal__shaper____fn_43(void *, int64_t);
static double signal__shaper____fn_50(void *, double);
static void * signal__shaper____fn_55(int64_t);
static double signal__shaper____fn_59(void *, double);
static void * signal__shaper____fn_64(int64_t);
static double signal__shaper____fn_76(void *, double);
static void * signal__shaper____fn_81(void *, int64_t);
static double signal__shaper____fn_91(void *, double);
static void * signal__shaper____fn_96(void *, int64_t);
static double signal__shaper____fn_108(void *, double);
static void * signal__shaper____fn_113(void *, int64_t);
static double signal__shaper____fn_125(void *, double);
static void * signal__shaper____fn_130(void *, int64_t);
static double signal__shaper____fn_138(void *, double);
static void * signal__shaper____fn_143(int64_t);
static double signal__shaper____fn_148(void *, double);
static void * signal__shaper____fn_153(int64_t);
static double signal__shaper___un_unpair_hyfst_hyf(void *);
static double signal__shaper___un_unpair_hysnd_hyf(void *);
static double signal__shaper____shaper_fabs(double);
static double signal__shaper____shaper_tanh(double);
void * signal__shaper__gain(double);
void * signal__shaper__offset(double);
int64_t signal__shaper__invert();
int64_t signal__shaper__abs_hysf();
double signal__shaper__scale(double, double, double, double, double);
void * signal__shaper__saturate_hytanh(double);
void * signal__shaper__hard_hyclip(double);
void * signal__shaper__clip(double, double);
void * signal__shaper__mix(double);
int64_t signal__shaper__add();
int64_t signal__shaper__multiply();

struct __env_26 { tur_thunk_double_double_t __fn; double gv; int64_t sig; };
static double signal__shaper____fn_24(void * __env_p_27, double t) {
        struct __env_26 *__env___env_26 = (struct __env_26 *)__env_p_27;
        return (__env___env_26->gv) * ((*( tur_thunk_double_double_t *)((void *)(intptr_t)(__env___env_26->sig)))((void *)(intptr_t)(__env___env_26->sig), t));
}

struct __env_31 { int64_t __fn; double gv; };
static void * signal__shaper____fn_29(void * __env_p_32, int64_t sig) {
        struct __env_31 *__env___env_31 = (struct __env_31 *)__env_p_32;
        struct __env_26 *__t0 = (struct __env_26 *)malloc(sizeof(struct __env_26));
        __t0->__fn = (tur_thunk_double_double_t)signal__shaper____fn_24;
        __t0->gv = __env___env_31->gv;
        __t0->sig = sig;
        void *__t1 = __t0;
        return __t1;
}

struct __env_40 { tur_thunk_double_double_t __fn; double cv; int64_t sig; };
static double signal__shaper____fn_38(void * __env_p_41, double t) {
        struct __env_40 *__env___env_40 = (struct __env_40 *)__env_p_41;
        return (__env___env_40->cv) + ((*( tur_thunk_double_double_t *)((void *)(intptr_t)(__env___env_40->sig)))((void *)(intptr_t)(__env___env_40->sig), t));
}

struct __env_45 { int64_t __fn; double cv; };
static void * signal__shaper____fn_43(void * __env_p_46, int64_t sig) {
        struct __env_45 *__env___env_45 = (struct __env_45 *)__env_p_46;
        struct __env_40 *__t2 = (struct __env_40 *)malloc(sizeof(struct __env_40));
        __t2->__fn = (tur_thunk_double_double_t)signal__shaper____fn_38;
        __t2->cv = __env___env_45->cv;
        __t2->sig = sig;
        void *__t3 = __t2;
        return __t3;
}

struct __env_52 { tur_thunk_double_double_t __fn; int64_t sig; };
static double signal__shaper____fn_50(void * __env_p_53, double t) {
        struct __env_52 *__env___env_52 = (struct __env_52 *)__env_p_53;
        return (0.0) - ((*( tur_thunk_double_double_t *)((void *)(intptr_t)(__env___env_52->sig)))((void *)(intptr_t)(__env___env_52->sig), t));
}

static void * signal__shaper____fn_55(int64_t sig) {
        struct __env_52 *__t4 = (struct __env_52 *)malloc(sizeof(struct __env_52));
        __t4->__fn = (tur_thunk_double_double_t)signal__shaper____fn_50;
        __t4->sig = sig;
        void *__t5 = __t4;
        return __t5;
}

struct __env_61 { tur_thunk_double_double_t __fn; int64_t sig; };
static double signal__shaper____fn_59(void * __env_p_62, double t) {
        struct __env_61 *__env___env_61 = (struct __env_61 *)__env_p_62;
        return signal__shaper____shaper_fabs((*( tur_thunk_double_double_t *)((void *)(intptr_t)(__env___env_61->sig)))((void *)(intptr_t)(__env___env_61->sig), t));
}

static void * signal__shaper____fn_64(int64_t sig) {
        struct __env_61 *__t6 = (struct __env_61 *)malloc(sizeof(struct __env_61));
        __t6->__fn = (tur_thunk_double_double_t)signal__shaper____fn_59;
        __t6->sig = sig;
        void *__t7 = __t6;
        return __t7;
}

struct __env_78 { tur_thunk_double_double_t __fn; double dv; int64_t sig; double peak; };
static double signal__shaper____fn_76(void * __env_p_79, double t) {
        struct __env_78 *__env___env_78 = (struct __env_78 *)__env_p_79;
        return ((__env___env_78->peak) ? ((signal__shaper____shaper_tanh((__env___env_78->dv) * ((*( tur_thunk_double_double_t *)((void *)(intptr_t)(__env___env_78->sig)))((void *)(intptr_t)(__env___env_78->sig), t)))) / (__env___env_78->peak)) : (fprintf(stderr, "division by zero\n"), abort(), 0));
}

struct __env_83 { int64_t __fn; double dv; double peak; };
static void * signal__shaper____fn_81(void * __env_p_84, int64_t sig) {
        struct __env_83 *__env___env_83 = (struct __env_83 *)__env_p_84;
        struct __env_78 *__t8 = (struct __env_78 *)malloc(sizeof(struct __env_78));
        __t8->__fn = (tur_thunk_double_double_t)signal__shaper____fn_76;
        __t8->dv = __env___env_83->dv;
        __t8->sig = sig;
        __t8->peak = __env___env_83->peak;
        void *__t9 = __t8;
        return __t9;
}

struct __env_93 { tur_thunk_double_double_t __fn; double lv; int64_t sig; };
static double signal__shaper____fn_91(void * __env_p_94, double t) {
        struct __env_93 *__env___env_93 = (struct __env_93 *)__env_p_94;
        double __t10;
        {
            double x_90 = (*( tur_thunk_double_double_t *)((void *)(intptr_t)(__env___env_93->sig)))((void *)(intptr_t)(__env___env_93->sig), t);
            (void)x_90;
            double __t11;
            if ((x_90) < ((0.0) - (__env___env_93->lv))) {
                __t11 = (0.0) - (__env___env_93->lv);
            } else {
                double __t12;
                if ((__env___env_93->lv) < (x_90)) {
                    __t12 = __env___env_93->lv;
                } else {
                    __t12 = x_90;
                }
                __t11 = __t12;
            }
            __t10 = __t11;
        }
        return __t10;
}

struct __env_98 { int64_t __fn; double lv; };
static void * signal__shaper____fn_96(void * __env_p_99, int64_t sig) {
        struct __env_98 *__env___env_98 = (struct __env_98 *)__env_p_99;
        struct __env_93 *__t13 = (struct __env_93 *)malloc(sizeof(struct __env_93));
        __t13->__fn = (tur_thunk_double_double_t)signal__shaper____fn_91;
        __t13->lv = __env___env_98->lv;
        __t13->sig = sig;
        void *__t14 = __t13;
        return __t14;
}

struct __env_110 { tur_thunk_double_double_t __fn; double lv; double hv; int64_t sig; };
static double signal__shaper____fn_108(void * __env_p_111, double t) {
        struct __env_110 *__env___env_110 = (struct __env_110 *)__env_p_111;
        double __t15;
        {
            double x_107 = (*( tur_thunk_double_double_t *)((void *)(intptr_t)(__env___env_110->sig)))((void *)(intptr_t)(__env___env_110->sig), t);
            (void)x_107;
            double __t16;
            if ((x_107) < (__env___env_110->lv)) {
                __t16 = __env___env_110->lv;
            } else {
                double __t17;
                if ((__env___env_110->hv) < (x_107)) {
                    __t17 = __env___env_110->hv;
                } else {
                    __t17 = x_107;
                }
                __t16 = __t17;
            }
            __t15 = __t16;
        }
        return __t15;
}

struct __env_115 { int64_t __fn; double lv; double hv; };
static void * signal__shaper____fn_113(void * __env_p_116, int64_t sig) {
        struct __env_115 *__env___env_115 = (struct __env_115 *)__env_p_116;
        struct __env_110 *__t18 = (struct __env_110 *)malloc(sizeof(struct __env_110));
        __t18->__fn = (tur_thunk_double_double_t)signal__shaper____fn_108;
        __t18->lv = __env___env_115->lv;
        __t18->hv = __env___env_115->hv;
        __t18->sig = sig;
        void *__t19 = __t18;
        return __t19;
}

struct __env_127 { tur_thunk_double_double_t __fn; double av; int64_t prod_sig; };
static double signal__shaper____fn_125(void * __env_p_128, double t) {
        struct __env_127 *__env___env_127 = (struct __env_127 *)__env_p_128;
        double __t20;
        {
            void * p_122 = (*( tur_thunk_void___double_t *)((void *)(intptr_t)(__env___env_127->prod_sig)))((void *)(intptr_t)(__env___env_127->prod_sig), t);
            (void)p_122;
            double x_123 = signal__shaper___un_unpair_hyfst_hyf((void *)(intptr_t)(p_122));
            (void)x_123;
            double y_124 = signal__shaper___un_unpair_hysnd_hyf((void *)(intptr_t)(p_122));
            (void)y_124;
            __t20 = ((__env___env_127->av) * (x_123)) + (((1.0) - (__env___env_127->av)) * (y_124));
        }
        return __t20;
}

struct __env_132 { int64_t __fn; double av; };
static void * signal__shaper____fn_130(void * __env_p_133, int64_t prod_sig) {
        struct __env_132 *__env___env_132 = (struct __env_132 *)__env_p_133;
        struct __env_127 *__t21 = (struct __env_127 *)malloc(sizeof(struct __env_127));
        __t21->__fn = (tur_thunk_double_double_t)signal__shaper____fn_125;
        __t21->av = __env___env_132->av;
        __t21->prod_sig = prod_sig;
        void *__t22 = __t21;
        return __t22;
}

struct __env_140 { tur_thunk_double_double_t __fn; int64_t prod_sig; };
static double signal__shaper____fn_138(void * __env_p_141, double t) {
        struct __env_140 *__env___env_140 = (struct __env_140 *)__env_p_141;
        double __t23;
        {
            void * p_137 = (*( tur_thunk_void___double_t *)((void *)(intptr_t)(__env___env_140->prod_sig)))((void *)(intptr_t)(__env___env_140->prod_sig), t);
            (void)p_137;
            __t23 = (signal__shaper___un_unpair_hyfst_hyf((void *)(intptr_t)(p_137))) + (signal__shaper___un_unpair_hysnd_hyf((void *)(intptr_t)(p_137)));
        }
        return __t23;
}

static void * signal__shaper____fn_143(int64_t prod_sig) {
        struct __env_140 *__t24 = (struct __env_140 *)malloc(sizeof(struct __env_140));
        __t24->__fn = (tur_thunk_double_double_t)signal__shaper____fn_138;
        __t24->prod_sig = prod_sig;
        void *__t25 = __t24;
        return __t25;
}

struct __env_150 { tur_thunk_double_double_t __fn; int64_t prod_sig; };
static double signal__shaper____fn_148(void * __env_p_151, double t) {
        struct __env_150 *__env___env_150 = (struct __env_150 *)__env_p_151;
        double __t26;
        {
            void * p_147 = (*( tur_thunk_void___double_t *)((void *)(intptr_t)(__env___env_150->prod_sig)))((void *)(intptr_t)(__env___env_150->prod_sig), t);
            (void)p_147;
            __t26 = (signal__shaper___un_unpair_hyfst_hyf((void *)(intptr_t)(p_147))) * (signal__shaper___un_unpair_hysnd_hyf((void *)(intptr_t)(p_147)));
        }
        return __t26;
}

static void * signal__shaper____fn_153(int64_t prod_sig) {
        struct __env_150 *__t27 = (struct __env_150 *)malloc(sizeof(struct __env_150));
        __t27->__fn = (tur_thunk_double_double_t)signal__shaper____fn_148;
        __t27->prod_sig = prod_sig;
        void *__t28 = __t27;
        return __t28;
}

static double signal__shaper___un_unpair_hyfst_hyf(void * p) {
        struct { double fst; double snd; } *q = (void*)(intptr_t)p;
  return q->fst;
  
}

static double signal__shaper___un_unpair_hysnd_hyf(void * p) {
        struct { double fst; double snd; } *q = (void*)(intptr_t)p;
  return q->snd;
  
}

static double signal__shaper____shaper_fabs(double x) {
        extern double fabs(double);
  return fabs(x);
  
}

static double signal__shaper____shaper_tanh(double x) {
        extern double tanh(double);
  return tanh(x);
  
}

void * signal__shaper__gain(double g) {
        void * __t29;
        {
            double gv_21 = g;
            (void)gv_21;
            struct __env_31 *__t30 = (struct __env_31 *)malloc(sizeof(struct __env_31));
            __t30->__fn = (int64_t)(intptr_t)signal__shaper____fn_29;
            __t30->gv = gv_21;
            void *__t31 = __t30;
            __t29 = __t31;
        }
        return __t29;
}

void * signal__shaper__offset(double c) {
        void * __t32;
        {
            double cv_35 = c;
            (void)cv_35;
            struct __env_45 *__t33 = (struct __env_45 *)malloc(sizeof(struct __env_45));
            __t33->__fn = (int64_t)(intptr_t)signal__shaper____fn_43;
            __t33->cv = cv_35;
            void *__t34 = __t33;
            __t32 = __t34;
        }
        return __t32;
}

int64_t signal__shaper__invert() {
        return (int64_t)(intptr_t)signal__shaper____fn_55;
}

int64_t signal__shaper__abs_hysf() {
        return (int64_t)(intptr_t)signal__shaper____fn_64;
}

double signal__shaper__scale(double in_lo, double in_hi, double out_lo, double out_hi, double x) {
        return (out_lo) + (((out_hi) - (out_lo)) * ((((in_hi) - (in_lo)) ? (((x) - (in_lo)) / ((in_hi) - (in_lo))) : (fprintf(stderr, "division by zero\n"), abort(), 0))));
}

void * signal__shaper__saturate_hytanh(double drive) {
        void * __t35;
        {
            double dv_72 = drive;
            (void)dv_72;
            double peak_73 = signal__shaper____shaper_tanh(drive);
            (void)peak_73;
            struct __env_83 *__t36 = (struct __env_83 *)malloc(sizeof(struct __env_83));
            __t36->__fn = (int64_t)(intptr_t)signal__shaper____fn_81;
            __t36->dv = dv_72;
            __t36->peak = peak_73;
            void *__t37 = __t36;
            __t35 = __t37;
        }
        return __t35;
}

void * signal__shaper__hard_hyclip(double limit) {
        void * __t38;
        {
            double lv_87 = limit;
            (void)lv_87;
            struct __env_98 *__t39 = (struct __env_98 *)malloc(sizeof(struct __env_98));
            __t39->__fn = (int64_t)(intptr_t)signal__shaper____fn_96;
            __t39->lv = lv_87;
            void *__t40 = __t39;
            __t38 = __t40;
        }
        return __t38;
}

void * signal__shaper__clip(double lo, double hi) {
        void * __t41;
        {
            double lv_103 = lo;
            (void)lv_103;
            double hv_104 = hi;
            (void)hv_104;
            struct __env_115 *__t42 = (struct __env_115 *)malloc(sizeof(struct __env_115));
            __t42->__fn = (int64_t)(intptr_t)signal__shaper____fn_113;
            __t42->lv = lv_103;
            __t42->hv = hv_104;
            void *__t43 = __t42;
            __t41 = __t43;
        }
        return __t41;
}

void * signal__shaper__mix(double alpha) {
        void * __t44;
        {
            double av_119 = alpha;
            (void)av_119;
            struct __env_132 *__t45 = (struct __env_132 *)malloc(sizeof(struct __env_132));
            __t45->__fn = (int64_t)(intptr_t)signal__shaper____fn_130;
            __t45->av = av_119;
            void *__t46 = __t45;
            __t44 = __t46;
        }
        return __t44;
}

int64_t signal__shaper__add() {
        return (int64_t)(intptr_t)signal__shaper____fn_143;
}

int64_t signal__shaper__multiply() {
        return (int64_t)(intptr_t)signal__shaper____fn_153;
}


