/* generated by tur (phase 2) */
#ifndef TUR_c_dsl__core_H
#define TUR_c_dsl__core_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "c_dsl__codegen.h"
#include "c_dsl__types.h"

const char * c_hydsl__core__c_hylet1(const char *, const char *, const char *);
const char * c_hydsl__core__c_hylet1_hyuninit(const char *, const char *);
const char * c_hydsl__core__c_hyconst1(const char *, const char *, const char *);
const char * c_hydsl__core__c_hyset_ex(const char *, const char *);
const char * c_hydsl__core__c_hyreturn(const char *);
const char * c_hydsl__core__c_hyreturn_hyvoid();
const char * c_hydsl__core__c_hybreak();
const char * c_hydsl__core__c_hycontinue();
const char * c_hydsl__core__c_hyinc_ex(const char *);
const char * c_hydsl__core__c_hydec_ex(const char *);
const char * c_hydsl__core__c_hyif(const char *, const char *, const char *);
const char * c_hydsl__core__c_hyif_hyonly(const char *, const char *);
const char * c_hydsl__core__c_hywhile(const char *, const char *);
const char * c_hydsl__core__c_hydo_hywhile(const char *, const char *);
const char * c_hydsl__core__c_hyfor1(const char *, const char *, const char *, const char *, const char *, const char *);
const char * c_hydsl__core__c_hyfor_hyraw(const char *, const char *, const char *, const char *);
const char * c_hydsl__core__c_hycase(const char *, const char *);
const char * c_hydsl__core__c_hydefault_hycase(const char *);
const char * c_hydsl__core__c_hyswitch(const char *, int64_t);
const char * c_hydsl__core__c_hylabel(const char *);
const char * c_hydsl__core__c_hygoto(const char *);
const char * c_hydsl__core__c_hybinop(const char *, const char *, const char *);
const char * c_hydsl__core__c_hyunop(const char *, const char *);
const char * c_hydsl__core__c_hyternary(const char *, const char *, const char *);
#endif /* TUR_c_dsl__core_H */
