/* generated by tur (phase 2) */
#ifndef TUR_c_dsl__typedef_H
#define TUR_c_dsl__typedef_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "c_dsl__codegen.h"
#include "c_dsl__types.h"

const char * c_hydsl__typedef__c_hyfield(const char *, const char *);
const char * c_hydsl__typedef__c_hydefstruct(const char *, int64_t);
const char * c_hydsl__typedef__c_hydefunion(const char *, int64_t);
const char * c_hydsl__typedef__c_hydefenum(const char *, int64_t);
const char * c_hydsl__typedef__c_hytypedef(const char *, const char *);
#endif /* TUR_c_dsl__typedef_H */
