/* generated by tur (phase 2) */
#include "c_dsl__fns.h"

#ifndef __TUR_CONS_HELPER
#define __TUR_CONS_HELPER
/* F3: cons -- allocate a {head,tail} cons cell; return pointer as int64 */
static int64_t cons(int64_t h, int64_t t) {
    struct { int64_t head; int64_t tail; } *c = malloc(sizeof(*c));
    c->head = h; c->tail = t;
    return (int64_t)(intptr_t)c;
}
#endif
const char * c_hydsl__fns__c_hyparam(const char *, const char *);
static const char * c_hydsl__fns___un_unc_hydefn_hyimpl(const char *, const char *, int64_t, const char *, const char *);
const char * c_hydsl__fns__c_hydefn(const char *, int64_t, const char *, const char *);
const char * c_hydsl__fns__c_hydefn_hystatic(const char *, int64_t, const char *, const char *);
const char * c_hydsl__fns__c_hydefn_hyinline(const char *, int64_t, const char *, const char *);
const char * c_hydsl__fns__c_hycall(const char *, int64_t);
const char * c_hydsl__fns__c_hydeclare(const char *, const char *, int64_t);
const char * c_hydsl__fns__c_hyextern(const char *, const char *, int64_t);

const char * c_hydsl__fns__c_hyparam(const char * name, const char * type) {
        return c_hydsl__codegen__c_hysprintf2("%s %s", c_hydsl__types__c_hytype(type), name);
}

static const char * c_hydsl__fns___un_unc_hydefn_hyimpl(const char * prefix, const char * name, int64_t params, const char * ret, const char * body) {
        #include <stdio.h>
  #include <string.h>
  #include <stdlib.h>
  struct __cdsl_cons { int64_t value; int64_t next; };
  const char *spre   = (const char*)(intptr_t)prefix;
  const char *sname  = (const char*)(intptr_t)name;
  const char *sret   = (const char*)(intptr_t)ret;
  const char *sbody  = (const char*)(intptr_t)body;
  /* Join params with ", " */
  size_t total = 0;
  int count = 0;
  struct __cdsl_cons *cur = (void*)(intptr_t)params;
  while (cur) {
    total += strlen((const char*)(intptr_t)cur->value);
    count++;
    cur = (void*)(intptr_t)cur->next;
  }
  if (count > 1) total += 2 * (size_t)(count - 1);
  char *params_str = malloc(total + 1);
  char *p = params_str;
  cur = (void*)(intptr_t)params;
  int first = 1;
  while (cur) {
    if (!first) { *p++ = ','; *p++ = ' '; }
    const char *s = (const char*)(intptr_t)cur->value;
    size_t slen = strlen(s);
    memcpy(p, s, slen); p += slen;
    first = 0;
    cur = (void*)(intptr_t)cur->next;
  }
  *p = '\0';
  /* Indent body */
  size_t blen = strlen(sbody);
  int blines = 1;
  for (size_t i = 0; i < blen; i++) if (sbody[i] == '\n') blines++;
  char *ibody = malloc(blen + (size_t)blines * 4 + 1);
  char *ib = ibody;
  int at_start = 1;
  for (size_t i = 0; i < blen; i++) {
    if (at_start) { memcpy(ib, "    ", 4); ib += 4; at_start = 0; }
    *ib++ = sbody[i];
    if (sbody[i] == '\n') at_start = 1;
  }
  *ib = '\0';
  /* Assemble: prefix ret name(params) {\n    body\n} */
  int n = snprintf(NULL, 0, "%s%s %s(%s) {\n%s\n}",
                   spre, sret, sname, params_str, ibody);
  char *out = malloc(n + 1);
  snprintf(out, n + 1, "%s%s %s(%s) {\n%s\n}",
           spre, sret, sname, params_str, ibody);
  free(params_str);
  free(ibody);
  return out;
  
}

const char * c_hydsl__fns__c_hydefn(const char * name, int64_t params, const char * ret, const char * body) {
        return c_hydsl__fns___un_unc_hydefn_hyimpl("", name, params, c_hydsl__types__c_hytype(ret), body);
}

const char * c_hydsl__fns__c_hydefn_hystatic(const char * name, int64_t params, const char * ret, const char * body) {
        return c_hydsl__fns___un_unc_hydefn_hyimpl("static ", name, params, c_hydsl__types__c_hytype(ret), body);
}

const char * c_hydsl__fns__c_hydefn_hyinline(const char * name, int64_t params, const char * ret, const char * body) {
        return c_hydsl__fns___un_unc_hydefn_hyimpl("static inline ", name, params, c_hydsl__types__c_hytype(ret), body);
}

const char * c_hydsl__fns__c_hycall(const char * fn_name, int64_t args) {
        #include <string.h>
  #include <stdlib.h>
  struct __cdsl_cons { int64_t value; int64_t next; };
  const char *sfn = (const char*)(intptr_t)fn_name;
  size_t fnlen = strlen(sfn);
  size_t total = 0;
  int count = 0;
  struct __cdsl_cons *cur = (void*)(intptr_t)args;
  while (cur) {
    total += strlen((const char*)(intptr_t)cur->value);
    count++;
    cur = (void*)(intptr_t)cur->next;
  }
  if (count > 1) total += 2 * (size_t)(count - 1);
  /* sfn + "(" + args + ")" */
  char *out = malloc(fnlen + total + 3);
  char *p = out;
  memcpy(p, sfn, fnlen); p += fnlen;
  *p++ = '(';
  cur = (void*)(intptr_t)args;
  int first = 1;
  while (cur) {
    if (!first) { *p++ = ','; *p++ = ' '; }
    const char *s = (const char*)(intptr_t)cur->value;
    size_t slen = strlen(s);
    memcpy(p, s, slen); p += slen;
    first = 0;
    cur = (void*)(intptr_t)cur->next;
  }
  *p++ = ')'; *p = '\0';
  return out;
  
}

const char * c_hydsl__fns__c_hydeclare(const char * ret, const char * name, int64_t params) {
        #include <string.h>
  #include <stdlib.h>
  struct __cdsl_cons { int64_t value; int64_t next; };
  const char *sret  = (const char*)(intptr_t)ret;
  const char *sname = (const char*)(intptr_t)name;
  size_t total = 0;
  int count = 0;
  struct __cdsl_cons *cur = (void*)(intptr_t)params;
  while (cur) {
    total += strlen((const char*)(intptr_t)cur->value);
    count++;
    cur = (void*)(intptr_t)cur->next;
  }
  if (count > 1) total += 2 * (size_t)(count - 1);
  size_t rlen = strlen(sret), nlen = strlen(sname);
  char *out = malloc(rlen + nlen + total + 5);
  char *p = out;
  memcpy(p, sret, rlen); p += rlen;
  *p++ = ' ';
  memcpy(p, sname, nlen); p += nlen;
  *p++ = '(';
  cur = (void*)(intptr_t)params;
  int first = 1;
  while (cur) {
    if (!first) { *p++ = ','; *p++ = ' '; }
    const char *s = (const char*)(intptr_t)cur->value;
    size_t slen = strlen(s);
    memcpy(p, s, slen); p += slen;
    first = 0;
    cur = (void*)(intptr_t)cur->next;
  }
  *p++ = ')'; *p++ = ';'; *p = '\0';
  return out;
  
}

const char * c_hydsl__fns__c_hyextern(const char * ret, const char * name, int64_t params) {
        return c_hydsl__codegen__c_hycat2("extern ", c_hydsl__fns__c_hydeclare(ret, name, params));
}


