/* generated by tur (phase 2) */
#include "c_dsl__pp.h"

const char * c_hydsl__pp__c_hyinclude(const char *);
const char * c_hydsl__pp__c_hyinclude_hysys(const char *);
const char * c_hydsl__pp__c_hydefine(const char *, const char *);
const char * c_hydsl__pp__c_hydefine_hyfn(const char *, const char *);
const char * c_hydsl__pp__c_hyundef(const char *);
const char * c_hydsl__pp__c_hyifdef(const char *, const char *);
const char * c_hydsl__pp__c_hyifndef(const char *, const char *);
const char * c_hydsl__pp__c_hyif_hypp(const char *, const char *);
const char * c_hydsl__pp__c_hystatic_hyassert(const char *, const char *);
const char * c_hydsl__pp__c_hypragma(const char *);

const char * c_hydsl__pp__c_hyinclude(const char * header) {
        return c_hydsl__codegen__c_hysprintf1("#include \"%s\"", header);
}

const char * c_hydsl__pp__c_hyinclude_hysys(const char * header) {
        return c_hydsl__codegen__c_hysprintf1("#include <%s>", header);
}

const char * c_hydsl__pp__c_hydefine(const char * name, const char * value) {
        return c_hydsl__codegen__c_hysprintf2("#define %s %s", name, value);
}

const char * c_hydsl__pp__c_hydefine_hyfn(const char * signature, const char * body) {
        return c_hydsl__codegen__c_hysprintf2("#define %s %s", signature, body);
}

const char * c_hydsl__pp__c_hyundef(const char * name) {
        return c_hydsl__codegen__c_hysprintf1("#undef %s", name);
}

const char * c_hydsl__pp__c_hyifdef(const char * guard, const char * body) {
        return c_hydsl__codegen__c_hysprintf2("#ifdef %s\n%s\n#endif", guard, body);
}

const char * c_hydsl__pp__c_hyifndef(const char * guard, const char * body) {
        return c_hydsl__codegen__c_hysprintf2("#ifndef %s\n%s\n#endif", guard, body);
}

const char * c_hydsl__pp__c_hyif_hypp(const char * cond, const char * body) {
        return c_hydsl__codegen__c_hysprintf2("#if %s\n%s\n#endif", cond, body);
}

const char * c_hydsl__pp__c_hystatic_hyassert(const char * expr, const char * msg) {
        return c_hydsl__codegen__c_hysprintf2("static_assert(%s, %s);", expr, msg);
}

const char * c_hydsl__pp__c_hypragma(const char * args) {
        return c_hydsl__codegen__c_hysprintf1("#pragma %s", args);
}


