/* generated by tur (phase 2) */
#ifndef TUR_c_dsl__codegen_H
#define TUR_c_dsl__codegen_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

const char * c_hydsl__codegen__c_hyraw(const char *);
const char * c_hydsl__codegen__c_hyint_hy_gtstr(int64_t);
const char * c_hydsl__codegen__c_hyfloat_hy_gtstr(double);
const char * c_hydsl__codegen__c_hycat2(const char *, const char *);
const char * c_hydsl__codegen__c_hycat3(const char *, const char *, const char *);
const char * c_hydsl__codegen__c_hycat4(const char *, const char *, const char *, const char *);
const char * c_hydsl__codegen__c_hysprintf1(const char *, const char *);
const char * c_hydsl__codegen__c_hysprintf2(const char *, const char *, const char *);
const char * c_hydsl__codegen__c_hysprintf3(const char *, const char *, const char *, const char *);
const char * c_hydsl__codegen__c_hysprintf4(const char *, const char *, const char *, const char *, const char *);
const char * c_hydsl__codegen__c_hyjoin(int64_t, const char *);
const char * c_hydsl__codegen__c_hylines(int64_t);
const char * c_hydsl__codegen__c_hyindent(const char *);
const char * c_hydsl__codegen__c_hyjoin_hyvec(int64_t, const char *);
const char * c_hydsl__codegen__c_hystmts(int64_t);
const char * c_hydsl__codegen__c_hyblock(int64_t);
const char * c_hydsl__codegen__compile_hyc(int64_t);
bool c_hydsl__codegen__emit_hyc_hyfile(const char *, int64_t);
#endif /* TUR_c_dsl__codegen_H */
