/* generated by tur (phase 2) */
#include "c_dsl__codegen.h"

const char * c_hydsl__codegen__c_hyraw(const char *);
const char * c_hydsl__codegen__c_hyint_hy_gtstr(int64_t);
const char * c_hydsl__codegen__c_hyfloat_hy_gtstr(double);
const char * c_hydsl__codegen__c_hycat2(const char *, const char *);
const char * c_hydsl__codegen__c_hycat3(const char *, const char *, const char *);
const char * c_hydsl__codegen__c_hycat4(const char *, const char *, const char *, const char *);
const char * c_hydsl__codegen__c_hysprintf1(const char *, const char *);
const char * c_hydsl__codegen__c_hysprintf2(const char *, const char *, const char *);
const char * c_hydsl__codegen__c_hysprintf3(const char *, const char *, const char *, const char *);
const char * c_hydsl__codegen__c_hysprintf4(const char *, const char *, const char *, const char *, const char *);
const char * c_hydsl__codegen__c_hyjoin(int64_t, const char *);
const char * c_hydsl__codegen__c_hylines(int64_t);
const char * c_hydsl__codegen__c_hyindent(const char *);
const char * c_hydsl__codegen__c_hyjoin_hyvec(int64_t, const char *);
const char * c_hydsl__codegen__c_hystmts(int64_t);
const char * c_hydsl__codegen__c_hyblock(int64_t);
const char * c_hydsl__codegen__compile_hyc(int64_t);
bool c_hydsl__codegen__emit_hyc_hyfile(const char *, int64_t);

const char * c_hydsl__codegen__c_hyraw(const char * s) {
        return s;
}

const char * c_hydsl__codegen__c_hyint_hy_gtstr(int64_t n) {
        #include <stdio.h>
  #include <stdlib.h>
  char *buf = malloc(32);
  snprintf(buf, 32, "%lld", (long long)n);
  return buf;
  
}

const char * c_hydsl__codegen__c_hyfloat_hy_gtstr(double f) {
        #include <stdio.h>
  #include <stdlib.h>
  char *buf = malloc(64);
  snprintf(buf, 64, "%g", (double)f);
  return buf;
  
}

const char * c_hydsl__codegen__c_hycat2(const char * a, const char * b) {
        #include <stdio.h>
  #include <stdlib.h>
  const char *sa = (const char*)(intptr_t)a;
  const char *sb = (const char*)(intptr_t)b;
  int n = snprintf(NULL, 0, "%s%s", sa, sb);
  char *out = malloc(n + 1);
  snprintf(out, n + 1, "%s%s", sa, sb);
  return out;
  
}

const char * c_hydsl__codegen__c_hycat3(const char * a, const char * b, const char * c) {
        #include <stdio.h>
  #include <stdlib.h>
  const char *sa = (const char*)(intptr_t)a;
  const char *sb = (const char*)(intptr_t)b;
  const char *sc = (const char*)(intptr_t)c;
  int n = snprintf(NULL, 0, "%s%s%s", sa, sb, sc);
  char *out = malloc(n + 1);
  snprintf(out, n + 1, "%s%s%s", sa, sb, sc);
  return out;
  
}

const char * c_hydsl__codegen__c_hycat4(const char * a, const char * b, const char * c, const char * d) {
        #include <stdio.h>
  #include <stdlib.h>
  const char *sa = (const char*)(intptr_t)a;
  const char *sb = (const char*)(intptr_t)b;
  const char *sc = (const char*)(intptr_t)c;
  const char *sd = (const char*)(intptr_t)d;
  int n = snprintf(NULL, 0, "%s%s%s%s", sa, sb, sc, sd);
  char *out = malloc(n + 1);
  snprintf(out, n + 1, "%s%s%s%s", sa, sb, sc, sd);
  return out;
  
}

const char * c_hydsl__codegen__c_hysprintf1(const char * fmt, const char * a) {
        #include <stdio.h>
  #include <stdlib.h>
  const char *f  = (const char*)(intptr_t)fmt;
  const char *s1 = (const char*)(intptr_t)a;
  int n = snprintf(NULL, 0, f, s1);
  char *out = malloc(n + 1);
  snprintf(out, n + 1, f, s1);
  return out;
  
}

const char * c_hydsl__codegen__c_hysprintf2(const char * fmt, const char * a, const char * b) {
        #include <stdio.h>
  #include <stdlib.h>
  const char *f  = (const char*)(intptr_t)fmt;
  const char *s1 = (const char*)(intptr_t)a;
  const char *s2 = (const char*)(intptr_t)b;
  int n = snprintf(NULL, 0, f, s1, s2);
  char *out = malloc(n + 1);
  snprintf(out, n + 1, f, s1, s2);
  return out;
  
}

const char * c_hydsl__codegen__c_hysprintf3(const char * fmt, const char * a, const char * b, const char * c) {
        #include <stdio.h>
  #include <stdlib.h>
  const char *f  = (const char*)(intptr_t)fmt;
  const char *s1 = (const char*)(intptr_t)a;
  const char *s2 = (const char*)(intptr_t)b;
  const char *s3 = (const char*)(intptr_t)c;
  int n = snprintf(NULL, 0, f, s1, s2, s3);
  char *out = malloc(n + 1);
  snprintf(out, n + 1, f, s1, s2, s3);
  return out;
  
}

const char * c_hydsl__codegen__c_hysprintf4(const char * fmt, const char * a, const char * b, const char * c, const char * d) {
        #include <stdio.h>
  #include <stdlib.h>
  const char *f  = (const char*)(intptr_t)fmt;
  const char *s1 = (const char*)(intptr_t)a;
  const char *s2 = (const char*)(intptr_t)b;
  const char *s3 = (const char*)(intptr_t)c;
  const char *s4 = (const char*)(intptr_t)d;
  int n = snprintf(NULL, 0, f, s1, s2, s3, s4);
  char *out = malloc(n + 1);
  snprintf(out, n + 1, f, s1, s2, s3, s4);
  return out;
  
}

const char * c_hydsl__codegen__c_hyjoin(int64_t items, const char * sep) {
        #include <string.h>
  #include <stdlib.h>
  struct __cdsl_cons { int64_t value; int64_t next; };
  const char *csep = (const char*)(intptr_t)sep;
  size_t seplen = strlen(csep);
  size_t total = 0;
  int count = 0;
  struct __cdsl_cons *cur = (void*)(intptr_t)items;
  while (cur) {
    const char *s = (const char*)(intptr_t)cur->value;
    total += strlen(s);
    count++;
    cur = (void*)(intptr_t)cur->next;
  }
  if (count > 1) total += seplen * (size_t)(count - 1);
  char *out = malloc(total + 1);
  char *p = out;
  cur = (void*)(intptr_t)items;
  int first = 1;
  while (cur) {
    if (!first) { memcpy(p, csep, seplen); p += seplen; }
    const char *s = (const char*)(intptr_t)cur->value;
    size_t slen = strlen(s);
    memcpy(p, s, slen);
    p += slen;
    first = 0;
    cur = (void*)(intptr_t)cur->next;
  }
  *p = '\0';
  return out;
  
}

const char * c_hydsl__codegen__c_hylines(int64_t items) {
        return c_hydsl__codegen__c_hyjoin(items, "\n");
}

const char * c_hydsl__codegen__c_hyindent(const char * code) {
        #include <string.h>
  #include <stdlib.h>
  const char *s = (const char*)(intptr_t)code;
  size_t slen = strlen(s);
  if (slen == 0) return "";
  int lines = 1;
  for (size_t i = 0; i < slen; i++) if (s[i] == '\n') lines++;
  char *out = malloc(slen + (size_t)lines * 4 + 1);
  char *p = out;
  int at_start = 1;
  for (size_t i = 0; i < slen; i++) {
    if (at_start) { memcpy(p, "    ", 4); p += 4; at_start = 0; }
    *p++ = s[i];
    if (s[i] == '\n') at_start = 1;
  }
  *p = '\0';
  return out;
  
}

const char * c_hydsl__codegen__c_hyjoin_hyvec(int64_t items, const char * sep) {
        #include <string.h>
  #include <stdlib.h>
  typedef struct { int64_t *data; size_t len; size_t cap; } CstrVec;
  CstrVec *vec = (CstrVec *)(intptr_t)items;
  const char *csep = (const char*)(intptr_t)sep;
  size_t seplen = strlen(csep);
  if (!vec || vec->len == 0) {
    char *empty = malloc(1);
    empty[0] = '\0';
    return empty;
  }
  size_t total = 0;
  for (size_t i = 0; i < vec->len; i++) {
    total += strlen((const char *)(intptr_t)vec->data[i]);
  }
  if (vec->len > 1) total += seplen * (vec->len - 1);
  char *out = malloc(total + 1);
  char *p = out;
  for (size_t i = 0; i < vec->len; i++) {
    if (i > 0) { memcpy(p, csep, seplen); p += seplen; }
    const char *s = (const char *)(intptr_t)vec->data[i];
    size_t slen = strlen(s);
    memcpy(p, s, slen); p += slen;
  }
  *p = '\0';
  return out;
  
}

const char * c_hydsl__codegen__c_hystmts(int64_t stmts) {
        return c_hydsl__codegen__c_hyjoin_hyvec(stmts, "\n");
}

const char * c_hydsl__codegen__c_hyblock(int64_t stmts) {
        #include <string.h>
  #include <stdlib.h>
  struct __cdsl_cons { int64_t value; int64_t next; };
  size_t total = 3; // "{\n" + "\n}" would be 4 but we add per-stmt
  struct __cdsl_cons *cur = (void*)(intptr_t)stmts;
  while (cur) {
    const char *s = (const char*)(intptr_t)cur->value;
    total += strlen(s) + 5; // "    " + s + "\n"
    cur = (void*)(intptr_t)cur->next;
  }
  char *out = malloc(total + 2);
  char *p = out;
  *p++ = '{'; *p++ = '\n';
  cur = (void*)(intptr_t)stmts;
  while (cur) {
    const char *s = (const char*)(intptr_t)cur->value;
    memcpy(p, "    ", 4); p += 4;
    size_t slen = strlen(s);
    memcpy(p, s, slen); p += slen;
    *p++ = '\n';
    cur = (void*)(intptr_t)cur->next;
  }
  *p++ = '}'; *p = '\0';
  return out;
  
}

const char * c_hydsl__codegen__compile_hyc(int64_t fragments) {
        return c_hydsl__codegen__c_hyjoin(fragments, "\n\n");
}

bool c_hydsl__codegen__emit_hyc_hyfile(const char * path, int64_t fragments) {
        #include <stdio.h>
  #include <string.h>
  #include <stdlib.h>
  struct __cdsl_cons { int64_t value; int64_t next; };
  const char *sep = "\n\n";
  size_t seplen = 2;
  size_t total = 0;
  int count = 0;
  struct __cdsl_cons *cur = (void*)(intptr_t)fragments;
  while (cur) {
    const char *s = (const char*)(intptr_t)cur->value;
    total += strlen(s);
    count++;
    cur = (void*)(intptr_t)cur->next;
  }
  if (count > 1) total += seplen * (size_t)(count - 1);
  char *src = malloc(total + 1);
  char *p = src;
  cur = (void*)(intptr_t)fragments;
  int first = 1;
  while (cur) {
    if (!first) { memcpy(p, sep, seplen); p += seplen; }
    const char *s = (const char*)(intptr_t)cur->value;
    size_t slen = strlen(s);
    memcpy(p, s, slen); p += slen;
    first = 0;
    cur = (void*)(intptr_t)cur->next;
  }
  *p = '\0';
  const char *fpath = (const char*)(intptr_t)path;
  FILE *f = fopen(fpath, "w");
  if (!f) { free(src); return 0; }
  fputs(src, f);
  fclose(f);
  free(src);
  return 1;
  
}


