/* generated by tur (phase 2) */
#ifndef TUR_c_dsl__fns_H
#define TUR_c_dsl__fns_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "c_dsl__codegen.h"
#include "c_dsl__types.h"

const char * c_hydsl__fns__c_hyparam(const char *, const char *);
const char * c_hydsl__fns__c_hydefn(const char *, int64_t, const char *, const char *);
const char * c_hydsl__fns__c_hydefn_hystatic(const char *, int64_t, const char *, const char *);
const char * c_hydsl__fns__c_hydefn_hyinline(const char *, int64_t, const char *, const char *);
const char * c_hydsl__fns__c_hycall(const char *, int64_t);
const char * c_hydsl__fns__c_hydeclare(const char *, const char *, int64_t);
const char * c_hydsl__fns__c_hyextern(const char *, const char *, int64_t);
#endif /* TUR_c_dsl__fns_H */
