/* generated by tur (phase 2) */
#ifndef TUR_c_dsl__pp_H
#define TUR_c_dsl__pp_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "c_dsl__codegen.h"

const char * c_hydsl__pp__c_hyinclude(const char *);
const char * c_hydsl__pp__c_hyinclude_hysys(const char *);
const char * c_hydsl__pp__c_hydefine(const char *, const char *);
const char * c_hydsl__pp__c_hydefine_hyfn(const char *, const char *);
const char * c_hydsl__pp__c_hyundef(const char *);
const char * c_hydsl__pp__c_hyifdef(const char *, const char *);
const char * c_hydsl__pp__c_hyifndef(const char *, const char *);
const char * c_hydsl__pp__c_hyif_hypp(const char *, const char *);
const char * c_hydsl__pp__c_hystatic_hyassert(const char *, const char *);
const char * c_hydsl__pp__c_hypragma(const char *);
#endif /* TUR_c_dsl__pp_H */
