/* generated by tur (phase 2) */
#include "c_dsl__mem.h"

const char * c_hydsl__mem__c_hyaddr(const char *);
const char * c_hydsl__mem__c_hyderef(const char *);
const char * c_hydsl__mem__c_hyindex(const char *, const char *);
const char * c_hydsl__mem__c_hycast(const char *, const char *);
const char * c_hydsl__mem__c_hymalloc(const char *);
const char * c_hydsl__mem__c_hycalloc(const char *, const char *);
const char * c_hydsl__mem__c_hyrealloc(const char *, const char *);
const char * c_hydsl__mem__c_hyfree(const char *);
const char * c_hydsl__mem__c_hyalloca(const char *);
const char * c_hydsl__mem__c_hysizeof(const char *);
const char * c_hydsl__mem__c_hyalignof(const char *);
const char * c_hydsl__mem__c_hynull(const char *);
const char * c_hydsl__mem__c_hyptr_hyadd(const char *, const char *);
const char * c_hydsl__mem__c_hyptr_hysub(const char *, const char *);
const char * c_hydsl__mem__c_hyoffsetof(const char *, const char *);

const char * c_hydsl__mem__c_hyaddr(const char * expr) {
        return c_hydsl__codegen__c_hysprintf1("(&%s)", expr);
}

const char * c_hydsl__mem__c_hyderef(const char * expr) {
        return c_hydsl__codegen__c_hysprintf1("(*%s)", expr);
}

const char * c_hydsl__mem__c_hyindex(const char * arr, const char * idx) {
        return c_hydsl__codegen__c_hysprintf2("%s[%s]", arr, idx);
}

const char * c_hydsl__mem__c_hycast(const char * expr, const char * type) {
        return c_hydsl__codegen__c_hysprintf2("((%s)%s)", c_hydsl__types__c_hytype(type), expr);
}

const char * c_hydsl__mem__c_hymalloc(const char * size) {
        return c_hydsl__codegen__c_hysprintf1("malloc(%s)", size);
}

const char * c_hydsl__mem__c_hycalloc(const char * n, const char * size) {
        return c_hydsl__codegen__c_hysprintf2("calloc(%s, %s)", n, size);
}

const char * c_hydsl__mem__c_hyrealloc(const char * ptr, const char * size) {
        return c_hydsl__codegen__c_hysprintf2("realloc(%s, %s)", ptr, size);
}

const char * c_hydsl__mem__c_hyfree(const char * ptr) {
        return c_hydsl__codegen__c_hysprintf1("free(%s);", ptr);
}

const char * c_hydsl__mem__c_hyalloca(const char * size) {
        return c_hydsl__codegen__c_hysprintf1("alloca(%s)", size);
}

const char * c_hydsl__mem__c_hysizeof(const char * type) {
        return c_hydsl__codegen__c_hysprintf1("sizeof(%s)", c_hydsl__types__c_hytype(type));
}

const char * c_hydsl__mem__c_hyalignof(const char * type) {
        return c_hydsl__codegen__c_hysprintf1("alignof(%s)", c_hydsl__types__c_hytype(type));
}

const char * c_hydsl__mem__c_hynull(const char * type) {
        return c_hydsl__codegen__c_hysprintf1("((%s)NULL)", c_hydsl__types__c_hytype(type));
}

const char * c_hydsl__mem__c_hyptr_hyadd(const char * ptr, const char * offset) {
        return c_hydsl__codegen__c_hysprintf2("(%s + %s)", ptr, offset);
}

const char * c_hydsl__mem__c_hyptr_hysub(const char * ptr, const char * offset) {
        return c_hydsl__codegen__c_hysprintf2("(%s - %s)", ptr, offset);
}

const char * c_hydsl__mem__c_hyoffsetof(const char * type, const char * field) {
        return c_hydsl__codegen__c_hysprintf2("offsetof(%s, %s)", c_hydsl__types__c_hytype(type), field);
}


