/* generated by tur (phase 2) */
#ifndef TUR_c_dsl__types_H
#define TUR_c_dsl__types_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "c_dsl__codegen.h"

const char * c_hydsl__types__c_hytype(const char *);
const char * c_hydsl__types__c_hyptr_hytype(const char *);
const char * c_hydsl__types__c_hyarr_hytype(const char *, int64_t);
const char * c_hydsl__types__c_hyfn_hytype(int64_t, const char *);
const char * c_hydsl__types__c_hyconst_hytype(const char *);
const char * c_hydsl__types__c_hyvolatile_hytype(const char *);
#endif /* TUR_c_dsl__types_H */
