/* generated by tur (phase 2) */
#ifndef TUR_c_dsl__mem_H
#define TUR_c_dsl__mem_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "c_dsl__codegen.h"
#include "c_dsl__types.h"

const char * c_hydsl__mem__c_hyaddr(const char *);
const char * c_hydsl__mem__c_hyderef(const char *);
const char * c_hydsl__mem__c_hyindex(const char *, const char *);
const char * c_hydsl__mem__c_hycast(const char *, const char *);
const char * c_hydsl__mem__c_hymalloc(const char *);
const char * c_hydsl__mem__c_hycalloc(const char *, const char *);
const char * c_hydsl__mem__c_hyrealloc(const char *, const char *);
const char * c_hydsl__mem__c_hyfree(const char *);
const char * c_hydsl__mem__c_hyalloca(const char *);
const char * c_hydsl__mem__c_hysizeof(const char *);
const char * c_hydsl__mem__c_hyalignof(const char *);
const char * c_hydsl__mem__c_hynull(const char *);
const char * c_hydsl__mem__c_hyptr_hyadd(const char *, const char *);
const char * c_hydsl__mem__c_hyptr_hysub(const char *, const char *);
const char * c_hydsl__mem__c_hyoffsetof(const char *, const char *);
#endif /* TUR_c_dsl__mem_H */
