/* generated by tur (phase 2) */
#include "c_dsl__typedef.h"

const char * c_hydsl__typedef__c_hyfield(const char *, const char *);
const char * c_hydsl__typedef__c_hydefstruct(const char *, int64_t);
const char * c_hydsl__typedef__c_hydefunion(const char *, int64_t);
const char * c_hydsl__typedef__c_hydefenum(const char *, int64_t);
const char * c_hydsl__typedef__c_hytypedef(const char *, const char *);

const char * c_hydsl__typedef__c_hyfield(const char * name, const char * type) {
        return c_hydsl__codegen__c_hysprintf2("%s %s;", c_hydsl__types__c_hytype(type), name);
}

const char * c_hydsl__typedef__c_hydefstruct(const char * name, int64_t fields) {
        #include <string.h>
  #include <stdlib.h>
  struct __cdsl_cons { int64_t value; int64_t next; };
  const char *sname = (const char*)(intptr_t)name;
  size_t total = 0;
  struct __cdsl_cons *cur = (void*)(intptr_t)fields;
  while (cur) {
    total += strlen((const char*)(intptr_t)cur->value) + 5; /* "    " + field + "\n" */
    cur = (void*)(intptr_t)cur->next;
  }
  size_t nlen = strlen(sname);
  /* "typedef struct {\n" + fields + "} name;" */
  char *out = malloc(18 + total + nlen + 4);
  char *p = out;
  memcpy(p, "typedef struct {\n", 17); p += 17;
  cur = (void*)(intptr_t)fields;
  while (cur) {
    const char *s = (const char*)(intptr_t)cur->value;
    memcpy(p, "    ", 4); p += 4;
    size_t slen = strlen(s);
    memcpy(p, s, slen); p += slen;
    *p++ = '\n';
    cur = (void*)(intptr_t)cur->next;
  }
  *p++ = '}'; *p++ = ' ';
  memcpy(p, sname, nlen); p += nlen;
  *p++ = ';'; *p = '\0';
  return out;
  
}

const char * c_hydsl__typedef__c_hydefunion(const char * name, int64_t fields) {
        #include <string.h>
  #include <stdlib.h>
  struct __cdsl_cons { int64_t value; int64_t next; };
  const char *sname = (const char*)(intptr_t)name;
  size_t total = 0;
  struct __cdsl_cons *cur = (void*)(intptr_t)fields;
  while (cur) {
    total += strlen((const char*)(intptr_t)cur->value) + 5;
    cur = (void*)(intptr_t)cur->next;
  }
  size_t nlen = strlen(sname);
  char *out = malloc(17 + total + nlen + 4);
  char *p = out;
  memcpy(p, "typedef union {\n", 16); p += 16;
  cur = (void*)(intptr_t)fields;
  while (cur) {
    const char *s = (const char*)(intptr_t)cur->value;
    memcpy(p, "    ", 4); p += 4;
    size_t slen = strlen(s);
    memcpy(p, s, slen); p += slen;
    *p++ = '\n';
    cur = (void*)(intptr_t)cur->next;
  }
  *p++ = '}'; *p++ = ' ';
  memcpy(p, sname, nlen); p += nlen;
  *p++ = ';'; *p = '\0';
  return out;
  
}

const char * c_hydsl__typedef__c_hydefenum(const char * name, int64_t variants) {
        #include <string.h>
  #include <stdlib.h>
  struct __cdsl_cons { int64_t value; int64_t next; };
  const char *sname = (const char*)(intptr_t)name;
  /* Count and measure variants */
  int count = 0;
  size_t total = 0;
  struct __cdsl_cons *cur = (void*)(intptr_t)variants;
  while (cur) {
    total += strlen((const char*)(intptr_t)cur->value) + 6; /* "    " + name + ",\n" */
    count++;
    cur = (void*)(intptr_t)cur->next;
  }
  size_t nlen = strlen(sname);
  char *out = malloc(16 + total + nlen + 4);
  char *p = out;
  memcpy(p, "typedef enum {\n", 15); p += 15;
  cur = (void*)(intptr_t)variants;
  int idx = 0;
  while (cur) {
    const char *s = (const char*)(intptr_t)cur->value;
    memcpy(p, "    ", 4); p += 4;
    size_t slen = strlen(s);
    memcpy(p, s, slen); p += slen;
    idx++;
    if (idx < count) *p++ = ',';
    *p++ = '\n';
    cur = (void*)(intptr_t)cur->next;
  }
  *p++ = '}'; *p++ = ' ';
  memcpy(p, sname, nlen); p += nlen;
  *p++ = ';'; *p = '\0';
  return out;
  
}

const char * c_hydsl__typedef__c_hytypedef(const char * type, const char * alias) {
        return c_hydsl__codegen__c_hysprintf2("typedef %s %s;", c_hydsl__types__c_hytype(type), alias);
}


