/* generated by tur (phase 2) */
#ifndef TUR_valkey__cmd_H
#define TUR_valkey__cmd_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void * valkey__cmd__cmd(int64_t, const char *, int64_t);
void * valkey__cmd__cmd_hyget(int64_t, const char *);
void * valkey__cmd__cmd_hyset(int64_t, const char *, const char *);
void * valkey__cmd__cmd_hydel(int64_t, const char *);
void * valkey__cmd__cmd_hyincr(int64_t, const char *);
void * valkey__cmd__cmd_hyexpire(int64_t, const char *, const char *);
void * valkey__cmd__cmd_hyhset(int64_t, const char *, const char *, const char *);
void * valkey__cmd__cmd_hyhget(int64_t, const char *, const char *);
void * valkey__cmd__cmd_hylpush(int64_t, const char *, const char *);
void * valkey__cmd__cmd_hylrange(int64_t, const char *, int64_t, int64_t);
#endif /* TUR_valkey__cmd_H */
