/* generated by tur (phase 2) */
#ifndef TUR_valkey__pubsub_H
#define TUR_valkey__pubsub_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void * valkey__pubsub__pubsub_hysubscribe(int64_t, const char *);
void * valkey__pubsub__pubsub_hyunsubscribe(int64_t, const char *);
void * valkey__pubsub__pubsub_hypublish(int64_t, const char *, const char *);
void * valkey__pubsub__pubsub_hyrecv(int64_t);
const char * valkey__pubsub__message_hychannel(int64_t);
const char * valkey__pubsub__message_hypayload(int64_t);
#endif /* TUR_valkey__pubsub_H */
