/* generated by tur (phase 2) */
#include "valkey__client.h"

static void * valkey__client____ok(int64_t);
static void * valkey__client____err(int64_t);
void * valkey__client__client_hyconnect(const char *, int64_t);
void * valkey__client__client_hyconnect_hyunix(const char *);
void valkey__client__client_hyclose(int64_t);
void * valkey__client__client_hyping(int64_t);

static void * valkey__client____ok(int64_t v) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = true; r->ok_val = v; r->err_val = 0; return r;
  
}

static void * valkey__client____err(int64_t e) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = false; r->ok_val = 0; r->err_val = e; return r;
  
}

void * valkey__client__client_hyconnect(const char * host, int64_t port) {
        #include <hiredis/hiredis.h>
  redisContext *ctx = redisConnect((const char *)host, (int)port);
  if (!ctx || ctx->err != 0) {
    if (ctx) redisFree(ctx);
    struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
    r->is_ok = false; r->ok_val = 0; r->err_val = 0; return r;
  }
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = true; r->ok_val = (int64_t)(intptr_t)ctx; r->err_val = 0; return r;
  
}

void * valkey__client__client_hyconnect_hyunix(const char * path) {
        #include <hiredis/hiredis.h>
  redisContext *ctx = redisConnectUnix((const char *)path);
  if (!ctx || ctx->err != 0) {
    if (ctx) redisFree(ctx);
    struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
    r->is_ok = false; r->ok_val = 0; r->err_val = 0; return r;
  }
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = true; r->ok_val = (int64_t)(intptr_t)ctx; r->err_val = 0; return r;
  
}

void valkey__client__client_hyclose(int64_t c) {
        #include <hiredis/hiredis.h>
  redisFree((redisContext *)(intptr_t)c);
  
}

void * valkey__client__client_hyping(int64_t c) {
        #include <stdlib.h>
  #include <hiredis/hiredis.h>
  redisContext *ctx = (redisContext *)(intptr_t)c;
  redisReply *reply = (redisReply *)redisCommand(ctx, "PING");
  bool ok = reply != NULL && reply->type == REDIS_REPLY_STATUS;
  if (reply) freeReplyObject(reply);
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = ok; r->ok_val = 0; r->err_val = 0; return r;
  
}


