/* generated by tur (phase 2) */
#include "valkey__pubsub.h"

static void * valkey__pubsub____ok(int64_t);
static void * valkey__pubsub____err(int64_t);
void * valkey__pubsub__pubsub_hysubscribe(int64_t, const char *);
void * valkey__pubsub__pubsub_hyunsubscribe(int64_t, const char *);
void * valkey__pubsub__pubsub_hypublish(int64_t, const char *, const char *);
void * valkey__pubsub__pubsub_hyrecv(int64_t);
const char * valkey__pubsub__message_hychannel(int64_t);
const char * valkey__pubsub__message_hypayload(int64_t);

static void * valkey__pubsub____ok(int64_t v) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = true; r->ok_val = v; r->err_val = 0; return r;
  
}

static void * valkey__pubsub____err(int64_t e) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = false; r->ok_val = 0; r->err_val = e; return r;
  
}

void * valkey__pubsub__pubsub_hysubscribe(int64_t c, const char * channel) {
        #include <stdlib.h>
  #include <hiredis/hiredis.h>
  redisContext *ctx = (redisContext *)(intptr_t)c;
  redisReply *reply = (redisReply *)redisCommand(ctx, "SUBSCRIBE %s",
                                                 (const char *)channel);
  bool ok = reply != NULL;
  if (reply) freeReplyObject(reply);
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = ok; r->ok_val = 0; r->err_val = 0; return r;
  
}

void * valkey__pubsub__pubsub_hyunsubscribe(int64_t c, const char * channel) {
        #include <stdlib.h>
  #include <hiredis/hiredis.h>
  redisContext *ctx = (redisContext *)(intptr_t)c;
  redisReply *reply = (redisReply *)redisCommand(ctx, "UNSUBSCRIBE %s",
                                                 (const char *)channel);
  bool ok = reply != NULL;
  if (reply) freeReplyObject(reply);
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = ok; r->ok_val = 0; r->err_val = 0; return r;
  
}

void * valkey__pubsub__pubsub_hypublish(int64_t c, const char * channel, const char * message) {
        #include <stdlib.h>
  #include <hiredis/hiredis.h>
  redisContext *ctx = (redisContext *)(intptr_t)c;
  redisReply *reply = (redisReply *)redisCommand(ctx, "PUBLISH %s %s",
                                                 (const char *)channel,
                                                 (const char *)message);
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  if (!reply || reply->type == REDIS_REPLY_ERROR) {
    if (reply) freeReplyObject(reply);
    r->is_ok = false; r->ok_val = 0; r->err_val = 0;
  } else {
    int64_t count = (reply->type == REDIS_REPLY_INTEGER) ? reply->integer : 0;
    freeReplyObject(reply);
    r->is_ok = true; r->ok_val = count; r->err_val = 0;
  }
  return r;
  
}

void * valkey__pubsub__pubsub_hyrecv(int64_t c) {
        #include <stdlib.h>
  #include <string.h>
  #include <hiredis/hiredis.h>
  struct __msg { char *channel; char *payload; };
  redisContext *ctx = (redisContext *)(intptr_t)c;
  void *raw = NULL;
  int rc = redisGetReply(ctx, &raw);
  redisReply *reply = (redisReply *)raw;
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  if (rc != REDIS_OK || !reply) {
    r->is_ok = false; r->ok_val = 0; r->err_val = 0; return r;
  }
  /* check for a "message" push: array of 3 elements, first is "message" */
  if (reply->type == REDIS_REPLY_ARRAY && reply->elements == 3 &&
      reply->element[0]->type == REDIS_REPLY_STRING &&
      reply->element[0]->str &&
      strcmp(reply->element[0]->str, "message") == 0) {
    struct __msg *m = malloc(sizeof(*m));
    m->channel = strdup(reply->element[1]->str ? reply->element[1]->str : "");
    m->payload = strdup(reply->element[2]->str ? reply->element[2]->str : "");
    freeReplyObject(reply);
    r->is_ok = true; r->ok_val = (int64_t)(intptr_t)m; r->err_val = 0;
  } else {
    freeReplyObject(reply);
    r->is_ok = true; r->ok_val = 0; r->err_val = 0;
  }
  return r;
  
}

const char * valkey__pubsub__message_hychannel(int64_t m) {
        struct __msg { char *channel; char *payload; };
  return ((struct __msg *)(intptr_t)m)->channel;
  
}

const char * valkey__pubsub__message_hypayload(int64_t m) {
        struct __msg { char *channel; char *payload; };
  return ((struct __msg *)(intptr_t)m)->payload;
  
}


