/* generated by tur (phase 2) */
#ifndef TUR_valkey__reply_H
#define TUR_valkey__reply_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

const char * valkey__reply__reply_hytype(int64_t);
const char * valkey__reply__reply_hystring(int64_t);
int64_t valkey__reply__reply_hyint(int64_t);
int64_t valkey__reply__reply_hyarray_hylen(int64_t);
int64_t valkey__reply__reply_hyarray_hyget(int64_t, int64_t);
void valkey__reply__reply_hyfree(int64_t);
#endif /* TUR_valkey__reply_H */
