/* generated by tur (phase 2) */
#include "valkey__reply.h"

const char * valkey__reply__reply_hytype(int64_t);
const char * valkey__reply__reply_hystring(int64_t);
int64_t valkey__reply__reply_hyint(int64_t);
int64_t valkey__reply__reply_hyarray_hylen(int64_t);
int64_t valkey__reply__reply_hyarray_hyget(int64_t, int64_t);
void valkey__reply__reply_hyfree(int64_t);

const char * valkey__reply__reply_hytype(int64_t r) {
        #include <hiredis/hiredis.h>
  redisReply *reply = (redisReply *)(intptr_t)r;
  switch (reply->type) {
    case REDIS_REPLY_STRING:  return (char *)"string";
    case REDIS_REPLY_INTEGER: return (char *)"integer";
    case REDIS_REPLY_ARRAY:   return (char *)"array";
    case REDIS_REPLY_NIL:     return (char *)"nil";
    case REDIS_REPLY_ERROR:   return (char *)"error";
    case REDIS_REPLY_STATUS:  return (char *)"status";
    default:                  return (char *)"unknown";
  }
  
}

const char * valkey__reply__reply_hystring(int64_t r) {
        #include <hiredis/hiredis.h>
  redisReply *reply = (redisReply *)(intptr_t)r;
  return reply->str ? reply->str : (char *)"";
  
}

int64_t valkey__reply__reply_hyint(int64_t r) {
        #include <hiredis/hiredis.h>
  redisReply *reply = (redisReply *)(intptr_t)r;
  return (int64_t)reply->integer;
  
}

int64_t valkey__reply__reply_hyarray_hylen(int64_t r) {
        #include <hiredis/hiredis.h>
  redisReply *reply = (redisReply *)(intptr_t)r;
  return (int64_t)reply->elements;
  
}

int64_t valkey__reply__reply_hyarray_hyget(int64_t r, int64_t i) {
        #include <hiredis/hiredis.h>
  redisReply *reply = (redisReply *)(intptr_t)r;
  return (int64_t)(intptr_t)reply->element[i];
  
}

void valkey__reply__reply_hyfree(int64_t r) {
        #include <hiredis/hiredis.h>
  freeReplyObject((redisReply *)(intptr_t)r);
  
}


