/* generated by tur (phase 2) */
#ifndef TUR_scscm__parser_H
#define TUR_scscm__parser_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "scscm__lexer.h"

int64_t scscm__parser__scscm_hyast_hyleaf(int64_t, const char *);
int64_t scscm__parser__scscm_hyast_hylist_hynode(int64_t);
void scscm__parser__scscm_hyast_hyadd_hychild(int64_t, int64_t);
const char * scscm__parser__ast_hykind(int64_t);
const char * scscm__parser__ast_hysymbol_hyname(int64_t);
const char * scscm__parser__ast_hynumber_hyvalue(int64_t);
const char * scscm__parser__ast_hystring_hyvalue(int64_t);
int64_t scscm__parser__ast_hylist_hylen(int64_t);
int64_t scscm__parser__ast_hylist_hyget(int64_t, int64_t);
const char * scscm__parser__scscm_hyast_hyvalue(int64_t);
void scscm__parser__ast_hyfree(int64_t);
void scscm__parser__ast_hyfree_hyall(int64_t);
void * scscm__parser__parse(int64_t);
#endif /* TUR_scscm__parser_H */
