/* generated by tur (phase 2) */
#include "scscm__lexer.h"

int64_t scscm__lexer__nil_hyvalue();
bool scscm__lexer__list_hynil_qu(int64_t);
int64_t scscm__lexer__cons(int64_t, int64_t);
int64_t scscm__lexer__head(int64_t);
int64_t scscm__lexer__tail(int64_t);
void * scscm__lexer__lex_hyok(int64_t);
void * scscm__lexer__lex_hyerr(int64_t);
bool scscm__lexer__lex_hyok_qu(void *);
bool scscm__lexer__lex_hyerr_qu(void *);
int64_t scscm__lexer__lex_hyok_hyval(void *);
int64_t scscm__lexer__lex_hyerr_hyval(void *);
static int64_t scscm__lexer__scscm_hytokenize_hyraw(const char *);
static bool scscm__lexer__scscm_hyrtl_hyerror_qu(int64_t);
static const char * scscm__lexer__scscm_hyrtl_hyerror(int64_t);
static int64_t scscm__lexer__scscm_hyrtl_hycount(int64_t);
static int64_t scscm__lexer__scscm_hyrtl_hyget(int64_t, int64_t);
static void scscm__lexer__scscm_hyrtl_hyfree(int64_t);
static void scscm__lexer__scscm_hyrtl_hyfree_hyshallow(int64_t);
const char * scscm__lexer__token_hytype(int64_t);
const char * scscm__lexer__token_hyvalue(int64_t);
int64_t scscm__lexer__token_hyline(int64_t);
int64_t scscm__lexer__token_hycol(int64_t);
static int64_t scscm__lexer__scscm_hytokens_hybuild(int64_t, int64_t, int64_t);
int64_t scscm__lexer__scscm_hylist_hyrev(int64_t, int64_t);
int64_t scscm__lexer__scscm_hycstr_hyas_hyint(const char *);
const char * scscm__lexer__scscm_hyint_hyas_hycstr(int64_t);
bool scscm__lexer__scscm_hycstr_hyeq_qu(const char *, const char *);
void * scscm__lexer__tokenize(const char *);
static void scscm__lexer__scscm_hytoken_hyfree_hyone(int64_t);
void scscm__lexer__tokens_hyfree(int64_t);
static void scscm__lexer__scscm_hyvoid_hynoop();

int64_t scscm__lexer__nil_hyvalue() {
        return 0;
  
}

bool scscm__lexer__list_hynil_qu(int64_t lst) {
        return lst == 0;
  
}

int64_t scscm__lexer__cons(int64_t value, int64_t next) {
        struct { int64_t value; int64_t next; } *cell = malloc(sizeof(*cell));
  cell->value = value; cell->next = next;
  return (int64_t)(intptr_t)cell;
  
}

int64_t scscm__lexer__head(int64_t lst) {
        struct { int64_t value; int64_t next; } *cell = (void*)(intptr_t)lst;
  if (!cell) { fprintf(stderr, "head: empty list\n"); exit(1); }
  return cell->value;
  
}

int64_t scscm__lexer__tail(int64_t lst) {
        struct { int64_t value; int64_t next; } *cell = (void*)(intptr_t)lst;
  if (!cell) { fprintf(stderr, "tail: empty list\n"); exit(1); }
  return cell->next;
  
}

void * scscm__lexer__lex_hyok(int64_t x) {
        struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = true; r->ok_val = x; r->err_val = 0;
  return (void*)r;
  
}

void * scscm__lexer__lex_hyerr(int64_t e) {
        struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = false; r->ok_val = 0; r->err_val = e;
  return (void*)r;
  
}

bool scscm__lexer__lex_hyok_qu(void * r) {
        struct { bool is_ok; int64_t ok_val; int64_t err_val; } *res = (void*)r;
  return res != NULL && res->is_ok;
  
}

bool scscm__lexer__lex_hyerr_qu(void * r) {
        struct { bool is_ok; int64_t ok_val; int64_t err_val; } *res = (void*)r;
  return res == NULL || !res->is_ok;
  
}

int64_t scscm__lexer__lex_hyok_hyval(void * r) {
        struct { bool is_ok; int64_t ok_val; int64_t err_val; } *res = (void*)r;
  return res->ok_val;
  
}

int64_t scscm__lexer__lex_hyerr_hyval(void * r) {
        struct { bool is_ok; int64_t ok_val; int64_t err_val; } *res = (void*)r;
  return res->err_val;
  
}

static int64_t scscm__lexer__scscm_hytokenize_hyraw(const char * source) {
        typedef struct { int type; char *value; int line; int col; } STok;
  typedef struct { int count; int cap; int64_t *handles; const char *error; } STL;
  const char *src = (const char *)(intptr_t)source;
  STL *tl = malloc(sizeof(*tl));
  tl->count = 0; tl->cap = 32; tl->error = NULL;
  tl->handles = malloc(tl->cap * sizeof(int64_t));

  int pos = 0, line = 1, col = 1;

  while (src[pos]) {
    /* skip whitespace */
    while (src[pos]==' '||src[pos]=='\t'||src[pos]=='\r'||src[pos]=='\n') {
      if (src[pos]=='\n'){line++;col=1;}else{col++;}
      pos++;
    }
    if (!src[pos]) break;
    /* skip line comments */
    if (src[pos]==';') { while(src[pos]&&src[pos]!='\n') pos++; continue; }

    int tok_line=line, tok_col=col;
    STok *tok = malloc(sizeof(*tok));
    tok->line=tok_line; tok->col=tok_col; tok->value=NULL; tok->type=-1;

    char c = src[pos];
    if      (c=='(') { tok->type=5;  tok->value=strdup("(");  pos++;col++; }
    else if (c==')') { tok->type=6;  tok->value=strdup(")");  pos++;col++; }
    else if (c=='[') { tok->type=7;  tok->value=strdup("[");  pos++;col++; }
    else if (c==']') { tok->type=8;  tok->value=strdup("]");  pos++;col++; }
    else if (c=='{') { tok->type=9;  tok->value=strdup("{");  pos++;col++; }
    else if (c=='}') { tok->type=10; tok->value=strdup("}");  pos++;col++; }
    else if (c=='\'') { tok->type=11; tok->value=strdup("'"); pos++;col++; }
    else if (c=='`') { tok->type=12; tok->value=strdup("`");  pos++;col++; }
    else if (c=='~') {
      if (src[pos+1]=='@') { tok->type=14; tok->value=strdup("~@"); pos+=2;col+=2; }
      else                 { tok->type=13; tok->value=strdup("~");  pos++;col++; }
    }
    else if (c=='#' && src[pos+1]=='(') {
      tok->type=15; tok->value=strdup("#("); pos+=2; col+=2;
    }
    else if (c=='"') {
      pos++; col++;
      int start=pos;
      while (src[pos] && src[pos]!='"') {
        if (src[pos]=='\\') { pos++;col++; if(!src[pos]) break; }
        if (src[pos]=='\n'){line++;col=1;}else{col++;}
        pos++;
      }
      if (!src[pos]) {
        tl->error = strdup("unterminated string literal");
        free(tok); return (int64_t)(intptr_t)tl;
      }
      int len=pos-start;
      tok->value=malloc(len+1); memcpy(tok->value,src+start,len); tok->value[len]='\0';
      tok->type=4; pos++;col++;
    }
    else if (c==':') {
      /* keyword :foo */
      int start=pos; pos++;col++;
      while (src[pos]&&!strchr("()[]{}\"';`,@# \t\r\n",src[pos])) { pos++;col++; }
      int len=pos-start;
      tok->value=malloc(len+1); memcpy(tok->value,src+start,len); tok->value[len]='\0';
      tok->type=2;
    }
    else if ((c>='0'&&c<='9') ||
             ((c=='-'||c=='+') && src[pos+1]>='0' && src[pos+1]<='9')) {
      int start=pos; pos++;col++;
      while (src[pos]>='0'&&src[pos]<='9') { pos++;col++; }
      if (src[pos]=='.') {
        pos++;col++;
        while (src[pos]>='0'&&src[pos]<='9') { pos++;col++; }
      }
      if (src[pos]=='e'||src[pos]=='E') {
        pos++;col++;
        if (src[pos]=='+'||src[pos]=='-') { pos++;col++; }
        while (src[pos]>='0'&&src[pos]<='9') { pos++;col++; }
      }
      int len=pos-start;
      tok->value=malloc(len+1); memcpy(tok->value,src+start,len); tok->value[len]='\0';
      tok->type=3;
    }
    else if (c && !strchr("()[]{}\"';`,@# \t\r\n",c)) {
      /* symbol or atom */
      int start=pos;
      while (src[pos]&&!strchr("()[]{}\"';`,@# \t\r\n",src[pos])) { pos++;col++; }
      int len=pos-start;
      tok->value=malloc(len+1); memcpy(tok->value,src+start,len); tok->value[len]='\0';
      if (strcmp(tok->value,"nil")==0||strcmp(tok->value,"true")==0||
          strcmp(tok->value,"false")==0)
        tok->type=0;
      else
        tok->type=1;
    }
    else {
      char msg[80];
      snprintf(msg,sizeof(msg),"unexpected char '%c' at line %d col %d",(char)c,line,col);
      tl->error=strdup(msg); free(tok); return (int64_t)(intptr_t)tl;
    }

    /* append token handle */
    if (tl->count >= tl->cap) {
      tl->cap *= 2;
      tl->handles = realloc(tl->handles, tl->cap * sizeof(int64_t));
    }
    tl->handles[tl->count++] = (int64_t)(intptr_t)tok;
  }
  return (int64_t)(intptr_t)tl;
  
}

static bool scscm__lexer__scscm_hyrtl_hyerror_qu(int64_t tl) {
        typedef struct { int count; int cap; int64_t *handles; const char *error; } STL;
  STL *t = (STL*)(intptr_t)tl;
  return t->error != NULL;
  
}

static const char * scscm__lexer__scscm_hyrtl_hyerror(int64_t tl) {
        typedef struct { int count; int cap; int64_t *handles; const char *error; } STL;
  STL *t = (STL*)(intptr_t)tl;
  return t->error ? t->error : "";
  
}

static int64_t scscm__lexer__scscm_hyrtl_hycount(int64_t tl) {
        typedef struct { int count; int cap; int64_t *handles; const char *error; } STL;
  STL *t = (STL*)(intptr_t)tl;
  return t->count;
  
}

static int64_t scscm__lexer__scscm_hyrtl_hyget(int64_t tl, int64_t i) {
        typedef struct { int count; int cap; int64_t *handles; const char *error; } STL;
  STL *t = (STL*)(intptr_t)tl;
  return t->handles[i];
  
}

static void scscm__lexer__scscm_hyrtl_hyfree(int64_t tl) {
        typedef struct { int type; char *value; int line; int col; } STok;
  typedef struct { int count; int cap; int64_t *handles; const char *error; } STL;
  STL *t = (STL*)(intptr_t)tl;
  if (!t) return;
  for (int i = 0; i < t->count; i++) {
    STok *tok = (STok*)(intptr_t)t->handles[i];
    if (tok) { free(tok->value); free(tok); }
  }
  free(t->handles);
  if (t->error) free((void*)t->error);
  free(t);
  
}

static void scscm__lexer__scscm_hyrtl_hyfree_hyshallow(int64_t tl) {
        typedef struct { int count; int cap; int64_t *handles; const char *error; } STL;
  STL *t = (STL*)(intptr_t)tl;
  if (!t) return;
  free(t->handles);
  free(t);
  
}

const char * scscm__lexer__token_hytype(int64_t tok) {
        typedef struct { int type; char *value; int line; int col; } STok;
  static const char *names[] = {
    ":atom",":symbol",":keyword",":number",":string",
    ":lparen",":rparen",":lbracket",":rbracket",":lbrace",":rbrace",
    ":quote",":quasiquote",":unquote",":unquote-splice",":hash-paren",":eof"
  };
  STok *t = (STok*)(intptr_t)tok;
  if (!t || t->type < 0 || t->type > 16) return ":unknown";
  return names[t->type];
  
}

const char * scscm__lexer__token_hyvalue(int64_t tok) {
        typedef struct { int type; char *value; int line; int col; } STok;
  STok *t = (STok*)(intptr_t)tok;
  return t && t->value ? t->value : "";
  
}

int64_t scscm__lexer__token_hyline(int64_t tok) {
        typedef struct { int type; char *value; int line; int col; } STok;
  STok *t = (STok*)(intptr_t)tok;
  return t ? t->line : 0;
  
}

int64_t scscm__lexer__token_hycol(int64_t tok) {
        typedef struct { int type; char *value; int line; int col; } STok;
  STok *t = (STok*)(intptr_t)tok;
  return t ? t->col : 0;
  
}

static int64_t scscm__lexer__scscm_hytokens_hybuild(int64_t tl, int64_t i, int64_t acc) {
        __tur_tailcall:;
        if ((i) >= (scscm__lexer__scscm_hyrtl_hycount(tl))) {
            return acc;
        } else {
            int64_t __t0 = tl;
            int64_t __t1 = (i) + (INT64_C(1));
            int64_t __t2 = scscm__lexer__cons(scscm__lexer__scscm_hyrtl_hyget(tl, i), acc);
            tl = __t0;
            i = __t1;
            acc = __t2;
            goto __tur_tailcall;
        }
}

int64_t scscm__lexer__scscm_hylist_hyrev(int64_t lst, int64_t acc) {
        __tur_tailcall:;
        if (scscm__lexer__list_hynil_qu(lst)) {
            return acc;
        } else {
            int64_t __t3 = scscm__lexer__tail(lst);
            int64_t __t4 = scscm__lexer__cons(scscm__lexer__head(lst), acc);
            lst = __t3;
            acc = __t4;
            goto __tur_tailcall;
        }
}

int64_t scscm__lexer__scscm_hycstr_hyas_hyint(const char * s) {
        return (int64_t)(intptr_t)s;
  
}

const char * scscm__lexer__scscm_hyint_hyas_hycstr(int64_t n) {
        return (const char *)(intptr_t)n;
  
}

bool scscm__lexer__scscm_hycstr_hyeq_qu(const char * a, const char * b) {
        const char *ca = (const char*)(intptr_t)a;
  const char *cb = (const char*)(intptr_t)b;
  if (!ca || !cb) return ca == cb;
  return strcmp(ca, cb) == 0;
  
}

void * scscm__lexer__tokenize(const char * source) {
        void * __t5;
        {
            int64_t tl_65 = scscm__lexer__scscm_hytokenize_hyraw(source);
            (void)tl_65;
            void * __t6;
            if (scscm__lexer__scscm_hyrtl_hyerror_qu(tl_65)) {
                void * __t7;
                {
                    const char * msg_66 = scscm__lexer__scscm_hyrtl_hyerror(tl_65);
                    (void)msg_66;
                    scscm__lexer__scscm_hyrtl_hyfree(tl_65);
                    void * __t8;
                    __t8 = scscm__lexer__lex_hyerr(scscm__lexer__scscm_hycstr_hyas_hyint(msg_66));
                    __t7 = __t8;
                }
                __t6 = __t7;
            } else {
                void * __t9;
                {
                    int64_t reversed_67 = scscm__lexer__scscm_hytokens_hybuild(tl_65, INT64_C(0), scscm__lexer__nil_hyvalue());
                    (void)reversed_67;
                    int64_t tokens_68 = scscm__lexer__scscm_hylist_hyrev(reversed_67, scscm__lexer__nil_hyvalue());
                    (void)tokens_68;
                    scscm__lexer__scscm_hyrtl_hyfree_hyshallow(tl_65);
                    void * __t10;
                    __t10 = scscm__lexer__lex_hyok(tokens_68);
                    __t9 = __t10;
                }
                __t6 = __t9;
            }
            __t5 = __t6;
        }
        return __t5;
}

static void scscm__lexer__scscm_hytoken_hyfree_hyone(int64_t tok) {
        typedef struct { int type; char *value; int line; int col; } STok;
  STok *t = (STok*)(intptr_t)tok;
  if (t) { free(t->value); free(t); }
  
}

void scscm__lexer__tokens_hyfree(int64_t ts) {
        if (scscm__lexer__list_hynil_qu(ts)) {
            scscm__lexer__scscm_hyvoid_hynoop();
        } else {
            scscm__lexer__scscm_hytoken_hyfree_hyone(scscm__lexer__head(ts));
            scscm__lexer__tokens_hyfree(scscm__lexer__tail(ts));
        }
}

static void scscm__lexer__scscm_hyvoid_hynoop() {
        (void)0;
  
}


