/* generated by tur (phase 2) */
#include "scscm__codegen.h"

static const char * scscm__codegen__scscm_hysym_hyescape(const char *);
static bool scscm__codegen__scscm_hyis_hybinary_hyop_qu(const char *);
static const char * scscm__codegen__scscm_hysclang_hyop(const char *);
static const char * scscm__codegen__scscm_hyconcat(const char *, const char *);
static const char * scscm__codegen__scscm_hybrace(const char *);
static const char * scscm__codegen__scscm_hygen_hyargs(int64_t, int64_t);
static const char * scscm__codegen__scscm_hygen_hycons_hylist(int64_t);
static const char * scscm__codegen__scscm_hygen_hyparams(int64_t, int64_t);
static const char * scscm__codegen__scscm_hygen_hystmts(int64_t, int64_t);
static const char * scscm__codegen__scscm_hygen_hylet_hybindings(int64_t, int64_t);
static const char * scscm__codegen__scscm_hygen_hydot(int64_t);
static const char * scscm__codegen__scscm_hygen_hydotdot(int64_t);
static const char * scscm__codegen__scscm_hygen_hyfn(int64_t);
static const char * scscm__codegen__scscm_hygen_hydefn(int64_t);
static const char * scscm__codegen__scscm_hygen_hyif(int64_t);
static const char * scscm__codegen__scscm_hygen_hylet(int64_t);
static const char * scscm__codegen__scscm_hygen_hyquote(int64_t);
static const char * scscm__codegen__scscm_hygen_hylist_hysym(int64_t, const char *);
static const char * scscm__codegen__scscm_hygen_hylist(int64_t);
static const char * scscm__codegen__scscm_hykw_hyname(const char *);
const char * scscm__codegen__generate(int64_t);
static const char * scscm__codegen__scscm_hygen_hyall_hyloop(int64_t, const char *);
const char * scscm__codegen__generate_hyall(int64_t);

static const char * scscm__codegen__scscm_hysym_hyescape(const char * name) {
        const char *src = (const char*)(intptr_t)name;
  int len = (int)strlen(src);
  /* worst case: each char stays same (no expansion needed) */
  char *out = malloc(len + 3); /* +3 for possible _p/_b suffix + NUL */
  int j = 0;
  for (int i = 0; i < len; i++) {
    char c = src[i];
    if (c == '-') out[j++] = '_';
    else if (c == '?' && i == len - 1) { out[j++] = '_'; out[j++] = 'p'; }
    else if (c == '!' && i == len - 1) { out[j++] = '_'; out[j++] = 'b'; }
    else out[j++] = c;
  }
  out[j] = '\0';
  return out;
  
}

static bool scscm__codegen__scscm_hyis_hybinary_hyop_qu(const char * name) {
        const char *n = (const char*)(intptr_t)name;
  if (!n) return false;
  static const char *ops[] = {
    "+","-","*","/","=","<",">","<=",">=","!=",
    "&&","||","&","|","^","<<",">>",
    "and","or","mod","rem",NULL
  };
  for (int i = 0; ops[i]; i++)
    if (strcmp(n, ops[i]) == 0) return true;
  return false;
  
}

static const char * scscm__codegen__scscm_hysclang_hyop(const char * name) {
        const char *n = (const char*)(intptr_t)name;
  if (strcmp(n,"=")==0) return "==";
  if (strcmp(n,"and")==0) return "&&";
  if (strcmp(n,"or")==0)  return "||";
  if (strcmp(n,"mod")==0) return "%";
  if (strcmp(n,"rem")==0) return "%";
  return n;
  
}

static const char * scscm__codegen__scscm_hyconcat(const char * a, const char * b) {
        const char *sa = (const char*)(intptr_t)a;
  const char *sb = (const char*)(intptr_t)b;
  if (!sa) sa = ""; if (!sb) sb = "";
  size_t la = strlen(sa), lb = strlen(sb);
  char *out = malloc(la + lb + 1);
  memcpy(out, sa, la); memcpy(out + la, sb, lb);
  out[la + lb] = '\0';
  return out;
  
}

static const char * scscm__codegen__scscm_hybrace(const char * s) {
        return scscm__codegen__scscm_hyconcat("{ ", scscm__codegen__scscm_hyconcat(s, " }"));
}

static const char * scscm__codegen__scscm_hygen_hyargs(int64_t node, int64_t i) {
        const char * __t0;
        if ((i) >= (scscm__parser__ast_hylist_hylen(node))) {
            __t0 = "";
        } else {
            const char * __t1;
            if ((i) == ((scscm__parser__ast_hylist_hylen(node)) - (INT64_C(1)))) {
                __t1 = scscm__codegen__generate(scscm__parser__ast_hylist_hyget(node, i));
            } else {
                __t1 = scscm__codegen__scscm_hyconcat(scscm__codegen__generate(scscm__parser__ast_hylist_hyget(node, i)), scscm__codegen__scscm_hyconcat(", ", scscm__codegen__scscm_hygen_hyargs(node, (i) + (INT64_C(1)))));
            }
            __t0 = __t1;
        }
        return __t0;
}

static const char * scscm__codegen__scscm_hygen_hycons_hylist(int64_t nodes) {
        const char * __t2;
        if (scscm__lexer__list_hynil_qu(nodes)) {
            __t2 = "";
        } else {
            const char * __t3;
            if (scscm__lexer__list_hynil_qu(scscm__lexer__tail(nodes))) {
                __t3 = scscm__codegen__generate(scscm__lexer__head(nodes));
            } else {
                __t3 = scscm__codegen__scscm_hyconcat(scscm__codegen__generate(scscm__lexer__head(nodes)), scscm__codegen__scscm_hyconcat(", ", scscm__codegen__scscm_hygen_hycons_hylist(scscm__lexer__tail(nodes))));
            }
            __t2 = __t3;
        }
        return __t2;
}

static const char * scscm__codegen__scscm_hygen_hyparams(int64_t node, int64_t i) {
        const char * __t4;
        if ((i) >= (scscm__parser__ast_hylist_hylen(node))) {
            __t4 = "";
        } else {
            const char * __t5;
            if ((i) == ((scscm__parser__ast_hylist_hylen(node)) - (INT64_C(1)))) {
                __t5 = scscm__codegen__scscm_hysym_hyescape(scscm__parser__ast_hysymbol_hyname(scscm__parser__ast_hylist_hyget(node, i)));
            } else {
                __t5 = scscm__codegen__scscm_hyconcat(scscm__codegen__scscm_hysym_hyescape(scscm__parser__ast_hysymbol_hyname(scscm__parser__ast_hylist_hyget(node, i))), scscm__codegen__scscm_hyconcat(", ", scscm__codegen__scscm_hygen_hyparams(node, (i) + (INT64_C(1)))));
            }
            __t4 = __t5;
        }
        return __t4;
}

static const char * scscm__codegen__scscm_hygen_hystmts(int64_t node, int64_t i) {
        const char * __t6;
        if ((i) >= (scscm__parser__ast_hylist_hylen(node))) {
            __t6 = "";
        } else {
            const char * __t7;
            if ((i) == ((scscm__parser__ast_hylist_hylen(node)) - (INT64_C(1)))) {
                __t7 = scscm__codegen__generate(scscm__parser__ast_hylist_hyget(node, i));
            } else {
                __t7 = scscm__codegen__scscm_hyconcat(scscm__codegen__generate(scscm__parser__ast_hylist_hyget(node, i)), scscm__codegen__scscm_hyconcat(";\n", scscm__codegen__scscm_hygen_hystmts(node, (i) + (INT64_C(1)))));
            }
            __t6 = __t7;
        }
        return __t6;
}

static const char * scscm__codegen__scscm_hygen_hylet_hybindings(int64_t bvec, int64_t i) {
        const char * __t8;
        if ((i) >= (scscm__parser__ast_hylist_hylen(bvec))) {
            __t8 = "";
        } else {
            const char * __t9;
            {
                int64_t name_hynode_168 = scscm__parser__ast_hylist_hyget(bvec, i);
                (void)name_hynode_168;
                int64_t val_hynode_169 = scscm__parser__ast_hylist_hyget(bvec, (i) + (INT64_C(1)));
                (void)val_hynode_169;
                const char * binding_170 = scscm__codegen__scscm_hyconcat("var ", scscm__codegen__scscm_hyconcat(scscm__codegen__scscm_hysym_hyescape(scscm__parser__ast_hysymbol_hyname(name_hynode_168)), scscm__codegen__scscm_hyconcat(" = ", scscm__codegen__generate(val_hynode_169))));
                (void)binding_170;
                const char * __t10;
                if (((i) + (INT64_C(2))) >= (scscm__parser__ast_hylist_hylen(bvec))) {
                    __t10 = binding_170;
                } else {
                    __t10 = scscm__codegen__scscm_hyconcat(binding_170, scscm__codegen__scscm_hyconcat(";\n", scscm__codegen__scscm_hygen_hylet_hybindings(bvec, (i) + (INT64_C(2)))));
                }
                __t9 = __t10;
            }
            __t8 = __t9;
        }
        return __t8;
}

static const char * scscm__codegen__scscm_hygen_hydot(int64_t node) {
        const char * __t11;
        {
            const char * obj_172 = scscm__codegen__generate(scscm__parser__ast_hylist_hyget(node, INT64_C(1)));
            (void)obj_172;
            const char * msg_173 = scscm__codegen__scscm_hysym_hyescape(scscm__parser__ast_hysymbol_hyname(scscm__parser__ast_hylist_hyget(node, INT64_C(2))));
            (void)msg_173;
            const char * __t12;
            if ((scscm__parser__ast_hylist_hylen(node)) <= (INT64_C(3))) {
                __t12 = scscm__codegen__scscm_hyconcat(obj_172, scscm__codegen__scscm_hyconcat(".", msg_173));
            } else {
                __t12 = scscm__codegen__scscm_hyconcat(obj_172, scscm__codegen__scscm_hyconcat(".", scscm__codegen__scscm_hyconcat(msg_173, scscm__codegen__scscm_hyconcat("(", scscm__codegen__scscm_hyconcat(scscm__codegen__scscm_hygen_hyargs(node, INT64_C(3)), ")")))));
            }
            __t11 = __t12;
        }
        return __t11;
}

static const char * scscm__codegen__scscm_hygen_hydotdot(int64_t node) {
        const char * __t13;
        {
            const char * cls_175 = scscm__parser__ast_hysymbol_hyname(scscm__parser__ast_hylist_hyget(node, INT64_C(1)));
            (void)cls_175;
            const char * msg_176 = scscm__codegen__scscm_hysym_hyescape(scscm__parser__ast_hysymbol_hyname(scscm__parser__ast_hylist_hyget(node, INT64_C(2))));
            (void)msg_176;
            const char * __t14;
            if ((scscm__parser__ast_hylist_hylen(node)) <= (INT64_C(3))) {
                __t14 = scscm__codegen__scscm_hyconcat(cls_175, scscm__codegen__scscm_hyconcat(".", msg_176));
            } else {
                __t14 = scscm__codegen__scscm_hyconcat(cls_175, scscm__codegen__scscm_hyconcat(".", scscm__codegen__scscm_hyconcat(msg_176, scscm__codegen__scscm_hyconcat("(", scscm__codegen__scscm_hyconcat(scscm__codegen__scscm_hygen_hyargs(node, INT64_C(3)), ")")))));
            }
            __t13 = __t14;
        }
        return __t13;
}

static const char * scscm__codegen__scscm_hygen_hyfn(int64_t node) {
        const char * __t15;
        {
            int64_t params_hynode_178 = scscm__parser__ast_hylist_hyget(node, INT64_C(1));
            (void)params_hynode_178;
            const char * __t16;
            if ((scscm__parser__ast_hylist_hylen(params_hynode_178)) == (INT64_C(0))) {
                __t16 = scscm__codegen__scscm_hyconcat("{ ", scscm__codegen__scscm_hyconcat(scscm__codegen__scscm_hygen_hystmts(node, INT64_C(2)), " }"));
            } else {
                __t16 = scscm__codegen__scscm_hyconcat("{ |", scscm__codegen__scscm_hyconcat(scscm__codegen__scscm_hygen_hyparams(params_hynode_178, INT64_C(0)), scscm__codegen__scscm_hyconcat("| ", scscm__codegen__scscm_hyconcat(scscm__codegen__scscm_hygen_hystmts(node, INT64_C(2)), " }"))));
            }
            __t15 = __t16;
        }
        return __t15;
}

static const char * scscm__codegen__scscm_hygen_hydefn(int64_t node) {
        const char * __t17;
        {
            const char * name_180 = scscm__codegen__scscm_hysym_hyescape(scscm__parser__ast_hysymbol_hyname(scscm__parser__ast_hylist_hyget(node, INT64_C(1))));
            (void)name_180;
            int64_t params_hynode_181 = scscm__parser__ast_hylist_hyget(node, INT64_C(2));
            (void)params_hynode_181;
            const char * __t18;
            if ((scscm__parser__ast_hylist_hylen(params_hynode_181)) == (INT64_C(0))) {
                __t18 = scscm__codegen__scscm_hyconcat(name_180, scscm__codegen__scscm_hyconcat(" = { ", scscm__codegen__scscm_hyconcat(scscm__codegen__scscm_hygen_hystmts(node, INT64_C(3)), " }")));
            } else {
                __t18 = scscm__codegen__scscm_hyconcat(name_180, scscm__codegen__scscm_hyconcat(" = { |", scscm__codegen__scscm_hyconcat(scscm__codegen__scscm_hygen_hyparams(params_hynode_181, INT64_C(0)), scscm__codegen__scscm_hyconcat("| ", scscm__codegen__scscm_hyconcat(scscm__codegen__scscm_hygen_hystmts(node, INT64_C(3)), " }")))));
            }
            __t17 = __t18;
        }
        return __t17;
}

static const char * scscm__codegen__scscm_hygen_hyif(int64_t node) {
        const char * __t19;
        if ((scscm__parser__ast_hylist_hylen(node)) >= (INT64_C(4))) {
            __t19 = scscm__codegen__scscm_hyconcat("if(", scscm__codegen__scscm_hyconcat(scscm__codegen__generate(scscm__parser__ast_hylist_hyget(node, INT64_C(1))), scscm__codegen__scscm_hyconcat(", ", scscm__codegen__scscm_hyconcat(scscm__codegen__scscm_hybrace(scscm__codegen__generate(scscm__parser__ast_hylist_hyget(node, INT64_C(2)))), scscm__codegen__scscm_hyconcat(", ", scscm__codegen__scscm_hyconcat(scscm__codegen__scscm_hybrace(scscm__codegen__generate(scscm__parser__ast_hylist_hyget(node, INT64_C(3)))), ")"))))));
        } else {
            __t19 = scscm__codegen__scscm_hyconcat("if(", scscm__codegen__scscm_hyconcat(scscm__codegen__generate(scscm__parser__ast_hylist_hyget(node, INT64_C(1))), scscm__codegen__scscm_hyconcat(", ", scscm__codegen__scscm_hyconcat(scscm__codegen__scscm_hybrace(scscm__codegen__generate(scscm__parser__ast_hylist_hyget(node, INT64_C(2)))), ")"))));
        }
        return __t19;
}

static const char * scscm__codegen__scscm_hygen_hylet(int64_t node) {
        const char * __t20;
        {
            int64_t bvec_184 = scscm__parser__ast_hylist_hyget(node, INT64_C(1));
            (void)bvec_184;
            const char * binds_185 = scscm__codegen__scscm_hygen_hylet_hybindings(bvec_184, INT64_C(0));
            (void)binds_185;
            const char * body_186 = scscm__codegen__scscm_hygen_hystmts(node, INT64_C(2));
            (void)body_186;
            __t20 = scscm__codegen__scscm_hyconcat(binds_185, scscm__codegen__scscm_hyconcat(";\n", body_186));
        }
        return __t20;
}

static const char * scscm__codegen__scscm_hygen_hyquote(int64_t node) {
        const char * __t21;
        {
            int64_t inner_188 = scscm__parser__ast_hylist_hyget(node, INT64_C(1));
            (void)inner_188;
            const char * __t22;
            if (scscm__lexer__scscm_hycstr_hyeq_qu(scscm__parser__ast_hykind(inner_188), ":symbol")) {
                __t22 = scscm__codegen__scscm_hyconcat("\\", scscm__parser__ast_hysymbol_hyname(inner_188));
            } else {
                __t22 = scscm__codegen__generate(inner_188);
            }
            __t21 = __t22;
        }
        return __t21;
}

static const char * scscm__codegen__scscm_hygen_hylist_hysym(int64_t node, const char * head_name) {
        const char * __t23;
        if (scscm__lexer__scscm_hycstr_hyeq_qu(head_name, ".")) {
            __t23 = scscm__codegen__scscm_hygen_hydot(node);
        } else {
            const char * __t24;
            if (scscm__lexer__scscm_hycstr_hyeq_qu(head_name, ".dot")) {
                __t24 = scscm__codegen__scscm_hygen_hydotdot(node);
            } else {
                const char * __t25;
                if (scscm__lexer__scscm_hycstr_hyeq_qu(head_name, "fn")) {
                    __t25 = scscm__codegen__scscm_hygen_hyfn(node);
                } else {
                    const char * __t26;
                    if (scscm__lexer__scscm_hycstr_hyeq_qu(head_name, "defn")) {
                        __t26 = scscm__codegen__scscm_hygen_hydefn(node);
                    } else {
                        const char * __t27;
                        if (scscm__lexer__scscm_hycstr_hyeq_qu(head_name, "var")) {
                            __t27 = scscm__codegen__scscm_hyconcat("var ", scscm__codegen__scscm_hyconcat(scscm__codegen__scscm_hysym_hyescape(scscm__parser__ast_hysymbol_hyname(scscm__parser__ast_hylist_hyget(node, INT64_C(1)))), scscm__codegen__scscm_hyconcat(" = ", scscm__codegen__generate(scscm__parser__ast_hylist_hyget(node, INT64_C(2))))));
                        } else {
                            const char * __t28;
                            if (scscm__lexer__scscm_hycstr_hyeq_qu(head_name, "set!")) {
                                __t28 = scscm__codegen__scscm_hyconcat(scscm__codegen__scscm_hysym_hyescape(scscm__parser__ast_hysymbol_hyname(scscm__parser__ast_hylist_hyget(node, INT64_C(1)))), scscm__codegen__scscm_hyconcat(" = ", scscm__codegen__generate(scscm__parser__ast_hylist_hyget(node, INT64_C(2)))));
                            } else {
                                const char * __t29;
                                if (scscm__lexer__scscm_hycstr_hyeq_qu(head_name, "let")) {
                                    __t29 = scscm__codegen__scscm_hygen_hylet(node);
                                } else {
                                    const char * __t30;
                                    if (scscm__lexer__scscm_hycstr_hyeq_qu(head_name, "if")) {
                                        __t30 = scscm__codegen__scscm_hygen_hyif(node);
                                    } else {
                                        const char * __t31;
                                        if (scscm__lexer__scscm_hycstr_hyeq_qu(head_name, "do")) {
                                            __t31 = scscm__codegen__scscm_hygen_hystmts(node, INT64_C(1));
                                        } else {
                                            const char * __t32;
                                            if (scscm__lexer__scscm_hycstr_hyeq_qu(head_name, "quote")) {
                                                __t32 = scscm__codegen__scscm_hygen_hyquote(node);
                                            } else {
                                                const char * __t33;
                                                if (scscm__codegen__scscm_hyis_hybinary_hyop_qu(head_name)) {
                                                    __t33 = scscm__codegen__scscm_hyconcat(scscm__codegen__generate(scscm__parser__ast_hylist_hyget(node, INT64_C(1))), scscm__codegen__scscm_hyconcat(" ", scscm__codegen__scscm_hyconcat(scscm__codegen__scscm_hysclang_hyop(head_name), scscm__codegen__scscm_hyconcat(" ", scscm__codegen__generate(scscm__parser__ast_hylist_hyget(node, INT64_C(2)))))));
                                                } else {
                                                    __t33 = scscm__codegen__scscm_hyconcat(scscm__codegen__scscm_hysym_hyescape(head_name), scscm__codegen__scscm_hyconcat("(", scscm__codegen__scscm_hyconcat(scscm__codegen__scscm_hygen_hyargs(node, INT64_C(1)), ")")));
                                                }
                                                __t32 = __t33;
                                            }
                                            __t31 = __t32;
                                        }
                                        __t30 = __t31;
                                    }
                                    __t29 = __t30;
                                }
                                __t28 = __t29;
                            }
                            __t27 = __t28;
                        }
                        __t26 = __t27;
                    }
                    __t25 = __t26;
                }
                __t24 = __t25;
            }
            __t23 = __t24;
        }
        return __t23;
}

static const char * scscm__codegen__scscm_hygen_hylist(int64_t node) {
        const char * __t34;
        if ((scscm__parser__ast_hylist_hylen(node)) == (INT64_C(0))) {
            __t34 = "()";
        } else {
            const char * __t35;
            {
                int64_t head_hynode_192 = scscm__parser__ast_hylist_hyget(node, INT64_C(0));
                (void)head_hynode_192;
                const char * head_hykind_193 = scscm__parser__ast_hykind(head_hynode_192);
                (void)head_hykind_193;
                const char * __t36;
                if (scscm__lexer__scscm_hycstr_hyeq_qu(head_hykind_193, ":symbol")) {
                    __t36 = scscm__codegen__scscm_hygen_hylist_hysym(node, scscm__parser__ast_hysymbol_hyname(head_hynode_192));
                } else {
                    __t36 = scscm__codegen__scscm_hyconcat(scscm__codegen__generate(head_hynode_192), scscm__codegen__scscm_hyconcat("(", scscm__codegen__scscm_hyconcat(scscm__codegen__scscm_hygen_hyargs(node, INT64_C(1)), ")")));
                }
                __t35 = __t36;
            }
            __t34 = __t35;
        }
        return __t34;
}

static const char * scscm__codegen__scscm_hykw_hyname(const char * raw) {
        const char *s = (const char*)(intptr_t)raw;
  if (s && s[0] == ':') return s + 1;
  return s ? s : "";
  
}

const char * scscm__codegen__generate(int64_t node) {
        __tur_tailcall:;
        {
            const char * knd_196 = scscm__parser__ast_hykind(node);
            (void)knd_196;
            if (scscm__lexer__scscm_hycstr_hyeq_qu(knd_196, ":atom")) {
                return scscm__parser__scscm_hyast_hyvalue(node);
            } else {
                if (scscm__lexer__scscm_hycstr_hyeq_qu(knd_196, ":symbol")) {
                    return scscm__codegen__scscm_hysym_hyescape(scscm__parser__ast_hysymbol_hyname(node));
                } else {
                    if (scscm__lexer__scscm_hycstr_hyeq_qu(knd_196, ":keyword")) {
                        {
                            const char * raw_197 = scscm__parser__scscm_hyast_hyvalue(node);
                            (void)raw_197;
                            return scscm__codegen__scscm_hyconcat("\\", scscm__codegen__scscm_hykw_hyname(raw_197));
                        }
                    } else {
                        if (scscm__lexer__scscm_hycstr_hyeq_qu(knd_196, ":number")) {
                            return scscm__parser__ast_hynumber_hyvalue(node);
                        } else {
                            if (scscm__lexer__scscm_hycstr_hyeq_qu(knd_196, ":string")) {
                                return scscm__codegen__scscm_hyconcat("\"", scscm__codegen__scscm_hyconcat(scscm__parser__ast_hystring_hyvalue(node), "\""));
                            } else {
                                if (scscm__lexer__scscm_hycstr_hyeq_qu(knd_196, ":list")) {
                                    return scscm__codegen__scscm_hygen_hylist(node);
                                } else {
                                    if (scscm__lexer__scscm_hycstr_hyeq_qu(knd_196, ":vector")) {
                                        return scscm__codegen__scscm_hyconcat("[", scscm__codegen__scscm_hyconcat(scscm__codegen__scscm_hygen_hyargs(node, INT64_C(0)), "]"));
                                    } else {
                                        if (scscm__lexer__scscm_hycstr_hyeq_qu(knd_196, ":hash-paren")) {
                                            return scscm__codegen__scscm_hyconcat("[", scscm__codegen__scscm_hyconcat(scscm__codegen__scscm_hygen_hyargs(node, INT64_C(0)), "]"));
                                        } else {
                                            if (scscm__lexer__scscm_hycstr_hyeq_qu(knd_196, ":quote")) {
                                                {
                                                    int64_t inner_198 = scscm__parser__ast_hylist_hyget(node, INT64_C(0));
                                                    (void)inner_198;
                                                    if (scscm__lexer__scscm_hycstr_hyeq_qu(scscm__parser__ast_hykind(inner_198), ":symbol")) {
                                                        return scscm__codegen__scscm_hyconcat("\\", scscm__parser__ast_hysymbol_hyname(inner_198));
                                                    } else {
                                                        int64_t __t37 = inner_198;
                                                        node = __t37;
                                                        goto __tur_tailcall;
                                                    }
                                                }
                                            } else {
                                                bool __t38 = scscm__lexer__scscm_hycstr_hyeq_qu(knd_196, ":quasiquote");
                                                if (!__t38) {
                                                    __t38 = scscm__lexer__scscm_hycstr_hyeq_qu(knd_196, ":unquote");
                                                }
                                                if (!__t38) {
                                                    __t38 = scscm__lexer__scscm_hycstr_hyeq_qu(knd_196, ":unquote-splice");
                                                }
                                                if (__t38) {
                                                    int64_t __t39 = scscm__parser__ast_hylist_hyget(node, INT64_C(0));
                                                    node = __t39;
                                                    goto __tur_tailcall;
                                                } else {
                                                    return "";
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
}

static const char * scscm__codegen__scscm_hygen_hyall_hyloop(int64_t nodes, const char * acc) {
        __tur_tailcall:;
        if (scscm__lexer__list_hynil_qu(nodes)) {
            return acc;
        } else {
            {
                const char * text_201 = scscm__codegen__generate(scscm__lexer__head(nodes));
                (void)text_201;
                int64_t rest_202 = scscm__lexer__tail(nodes);
                (void)rest_202;
                if (scscm__lexer__list_hynil_qu(rest_202)) {
                    return scscm__codegen__scscm_hyconcat(acc, text_201);
                } else {
                    int64_t __t40 = rest_202;
                    const char * __t41 = scscm__codegen__scscm_hyconcat(acc, scscm__codegen__scscm_hyconcat(text_201, ";\n"));
                    nodes = __t40;
                    acc = __t41;
                    goto __tur_tailcall;
                }
            }
        }
}

const char * scscm__codegen__generate_hyall(int64_t nodes) {
        return scscm__codegen__scscm_hygen_hyall_hyloop(nodes, "");
}


