/* generated by tur (phase 2) */
#ifndef TUR_scscm__expander_H
#define TUR_scscm__expander_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "scscm__lexer.h"
#include "scscm__parser.h"

int64_t scscm__expander__expand(int64_t);
int64_t scscm__expander__expand_hyall(int64_t);
#endif /* TUR_scscm__expander_H */
