/* generated by tur (phase 2) */
#include "scscm__codegen.h"

static const char * scscm__codegen__scscm_sym_escape(const char *);
static bool scscm__codegen__scscm_is_binary_op_(const char *);
static const char * scscm__codegen__scscm_sclang_op(const char *);
static const char * scscm__codegen__scscm_concat(const char *, const char *);
static const char * scscm__codegen__scscm_brace(const char *);
static const char * scscm__codegen__scscm_gen_args(int64_t, int64_t);
static const char * scscm__codegen__scscm_gen_cons_list(int64_t);
static const char * scscm__codegen__scscm_gen_params(int64_t, int64_t);
static const char * scscm__codegen__scscm_gen_stmts(int64_t, int64_t);
static const char * scscm__codegen__scscm_gen_let_bindings(int64_t, int64_t);
static const char * scscm__codegen__scscm_gen_dot(int64_t);
static const char * scscm__codegen__scscm_gen_dotdot(int64_t);
static const char * scscm__codegen__scscm_gen_fn(int64_t);
static const char * scscm__codegen__scscm_gen_defn(int64_t);
static const char * scscm__codegen__scscm_gen_if(int64_t);
static const char * scscm__codegen__scscm_gen_let(int64_t);
static const char * scscm__codegen__scscm_gen_quote(int64_t);
static const char * scscm__codegen__scscm_gen_list_sym(int64_t, const char *);
static const char * scscm__codegen__scscm_gen_list(int64_t);
static const char * scscm__codegen__scscm_kw_name(const char *);
const char * scscm__codegen__generate(int64_t);
static const char * scscm__codegen__scscm_gen_all_loop(int64_t, const char *);
const char * scscm__codegen__generate_all(int64_t);

static const char * scscm__codegen__scscm_sym_escape(const char * name) {
        const char *src = (const char*)(intptr_t)name;
  int len = (int)strlen(src);
  /* worst case: each char stays same (no expansion needed) */
  char *out = malloc(len + 3); /* +3 for possible _p/_b suffix + NUL */
  int j = 0;
  for (int i = 0; i < len; i++) {
    char c = src[i];
    if (c == '-') out[j++] = '_';
    else if (c == '?' && i == len - 1) { out[j++] = '_'; out[j++] = 'p'; }
    else if (c == '!' && i == len - 1) { out[j++] = '_'; out[j++] = 'b'; }
    else out[j++] = c;
  }
  out[j] = '\0';
  return out;
  
}

static bool scscm__codegen__scscm_is_binary_op_(const char * name) {
        const char *n = (const char*)(intptr_t)name;
  if (!n) return false;
  static const char *ops[] = {
    "+","-","*","/","=","<",">","<=",">=","!=",
    "&&","||","&","|","^","<<",">>",
    "and","or","mod","rem",NULL
  };
  for (int i = 0; ops[i]; i++)
    if (strcmp(n, ops[i]) == 0) return true;
  return false;
  
}

static const char * scscm__codegen__scscm_sclang_op(const char * name) {
        const char *n = (const char*)(intptr_t)name;
  if (strcmp(n,"=")==0) return "==";
  if (strcmp(n,"and")==0) return "&&";
  if (strcmp(n,"or")==0)  return "||";
  if (strcmp(n,"mod")==0) return "%";
  if (strcmp(n,"rem")==0) return "%";
  return n;
  
}

static const char * scscm__codegen__scscm_concat(const char * a, const char * b) {
        const char *sa = (const char*)(intptr_t)a;
  const char *sb = (const char*)(intptr_t)b;
  if (!sa) sa = ""; if (!sb) sb = "";
  size_t la = strlen(sa), lb = strlen(sb);
  char *out = malloc(la + lb + 1);
  memcpy(out, sa, la); memcpy(out + la, sb, lb);
  out[la + lb] = '\0';
  return out;
  
}

static const char * scscm__codegen__scscm_brace(const char * s) {
        return scscm__codegen__scscm_concat("{ ", scscm__codegen__scscm_concat(s, " }"));
}

static const char * scscm__codegen__scscm_gen_args(int64_t node, int64_t i) {
        const char * __t0;
        if (((i) >= (scscm__parser__ast_list_len(node)))) {
            __t0 = "";
        } else {
            const char * __t1;
            if (((i) == (((scscm__parser__ast_list_len(node)) - (INT64_C(1)))))) {
                __t1 = scscm__codegen__generate(scscm__parser__ast_list_get(node, i));
            } else {
                __t1 = scscm__codegen__scscm_concat(scscm__codegen__generate(scscm__parser__ast_list_get(node, i)), scscm__codegen__scscm_concat(", ", scscm__codegen__scscm_gen_args(node, ((i) + (INT64_C(1))))));
            }
            __t0 = __t1;
        }
        return __t0;
}

static const char * scscm__codegen__scscm_gen_cons_list(int64_t nodes) {
        const char * __t2;
        if (scscm__lexer__list_nil_(nodes)) {
            __t2 = "";
        } else {
            const char * __t3;
            if (scscm__lexer__list_nil_(scscm__lexer__tail(nodes))) {
                __t3 = scscm__codegen__generate(scscm__lexer__head(nodes));
            } else {
                __t3 = scscm__codegen__scscm_concat(scscm__codegen__generate(scscm__lexer__head(nodes)), scscm__codegen__scscm_concat(", ", scscm__codegen__scscm_gen_cons_list(scscm__lexer__tail(nodes))));
            }
            __t2 = __t3;
        }
        return __t2;
}

static const char * scscm__codegen__scscm_gen_params(int64_t node, int64_t i) {
        const char * __t4;
        if (((i) >= (scscm__parser__ast_list_len(node)))) {
            __t4 = "";
        } else {
            const char * __t5;
            if (((i) == (((scscm__parser__ast_list_len(node)) - (INT64_C(1)))))) {
                __t5 = scscm__codegen__scscm_sym_escape(scscm__parser__ast_symbol_name(scscm__parser__ast_list_get(node, i)));
            } else {
                __t5 = scscm__codegen__scscm_concat(scscm__codegen__scscm_sym_escape(scscm__parser__ast_symbol_name(scscm__parser__ast_list_get(node, i))), scscm__codegen__scscm_concat(", ", scscm__codegen__scscm_gen_params(node, ((i) + (INT64_C(1))))));
            }
            __t4 = __t5;
        }
        return __t4;
}

static const char * scscm__codegen__scscm_gen_stmts(int64_t node, int64_t i) {
        const char * __t6;
        if (((i) >= (scscm__parser__ast_list_len(node)))) {
            __t6 = "";
        } else {
            const char * __t7;
            if (((i) == (((scscm__parser__ast_list_len(node)) - (INT64_C(1)))))) {
                __t7 = scscm__codegen__generate(scscm__parser__ast_list_get(node, i));
            } else {
                __t7 = scscm__codegen__scscm_concat(scscm__codegen__generate(scscm__parser__ast_list_get(node, i)), scscm__codegen__scscm_concat(";\n", scscm__codegen__scscm_gen_stmts(node, ((i) + (INT64_C(1))))));
            }
            __t6 = __t7;
        }
        return __t6;
}

static const char * scscm__codegen__scscm_gen_let_bindings(int64_t bvec, int64_t i) {
        const char * __t8;
        if (((i) >= (scscm__parser__ast_list_len(bvec)))) {
            __t8 = "";
        } else {
            const char * __t9;
            {
                int64_t name_node_166 = scscm__parser__ast_list_get(bvec, i);
                (void)name_node_166;
                int64_t val_node_167 = scscm__parser__ast_list_get(bvec, ((i) + (INT64_C(1))));
                (void)val_node_167;
                const char * binding_168 = scscm__codegen__scscm_concat("var ", scscm__codegen__scscm_concat(scscm__codegen__scscm_sym_escape(scscm__parser__ast_symbol_name(name_node_166)), scscm__codegen__scscm_concat(" = ", scscm__codegen__generate(val_node_167))));
                (void)binding_168;
                const char * __t10;
                if (((((i) + (INT64_C(2)))) >= (scscm__parser__ast_list_len(bvec)))) {
                    __t10 = binding_168;
                } else {
                    __t10 = scscm__codegen__scscm_concat(binding_168, scscm__codegen__scscm_concat(";\n", scscm__codegen__scscm_gen_let_bindings(bvec, ((i) + (INT64_C(2))))));
                }
                __t9 = __t10;
            }
            __t8 = __t9;
        }
        return __t8;
}

static const char * scscm__codegen__scscm_gen_dot(int64_t node) {
        const char * __t11;
        {
            const char * obj_170 = scscm__codegen__generate(scscm__parser__ast_list_get(node, INT64_C(1)));
            (void)obj_170;
            const char * msg_171 = scscm__codegen__scscm_sym_escape(scscm__parser__ast_symbol_name(scscm__parser__ast_list_get(node, INT64_C(2))));
            (void)msg_171;
            const char * __t12;
            if (((scscm__parser__ast_list_len(node)) <= (INT64_C(3)))) {
                __t12 = scscm__codegen__scscm_concat(obj_170, scscm__codegen__scscm_concat(".", msg_171));
            } else {
                __t12 = scscm__codegen__scscm_concat(obj_170, scscm__codegen__scscm_concat(".", scscm__codegen__scscm_concat(msg_171, scscm__codegen__scscm_concat("(", scscm__codegen__scscm_concat(scscm__codegen__scscm_gen_args(node, INT64_C(3)), ")")))));
            }
            __t11 = __t12;
        }
        return __t11;
}

static const char * scscm__codegen__scscm_gen_dotdot(int64_t node) {
        const char * __t13;
        {
            const char * cls_173 = scscm__parser__ast_symbol_name(scscm__parser__ast_list_get(node, INT64_C(1)));
            (void)cls_173;
            const char * msg_174 = scscm__codegen__scscm_sym_escape(scscm__parser__ast_symbol_name(scscm__parser__ast_list_get(node, INT64_C(2))));
            (void)msg_174;
            const char * __t14;
            if (((scscm__parser__ast_list_len(node)) <= (INT64_C(3)))) {
                __t14 = scscm__codegen__scscm_concat(cls_173, scscm__codegen__scscm_concat(".", msg_174));
            } else {
                __t14 = scscm__codegen__scscm_concat(cls_173, scscm__codegen__scscm_concat(".", scscm__codegen__scscm_concat(msg_174, scscm__codegen__scscm_concat("(", scscm__codegen__scscm_concat(scscm__codegen__scscm_gen_args(node, INT64_C(3)), ")")))));
            }
            __t13 = __t14;
        }
        return __t13;
}

static const char * scscm__codegen__scscm_gen_fn(int64_t node) {
        const char * __t15;
        {
            int64_t params_node_176 = scscm__parser__ast_list_get(node, INT64_C(1));
            (void)params_node_176;
            const char * __t16;
            if (((scscm__parser__ast_list_len(params_node_176)) == (INT64_C(0)))) {
                __t16 = scscm__codegen__scscm_concat("{ ", scscm__codegen__scscm_concat(scscm__codegen__scscm_gen_stmts(node, INT64_C(2)), " }"));
            } else {
                __t16 = scscm__codegen__scscm_concat("{ |", scscm__codegen__scscm_concat(scscm__codegen__scscm_gen_params(params_node_176, INT64_C(0)), scscm__codegen__scscm_concat("| ", scscm__codegen__scscm_concat(scscm__codegen__scscm_gen_stmts(node, INT64_C(2)), " }"))));
            }
            __t15 = __t16;
        }
        return __t15;
}

static const char * scscm__codegen__scscm_gen_defn(int64_t node) {
        const char * __t17;
        {
            const char * name_178 = scscm__codegen__scscm_sym_escape(scscm__parser__ast_symbol_name(scscm__parser__ast_list_get(node, INT64_C(1))));
            (void)name_178;
            int64_t params_node_179 = scscm__parser__ast_list_get(node, INT64_C(2));
            (void)params_node_179;
            const char * __t18;
            if (((scscm__parser__ast_list_len(params_node_179)) == (INT64_C(0)))) {
                __t18 = scscm__codegen__scscm_concat(name_178, scscm__codegen__scscm_concat(" = { ", scscm__codegen__scscm_concat(scscm__codegen__scscm_gen_stmts(node, INT64_C(3)), " }")));
            } else {
                __t18 = scscm__codegen__scscm_concat(name_178, scscm__codegen__scscm_concat(" = { |", scscm__codegen__scscm_concat(scscm__codegen__scscm_gen_params(params_node_179, INT64_C(0)), scscm__codegen__scscm_concat("| ", scscm__codegen__scscm_concat(scscm__codegen__scscm_gen_stmts(node, INT64_C(3)), " }")))));
            }
            __t17 = __t18;
        }
        return __t17;
}

static const char * scscm__codegen__scscm_gen_if(int64_t node) {
        const char * __t19;
        if (((scscm__parser__ast_list_len(node)) >= (INT64_C(4)))) {
            __t19 = scscm__codegen__scscm_concat("if(", scscm__codegen__scscm_concat(scscm__codegen__generate(scscm__parser__ast_list_get(node, INT64_C(1))), scscm__codegen__scscm_concat(", ", scscm__codegen__scscm_concat(scscm__codegen__scscm_brace(scscm__codegen__generate(scscm__parser__ast_list_get(node, INT64_C(2)))), scscm__codegen__scscm_concat(", ", scscm__codegen__scscm_concat(scscm__codegen__scscm_brace(scscm__codegen__generate(scscm__parser__ast_list_get(node, INT64_C(3)))), ")"))))));
        } else {
            __t19 = scscm__codegen__scscm_concat("if(", scscm__codegen__scscm_concat(scscm__codegen__generate(scscm__parser__ast_list_get(node, INT64_C(1))), scscm__codegen__scscm_concat(", ", scscm__codegen__scscm_concat(scscm__codegen__scscm_brace(scscm__codegen__generate(scscm__parser__ast_list_get(node, INT64_C(2)))), ")"))));
        }
        return __t19;
}

static const char * scscm__codegen__scscm_gen_let(int64_t node) {
        const char * __t20;
        {
            int64_t bvec_182 = scscm__parser__ast_list_get(node, INT64_C(1));
            (void)bvec_182;
            const char * binds_183 = scscm__codegen__scscm_gen_let_bindings(bvec_182, INT64_C(0));
            (void)binds_183;
            const char * body_184 = scscm__codegen__scscm_gen_stmts(node, INT64_C(2));
            (void)body_184;
            __t20 = scscm__codegen__scscm_concat(binds_183, scscm__codegen__scscm_concat(";\n", body_184));
        }
        return __t20;
}

static const char * scscm__codegen__scscm_gen_quote(int64_t node) {
        const char * __t21;
        {
            int64_t inner_186 = scscm__parser__ast_list_get(node, INT64_C(1));
            (void)inner_186;
            const char * __t22;
            if (scscm__lexer__scscm_cstr_eq_(scscm__parser__ast_kind(inner_186), ":symbol")) {
                __t22 = scscm__codegen__scscm_concat("\\", scscm__parser__ast_symbol_name(inner_186));
            } else {
                __t22 = scscm__codegen__generate(inner_186);
            }
            __t21 = __t22;
        }
        return __t21;
}

static const char * scscm__codegen__scscm_gen_list_sym(int64_t node, const char * head_name) {
        const char * __t23;
        if (scscm__lexer__scscm_cstr_eq_(head_name, ".")) {
            __t23 = scscm__codegen__scscm_gen_dot(node);
        } else {
            const char * __t24;
            if (scscm__lexer__scscm_cstr_eq_(head_name, ".dot")) {
                __t24 = scscm__codegen__scscm_gen_dotdot(node);
            } else {
                const char * __t25;
                if (scscm__lexer__scscm_cstr_eq_(head_name, "fn")) {
                    __t25 = scscm__codegen__scscm_gen_fn(node);
                } else {
                    const char * __t26;
                    if (scscm__lexer__scscm_cstr_eq_(head_name, "defn")) {
                        __t26 = scscm__codegen__scscm_gen_defn(node);
                    } else {
                        const char * __t27;
                        if (scscm__lexer__scscm_cstr_eq_(head_name, "var")) {
                            __t27 = scscm__codegen__scscm_concat("var ", scscm__codegen__scscm_concat(scscm__codegen__scscm_sym_escape(scscm__parser__ast_symbol_name(scscm__parser__ast_list_get(node, INT64_C(1)))), scscm__codegen__scscm_concat(" = ", scscm__codegen__generate(scscm__parser__ast_list_get(node, INT64_C(2))))));
                        } else {
                            const char * __t28;
                            if (scscm__lexer__scscm_cstr_eq_(head_name, "set!")) {
                                __t28 = scscm__codegen__scscm_concat(scscm__codegen__scscm_sym_escape(scscm__parser__ast_symbol_name(scscm__parser__ast_list_get(node, INT64_C(1)))), scscm__codegen__scscm_concat(" = ", scscm__codegen__generate(scscm__parser__ast_list_get(node, INT64_C(2)))));
                            } else {
                                const char * __t29;
                                if (scscm__lexer__scscm_cstr_eq_(head_name, "let")) {
                                    __t29 = scscm__codegen__scscm_gen_let(node);
                                } else {
                                    const char * __t30;
                                    if (scscm__lexer__scscm_cstr_eq_(head_name, "if")) {
                                        __t30 = scscm__codegen__scscm_gen_if(node);
                                    } else {
                                        const char * __t31;
                                        if (scscm__lexer__scscm_cstr_eq_(head_name, "do")) {
                                            __t31 = scscm__codegen__scscm_gen_stmts(node, INT64_C(1));
                                        } else {
                                            const char * __t32;
                                            if (scscm__lexer__scscm_cstr_eq_(head_name, "quote")) {
                                                __t32 = scscm__codegen__scscm_gen_quote(node);
                                            } else {
                                                const char * __t33;
                                                if (scscm__codegen__scscm_is_binary_op_(head_name)) {
                                                    __t33 = scscm__codegen__scscm_concat(scscm__codegen__generate(scscm__parser__ast_list_get(node, INT64_C(1))), scscm__codegen__scscm_concat(" ", scscm__codegen__scscm_concat(scscm__codegen__scscm_sclang_op(head_name), scscm__codegen__scscm_concat(" ", scscm__codegen__generate(scscm__parser__ast_list_get(node, INT64_C(2)))))));
                                                } else {
                                                    __t33 = scscm__codegen__scscm_concat(scscm__codegen__scscm_sym_escape(head_name), scscm__codegen__scscm_concat("(", scscm__codegen__scscm_concat(scscm__codegen__scscm_gen_args(node, INT64_C(1)), ")")));
                                                }
                                                __t32 = __t33;
                                            }
                                            __t31 = __t32;
                                        }
                                        __t30 = __t31;
                                    }
                                    __t29 = __t30;
                                }
                                __t28 = __t29;
                            }
                            __t27 = __t28;
                        }
                        __t26 = __t27;
                    }
                    __t25 = __t26;
                }
                __t24 = __t25;
            }
            __t23 = __t24;
        }
        return __t23;
}

static const char * scscm__codegen__scscm_gen_list(int64_t node) {
        const char * __t34;
        if (((scscm__parser__ast_list_len(node)) == (INT64_C(0)))) {
            __t34 = "()";
        } else {
            const char * __t35;
            {
                int64_t head_node_190 = scscm__parser__ast_list_get(node, INT64_C(0));
                (void)head_node_190;
                const char * head_kind_191 = scscm__parser__ast_kind(head_node_190);
                (void)head_kind_191;
                const char * __t36;
                if (scscm__lexer__scscm_cstr_eq_(head_kind_191, ":symbol")) {
                    __t36 = scscm__codegen__scscm_gen_list_sym(node, scscm__parser__ast_symbol_name(head_node_190));
                } else {
                    __t36 = scscm__codegen__scscm_concat(scscm__codegen__generate(head_node_190), scscm__codegen__scscm_concat("(", scscm__codegen__scscm_concat(scscm__codegen__scscm_gen_args(node, INT64_C(1)), ")")));
                }
                __t35 = __t36;
            }
            __t34 = __t35;
        }
        return __t34;
}

static const char * scscm__codegen__scscm_kw_name(const char * raw) {
        const char *s = (const char*)(intptr_t)raw;
  if (s && s[0] == ':') return s + 1;
  return s ? s : "";
  
}

const char * scscm__codegen__generate(int64_t node) {
        const char * __t37;
        {
            const char * knd_194 = scscm__parser__ast_kind(node);
            (void)knd_194;
            const char * __t38;
            if (scscm__lexer__scscm_cstr_eq_(knd_194, ":atom")) {
                __t38 = scscm__parser__scscm_ast_value(node);
            } else {
                const char * __t39;
                if (scscm__lexer__scscm_cstr_eq_(knd_194, ":symbol")) {
                    __t39 = scscm__codegen__scscm_sym_escape(scscm__parser__ast_symbol_name(node));
                } else {
                    const char * __t40;
                    if (scscm__lexer__scscm_cstr_eq_(knd_194, ":keyword")) {
                        const char * __t41;
                        {
                            const char * raw_195 = scscm__parser__scscm_ast_value(node);
                            (void)raw_195;
                            __t41 = scscm__codegen__scscm_concat("\\", scscm__codegen__scscm_kw_name(raw_195));
                        }
                        __t40 = __t41;
                    } else {
                        const char * __t42;
                        if (scscm__lexer__scscm_cstr_eq_(knd_194, ":number")) {
                            __t42 = scscm__parser__ast_number_value(node);
                        } else {
                            const char * __t43;
                            if (scscm__lexer__scscm_cstr_eq_(knd_194, ":string")) {
                                __t43 = scscm__codegen__scscm_concat("\"", scscm__codegen__scscm_concat(scscm__parser__ast_string_value(node), "\""));
                            } else {
                                const char * __t44;
                                if (scscm__lexer__scscm_cstr_eq_(knd_194, ":list")) {
                                    __t44 = scscm__codegen__scscm_gen_list(node);
                                } else {
                                    const char * __t45;
                                    if (scscm__lexer__scscm_cstr_eq_(knd_194, ":vector")) {
                                        __t45 = scscm__codegen__scscm_concat("[", scscm__codegen__scscm_concat(scscm__codegen__scscm_gen_args(node, INT64_C(0)), "]"));
                                    } else {
                                        const char * __t46;
                                        if (scscm__lexer__scscm_cstr_eq_(knd_194, ":hash-paren")) {
                                            __t46 = scscm__codegen__scscm_concat("[", scscm__codegen__scscm_concat(scscm__codegen__scscm_gen_args(node, INT64_C(0)), "]"));
                                        } else {
                                            const char * __t47;
                                            if (scscm__lexer__scscm_cstr_eq_(knd_194, ":quote")) {
                                                const char * __t48;
                                                {
                                                    int64_t inner_196 = scscm__parser__ast_list_get(node, INT64_C(0));
                                                    (void)inner_196;
                                                    const char * __t49;
                                                    if (scscm__lexer__scscm_cstr_eq_(scscm__parser__ast_kind(inner_196), ":symbol")) {
                                                        __t49 = scscm__codegen__scscm_concat("\\", scscm__parser__ast_symbol_name(inner_196));
                                                    } else {
                                                        __t49 = scscm__codegen__generate(inner_196);
                                                    }
                                                    __t48 = __t49;
                                                }
                                                __t47 = __t48;
                                            } else {
                                                const char * __t50;
                                                bool __t51 = scscm__lexer__scscm_cstr_eq_(knd_194, ":quasiquote");
                                                if (!__t51) {
                                                    __t51 = scscm__lexer__scscm_cstr_eq_(knd_194, ":unquote");
                                                }
                                                if (!__t51) {
                                                    __t51 = scscm__lexer__scscm_cstr_eq_(knd_194, ":unquote-splice");
                                                }
                                                if (__t51) {
                                                    __t50 = scscm__codegen__generate(scscm__parser__ast_list_get(node, INT64_C(0)));
                                                } else {
                                                    __t50 = "";
                                                }
                                                __t47 = __t50;
                                            }
                                            __t46 = __t47;
                                        }
                                        __t45 = __t46;
                                    }
                                    __t44 = __t45;
                                }
                                __t43 = __t44;
                            }
                            __t42 = __t43;
                        }
                        __t40 = __t42;
                    }
                    __t39 = __t40;
                }
                __t38 = __t39;
            }
            __t37 = __t38;
        }
        return __t37;
}

static const char * scscm__codegen__scscm_gen_all_loop(int64_t nodes, const char * acc) {
        const char * __t52;
        if (scscm__lexer__list_nil_(nodes)) {
            __t52 = acc;
        } else {
            const char * __t53;
            {
                const char * text_199 = scscm__codegen__generate(scscm__lexer__head(nodes));
                (void)text_199;
                int64_t rest_200 = scscm__lexer__tail(nodes);
                (void)rest_200;
                const char * __t54;
                if (scscm__lexer__list_nil_(rest_200)) {
                    __t54 = scscm__codegen__scscm_concat(acc, text_199);
                } else {
                    __t54 = scscm__codegen__scscm_gen_all_loop(rest_200, scscm__codegen__scscm_concat(acc, scscm__codegen__scscm_concat(text_199, ";\n")));
                }
                __t53 = __t54;
            }
            __t52 = __t53;
        }
        return __t52;
}

const char * scscm__codegen__generate_all(int64_t nodes) {
        return scscm__codegen__scscm_gen_all_loop(nodes, "");
}


