/* generated by tur (phase 2) */
#include "scscm__compile.h"

static int64_t scscm__compile__scscm_read_file(const char *);
static const char * scscm__compile__scscm_int_as_cstr(int64_t);
void * scscm__compile__compile_text(const char *);
void * scscm__compile__compile_file(const char *);

static int64_t scscm__compile__scscm_read_file(const char * path) {
        const char *p = (const char*)(intptr_t)path;
  FILE *f = fopen(p, "rb");
  if (!f) return 0;
  fseek(f, 0, SEEK_END);
  long sz = ftell(f);
  rewind(f);
  char *buf = malloc(sz + 1);
  if (!buf) { fclose(f); return 0; }
  fread(buf, 1, sz, f);
  buf[sz] = '\0';
  fclose(f);
  return (int64_t)(intptr_t)buf;
  
}

static const char * scscm__compile__scscm_int_as_cstr(int64_t n) {
        return (const char *)(intptr_t)n;
  
}

void * scscm__compile__compile_text(const char * source) {
        void * __t0;
        {
            void * lex_res_469 = scscm__lexer__tokenize(source);
            (void)lex_res_469;
            void * __t1;
            if (scscm__lexer__lex_err_((void *)(intptr_t)(lex_res_469))) {
                __t1 = lex_res_469;
            } else {
                void * __t2;
                {
                    int64_t tokens_470 = scscm__lexer__lex_ok_val((void *)(intptr_t)(lex_res_469));
                    (void)tokens_470;
                    void * parse_res_471 = scscm__parser__parse(tokens_470);
                    (void)parse_res_471;
                    scscm__lexer__tokens_free(tokens_470);
                    void * __t3;
                    void * __t4;
                    if (scscm__lexer__lex_err_((void *)(intptr_t)(parse_res_471))) {
                        __t4 = parse_res_471;
                    } else {
                        void * __t5;
                        {
                            int64_t ast_list_472 = scscm__lexer__lex_ok_val((void *)(intptr_t)(parse_res_471));
                            (void)ast_list_472;
                            int64_t expanded_473 = scscm__expander__expand_all(ast_list_472);
                            (void)expanded_473;
                            const char * sclang_474 = scscm__codegen__generate_all(expanded_473);
                            (void)sclang_474;
                            scscm__parser__ast_free_all(ast_list_472);
                            void * __t6;
                            __t6 = scscm__lexer__lex_ok(scscm__lexer__scscm_cstr_as_int(sclang_474));
                            __t5 = __t6;
                        }
                        __t4 = __t5;
                    }
                    __t3 = __t4;
                    __t2 = __t3;
                }
                __t1 = __t2;
            }
            __t0 = __t1;
        }
        return __t0;
}

void * scscm__compile__compile_file(const char * path) {
        void * __t7;
        {
            int64_t buf_476 = scscm__compile__scscm_read_file(path);
            (void)buf_476;
            void * __t8;
            if (((buf_476) == (INT64_C(0)))) {
                __t8 = scscm__lexer__lex_err(INT64_C(0));
            } else {
                void * __t9;
                {
                    const char * src_477 = scscm__compile__scscm_int_as_cstr(buf_476);
                    (void)src_477;
                    __t9 = scscm__compile__compile_text(src_477);
                }
                __t8 = __t9;
            }
            __t7 = __t8;
        }
        return __t7;
}


