/* generated by tur (phase 2) */
#ifndef TUR_scscm__compile_H
#define TUR_scscm__compile_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "scscm__lexer.h"
#include "scscm__parser.h"
#include "scscm__expander.h"
#include "scscm__codegen.h"

void * scscm__compile__compile_hytext(const char *);
void * scscm__compile__compile_hyfile(const char *);
#endif /* TUR_scscm__compile_H */
