/* generated by tur (phase 2) */
#include "scscm__compile.h"

static int64_t scscm__compile__scscm_hyread_hyfile(const char *);
static const char * scscm__compile__scscm_hyint_hyas_hycstr(int64_t);
void * scscm__compile__compile_hytext(const char *);
void * scscm__compile__compile_hyfile(const char *);

static int64_t scscm__compile__scscm_hyread_hyfile(const char * path) {
        const char *p = (const char*)(intptr_t)path;
  FILE *f = fopen(p, "rb");
  if (!f) return 0;
  fseek(f, 0, SEEK_END);
  long sz = ftell(f);
  rewind(f);
  char *buf = malloc(sz + 1);
  if (!buf) { fclose(f); return 0; }
  fread(buf, 1, sz, f);
  buf[sz] = '\0';
  fclose(f);
  return (int64_t)(intptr_t)buf;
  
}

static const char * scscm__compile__scscm_hyint_hyas_hycstr(int64_t n) {
        return (const char *)(intptr_t)n;
  
}

void * scscm__compile__compile_hytext(const char * source) {
        void * __t0;
        {
            void * lex_hyres_471 = scscm__lexer__tokenize(source);
            (void)lex_hyres_471;
            void * __t1;
            if (scscm__lexer__lex_hyerr_qu((void *)(intptr_t)(lex_hyres_471))) {
                __t1 = lex_hyres_471;
            } else {
                void * __t2;
                {
                    int64_t tokens_472 = scscm__lexer__lex_hyok_hyval((void *)(intptr_t)(lex_hyres_471));
                    (void)tokens_472;
                    void * parse_hyres_473 = scscm__parser__parse(tokens_472);
                    (void)parse_hyres_473;
                    scscm__lexer__tokens_hyfree(tokens_472);
                    void * __t3;
                    void * __t4;
                    if (scscm__lexer__lex_hyerr_qu((void *)(intptr_t)(parse_hyres_473))) {
                        __t4 = parse_hyres_473;
                    } else {
                        void * __t5;
                        {
                            int64_t ast_hylist_474 = scscm__lexer__lex_hyok_hyval((void *)(intptr_t)(parse_hyres_473));
                            (void)ast_hylist_474;
                            int64_t expanded_475 = scscm__expander__expand_hyall(ast_hylist_474);
                            (void)expanded_475;
                            const char * sclang_476 = scscm__codegen__generate_hyall(expanded_475);
                            (void)sclang_476;
                            scscm__parser__ast_hyfree_hyall(ast_hylist_474);
                            void * __t6;
                            __t6 = scscm__lexer__lex_hyok(scscm__lexer__scscm_hycstr_hyas_hyint(sclang_476));
                            __t5 = __t6;
                        }
                        __t4 = __t5;
                    }
                    __t3 = __t4;
                    __t2 = __t3;
                }
                __t1 = __t2;
            }
            __t0 = __t1;
        }
        return __t0;
}

void * scscm__compile__compile_hyfile(const char * path) {
        void * __t7;
        {
            int64_t buf_478 = scscm__compile__scscm_hyread_hyfile(path);
            (void)buf_478;
            void * __t8;
            if ((buf_478) == (INT64_C(0))) {
                __t8 = scscm__lexer__lex_hyerr(INT64_C(0));
            } else {
                void * __t9;
                {
                    const char * src_479 = scscm__compile__scscm_hyint_hyas_hycstr(buf_478);
                    (void)src_479;
                    __t9 = scscm__compile__compile_hytext(src_479);
                }
                __t8 = __t9;
            }
            __t7 = __t8;
        }
        return __t7;
}


