/* generated by tur (phase 2) */
#include "sqlite__db.h"

static void * sqlite__db____ok(int64_t);
static void * sqlite__db____err(int64_t);
static bool sqlite__db___un_unok_qu(void *);
static int64_t sqlite__db___un_unok_hyval(void *);
static int64_t sqlite__db____nil();
static int64_t sqlite__db____cons(int64_t, int64_t);
static int64_t sqlite__db___un_undb_hyopen_hyraw(const char *);
static void sqlite__db___un_undb_hyclose_hyraw(int64_t);
static int64_t sqlite__db___un_undb_hyexec_hyraw(int64_t, const char *);
static int64_t sqlite__db___un_undb_hyprepare_hyraw(int64_t, const char *);
static int64_t sqlite__db____ncols(int64_t);
static int64_t sqlite__db___un_uncolname_hydup(int64_t, int64_t);
static int64_t sqlite__db___un_uncoltext_hydup(int64_t, int64_t);
static int64_t sqlite__db___un_unstep_hyraw(int64_t);
static void sqlite__db___un_unfinalize_hyraw(int64_t);
static int64_t sqlite__db___un_unbuild_hyrow(int64_t, int64_t, int64_t);
static int64_t sqlite__db___un_uncollect_hyrows(int64_t, int64_t, int64_t);
void * sqlite__db__db_hyopen(const char *);
void * sqlite__db__db_hyclose(int64_t);
void * sqlite__db__db_hyexec(int64_t, const char *);
void * sqlite__db__db_hyprepare(int64_t, const char *);
void * sqlite__db__db_hyquery(int64_t, const char *);

static void * sqlite__db____ok(int64_t v) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = true; r->ok_val = v; r->err_val = 0; return r;
  
}

static void * sqlite__db____err(int64_t e) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = false; r->ok_val = 0; r->err_val = e; return r;
  
}

static bool sqlite__db___un_unok_qu(void * r) {
        struct { bool is_ok; int64_t ok_val; int64_t err_val; } *res = (void *)r;
  return res != NULL && res->is_ok;
  
}

static int64_t sqlite__db___un_unok_hyval(void * r) {
        struct { bool is_ok; int64_t ok_val; int64_t err_val; } *res = (void *)r;
  return res->ok_val;
  
}

static int64_t sqlite__db____nil() {
        return 0;
  
}

static int64_t sqlite__db____cons(int64_t v, int64_t n) {
        #include <stdlib.h>
  struct { int64_t value; int64_t next; } *cell = malloc(sizeof(*cell));
  cell->value = v; cell->next = n;
  return (int64_t)(intptr_t)cell;
  
}

static int64_t sqlite__db___un_undb_hyopen_hyraw(const char * path) {
        #include <sqlite3.h>
  sqlite3 *db = NULL;
  if (sqlite3_open((const char *)path, &db) != SQLITE_OK) {
    if (db) sqlite3_close(db);
    return 0;
  }
  return (int64_t)(intptr_t)db;
  
}

static void sqlite__db___un_undb_hyclose_hyraw(int64_t db) {
        #include <sqlite3.h>
  sqlite3_close((sqlite3 *)(intptr_t)db);
  
}

static int64_t sqlite__db___un_undb_hyexec_hyraw(int64_t db, const char * sql) {
        #include <sqlite3.h>
  return (int64_t)sqlite3_exec((sqlite3 *)(intptr_t)db,
                               (const char *)sql, NULL, NULL, NULL);
  
}

static int64_t sqlite__db___un_undb_hyprepare_hyraw(int64_t db, const char * sql) {
        #include <sqlite3.h>
  sqlite3_stmt *stmt = NULL;
  if (sqlite3_prepare_v2((sqlite3 *)(intptr_t)db,
                         (const char *)sql, -1, &stmt, NULL) != SQLITE_OK)
    return 0;
  return (int64_t)(intptr_t)stmt;
  
}

static int64_t sqlite__db____ncols(int64_t stmt) {
        #include <sqlite3.h>
  return (int64_t)sqlite3_column_count((sqlite3_stmt *)(intptr_t)stmt);
  
}

static int64_t sqlite__db___un_uncolname_hydup(int64_t stmt, int64_t i) {
        #include <sqlite3.h>
  #include <string.h>
  const char *n = sqlite3_column_name((sqlite3_stmt *)(intptr_t)stmt, (int)i);
  if (!n) return (int64_t)(intptr_t)"";
  size_t len = strlen(n);
  char *copy = malloc(len + 1);
  memcpy(copy, n, len + 1);
  return (int64_t)(intptr_t)copy;
  
}

static int64_t sqlite__db___un_uncoltext_hydup(int64_t stmt, int64_t i) {
        #include <sqlite3.h>
  #include <string.h>
  const char *v = (const char *)sqlite3_column_text(
                      (sqlite3_stmt *)(intptr_t)stmt, (int)i);
  if (!v) v = "";
  size_t len = strlen(v);
  char *copy = malloc(len + 1);
  memcpy(copy, v, len + 1);
  return (int64_t)(intptr_t)copy;
  
}

static int64_t sqlite__db___un_unstep_hyraw(int64_t stmt) {
        #include <sqlite3.h>
  int rc = sqlite3_step((sqlite3_stmt *)(intptr_t)stmt);
  if (rc == SQLITE_ROW)  return 1;
  if (rc == SQLITE_DONE) return 0;
  return -1;
  
}

static void sqlite__db___un_unfinalize_hyraw(int64_t stmt) {
        #include <sqlite3.h>
  sqlite3_finalize((sqlite3_stmt *)(intptr_t)stmt);
  
}

static int64_t sqlite__db___un_unbuild_hyrow(int64_t stmt, int64_t i, int64_t acc) {
        __tur_tailcall:;
        if ((i) < (INT64_C(0))) {
            return acc;
        } else {
            int64_t __t0 = stmt;
            int64_t __t1 = (i) - (INT64_C(1));
            int64_t __t2 = sqlite__db____cons(sqlite__db___un_uncolname_hydup(stmt, i), sqlite__db____cons(sqlite__db___un_uncoltext_hydup(stmt, i), acc));
            stmt = __t0;
            i = __t1;
            acc = __t2;
            goto __tur_tailcall;
        }
}

static int64_t sqlite__db___un_uncollect_hyrows(int64_t stmt, int64_t ncols, int64_t acc) {
        __tur_tailcall:;
        {
            int64_t rc_48 = sqlite__db___un_unstep_hyraw(stmt);
            (void)rc_48;
            if ((rc_48) == (INT64_C(1))) {
                int64_t __t3 = stmt;
                int64_t __t4 = ncols;
                int64_t __t5 = sqlite__db____cons(sqlite__db___un_unbuild_hyrow(stmt, (ncols) - (INT64_C(1)), sqlite__db____nil()), acc);
                stmt = __t3;
                ncols = __t4;
                acc = __t5;
                goto __tur_tailcall;
            } else {
                sqlite__db___un_unfinalize_hyraw(stmt);
                return acc;
            }
        }
}

void * sqlite__db__db_hyopen(const char * path) {
        void * __t6;
        {
            int64_t raw_50 = sqlite__db___un_undb_hyopen_hyraw(path);
            (void)raw_50;
            void * __t7;
            if ((raw_50) != (INT64_C(0))) {
                __t7 = sqlite__db____ok(raw_50);
            } else {
                __t7 = sqlite__db____err(INT64_C(0));
            }
            __t6 = __t7;
        }
        return __t6;
}

void * sqlite__db__db_hyclose(int64_t db) {
        sqlite__db___un_undb_hyclose_hyraw(db);
        void * __t8;
        __t8 = sqlite__db____ok(INT64_C(0));
        return __t8;
}

void * sqlite__db__db_hyexec(int64_t db, const char * sql) {
        void * __t9;
        {
            int64_t rc_54 = sqlite__db___un_undb_hyexec_hyraw(db, sql);
            (void)rc_54;
            void * __t10;
            if ((rc_54) == (INT64_C(0))) {
                __t10 = sqlite__db____ok(INT64_C(0));
            } else {
                __t10 = sqlite__db____err(INT64_C(0));
            }
            __t9 = __t10;
        }
        return __t9;
}

void * sqlite__db__db_hyprepare(int64_t db, const char * sql) {
        void * __t11;
        {
            int64_t raw_57 = sqlite__db___un_undb_hyprepare_hyraw(db, sql);
            (void)raw_57;
            void * __t12;
            if ((raw_57) != (INT64_C(0))) {
                __t12 = sqlite__db____ok(raw_57);
            } else {
                __t12 = sqlite__db____err(INT64_C(0));
            }
            __t11 = __t12;
        }
        return __t11;
}

void * sqlite__db__db_hyquery(int64_t db, const char * sql) {
        void * __t13;
        {
            void * pr_60 = sqlite__db__db_hyprepare(db, sql);
            (void)pr_60;
            void * __t14;
            if (sqlite__db___un_unok_qu((void *)(intptr_t)(pr_60))) {
                void * __t15;
                {
                    int64_t stmt_61 = sqlite__db___un_unok_hyval((void *)(intptr_t)(pr_60));
                    (void)stmt_61;
                    __t15 = sqlite__db____ok(sqlite__db___un_uncollect_hyrows(stmt_61, sqlite__db____ncols(stmt_61), sqlite__db____nil()));
                }
                __t14 = __t15;
            } else {
                __t14 = pr_60;
            }
            __t13 = __t14;
        }
        return __t13;
}


