/* generated by tur (phase 2) */
#ifndef TUR_sqlite__db_H
#define TUR_sqlite__db_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void * sqlite__db__db_hyopen(const char *);
void * sqlite__db__db_hyclose(int64_t);
void * sqlite__db__db_hyexec(int64_t, const char *);
void * sqlite__db__db_hyprepare(int64_t, const char *);
void * sqlite__db__db_hyquery(int64_t, const char *);
#endif /* TUR_sqlite__db_H */
