/* generated by tur (phase 2) */
#ifndef TUR_sqlite__row_H
#define TUR_sqlite__row_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int64_t sqlite__row__col_hycount(int64_t);
const char * sqlite__row__col_hyname(int64_t, int64_t);
int64_t sqlite__row__col_hyint(int64_t, int64_t);
double sqlite__row__col_hyreal(int64_t, int64_t);
const char * sqlite__row__col_hytext(int64_t, int64_t);
int64_t sqlite__row__col_hytype(int64_t, int64_t);
const char * sqlite__row__row_hyget(int64_t, const char *);
int64_t sqlite__row__row_hykeys(int64_t);
#endif /* TUR_sqlite__row_H */
