/* generated by tur (phase 2) */
#ifndef TUR_sqlite__stmt_H
#define TUR_sqlite__stmt_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int64_t sqlite__stmt__stmt_hystep(int64_t);
bool sqlite__stmt__stmt_hybind_hyint(int64_t, int64_t, int64_t);
bool sqlite__stmt__stmt_hybind_hyreal(int64_t, int64_t, double);
bool sqlite__stmt__stmt_hybind_hytext(int64_t, int64_t, const char *);
bool sqlite__stmt__stmt_hybind_hynull(int64_t, int64_t);
bool sqlite__stmt__stmt_hyreset(int64_t);
bool sqlite__stmt__stmt_hyfinalize(int64_t);
#endif /* TUR_sqlite__stmt_H */
