/* generated by tur (phase 2) */
#include "sqlite__row.h"

int64_t sqlite__row__col_hycount(int64_t);
const char * sqlite__row__col_hyname(int64_t, int64_t);
int64_t sqlite__row__col_hyint(int64_t, int64_t);
double sqlite__row__col_hyreal(int64_t, int64_t);
const char * sqlite__row__col_hytext(int64_t, int64_t);
int64_t sqlite__row__col_hytype(int64_t, int64_t);
const char * sqlite__row__row_hyget(int64_t, const char *);
int64_t sqlite__row__row_hykeys(int64_t);

int64_t sqlite__row__col_hycount(int64_t stmt) {
        #include <sqlite3.h>
  return (int64_t)sqlite3_column_count((sqlite3_stmt *)(intptr_t)stmt);
  
}

const char * sqlite__row__col_hyname(int64_t stmt, int64_t i) {
        #include <sqlite3.h>
  const char *n = sqlite3_column_name((sqlite3_stmt *)(intptr_t)stmt, (int)i);
  return n ? (char *)n : (char *)"";
  
}

int64_t sqlite__row__col_hyint(int64_t stmt, int64_t i) {
        #include <sqlite3.h>
  return (int64_t)sqlite3_column_int64((sqlite3_stmt *)(intptr_t)stmt, (int)i);
  
}

double sqlite__row__col_hyreal(int64_t stmt, int64_t i) {
        #include <sqlite3.h>
  return sqlite3_column_double((sqlite3_stmt *)(intptr_t)stmt, (int)i);
  
}

const char * sqlite__row__col_hytext(int64_t stmt, int64_t i) {
        #include <sqlite3.h>
  const char *v = (const char *)sqlite3_column_text(
                      (sqlite3_stmt *)(intptr_t)stmt, (int)i);
  return v ? (char *)v : (char *)"";
  
}

int64_t sqlite__row__col_hytype(int64_t stmt, int64_t i) {
        #include <sqlite3.h>
  return (int64_t)sqlite3_column_type((sqlite3_stmt *)(intptr_t)stmt, (int)i);
  
}

const char * sqlite__row__row_hyget(int64_t row, const char * name) {
        #include <string.h>
  struct __rcons { int64_t value; int64_t next; };
  struct __rcons *cell = (struct __rcons *)(intptr_t)row;
  while (cell) {
    const char *k  = (const char *)(intptr_t)cell->value;
    struct __rcons *vc = (struct __rcons *)(intptr_t)cell->next;
    if (!vc) break;
    if (k && strcmp(k, (const char *)name) == 0)
      return (char *)(intptr_t)vc->value;
    cell = (struct __rcons *)(intptr_t)vc->next;
  }
  return (char *)"";
  
}

int64_t sqlite__row__row_hykeys(int64_t row) {
        #include <stdlib.h>
  struct __rcons { int64_t value; int64_t next; };
  struct __rcons *cell = (struct __rcons *)(intptr_t)row;
  struct __rcons *head = NULL, *tail = NULL;
  while (cell) {
    struct __rcons *knode = malloc(sizeof(*knode));
    knode->value = cell->value;
    knode->next  = 0;
    if (!tail) { head = knode; tail = knode; }
    else        { tail->next = (int64_t)(intptr_t)knode; tail = knode; }
    struct __rcons *vc = (struct __rcons *)(intptr_t)cell->next;
    if (!vc) break;
    cell = (struct __rcons *)(intptr_t)vc->next;
  }
  return (int64_t)(intptr_t)head;
  
}


