/* generated by tur (phase 2) */
#include "sqlite__stmt.h"

int64_t sqlite__stmt__stmt_hystep(int64_t);
bool sqlite__stmt__stmt_hybind_hyint(int64_t, int64_t, int64_t);
bool sqlite__stmt__stmt_hybind_hyreal(int64_t, int64_t, double);
bool sqlite__stmt__stmt_hybind_hytext(int64_t, int64_t, const char *);
bool sqlite__stmt__stmt_hybind_hynull(int64_t, int64_t);
bool sqlite__stmt__stmt_hyreset(int64_t);
bool sqlite__stmt__stmt_hyfinalize(int64_t);

int64_t sqlite__stmt__stmt_hystep(int64_t stmt) {
        #include <sqlite3.h>
  int rc = sqlite3_step((sqlite3_stmt *)(intptr_t)stmt);
  if (rc == SQLITE_ROW)  return 1;
  if (rc == SQLITE_DONE) return 0;
  return -1;
  
}

bool sqlite__stmt__stmt_hybind_hyint(int64_t stmt, int64_t i, int64_t value) {
        #include <sqlite3.h>
  return sqlite3_bind_int64((sqlite3_stmt *)(intptr_t)stmt,
                            (int)i, (sqlite3_int64)value) == SQLITE_OK;
  
}

bool sqlite__stmt__stmt_hybind_hyreal(int64_t stmt, int64_t i, double value) {
        #include <sqlite3.h>
  return sqlite3_bind_double((sqlite3_stmt *)(intptr_t)stmt,
                             (int)i, (double)value) == SQLITE_OK;
  
}

bool sqlite__stmt__stmt_hybind_hytext(int64_t stmt, int64_t i, const char * value) {
        #include <sqlite3.h>
  return sqlite3_bind_text((sqlite3_stmt *)(intptr_t)stmt,
                           (int)i, (const char *)value,
                           -1, SQLITE_TRANSIENT) == SQLITE_OK;
  
}

bool sqlite__stmt__stmt_hybind_hynull(int64_t stmt, int64_t i) {
        #include <sqlite3.h>
  return sqlite3_bind_null((sqlite3_stmt *)(intptr_t)stmt, (int)i) == SQLITE_OK;
  
}

bool sqlite__stmt__stmt_hyreset(int64_t stmt) {
        #include <sqlite3.h>
  return sqlite3_reset((sqlite3_stmt *)(intptr_t)stmt) == SQLITE_OK;
  
}

bool sqlite__stmt__stmt_hyfinalize(int64_t stmt) {
        #include <sqlite3.h>
  sqlite3_finalize((sqlite3_stmt *)(intptr_t)stmt);
  return true;
  
}


