/* generated by tur (phase 2) */
#ifndef TUR_wav__info_H
#define TUR_wav__info_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void * wav__info__wav_hyopen_hyread(const char *);
void * wav__info__wav_hyopen_hywrite(const char *, int64_t, int64_t, const char *);
void wav__info__wav_hyclose(int64_t);
int64_t wav__info__wav_hysample_hyrate(int64_t);
int64_t wav__info__wav_hychannels(int64_t);
int64_t wav__info__wav_hyframe_hycount(int64_t);
const char * wav__info__wav_hyformat(int64_t);
#endif /* TUR_wav__info_H */
