/* generated by tur (phase 2) */
#ifndef TUR_wav__reader_H
#define TUR_wav__reader_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void * wav__reader__wav_hyopen_hyread(const char *);
void wav__reader__wav_hyclose(int64_t);
int64_t wav__reader__wav_hyread_hyfloat(int64_t, const char *, int64_t);
void * wav__reader__wav_hyseek(int64_t, int64_t, const char *);
#endif /* TUR_wav__reader_H */
