/* generated by tur (phase 2) */
#include "wav__writer.h"

static void * wav__writer____ok(int64_t);
static void * wav__writer____err(int64_t);
void * wav__writer__wav_hyopen_hywrite(const char *, int64_t, int64_t, const char *);
int64_t wav__writer__wav_hywrite_hyfloat(int64_t, const char *, int64_t);

static void * wav__writer____ok(int64_t v) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = true; r->ok_val = v; r->err_val = 0; return r;
  
}

static void * wav__writer____err(int64_t e) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = false; r->ok_val = 0; r->err_val = e; return r;
  
}

void * wav__writer__wav_hyopen_hywrite(const char * path, int64_t sample_rate, int64_t channels, const char * format) {
        #include <stdlib.h>
  #include <string.h>
  #include <sndfile.h>
  struct __wav { SNDFILE *sf; SF_INFO info; };
  int fmt = SF_FORMAT_WAV | SF_FORMAT_PCM_16;
  if      (strcmp((const char *)format, ":wav-pcm16")  == 0) fmt = SF_FORMAT_WAV  | SF_FORMAT_PCM_16;
  else if (strcmp((const char *)format, ":wav-pcm24")  == 0) fmt = SF_FORMAT_WAV  | SF_FORMAT_PCM_24;
  else if (strcmp((const char *)format, ":wav-pcm32")  == 0) fmt = SF_FORMAT_WAV  | SF_FORMAT_PCM_32;
  else if (strcmp((const char *)format, ":wav-float")  == 0) fmt = SF_FORMAT_WAV  | SF_FORMAT_FLOAT;
  else if (strcmp((const char *)format, ":aiff-pcm16") == 0) fmt = SF_FORMAT_AIFF | SF_FORMAT_PCM_16;
  else if (strcmp((const char *)format, ":flac-pcm16") == 0) fmt = SF_FORMAT_FLAC | SF_FORMAT_PCM_16;
  else if (strcmp((const char *)format, ":flac-pcm24") == 0) fmt = SF_FORMAT_FLAC | SF_FORMAT_PCM_24;
  SF_INFO info;
  memset(&info, 0, sizeof(info));
  info.samplerate = (int)sample_rate;
  info.channels   = (int)channels;
  info.format     = fmt;
  SNDFILE *sf = sf_open((const char *)path, SFM_WRITE, &info);
  if (!sf) {
    struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
    r->is_ok = false; r->ok_val = 0; r->err_val = 0; return r;
  }
  struct __wav *w = malloc(sizeof(struct __wav));
  w->sf = sf;
  w->info = info;
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = true; r->ok_val = (int64_t)(intptr_t)w; r->err_val = 0; return r;
  
}

int64_t wav__writer__wav_hywrite_hyfloat(int64_t w, const char * buf, int64_t frames) {
        #include <sndfile.h>
  struct __wav { SNDFILE *sf; SF_INFO info; };
  struct __wav *wav = (struct __wav *)(intptr_t)w;
  return (int64_t)sf_writef_float(wav->sf, (const float *)(intptr_t)buf, (sf_count_t)frames);
  
}


