/* generated by tur (phase 2) */
#include "wav__info.h"

static void * wav__info____ok(int64_t);
static void * wav__info____err(int64_t);
void * wav__info__wav_hyopen_hyread(const char *);
void * wav__info__wav_hyopen_hywrite(const char *, int64_t, int64_t, const char *);
void wav__info__wav_hyclose(int64_t);
int64_t wav__info__wav_hysample_hyrate(int64_t);
int64_t wav__info__wav_hychannels(int64_t);
int64_t wav__info__wav_hyframe_hycount(int64_t);
const char * wav__info__wav_hyformat(int64_t);

static void * wav__info____ok(int64_t v) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = true; r->ok_val = v; r->err_val = 0; return r;
  
}

static void * wav__info____err(int64_t e) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = false; r->ok_val = 0; r->err_val = e; return r;
  
}

void * wav__info__wav_hyopen_hyread(const char * path) {
        #include <stdlib.h>
  #include <string.h>
  #include <sndfile.h>
  struct __wav { SNDFILE *sf; SF_INFO info; };
  SF_INFO info;
  memset(&info, 0, sizeof(info));
  SNDFILE *sf = sf_open((const char *)path, SFM_READ, &info);
  if (!sf) {
    struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
    r->is_ok = false; r->ok_val = 0; r->err_val = 0; return r;
  }
  struct __wav *w = malloc(sizeof(struct __wav));
  w->sf = sf;
  w->info = info;
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = true; r->ok_val = (int64_t)(intptr_t)w; r->err_val = 0; return r;
  
}

void * wav__info__wav_hyopen_hywrite(const char * path, int64_t sample_rate, int64_t channels, const char * format) {
        #include <stdlib.h>
  #include <string.h>
  #include <sndfile.h>
  struct __wav { SNDFILE *sf; SF_INFO info; };
  int fmt = SF_FORMAT_WAV | SF_FORMAT_PCM_16;
  if      (strcmp((const char *)format, ":wav-pcm16")  == 0) fmt = SF_FORMAT_WAV  | SF_FORMAT_PCM_16;
  else if (strcmp((const char *)format, ":wav-pcm24")  == 0) fmt = SF_FORMAT_WAV  | SF_FORMAT_PCM_24;
  else if (strcmp((const char *)format, ":wav-pcm32")  == 0) fmt = SF_FORMAT_WAV  | SF_FORMAT_PCM_32;
  else if (strcmp((const char *)format, ":wav-float")  == 0) fmt = SF_FORMAT_WAV  | SF_FORMAT_FLOAT;
  else if (strcmp((const char *)format, ":aiff-pcm16") == 0) fmt = SF_FORMAT_AIFF | SF_FORMAT_PCM_16;
  else if (strcmp((const char *)format, ":flac-pcm16") == 0) fmt = SF_FORMAT_FLAC | SF_FORMAT_PCM_16;
  else if (strcmp((const char *)format, ":flac-pcm24") == 0) fmt = SF_FORMAT_FLAC | SF_FORMAT_PCM_24;
  SF_INFO info;
  memset(&info, 0, sizeof(info));
  info.samplerate = (int)sample_rate;
  info.channels   = (int)channels;
  info.format     = fmt;
  SNDFILE *sf = sf_open((const char *)path, SFM_WRITE, &info);
  if (!sf) {
    struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
    r->is_ok = false; r->ok_val = 0; r->err_val = 0; return r;
  }
  struct __wav *w = malloc(sizeof(struct __wav));
  w->sf = sf;
  w->info = info;
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = true; r->ok_val = (int64_t)(intptr_t)w; r->err_val = 0; return r;
  
}

void wav__info__wav_hyclose(int64_t w) {
        #include <stdlib.h>
  #include <sndfile.h>
  struct __wav { SNDFILE *sf; SF_INFO info; };
  struct __wav *wav = (struct __wav *)(intptr_t)w;
  if (wav) { sf_close(wav->sf); free(wav); }
  
}

int64_t wav__info__wav_hysample_hyrate(int64_t w) {
        #include <sndfile.h>
  struct __wav { SNDFILE *sf; SF_INFO info; };
  return (int64_t)((struct __wav *)(intptr_t)w)->info.samplerate;
  
}

int64_t wav__info__wav_hychannels(int64_t w) {
        #include <sndfile.h>
  struct __wav { SNDFILE *sf; SF_INFO info; };
  return (int64_t)((struct __wav *)(intptr_t)w)->info.channels;
  
}

int64_t wav__info__wav_hyframe_hycount(int64_t w) {
        #include <sndfile.h>
  struct __wav { SNDFILE *sf; SF_INFO info; };
  return (int64_t)((struct __wav *)(intptr_t)w)->info.frames;
  
}

const char * wav__info__wav_hyformat(int64_t w) {
        #include <sndfile.h>
  struct __wav { SNDFILE *sf; SF_INFO info; };
  int type = ((struct __wav *)(intptr_t)w)->info.format & SF_FORMAT_TYPEMASK;
  if      (type == SF_FORMAT_WAV)  return "wav";
  else if (type == SF_FORMAT_AIFF) return "aiff";
  else if (type == SF_FORMAT_FLAC) return "flac";
  else                             return "unknown";
  
}


