/* generated by tur (phase 2) */
#include "wav__reader.h"

static void * wav__reader____ok(int64_t);
static void * wav__reader____err(int64_t);
void * wav__reader__wav_hyopen_hyread(const char *);
void wav__reader__wav_hyclose(int64_t);
int64_t wav__reader__wav_hyread_hyfloat(int64_t, const char *, int64_t);
void * wav__reader__wav_hyseek(int64_t, int64_t, const char *);

static void * wav__reader____ok(int64_t v) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = true; r->ok_val = v; r->err_val = 0; return r;
  
}

static void * wav__reader____err(int64_t e) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = false; r->ok_val = 0; r->err_val = e; return r;
  
}

void * wav__reader__wav_hyopen_hyread(const char * path) {
        #include <stdlib.h>
  #include <string.h>
  #include <sndfile.h>
  struct __wav { SNDFILE *sf; SF_INFO info; };
  SF_INFO info;
  memset(&info, 0, sizeof(info));
  SNDFILE *sf = sf_open((const char *)path, SFM_READ, &info);
  if (!sf) {
    struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
    r->is_ok = false; r->ok_val = 0; r->err_val = 0; return r;
  }
  struct __wav *w = malloc(sizeof(struct __wav));
  w->sf = sf;
  w->info = info;
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = true; r->ok_val = (int64_t)(intptr_t)w; r->err_val = 0; return r;
  
}

void wav__reader__wav_hyclose(int64_t w) {
        #include <stdlib.h>
  #include <sndfile.h>
  struct __wav { SNDFILE *sf; SF_INFO info; };
  struct __wav *wav = (struct __wav *)(intptr_t)w;
  if (wav) { sf_close(wav->sf); free(wav); }
  
}

int64_t wav__reader__wav_hyread_hyfloat(int64_t w, const char * buf, int64_t frames) {
        #include <sndfile.h>
  struct __wav { SNDFILE *sf; SF_INFO info; };
  struct __wav *wav = (struct __wav *)(intptr_t)w;
  return (int64_t)sf_readf_float(wav->sf, (float *)(intptr_t)buf, (sf_count_t)frames);
  
}

void * wav__reader__wav_hyseek(int64_t w, int64_t frame_offset, const char * whence) {
        #include <stdlib.h>
  #include <string.h>
  #include <sndfile.h>
  struct __wav { SNDFILE *sf; SF_INFO info; };
  struct __wav *wav = (struct __wav *)(intptr_t)w;
  int whence_val = SEEK_SET;
  if      (strcmp((const char *)whence, ":set") == 0) whence_val = SEEK_SET;
  else if (strcmp((const char *)whence, ":cur") == 0) whence_val = SEEK_CUR;
  else if (strcmp((const char *)whence, ":end") == 0) whence_val = SEEK_END;
  sf_count_t result = sf_seek(wav->sf, (sf_count_t)frame_offset, whence_val);
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  if (result < 0) {
    r->is_ok = false; r->ok_val = 0; r->err_val = 0;
  } else {
    r->is_ok = true; r->ok_val = (int64_t)result; r->err_val = 0;
  }
  return r;
  
}


