/* generated by tur (phase 2) */
#ifndef TUR_wav__writer_H
#define TUR_wav__writer_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void * wav__writer__wav_hyopen_hywrite(const char *, int64_t, int64_t, const char *);
int64_t wav__writer__wav_hywrite_hyfloat(int64_t, const char *, int64_t);
#endif /* TUR_wav__writer_H */
