#define _DEFAULT_SOURCE 1
typedef struct __tur_cons_s { int64_t head; int64_t tail; } __tur_cons_cell;
/* generated by tur (phase 2) */
#include "main.h"

static int64_t g_tur_args = 0;  /* *args*: CLI arguments as list of :cstr */

static int64_t watch__watch___un_unwatch_hymake_hycons(int64_t);
int64_t watch__watch__watch_hydrain(int64_t, int64_t, int64_t);

static int64_t watch__watch___un_unwatch_hymake_hycons(int64_t head) {
        /* __tur_include__: typedef struct __tur_cons_s { int64_t head; int64_t tail; } __tur_cons_cell; */
    if (head == 0) return 0;
    __tur_cons_cell *cell = (__tur_cons_cell *)calloc(1, sizeof(*cell));
    if (!cell) return 0;
    cell->head = head;
    cell->tail = 0;
    return (int64_t)(intptr_t)cell;
    
}

int64_t watch__watch__watch_hydrain(int64_t watcher, int64_t timeout_ms, int64_t debounce_ms) {
        int64_t __t0;
        {
            int64_t _un_1534 = debounce_ms;
            (void)_un_1534;
            int64_t ev_1535 = watch__watch__watch_hynext(watcher, timeout_ms);
            (void)ev_1535;
            __t0 = watch__watch___un_unwatch_hymake_hycons(ev_1535);
        }
        return __t0;
}

int main(int argc, char **argv) {
        /* *args*: build cons list from argv[1..argc-1] */
        g_tur_args = 0;
        for (int _ai = argc - 1; _ai >= 1; _ai--) {
            typedef struct { int64_t value; int64_t next; } __tur_args_cell;
            __tur_args_cell *_c = (__tur_args_cell *)malloc(sizeof(__tur_args_cell));
            _c->value = (int64_t)(intptr_t)argv[_ai];
            _c->next = g_tur_args;
            g_tur_args = (int64_t)(intptr_t)_c;
        }
        return (int)notebook__cli__cli_hymain(g_tur_args);
}


