/* generated by tur (phase 2) */
#ifndef TUR_main_H
#define TUR_main_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "notebook__cli.h"

int64_t watch__watch__watch_hydrain(int64_t, int64_t, int64_t);
#endif /* TUR_main_H */
