/* generated by tur (phase 2) */
#include "plutovg__canvas.h"

static void * plutovg__canvas____ok(int64_t);
static void * plutovg__canvas____err(int64_t);
void * plutovg__canvas__canvas_hycreate(int64_t);
void plutovg__canvas__canvas_hydestroy(int64_t);
void plutovg__canvas__canvas_hyset_hysource_hycolor(int64_t, double, double, double, double);
void plutovg__canvas__canvas_hyfill_hyrect(int64_t, double, double, double, double);
void plutovg__canvas__canvas_hymove_hyto(int64_t, double, double);
void plutovg__canvas__canvas_hyline_hyto(int64_t, double, double);
void plutovg__canvas__canvas_hyquad_hyto(int64_t, double, double, double, double);
void plutovg__canvas__canvas_hycubic_hyto(int64_t, double, double, double, double, double, double);
void plutovg__canvas__canvas_hyclose_hypath(int64_t);
void plutovg__canvas__canvas_hyrect(int64_t, double, double, double, double);
void plutovg__canvas__canvas_hyellipse(int64_t, double, double, double, double);
void plutovg__canvas__canvas_hycircle(int64_t, double, double, double);
void plutovg__canvas__canvas_hyfill(int64_t);
void plutovg__canvas__canvas_hystroke(int64_t);
void plutovg__canvas__canvas_hyclip(int64_t);
void plutovg__canvas__canvas_hyadd_hypath(int64_t, int64_t);
void plutovg__canvas__canvas_hyfill_hypath(int64_t, int64_t);
void plutovg__canvas__canvas_hystroke_hypath(int64_t, int64_t);
void plutovg__canvas__canvas_hysave(int64_t);
void plutovg__canvas__canvas_hyrestore(int64_t);
void plutovg__canvas__canvas_hytranslate(int64_t, double, double);
void plutovg__canvas__canvas_hyscale(int64_t, double, double);
void plutovg__canvas__canvas_hyrotate(int64_t, double);
void plutovg__canvas__canvas_hytransform(int64_t, double, double, double, double, double, double);
void plutovg__canvas__canvas_hyreset_hytransform(int64_t);
void plutovg__canvas__canvas_hyset_hyline_hywidth(int64_t, double);
void plutovg__canvas__canvas_hyset_hyline_hycap(int64_t, const char *);
void plutovg__canvas__canvas_hyset_hyline_hyjoin(int64_t, const char *);
void plutovg__canvas__canvas_hyset_hymiter_hylimit(int64_t, double);
void * plutovg__canvas__dash_hyarray_hycreate();
void plutovg__canvas__dash_hyarray_hyadd(int64_t, double);
int64_t plutovg__canvas__dash_hyarray_hycount(int64_t);
void plutovg__canvas__dash_hyarray_hydestroy(int64_t);
void plutovg__canvas__canvas_hyset_hydash_hyoffset(int64_t, double);
void plutovg__canvas__canvas_hyset_hydash_hyarray(int64_t, int64_t);
void plutovg__canvas__canvas_hyset_hyfill_hyrule(int64_t, const char *);
void plutovg__canvas__canvas_hyset_hyoperator(int64_t, const char *);
void plutovg__canvas__canvas_hyset_hyopacity(int64_t, double);
void plutovg__canvas__canvas_hyarc(int64_t, double, double, double, double, double);
void plutovg__canvas__canvas_hyarc_hyto(int64_t, double, double, double, bool, bool, double, double);
void plutovg__canvas__canvas_hyround_hyrect(int64_t, double, double, double, double, double, double);
void plutovg__canvas__canvas_hydraw_hyimage(int64_t, int64_t, double, double, double, double);

static void * plutovg__canvas____ok(int64_t v) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = true; r->ok_val = v; r->err_val = 0; return r;
  
}

static void * plutovg__canvas____err(int64_t e) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = false; r->ok_val = 0; r->err_val = e; return r;
  
}

void * plutovg__canvas__canvas_hycreate(int64_t s) {
        #include <stdlib.h>
  #include <plutovg.h>
  plutovg_canvas_t *c = plutovg_canvas_create((plutovg_surface_t *)(intptr_t)s);
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  if (!c) { r->is_ok = false; r->ok_val = 0; r->err_val = 0; return r; }
  r->is_ok = true; r->ok_val = (int64_t)(intptr_t)c; r->err_val = 0;
  return r;
  
}

void plutovg__canvas__canvas_hydestroy(int64_t c) {
        #include <plutovg.h>
  if (c) plutovg_canvas_destroy((plutovg_canvas_t *)(intptr_t)c);
  
}

void plutovg__canvas__canvas_hyset_hysource_hycolor(int64_t c, double r, double g, double b, double a) {
        #include <plutovg.h>
  plutovg_canvas_set_rgba((plutovg_canvas_t *)(intptr_t)c,
                          (float)r, (float)g, (float)b, (float)a);
  
}

void plutovg__canvas__canvas_hyfill_hyrect(int64_t c, double x, double y, double w, double h) {
        #include <plutovg.h>
  plutovg_canvas_fill_rect((plutovg_canvas_t *)(intptr_t)c,
                           (float)x, (float)y, (float)w, (float)h);
  
}

void plutovg__canvas__canvas_hymove_hyto(int64_t c, double x, double y) {
        #include <plutovg.h>
  plutovg_canvas_move_to((plutovg_canvas_t *)(intptr_t)c,
                         (float)x, (float)y);
  
}

void plutovg__canvas__canvas_hyline_hyto(int64_t c, double x, double y) {
        #include <plutovg.h>
  plutovg_canvas_line_to((plutovg_canvas_t *)(intptr_t)c,
                         (float)x, (float)y);
  
}

void plutovg__canvas__canvas_hyquad_hyto(int64_t c, double x1, double y1, double x, double y) {
        #include <plutovg.h>
  plutovg_canvas_quad_to((plutovg_canvas_t *)(intptr_t)c,
                         (float)x1, (float)y1, (float)x, (float)y);
  
}

void plutovg__canvas__canvas_hycubic_hyto(int64_t c, double x1, double y1, double x2, double y2, double x, double y) {
        #include <plutovg.h>
  plutovg_canvas_cubic_to((plutovg_canvas_t *)(intptr_t)c,
                          (float)x1, (float)y1,
                          (float)x2, (float)y2,
                          (float)x,  (float)y);
  
}

void plutovg__canvas__canvas_hyclose_hypath(int64_t c) {
        #include <plutovg.h>
  plutovg_canvas_close_path((plutovg_canvas_t *)(intptr_t)c);
  
}

void plutovg__canvas__canvas_hyrect(int64_t c, double x, double y, double w, double h) {
        #include <plutovg.h>
  plutovg_canvas_rect((plutovg_canvas_t *)(intptr_t)c,
                      (float)x, (float)y, (float)w, (float)h);
  
}

void plutovg__canvas__canvas_hyellipse(int64_t c, double cx, double cy, double rx, double ry) {
        #include <plutovg.h>
  plutovg_canvas_ellipse((plutovg_canvas_t *)(intptr_t)c,
                         (float)cx, (float)cy, (float)rx, (float)ry);
  
}

void plutovg__canvas__canvas_hycircle(int64_t c, double cx, double cy, double r) {
        #include <plutovg.h>
  plutovg_canvas_circle((plutovg_canvas_t *)(intptr_t)c,
                        (float)cx, (float)cy, (float)r);
  
}

void plutovg__canvas__canvas_hyfill(int64_t c) {
        #include <plutovg.h>
  plutovg_canvas_fill((plutovg_canvas_t *)(intptr_t)c);
  
}

void plutovg__canvas__canvas_hystroke(int64_t c) {
        #include <plutovg.h>
  plutovg_canvas_stroke((plutovg_canvas_t *)(intptr_t)c);
  
}

void plutovg__canvas__canvas_hyclip(int64_t c) {
        #include <plutovg.h>
  plutovg_canvas_clip((plutovg_canvas_t *)(intptr_t)c);
  
}

void plutovg__canvas__canvas_hyadd_hypath(int64_t c, int64_t path) {
        #include <plutovg.h>
  plutovg_canvas_add_path((plutovg_canvas_t *)(intptr_t)c,
                          (plutovg_path_t *)(intptr_t)path);
  
}

void plutovg__canvas__canvas_hyfill_hypath(int64_t c, int64_t path) {
        #include <plutovg.h>
  plutovg_canvas_fill_path((plutovg_canvas_t *)(intptr_t)c,
                           (plutovg_path_t *)(intptr_t)path);
  
}

void plutovg__canvas__canvas_hystroke_hypath(int64_t c, int64_t path) {
        #include <plutovg.h>
  plutovg_canvas_stroke_path((plutovg_canvas_t *)(intptr_t)c,
                             (plutovg_path_t *)(intptr_t)path);
  
}

void plutovg__canvas__canvas_hysave(int64_t c) {
        #include <plutovg.h>
  plutovg_canvas_save((plutovg_canvas_t *)(intptr_t)c);
  
}

void plutovg__canvas__canvas_hyrestore(int64_t c) {
        #include <plutovg.h>
  plutovg_canvas_restore((plutovg_canvas_t *)(intptr_t)c);
  
}

void plutovg__canvas__canvas_hytranslate(int64_t c, double tx, double ty) {
        #include <plutovg.h>
  plutovg_canvas_translate((plutovg_canvas_t *)(intptr_t)c,
                           (float)tx, (float)ty);
  
}

void plutovg__canvas__canvas_hyscale(int64_t c, double sx, double sy) {
        #include <plutovg.h>
  plutovg_canvas_scale((plutovg_canvas_t *)(intptr_t)c,
                       (float)sx, (float)sy);
  
}

void plutovg__canvas__canvas_hyrotate(int64_t c, double radians) {
        #include <plutovg.h>
  plutovg_canvas_rotate((plutovg_canvas_t *)(intptr_t)c, (float)radians);
  
}

void plutovg__canvas__canvas_hytransform(int64_t c, double a, double b, double cc, double d, double e, double f) {
        #include <plutovg.h>
  plutovg_matrix_t m;
  plutovg_matrix_init(&m, (float)a, (float)b, (float)cc,
                          (float)d, (float)e, (float)f);
  plutovg_canvas_transform((plutovg_canvas_t *)(intptr_t)c, &m);
  
}

void plutovg__canvas__canvas_hyreset_hytransform(int64_t c) {
        #include <plutovg.h>
  plutovg_canvas_reset_matrix((plutovg_canvas_t *)(intptr_t)c);
  
}

void plutovg__canvas__canvas_hyset_hyline_hywidth(int64_t c, double w) {
        #include <plutovg.h>
  plutovg_canvas_set_line_width((plutovg_canvas_t *)(intptr_t)c, (float)w);
  
}

void plutovg__canvas__canvas_hyset_hyline_hycap(int64_t c, const char * cap) {
        #include <string.h>
  #include <plutovg.h>
  const char *k = (const char *)(intptr_t)cap;
  int v = 0; /* PLUTOVG_LINE_CAP_BUTT */
  if (k) {
    if (strcmp(k, ":round")  == 0) v = 1;
    else if (strcmp(k, ":square") == 0) v = 2;
  }
  plutovg_canvas_set_line_cap((plutovg_canvas_t *)(intptr_t)c,
                              (plutovg_line_cap_t)v);
  
}

void plutovg__canvas__canvas_hyset_hyline_hyjoin(int64_t c, const char * join) {
        #include <string.h>
  #include <plutovg.h>
  const char *k = (const char *)(intptr_t)join;
  int v = 0; /* PLUTOVG_LINE_JOIN_MITER */
  if (k) {
    if (strcmp(k, ":round") == 0) v = 1;
    else if (strcmp(k, ":bevel") == 0) v = 2;
  }
  plutovg_canvas_set_line_join((plutovg_canvas_t *)(intptr_t)c,
                               (plutovg_line_join_t)v);
  
}

void plutovg__canvas__canvas_hyset_hymiter_hylimit(int64_t c, double limit) {
        #include <plutovg.h>
  plutovg_canvas_set_miter_limit((plutovg_canvas_t *)(intptr_t)c, (float)limit);
  
}

void * plutovg__canvas__dash_hyarray_hycreate() {
        #include <stdlib.h>
  int initial_cap = 8;
  size_t bytes = sizeof(int) * 2 + (size_t)initial_cap * sizeof(float);
  char *buf = (char *)malloc(bytes);
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  if (!buf) { r->is_ok = false; r->ok_val = 0; r->err_val = 0; return r; }
  ((int *)buf)[0] = initial_cap;
  ((int *)buf)[1] = 0;
  r->is_ok = true; r->ok_val = (int64_t)(intptr_t)buf; r->err_val = 0;
  return r;
  
}

void plutovg__canvas__dash_hyarray_hyadd(int64_t dashes, double length) {
        char *buf = (char *)(intptr_t)dashes;
  if (!buf) return;
  int *header = (int *)buf;
  int cap = header[0];
  int n = header[1];
  if (n >= cap) return; /* drop on overflow; raise capacity in dash-array-create */
  float *arr = (float *)(buf + sizeof(int) * 2);
  arr[n] = (float)length;
  header[1] = n + 1;
  
}

int64_t plutovg__canvas__dash_hyarray_hycount(int64_t dashes) {
        char *buf = (char *)(intptr_t)dashes;
  return buf ? (int64_t)((int *)buf)[1] : 0;
  
}

void plutovg__canvas__dash_hyarray_hydestroy(int64_t dashes) {
        #include <stdlib.h>
  if (dashes) free((void *)(intptr_t)dashes);
  
}

void plutovg__canvas__canvas_hyset_hydash_hyoffset(int64_t c, double offset) {
        #include <plutovg.h>
  plutovg_canvas_set_dash_offset((plutovg_canvas_t *)(intptr_t)c, (float)offset);
  
}

void plutovg__canvas__canvas_hyset_hydash_hyarray(int64_t c, int64_t dashes) {
        #include <plutovg.h>
  char *buf = (char *)(intptr_t)dashes;
  int n = buf ? ((int *)buf)[1] : 0;
  const float *arr = buf ? (const float *)(buf + sizeof(int) * 2) : NULL;
  plutovg_canvas_set_dash_array((plutovg_canvas_t *)(intptr_t)c, arr, n);
  
}

void plutovg__canvas__canvas_hyset_hyfill_hyrule(int64_t c, const char * rule) {
        #include <string.h>
  #include <plutovg.h>
  const char *k = (const char *)(intptr_t)rule;
  int v = 0; /* PLUTOVG_FILL_RULE_NON_ZERO */
  if (k && strcmp(k, ":even-odd") == 0) v = 1;
  plutovg_canvas_set_fill_rule((plutovg_canvas_t *)(intptr_t)c,
                               (plutovg_fill_rule_t)v);
  
}

void plutovg__canvas__canvas_hyset_hyoperator(int64_t c, const char * op) {
        #include <string.h>
  #include <plutovg.h>
  const char *k = (const char *)(intptr_t)op;
  int v = 3; /* PLUTOVG_OPERATOR_SRC_OVER (default) */
  if (k) {
    if      (strcmp(k, ":clear")    == 0) v = 0;
    else if (strcmp(k, ":src")      == 0) v = 1;
    else if (strcmp(k, ":dst")      == 0) v = 2;
    else if (strcmp(k, ":src-over") == 0) v = 3;
    else if (strcmp(k, ":dst-over") == 0) v = 4;
    else if (strcmp(k, ":src-in")   == 0) v = 5;
    else if (strcmp(k, ":dst-in")   == 0) v = 6;
    else if (strcmp(k, ":src-out")  == 0) v = 7;
    else if (strcmp(k, ":dst-out")  == 0) v = 8;
    else if (strcmp(k, ":src-atop") == 0) v = 9;
    else if (strcmp(k, ":dst-atop") == 0) v = 10;
    else if (strcmp(k, ":xor")      == 0) v = 11;
  }
  plutovg_canvas_set_operator((plutovg_canvas_t *)(intptr_t)c,
                              (plutovg_operator_t)v);
  
}

void plutovg__canvas__canvas_hyset_hyopacity(int64_t c, double alpha) {
        #include <plutovg.h>
  plutovg_canvas_set_opacity((plutovg_canvas_t *)(intptr_t)c, (float)alpha);
  
}

void plutovg__canvas__canvas_hyarc(int64_t c, double cx, double cy, double r, double start_angle, double sweep_angle) {
        #include <plutovg.h>
  plutovg_canvas_arc((plutovg_canvas_t *)(intptr_t)c,
                     (float)cx, (float)cy, (float)r,
                     (float)start_angle, (float)sweep_angle, false);
  
}

void plutovg__canvas__canvas_hyarc_hyto(int64_t c, double rx, double ry, double rotation, bool large_arc_qu, bool sweep_qu, double x, double y) {
        #include <plutovg.h>
  plutovg_canvas_arc_to((plutovg_canvas_t *)(intptr_t)c,
                        (float)rx, (float)ry, (float)rotation,
                        large_arc, sweep,
                        (float)x, (float)y);
  
}

void plutovg__canvas__canvas_hyround_hyrect(int64_t c, double x, double y, double w, double h, double rx, double ry) {
        #include <plutovg.h>
  plutovg_canvas_round_rect((plutovg_canvas_t *)(intptr_t)c,
                            (float)x, (float)y, (float)w, (float)h,
                            (float)rx, (float)ry);
  
}

void plutovg__canvas__canvas_hydraw_hyimage(int64_t c, int64_t src, double x, double y, double w, double h) {
        #include <plutovg.h>
  plutovg_surface_t *ss = (plutovg_surface_t *)(intptr_t)src;
  int sw = plutovg_surface_get_width(ss);
  int sh = plutovg_surface_get_height(ss);
  float scale_x = sw > 0 ? (float)w / (float)sw : 1.0f;
  float scale_y = sh > 0 ? (float)h / (float)sh : 1.0f;
  /* Matrix from texture coords (u, v) -> canvas coords:
   *   canvas_x = scale_x * u + x
   *   canvas_y = scale_y * v + y                                     */
  plutovg_matrix_t m;
  plutovg_matrix_init(&m, scale_x, 0.0f, 0.0f, scale_y,
                          (float)x, (float)y);
  plutovg_canvas_save((plutovg_canvas_t *)(intptr_t)c);
  plutovg_canvas_set_texture((plutovg_canvas_t *)(intptr_t)c, ss,
                             PLUTOVG_TEXTURE_TYPE_PLAIN, 1.0f, &m);
  plutovg_canvas_rect((plutovg_canvas_t *)(intptr_t)c,
                      (float)x, (float)y, (float)w, (float)h);
  plutovg_canvas_fill((plutovg_canvas_t *)(intptr_t)c);
  plutovg_canvas_restore((plutovg_canvas_t *)(intptr_t)c);
  
}


