/* generated by tur (phase 2) */
#ifndef TUR_plutovg__paint_H
#define TUR_plutovg__paint_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void * plutovg__paint__paint_hycreate_hycolor(double, double, double, double);
void * plutovg__paint__paint_hycreate_hycolor_hyhex(const char *);
void plutovg__paint__paint_hydestroy(int64_t);
void * plutovg__paint__gradient_hystops_hycreate();
void plutovg__paint__gradient_hystops_hyadd(int64_t, double, double, double, double, double);
int64_t plutovg__paint__gradient_hystops_hycount(int64_t);
void plutovg__paint__gradient_hystops_hydestroy(int64_t);
void * plutovg__paint__paint_hycreate_hylinear_hygradient(double, double, double, double, const char *, int64_t);
void * plutovg__paint__paint_hycreate_hyradial_hygradient(double, double, double, double, double, double, const char *, int64_t);
void * plutovg__paint__paint_hycreate_hytexture(int64_t, const char *, double);
void plutovg__paint__canvas_hyset_hysource(int64_t, int64_t);
#endif /* TUR_plutovg__paint_H */
