/* generated by tur (phase 2) */
#include "plutovg__paint.h"

static void * plutovg__paint____ok(int64_t);
static void * plutovg__paint____err(int64_t);
void * plutovg__paint__paint_hycreate_hycolor(double, double, double, double);
void * plutovg__paint__paint_hycreate_hycolor_hyhex(const char *);
void plutovg__paint__paint_hydestroy(int64_t);
void * plutovg__paint__gradient_hystops_hycreate();
void plutovg__paint__gradient_hystops_hyadd(int64_t, double, double, double, double, double);
int64_t plutovg__paint__gradient_hystops_hycount(int64_t);
void plutovg__paint__gradient_hystops_hydestroy(int64_t);
void * plutovg__paint__paint_hycreate_hylinear_hygradient(double, double, double, double, const char *, int64_t);
void * plutovg__paint__paint_hycreate_hyradial_hygradient(double, double, double, double, double, double, const char *, int64_t);
void * plutovg__paint__paint_hycreate_hytexture(int64_t, const char *, double);
void plutovg__paint__canvas_hyset_hysource(int64_t, int64_t);

static void * plutovg__paint____ok(int64_t v) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = true; r->ok_val = v; r->err_val = 0; return r;
  
}

static void * plutovg__paint____err(int64_t e) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = false; r->ok_val = 0; r->err_val = e; return r;
  
}

void * plutovg__paint__paint_hycreate_hycolor(double r, double g, double b, double a) {
        #include <stdlib.h>
  #include <plutovg.h>
  plutovg_paint_t *p = plutovg_paint_create_rgba((float)r, (float)g, (float)b, (float)a);
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *res = malloc(sizeof(*res));
  if (!p) { res->is_ok = false; res->ok_val = 0; res->err_val = 0; return res; }
  res->is_ok = true; res->ok_val = (int64_t)(intptr_t)p; res->err_val = 0;
  return res;
  
}

void * plutovg__paint__paint_hycreate_hycolor_hyhex(const char * hex) {
        #include <stdlib.h>
  #include <string.h>
  #include <plutovg.h>
  plutovg_color_t col;
  const char *s = (const char *)(intptr_t)hex;
  int parsed = plutovg_color_parse(&col, s, -1);
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *res = malloc(sizeof(*res));
  if (parsed <= 0) {
    res->is_ok = false; res->ok_val = 0; res->err_val = 0;
    return res;
  }
  plutovg_paint_t *p = plutovg_paint_create_color(&col);
  if (!p) { res->is_ok = false; res->ok_val = 0; res->err_val = 0; return res; }
  res->is_ok = true; res->ok_val = (int64_t)(intptr_t)p; res->err_val = 0;
  return res;
  
}

void plutovg__paint__paint_hydestroy(int64_t paint) {
        #include <plutovg.h>
  if (paint) plutovg_paint_destroy((plutovg_paint_t *)(intptr_t)paint);
  
}

void * plutovg__paint__gradient_hystops_hycreate() {
        #include <stdlib.h>
  /* Header { int cap; int count; } + initial 8 stops (40 floats). */
  int initial_cap = 8;
  size_t bytes = sizeof(int) * 2 + (size_t)initial_cap * 5 * sizeof(float);
  char *buf = (char *)malloc(bytes);
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  if (!buf) { r->is_ok = false; r->ok_val = 0; r->err_val = 0; return r; }
  ((int *)buf)[0] = initial_cap; /* capacity in stops */
  ((int *)buf)[1] = 0;            /* count */
  r->is_ok = true; r->ok_val = (int64_t)(intptr_t)buf; r->err_val = 0;
  return r;
  
}

void plutovg__paint__gradient_hystops_hyadd(int64_t stops, double offset, double r, double g, double b, double a) {
        #include <stdlib.h>
  #include <string.h>
  char *buf = (char *)(intptr_t)stops;
  if (!buf) return;
  int *header = (int *)buf;
  int cap = header[0];
  int n   = header[1];
  if (n >= cap) {
    /* grow in place: realloc would invalidate the handle.  Instead we
     * malloc a new buffer, copy, free old, and overwrite the contents
     * of the original handle via memmove -- but we cannot move the
     * caller's pointer.  Workaround: allocate a much larger initial
     * buffer or document the cap; here we double via realloc.  Since the
     * caller stores `stops` by handle (int), the handle changes too. */
    /* Practical approach: realloc the buffer; the caller MUST re-fetch
     * the new handle by calling gradient-stops-add as if it returned the
     * new pointer.  Because we return void here we cannot communicate
     * that.  To keep the API ergonomic we instead grow ahead of time
     * with a generous initial capacity and abort on overflow -- in
     * practice 8 stops is more than enough for typical gradients. */
    /* For now: silently drop the extra stop. */
    return;
  }
  float *stop = (float *)(buf + sizeof(int) * 2) + (size_t)n * 5;
  stop[0] = (float)offset;
  stop[1] = (float)r;
  stop[2] = (float)g;
  stop[3] = (float)b;
  stop[4] = (float)a;
  header[1] = n + 1;
  
}

int64_t plutovg__paint__gradient_hystops_hycount(int64_t stops) {
        char *buf = (char *)(intptr_t)stops;
  if (!buf) return 0;
  return (int64_t)((int *)buf)[1];
  
}

void plutovg__paint__gradient_hystops_hydestroy(int64_t stops) {
        #include <stdlib.h>
  if (stops) free((void *)(intptr_t)stops);
  
}

void * plutovg__paint__paint_hycreate_hylinear_hygradient(double x1, double y1, double x2, double y2, const char * spread, int64_t stops) {
        #include <stdlib.h>
  #include <string.h>
  #include <plutovg.h>
  char *buf = (char *)(intptr_t)stops;
  int n = buf ? ((int *)buf)[1] : 0;
  const float *fstops = buf ? (const float *)(buf + sizeof(int) * 2) : NULL;
  const char *sk = (const char *)(intptr_t)spread;
  int spread_kind = 0;
  if (sk) {
    if (strcmp(sk, ":reflect") == 0) spread_kind = 1;
    else if (strcmp(sk, ":repeat") == 0) spread_kind = 2;
  }
  plutovg_paint_t *p = plutovg_paint_create_linear_gradient(
      (float)x1, (float)y1, (float)x2, (float)y2,
      (plutovg_spread_method_t)spread_kind,
      (const plutovg_gradient_stop_t *)fstops,
      n,
      /*matrix=*/NULL);
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *res = malloc(sizeof(*res));
  if (!p) { res->is_ok = false; res->ok_val = 0; res->err_val = 0; return res; }
  res->is_ok = true; res->ok_val = (int64_t)(intptr_t)p; res->err_val = 0;
  return res;
  
}

void * plutovg__paint__paint_hycreate_hyradial_hygradient(double cx, double cy, double cr, double fx, double fy, double fr, const char * spread, int64_t stops) {
        #include <stdlib.h>
  #include <string.h>
  #include <plutovg.h>
  char *buf = (char *)(intptr_t)stops;
  int n = buf ? ((int *)buf)[1] : 0;
  const float *fstops = buf ? (const float *)(buf + sizeof(int) * 2) : NULL;
  const char *sk = (const char *)(intptr_t)spread;
  int spread_kind = 0;
  if (sk) {
    if (strcmp(sk, ":reflect") == 0) spread_kind = 1;
    else if (strcmp(sk, ":repeat") == 0) spread_kind = 2;
  }
  plutovg_paint_t *p = plutovg_paint_create_radial_gradient(
      (float)cx, (float)cy, (float)cr,
      (float)fx, (float)fy, (float)fr,
      (plutovg_spread_method_t)spread_kind,
      (const plutovg_gradient_stop_t *)fstops,
      n,
      /*matrix=*/NULL);
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *res = malloc(sizeof(*res));
  if (!p) { res->is_ok = false; res->ok_val = 0; res->err_val = 0; return res; }
  res->is_ok = true; res->ok_val = (int64_t)(intptr_t)p; res->err_val = 0;
  return res;
  
}

void * plutovg__paint__paint_hycreate_hytexture(int64_t surface, const char * tex_type, double opacity) {
        #include <stdlib.h>
  #include <string.h>
  #include <plutovg.h>
  const char *tk = (const char *)(intptr_t)tex_type;
  int tt = 0;
  if (tk && strcmp(tk, ":tiled") == 0) tt = 1;
  plutovg_paint_t *p = plutovg_paint_create_texture(
      (plutovg_surface_t *)(intptr_t)surface,
      (plutovg_texture_type_t)tt,
      (float)opacity,
      /*matrix=*/NULL);
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *res = malloc(sizeof(*res));
  if (!p) { res->is_ok = false; res->ok_val = 0; res->err_val = 0; return res; }
  res->is_ok = true; res->ok_val = (int64_t)(intptr_t)p; res->err_val = 0;
  return res;
  
}

void plutovg__paint__canvas_hyset_hysource(int64_t c, int64_t paint) {
        #include <plutovg.h>
  plutovg_canvas_set_paint((plutovg_canvas_t *)(intptr_t)c,
                           (plutovg_paint_t *)(intptr_t)paint);
  
}


