/* generated by tur (phase 2) */
#include "plutovg__surface.h"

static void * plutovg__surface____ok(int64_t);
static void * plutovg__surface____err(int64_t);
void * plutovg__surface__surface_hycreate(int64_t, int64_t);
void * plutovg__surface__surface_hycreate_hyfrom_hydata(const char *, int64_t, int64_t, int64_t);
void plutovg__surface__surface_hydestroy(int64_t);
int64_t plutovg__surface__surface_hywidth(int64_t);
int64_t plutovg__surface__surface_hyheight(int64_t);
int64_t plutovg__surface__surface_hystride(int64_t);
const char * plutovg__surface__surface_hydata(int64_t);
void * plutovg__surface__surface_hywrite_hypng(int64_t, const char *);
void * plutovg__surface__surface_hywrite_hyjpeg(int64_t, const char *, int64_t);

static void * plutovg__surface____ok(int64_t v) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = true; r->ok_val = v; r->err_val = 0; return r;
  
}

static void * plutovg__surface____err(int64_t e) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = false; r->ok_val = 0; r->err_val = e; return r;
  
}

void * plutovg__surface__surface_hycreate(int64_t width, int64_t height) {
        #include <stdlib.h>
  #include <plutovg.h>
  plutovg_surface_t *s = plutovg_surface_create((int)width, (int)height);
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  if (!s) { r->is_ok = false; r->ok_val = 0; r->err_val = 0; return r; }
  r->is_ok = true; r->ok_val = (int64_t)(intptr_t)s; r->err_val = 0;
  return r;
  
}

void * plutovg__surface__surface_hycreate_hyfrom_hydata(const char * data, int64_t width, int64_t height, int64_t stride) {
        #include <stdlib.h>
  #include <plutovg.h>
  plutovg_surface_t *s = plutovg_surface_create_for_data(
    (unsigned char *)(intptr_t)data, (int)width, (int)height, (int)stride);
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  if (!s) { r->is_ok = false; r->ok_val = 0; r->err_val = 0; return r; }
  r->is_ok = true; r->ok_val = (int64_t)(intptr_t)s; r->err_val = 0;
  return r;
  
}

void plutovg__surface__surface_hydestroy(int64_t s) {
        #include <plutovg.h>
  if (s) plutovg_surface_destroy((plutovg_surface_t *)(intptr_t)s);
  
}

int64_t plutovg__surface__surface_hywidth(int64_t s) {
        #include <plutovg.h>
  return (int64_t)plutovg_surface_get_width((plutovg_surface_t *)(intptr_t)s);
  
}

int64_t plutovg__surface__surface_hyheight(int64_t s) {
        #include <plutovg.h>
  return (int64_t)plutovg_surface_get_height((plutovg_surface_t *)(intptr_t)s);
  
}

int64_t plutovg__surface__surface_hystride(int64_t s) {
        #include <plutovg.h>
  return (int64_t)plutovg_surface_get_stride((plutovg_surface_t *)(intptr_t)s);
  
}

const char * plutovg__surface__surface_hydata(int64_t s) {
        #include <plutovg.h>
  return (char *)plutovg_surface_get_data((plutovg_surface_t *)(intptr_t)s);
  
}

void * plutovg__surface__surface_hywrite_hypng(int64_t s, const char * path) {
        #include <stdlib.h>
  #include <plutovg.h>
  bool ok = plutovg_surface_write_to_png(
      (const plutovg_surface_t *)(intptr_t)s,
      (const char *)(intptr_t)path);
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = ok; r->ok_val = 0; r->err_val = ok ? 0 : 1;
  return r;
  
}

void * plutovg__surface__surface_hywrite_hyjpeg(int64_t s, const char * path, int64_t quality) {
        #include <stdlib.h>
  #include <plutovg.h>
  bool ok = plutovg_surface_write_to_jpg(
      (const plutovg_surface_t *)(intptr_t)s,
      (const char *)(intptr_t)path,
      (int)quality);
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = ok; r->ok_val = 0; r->err_val = ok ? 0 : 1;
  return r;
  
}


