/* generated by tur (phase 2) */
#include "plutovg__font.h"

static void * plutovg__font____ok(int64_t);
static void * plutovg__font____err(int64_t);
void * plutovg__font__font_hyface_hyload_hyfrom_hyfile(const char *, int64_t);
void * plutovg__font__font_hyface_hyload_hyfrom_hydata(const char *, int64_t, int64_t);
void plutovg__font__font_hyface_hydestroy(int64_t);
double plutovg__font__font_hyface_hyascent(int64_t, double);
double plutovg__font__font_hyface_hydescent(int64_t, double);
double plutovg__font__font_hyface_hyline_hygap(int64_t, double);
void * plutovg__font__font_hyface_hytext_hyextents(int64_t, double, const char *);
void * plutovg__font__font_hycache_hycreate();
void plutovg__font__font_hycache_hydestroy(int64_t);
void * plutovg__font__font_hycache_hyadd_hyfile(int64_t, const char *);
void * plutovg__font__font_hycache_hyload_hysystem(int64_t);
void * plutovg__font__font_hycache_hyget(int64_t, const char *, const char *, double);
void plutovg__font__canvas_hyset_hyfont_hyface(int64_t, int64_t);
void plutovg__font__canvas_hyset_hyfont_hysize(int64_t, double);
void plutovg__font__canvas_hyset_hyfont(int64_t, int64_t, double);
void plutovg__font__canvas_hyfill_hytext(int64_t, const char *, const char *, double, double);
void plutovg__font__canvas_hystroke_hytext(int64_t, const char *, const char *, double, double);
void * plutovg__font__canvas_hytext_hyextents(int64_t, const char *, const char *);

static void * plutovg__font____ok(int64_t v) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = true; r->ok_val = v; r->err_val = 0; return r;
  
}

static void * plutovg__font____err(int64_t e) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = false; r->ok_val = 0; r->err_val = e; return r;
  
}

void * plutovg__font__font_hyface_hyload_hyfrom_hyfile(const char * path, int64_t index) {
        #include <stdlib.h>
  #include <plutovg.h>
  plutovg_font_face_t *ff = plutovg_font_face_load_from_file(
      (const char *)(intptr_t)path, (int)index);
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  if (!ff) { r->is_ok = false; r->ok_val = 0; r->err_val = 0; return r; }
  r->is_ok = true; r->ok_val = (int64_t)(intptr_t)ff; r->err_val = 0;
  return r;
  
}

void * plutovg__font__font_hyface_hyload_hyfrom_hydata(const char * data, int64_t len, int64_t index) {
        #include <stdlib.h>
  #include <plutovg.h>
  plutovg_font_face_t *ff = plutovg_font_face_load_from_data(
      (const void *)(intptr_t)data, (unsigned int)(int)len,
      (int)index, NULL, NULL);
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  if (!ff) { r->is_ok = false; r->ok_val = 0; r->err_val = 0; return r; }
  r->is_ok = true; r->ok_val = (int64_t)(intptr_t)ff; r->err_val = 0;
  return r;
  
}

void plutovg__font__font_hyface_hydestroy(int64_t ff) {
        #include <plutovg.h>
  if (ff) plutovg_font_face_destroy((plutovg_font_face_t *)(intptr_t)ff);
  
}

double plutovg__font__font_hyface_hyascent(int64_t ff, double size) {
        #include <plutovg.h>
  float ascent = 0.0f, descent = 0.0f, line_gap = 0.0f;
  plutovg_font_face_get_metrics((const plutovg_font_face_t *)(intptr_t)ff,
                                (float)size,
                                &ascent, &descent, &line_gap,
                                /*extents=*/NULL);
  return (double)ascent;
  
}

double plutovg__font__font_hyface_hydescent(int64_t ff, double size) {
        #include <plutovg.h>
  float ascent = 0.0f, descent = 0.0f, line_gap = 0.0f;
  plutovg_font_face_get_metrics((const plutovg_font_face_t *)(intptr_t)ff,
                                (float)size,
                                &ascent, &descent, &line_gap,
                                /*extents=*/NULL);
  return (double)descent;
  
}

double plutovg__font__font_hyface_hyline_hygap(int64_t ff, double size) {
        #include <plutovg.h>
  float ascent = 0.0f, descent = 0.0f, line_gap = 0.0f;
  plutovg_font_face_get_metrics((const plutovg_font_face_t *)(intptr_t)ff,
                                (float)size,
                                &ascent, &descent, &line_gap,
                                /*extents=*/NULL);
  return (double)line_gap;
  
}

void * plutovg__font__font_hyface_hytext_hyextents(int64_t ff, double size, const char * text) {
        #include <stdlib.h>
  #include <string.h>
  #include <plutovg.h>
  plutovg_rect_t ext = {0};
  const char *s = (const char *)(intptr_t)text;
  int len = s ? (int)strlen(s) : 0;
  plutovg_font_face_text_extents((plutovg_font_face_t *)(intptr_t)ff,
                                 (float)size, s, len,
                                 PLUTOVG_TEXT_ENCODING_UTF8, &ext);
  float *out = malloc(sizeof(float) * 4);
  out[0] = ext.x; out[1] = ext.y; out[2] = ext.w; out[3] = ext.h;
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = true; r->ok_val = (int64_t)(intptr_t)out; r->err_val = 0;
  return r;
  
}

void * plutovg__font__font_hycache_hycreate() {
        #include <stdlib.h>
  #include <plutovg.h>
  plutovg_font_face_cache_t *fc = plutovg_font_face_cache_create();
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  if (!fc) { r->is_ok = false; r->ok_val = 0; r->err_val = 0; return r; }
  r->is_ok = true; r->ok_val = (int64_t)(intptr_t)fc; r->err_val = 0;
  return r;
  
}

void plutovg__font__font_hycache_hydestroy(int64_t fc) {
        #include <plutovg.h>
  if (fc) plutovg_font_face_cache_destroy((plutovg_font_face_cache_t *)(intptr_t)fc);
  
}

void * plutovg__font__font_hycache_hyadd_hyfile(int64_t fc, const char * path) {
        #include <stdlib.h>
  #include <plutovg.h>
  int n = plutovg_font_face_cache_load_file(
      (plutovg_font_face_cache_t *)(intptr_t)fc,
      (const char *)(intptr_t)path);
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  if (n <= 0) { r->is_ok = false; r->ok_val = 0; r->err_val = 0; return r; }
  r->is_ok = true; r->ok_val = (int64_t)n; r->err_val = 0;
  return r;
  
}

void * plutovg__font__font_hycache_hyload_hysystem(int64_t fc) {
        #include <stdlib.h>
  #include <plutovg.h>
  int n = plutovg_font_face_cache_load_sys((plutovg_font_face_cache_t *)(intptr_t)fc);
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  if (n <= 0) { r->is_ok = false; r->ok_val = 0; r->err_val = 0; return r; }
  r->is_ok = true; r->ok_val = (int64_t)n; r->err_val = 0;
  return r;
  
}

void * plutovg__font__font_hycache_hyget(int64_t fc, const char * family, const char * style, double size) {
        #include <stdlib.h>
  #include <string.h>
  #include <plutovg.h>
  const char *k = (const char *)(intptr_t)style;
  bool bold = false, italic = false;
  if (k) {
    if (strcmp(k, ":bold") == 0)        { bold = true; }
    else if (strcmp(k, ":italic") == 0) { italic = true; }
    else if (strcmp(k, ":bold-italic") == 0) { bold = true; italic = true; }
    /* default ":regular" -> bold=false italic=false */
  }
  plutovg_font_face_t *ff = plutovg_font_face_cache_get(
      (plutovg_font_face_cache_t *)(intptr_t)fc,
      (const char *)(intptr_t)family, bold, italic);
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  if (!ff) { r->is_ok = false; r->ok_val = 0; r->err_val = 0; return r; }
  r->is_ok = true; r->ok_val = (int64_t)(intptr_t)ff; r->err_val = 0;
  (void)size;
  return r;
  
}

void plutovg__font__canvas_hyset_hyfont_hyface(int64_t c, int64_t ff) {
        #include <plutovg.h>
  plutovg_canvas_set_font_face((plutovg_canvas_t *)(intptr_t)c,
                               (plutovg_font_face_t *)(intptr_t)ff);
  
}

void plutovg__font__canvas_hyset_hyfont_hysize(int64_t c, double size) {
        #include <plutovg.h>
  plutovg_canvas_set_font_size((plutovg_canvas_t *)(intptr_t)c, (float)size);
  
}

void plutovg__font__canvas_hyset_hyfont(int64_t c, int64_t ff, double size) {
        #include <plutovg.h>
  plutovg_canvas_set_font((plutovg_canvas_t *)(intptr_t)c,
                          (plutovg_font_face_t *)(intptr_t)ff,
                          (float)size);
  
}

void plutovg__font__canvas_hyfill_hytext(int64_t c, const char * text, const char * encoding, double x, double y) {
        #include <string.h>
  #include <plutovg.h>
  const char *s = (const char *)(intptr_t)text;
  int len = s ? (int)strlen(s) : 0;
  const char *k = (const char *)(intptr_t)encoding;
  plutovg_text_encoding_t enc = PLUTOVG_TEXT_ENCODING_UTF8;
  if (k) {
    if      (strcmp(k, ":latin1") == 0) enc = PLUTOVG_TEXT_ENCODING_LATIN1;
    else if (strcmp(k, ":utf16")  == 0) enc = PLUTOVG_TEXT_ENCODING_UTF16;
    else if (strcmp(k, ":utf32")  == 0) enc = PLUTOVG_TEXT_ENCODING_UTF32;
  }
  plutovg_canvas_fill_text((plutovg_canvas_t *)(intptr_t)c,
                           s, len, enc, (float)x, (float)y);
  
}

void plutovg__font__canvas_hystroke_hytext(int64_t c, const char * text, const char * encoding, double x, double y) {
        #include <string.h>
  #include <plutovg.h>
  const char *s = (const char *)(intptr_t)text;
  int len = s ? (int)strlen(s) : 0;
  const char *k = (const char *)(intptr_t)encoding;
  plutovg_text_encoding_t enc = PLUTOVG_TEXT_ENCODING_UTF8;
  if (k) {
    if      (strcmp(k, ":latin1") == 0) enc = PLUTOVG_TEXT_ENCODING_LATIN1;
    else if (strcmp(k, ":utf16")  == 0) enc = PLUTOVG_TEXT_ENCODING_UTF16;
    else if (strcmp(k, ":utf32")  == 0) enc = PLUTOVG_TEXT_ENCODING_UTF32;
  }
  plutovg_canvas_stroke_text((plutovg_canvas_t *)(intptr_t)c,
                             s, len, enc, (float)x, (float)y);
  
}

void * plutovg__font__canvas_hytext_hyextents(int64_t c, const char * text, const char * encoding) {
        #include <stdlib.h>
  #include <string.h>
  #include <plutovg.h>
  const char *s = (const char *)(intptr_t)text;
  int len = s ? (int)strlen(s) : 0;
  const char *k = (const char *)(intptr_t)encoding;
  plutovg_text_encoding_t enc = PLUTOVG_TEXT_ENCODING_UTF8;
  if (k) {
    if      (strcmp(k, ":latin1") == 0) enc = PLUTOVG_TEXT_ENCODING_LATIN1;
    else if (strcmp(k, ":utf16")  == 0) enc = PLUTOVG_TEXT_ENCODING_UTF16;
    else if (strcmp(k, ":utf32")  == 0) enc = PLUTOVG_TEXT_ENCODING_UTF32;
  }
  plutovg_rect_t ext = {0};
  plutovg_canvas_text_extents((plutovg_canvas_t *)(intptr_t)c,
                              s, len, enc, &ext);
  float *out = malloc(sizeof(float) * 4);
  out[0] = ext.x; out[1] = ext.y; out[2] = ext.w; out[3] = ext.h;
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = true; r->ok_val = (int64_t)(intptr_t)out; r->err_val = 0;
  return r;
  
}


