/* generated by tur (phase 2) */
#include "png__reader.h"

static void * png__reader____ok(int64_t);
static void * png__reader____err(int64_t);
void * png__reader__png_hyread(const char *);
void png__reader__img_hyfree(int64_t);

static void * png__reader____ok(int64_t v) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = true; r->ok_val = v; r->err_val = 0; return r;
  
}

static void * png__reader____err(int64_t e) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = false; r->ok_val = 0; r->err_val = e; return r;
  
}

void * png__reader__png_hyread(const char * path) {
        #include <stdlib.h>
  #include <string.h>
  #include <setjmp.h>
  #include <png.h>
  #include <stdio.h>
  struct __img {
    unsigned int width;
    unsigned int height;
    int channels;
    int bit_depth;
    unsigned char *pixels;
  };
  FILE *fp = fopen((const char *)path, "rb");
  if (!fp) {
    struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
    r->is_ok = false; r->ok_val = 0; r->err_val = 0; return r;
  }
  png_structp png = png_create_read_struct(PNG_LIBPNG_VER_STRING, NULL, NULL, NULL);
  if (!png) {
    fclose(fp);
    struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
    r->is_ok = false; r->ok_val = 0; r->err_val = 0; return r;
  }
  png_infop info = png_create_info_struct(png);
  if (!info) {
    png_destroy_read_struct(&png, NULL, NULL);
    fclose(fp);
    struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
    r->is_ok = false; r->ok_val = 0; r->err_val = 0; return r;
  }
  if (setjmp(png_jmpbuf(png))) {
    png_destroy_read_struct(&png, &info, NULL);
    fclose(fp);
    struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
    r->is_ok = false; r->ok_val = 0; r->err_val = 0; return r;
  }
  png_init_io(png, fp);
  png_read_info(png, info);
  unsigned int width     = png_get_image_width(png, info);
  unsigned int height    = png_get_image_height(png, info);
  int color_type = png_get_color_type(png, info);
  int bit_depth  = png_get_bit_depth(png, info);
  if (bit_depth == 16)
    png_set_strip_16(png);
  if (color_type == PNG_COLOR_TYPE_PALETTE)
    png_set_expand(png);
  if (color_type == PNG_COLOR_TYPE_GRAY && bit_depth < 8)
    png_set_expand_gray_1_2_4_to_8(png);
  if (png_get_valid(png, info, PNG_INFO_tRNS))
    png_set_tRNS_to_alpha(png);
  if (color_type == PNG_COLOR_TYPE_GRAY ||
      color_type == PNG_COLOR_TYPE_GRAY_ALPHA)
    png_set_gray_to_rgb(png);
  if (color_type == PNG_COLOR_TYPE_RGB ||
      color_type == PNG_COLOR_TYPE_GRAY ||
      color_type == PNG_COLOR_TYPE_PALETTE)
    png_set_add_alpha(png, 0xFF, PNG_FILLER_AFTER);
  png_read_update_info(png, info);
  size_t row_bytes = png_get_rowbytes(png, info);
  unsigned char *pixels = malloc(row_bytes * height);
  unsigned char **row_ptrs = malloc(sizeof(unsigned char *) * height);
  for (unsigned int y = 0; y < height; y++)
    row_ptrs[y] = pixels + y * row_bytes;
  png_read_image(png, row_ptrs);
  free(row_ptrs);
  png_destroy_read_struct(&png, &info, NULL);
  fclose(fp);
  struct __img *img = malloc(sizeof(struct __img));
  img->width     = width;
  img->height    = height;
  img->channels  = 4;
  img->bit_depth = 8;
  img->pixels    = pixels;
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = true; r->ok_val = (int64_t)(intptr_t)img; r->err_val = 0; return r;
  
}

void png__reader__img_hyfree(int64_t img) {
        #include <stdlib.h>
  struct __img {
    unsigned int width;
    unsigned int height;
    int channels;
    int bit_depth;
    unsigned char *pixels;
  };
  struct __img *i = (struct __img *)(intptr_t)img;
  if (i) { free(i->pixels); free(i); }
  
}


