/* generated by tur (phase 2) */
#include "png__info.h"

int64_t png__info__img_hywidth(int64_t);
int64_t png__info__img_hyheight(int64_t);
int64_t png__info__img_hychannels(int64_t);
int64_t png__info__img_hybit_hydepth(int64_t);
const char * png__info__img_hypixels(int64_t);
int64_t png__info__pixel_hyr(int64_t, int64_t, int64_t);
int64_t png__info__pixel_hyg(int64_t, int64_t, int64_t);
int64_t png__info__pixel_hyb(int64_t, int64_t, int64_t);
int64_t png__info__pixel_hya(int64_t, int64_t, int64_t);
void png__info__pixel_hyset_ex(int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t);

int64_t png__info__img_hywidth(int64_t img) {
        struct __img { unsigned int width; unsigned int height; int channels; int bit_depth; unsigned char *pixels; };
  return (int64_t)((struct __img *)(intptr_t)img)->width;
  
}

int64_t png__info__img_hyheight(int64_t img) {
        struct __img { unsigned int width; unsigned int height; int channels; int bit_depth; unsigned char *pixels; };
  return (int64_t)((struct __img *)(intptr_t)img)->height;
  
}

int64_t png__info__img_hychannels(int64_t img) {
        struct __img { unsigned int width; unsigned int height; int channels; int bit_depth; unsigned char *pixels; };
  return (int64_t)((struct __img *)(intptr_t)img)->channels;
  
}

int64_t png__info__img_hybit_hydepth(int64_t img) {
        struct __img { unsigned int width; unsigned int height; int channels; int bit_depth; unsigned char *pixels; };
  return (int64_t)((struct __img *)(intptr_t)img)->bit_depth;
  
}

const char * png__info__img_hypixels(int64_t img) {
        struct __img { unsigned int width; unsigned int height; int channels; int bit_depth; unsigned char *pixels; };
  return (char *)((struct __img *)(intptr_t)img)->pixels;
  
}

int64_t png__info__pixel_hyr(int64_t img, int64_t x, int64_t y) {
        struct __img { unsigned int width; unsigned int height; int channels; int bit_depth; unsigned char *pixels; };
  struct __img *i = (struct __img *)(intptr_t)img;
  return (int64_t)i->pixels[((int)y * (int)i->width + (int)x) * i->channels + 0];
  
}

int64_t png__info__pixel_hyg(int64_t img, int64_t x, int64_t y) {
        struct __img { unsigned int width; unsigned int height; int channels; int bit_depth; unsigned char *pixels; };
  struct __img *i = (struct __img *)(intptr_t)img;
  return (int64_t)i->pixels[((int)y * (int)i->width + (int)x) * i->channels + 1];
  
}

int64_t png__info__pixel_hyb(int64_t img, int64_t x, int64_t y) {
        struct __img { unsigned int width; unsigned int height; int channels; int bit_depth; unsigned char *pixels; };
  struct __img *i = (struct __img *)(intptr_t)img;
  return (int64_t)i->pixels[((int)y * (int)i->width + (int)x) * i->channels + 2];
  
}

int64_t png__info__pixel_hya(int64_t img, int64_t x, int64_t y) {
        struct __img { unsigned int width; unsigned int height; int channels; int bit_depth; unsigned char *pixels; };
  struct __img *i = (struct __img *)(intptr_t)img;
  if (i->channels < 4) return 255;
  return (int64_t)i->pixels[((int)y * (int)i->width + (int)x) * i->channels + 3];
  
}

void png__info__pixel_hyset_ex(int64_t img, int64_t x, int64_t y, int64_t r, int64_t g, int64_t b, int64_t a) {
        struct __img { unsigned int width; unsigned int height; int channels; int bit_depth; unsigned char *pixels; };
  struct __img *i = (struct __img *)(intptr_t)img;
  int off = ((int)y * (int)i->width + (int)x) * i->channels;
  i->pixels[off + 0] = (unsigned char)r;
  i->pixels[off + 1] = (unsigned char)g;
  i->pixels[off + 2] = (unsigned char)b;
  if (i->channels >= 4) i->pixels[off + 3] = (unsigned char)a;
  
}


