/* generated by tur (phase 2) */
#include "png__writer.h"

static void * png__writer____ok(int64_t);
static void * png__writer____err(int64_t);
void * png__writer__png_hywrite(const char *, int64_t);
void * png__writer__png_hywrite_hyraw(const char *, const char *, int64_t, int64_t, int64_t, int64_t);

static void * png__writer____ok(int64_t v) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = true; r->ok_val = v; r->err_val = 0; return r;
  
}

static void * png__writer____err(int64_t e) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = false; r->ok_val = 0; r->err_val = e; return r;
  
}

void * png__writer__png_hywrite(const char * path, int64_t img) {
        #include <stdlib.h>
  #include <string.h>
  #include <setjmp.h>
  #include <png.h>
  #include <stdio.h>
  struct __img {
    unsigned int width;
    unsigned int height;
    int channels;
    int bit_depth;
    unsigned char *pixels;
  };
  struct __img *i = (struct __img *)(intptr_t)img;
  FILE *fp = fopen((const char *)path, "wb");
  if (!fp) {
    struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
    r->is_ok = false; r->ok_val = 0; r->err_val = 0; return r;
  }
  png_structp png = png_create_write_struct(PNG_LIBPNG_VER_STRING, NULL, NULL, NULL);
  if (!png) {
    fclose(fp);
    struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
    r->is_ok = false; r->ok_val = 0; r->err_val = 0; return r;
  }
  png_infop info = png_create_info_struct(png);
  if (!info) {
    png_destroy_write_struct(&png, NULL);
    fclose(fp);
    struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
    r->is_ok = false; r->ok_val = 0; r->err_val = 0; return r;
  }
  if (setjmp(png_jmpbuf(png))) {
    png_destroy_write_struct(&png, &info);
    fclose(fp);
    struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
    r->is_ok = false; r->ok_val = 0; r->err_val = 0; return r;
  }
  png_init_io(png, fp);
  int color_type = PNG_COLOR_TYPE_RGBA;
  if      (i->channels == 1) color_type = PNG_COLOR_TYPE_GRAY;
  else if (i->channels == 2) color_type = PNG_COLOR_TYPE_GRAY_ALPHA;
  else if (i->channels == 3) color_type = PNG_COLOR_TYPE_RGB;
  else                       color_type = PNG_COLOR_TYPE_RGBA;
  png_set_IHDR(png, info, i->width, i->height, i->bit_depth, color_type,
               PNG_INTERLACE_NONE, PNG_COMPRESSION_TYPE_DEFAULT,
               PNG_FILTER_TYPE_DEFAULT);
  png_write_info(png, info);
  size_t row_bytes = (size_t)i->width * (size_t)i->channels;
  for (unsigned int y = 0; y < i->height; y++)
    png_write_row(png, i->pixels + y * row_bytes);
  png_write_end(png, NULL);
  png_destroy_write_struct(&png, &info);
  fclose(fp);
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = true; r->ok_val = 0; r->err_val = 0; return r;
  
}

void * png__writer__png_hywrite_hyraw(const char * path, const char * pixels, int64_t width, int64_t height, int64_t channels, int64_t bit_depth) {
        #include <stdlib.h>
  #include <string.h>
  #include <setjmp.h>
  #include <png.h>
  #include <stdio.h>
  FILE *fp = fopen((const char *)path, "wb");
  if (!fp) {
    struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
    r->is_ok = false; r->ok_val = 0; r->err_val = 0; return r;
  }
  png_structp png = png_create_write_struct(PNG_LIBPNG_VER_STRING, NULL, NULL, NULL);
  if (!png) {
    fclose(fp);
    struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
    r->is_ok = false; r->ok_val = 0; r->err_val = 0; return r;
  }
  png_infop info = png_create_info_struct(png);
  if (!info) {
    png_destroy_write_struct(&png, NULL);
    fclose(fp);
    struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
    r->is_ok = false; r->ok_val = 0; r->err_val = 0; return r;
  }
  if (setjmp(png_jmpbuf(png))) {
    png_destroy_write_struct(&png, &info);
    fclose(fp);
    struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
    r->is_ok = false; r->ok_val = 0; r->err_val = 0; return r;
  }
  png_init_io(png, fp);
  int color_type = PNG_COLOR_TYPE_RGBA;
  if      ((int)channels == 1) color_type = PNG_COLOR_TYPE_GRAY;
  else if ((int)channels == 2) color_type = PNG_COLOR_TYPE_GRAY_ALPHA;
  else if ((int)channels == 3) color_type = PNG_COLOR_TYPE_RGB;
  else                         color_type = PNG_COLOR_TYPE_RGBA;
  png_set_IHDR(png, info, (unsigned int)width, (unsigned int)height,
               (int)bit_depth, color_type,
               PNG_INTERLACE_NONE, PNG_COMPRESSION_TYPE_DEFAULT,
               PNG_FILTER_TYPE_DEFAULT);
  png_write_info(png, info);
  unsigned char *px = (unsigned char *)(intptr_t)pixels;
  size_t row_bytes = (size_t)width * (size_t)channels;
  for (int y = 0; y < (int)height; y++)
    png_write_row(png, px + (size_t)y * row_bytes);
  png_write_end(png, NULL);
  png_destroy_write_struct(&png, &info);
  fclose(fp);
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = true; r->ok_val = 0; r->err_val = 0; return r;
  
}


