/* generated by tur (phase 2) */
#ifndef TUR_png__reader_H
#define TUR_png__reader_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void * png__reader__png_hyread(const char *);
void png__reader__img_hyfree(int64_t);
#endif /* TUR_png__reader_H */
