/* generated by tur (phase 2) */
#ifndef TUR_png__writer_H
#define TUR_png__writer_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void * png__writer__png_hywrite(const char *, int64_t);
void * png__writer__png_hywrite_hyraw(const char *, const char *, int64_t, int64_t, int64_t, int64_t);
#endif /* TUR_png__writer_H */
