/* generated by tur (phase 2) */
#ifndef TUR_postgres__db_H
#define TUR_postgres__db_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void * postgres__db__db_hyconnect(const char *);
void * postgres__db__db_hyclose(int64_t);
void * postgres__db__db_hyexec(int64_t, const char *);
void * postgres__db__db_hyquery(int64_t, const char *);
void * postgres__db__db_hyquery_hyparams(int64_t, const char *, int64_t);
void * postgres__db__db_hybegin(int64_t);
void * postgres__db__db_hycommit(int64_t);
void * postgres__db__db_hyrollback(int64_t);
#endif /* TUR_postgres__db_H */
