/* generated by tur (phase 2) */
#include "postgres__stmt.h"

static void * postgres__stmt____ok(int64_t);
static void * postgres__stmt____err(int64_t);
static int64_t postgres__stmt___un_unparams_hycount(int64_t);
static int64_t postgres__stmt___un_unparams_hyvalues(int64_t, int64_t);
static const char * postgres__stmt___un_undealloc_hysql(const char *);
static int64_t postgres__stmt___un_unpq_hyprepare_hyraw(int64_t, const char *, const char *, int64_t);
static int64_t postgres__stmt___un_unpq_hyexec_hyprepared_hyraw(int64_t, const char *, int64_t, int64_t);
static int64_t postgres__stmt___un_unpq_hyexec_hyraw(int64_t, const char *);
void * postgres__stmt__stmt_hyprepare(int64_t, const char *, const char *, int64_t);
void * postgres__stmt__stmt_hyexec_hyprepared(int64_t, const char *, int64_t);
void * postgres__stmt__stmt_hydeallocate(int64_t, const char *);

static void * postgres__stmt____ok(int64_t v) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = true; r->ok_val = v; r->err_val = 0; return r;
  
}

static void * postgres__stmt____err(int64_t e) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = false; r->ok_val = 0; r->err_val = e; return r;
  
}

static int64_t postgres__stmt___un_unparams_hycount(int64_t params) {
        struct { int64_t value; int64_t next; } *cell =
      (struct { int64_t value; int64_t next; } *)(intptr_t)params;
  int64_t n = 0;
  while (cell) { n++; cell = (struct { int64_t value; int64_t next; } *)(intptr_t)cell->next; }
  return n;
  
}

static int64_t postgres__stmt___un_unparams_hyvalues(int64_t params, int64_t n) {
        #include <stdlib.h>
  struct __stcons { int64_t value; int64_t next; };
  const char **arr = (const char **)malloc((size_t)n * sizeof(const char *));
  struct __stcons *cell = (struct __stcons *)(intptr_t)params;
  for (int64_t i = 0; i < n && cell; i++) {
    arr[i] = (const char *)(intptr_t)cell->value;
    cell = (struct __stcons *)(intptr_t)cell->next;
  }
  return (int64_t)(intptr_t)arr;
  
}

static const char * postgres__stmt___un_undealloc_hysql(const char * name) {
        #include <stdlib.h>
  #include <string.h>
  #include <stdio.h>
  const char *prefix = "DEALLOCATE ";
  size_t plen = strlen(prefix);
  size_t nlen = strlen((const char *)name);
  char *buf = (char *)malloc(plen + nlen + 1);
  memcpy(buf, prefix, plen);
  memcpy(buf + plen, (const char *)name, nlen);
  buf[plen + nlen] = '\0';
  return buf;
  
}

static int64_t postgres__stmt___un_unpq_hyprepare_hyraw(int64_t conn, const char * name, const char * sql, int64_t nparams) {
        #include <libpq-fe.h>
  PGresult *res = PQprepare((PGconn *)(intptr_t)conn,
                            (const char *)name,
                            (const char *)sql,
                            (int)nparams,
                            NULL);
  if (!res) return 0;
  int ok = (PQresultStatus(res) == PGRES_COMMAND_OK) ? 1 : 0;
  PQclear(res);
  return ok;
  
}

static int64_t postgres__stmt___un_unpq_hyexec_hyprepared_hyraw(int64_t conn, const char * name, int64_t paramValues, int64_t nparams) {
        #include <libpq-fe.h>
  const char **vals = (const char **)(intptr_t)paramValues;
  PGresult *res = PQexecPrepared((PGconn *)(intptr_t)conn,
                                 (const char *)name,
                                 (int)nparams,
                                 vals, NULL, NULL, 0);
  if (!res) return 0;
  ExecStatusType st = PQresultStatus(res);
  if (st != PGRES_TUPLES_OK && st != PGRES_COMMAND_OK) { PQclear(res); return 0; }
  return (int64_t)(intptr_t)res;
  
}

static int64_t postgres__stmt___un_unpq_hyexec_hyraw(int64_t conn, const char * sql) {
        #include <libpq-fe.h>
  PGresult *res = PQexec((PGconn *)(intptr_t)conn, (const char *)sql);
  if (!res) return 0;
  ExecStatusType st = PQresultStatus(res);
  PQclear(res);
  return (st == PGRES_COMMAND_OK || st == PGRES_TUPLES_OK) ? 1 : 0;
  
}

void * postgres__stmt__stmt_hyprepare(int64_t conn, const char * name, const char * sql, int64_t nparams) {
        void * __t0;
        {
            int64_t rc_32 = postgres__stmt___un_unpq_hyprepare_hyraw(conn, name, sql, nparams);
            (void)rc_32;
            void * __t1;
            if ((rc_32) != (INT64_C(0))) {
                __t1 = postgres__stmt____ok(INT64_C(0));
            } else {
                __t1 = postgres__stmt____err(INT64_C(0));
            }
            __t0 = __t1;
        }
        return __t0;
}

void * postgres__stmt__stmt_hyexec_hyprepared(int64_t conn, const char * name, int64_t params) {
        void * __t2;
        {
            int64_t n_36 = postgres__stmt___un_unparams_hycount(params);
            (void)n_36;
            int64_t vals_37 = postgres__stmt___un_unparams_hyvalues(params, n_36);
            (void)vals_37;
            int64_t raw_38 = postgres__stmt___un_unpq_hyexec_hyprepared_hyraw(conn, name, vals_37, n_36);
            (void)raw_38;
            void * __t3;
            if ((raw_38) != (INT64_C(0))) {
                __t3 = postgres__stmt____ok(raw_38);
            } else {
                __t3 = postgres__stmt____err(INT64_C(0));
            }
            __t2 = __t3;
        }
        return __t2;
}

void * postgres__stmt__stmt_hydeallocate(int64_t conn, const char * name) {
        void * __t4;
        {
            const char * sql_41 = postgres__stmt___un_undealloc_hysql(name);
            (void)sql_41;
            int64_t rc_42 = postgres__stmt___un_unpq_hyexec_hyraw(conn, sql_41);
            (void)rc_42;
            void * __t5;
            if ((rc_42) != (INT64_C(0))) {
                __t5 = postgres__stmt____ok(INT64_C(0));
            } else {
                __t5 = postgres__stmt____err(INT64_C(0));
            }
            __t4 = __t5;
        }
        return __t4;
}


