/* generated by tur (phase 2) */
#ifndef TUR_postgres__row_H
#define TUR_postgres__row_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int64_t postgres__row__rows_hycount(int64_t);
void postgres__row__rows_hyfree(int64_t);
const char * postgres__row__row_hyget(int64_t, int64_t, const char *);
int64_t postgres__row__row_hyget_hyint(int64_t, int64_t, const char *);
int64_t postgres__row__col_hycount(int64_t);
const char * postgres__row__col_hyname(int64_t, int64_t);
#endif /* TUR_postgres__row_H */
