/* generated by tur (phase 2) */
#include "postgres__row.h"

int64_t postgres__row__rows_hycount(int64_t);
void postgres__row__rows_hyfree(int64_t);
const char * postgres__row__row_hyget(int64_t, int64_t, const char *);
int64_t postgres__row__row_hyget_hyint(int64_t, int64_t, const char *);
int64_t postgres__row__col_hycount(int64_t);
const char * postgres__row__col_hyname(int64_t, int64_t);

int64_t postgres__row__rows_hycount(int64_t rows) {
        #include <libpq-fe.h>
  return (int64_t)PQntuples((PGresult *)(intptr_t)rows);
  
}

void postgres__row__rows_hyfree(int64_t rows) {
        #include <libpq-fe.h>
  PQclear((PGresult *)(intptr_t)rows);
  
}

const char * postgres__row__row_hyget(int64_t rows, int64_t i, const char * colname) {
        #include <libpq-fe.h>
  PGresult *res = (PGresult *)(intptr_t)rows;
  int col = PQfnumber(res, (const char *)colname);
  if (col < 0) return (char *)"";
  if (PQgetisnull(res, (int)i, col)) return (char *)"";
  const char *v = PQgetvalue(res, (int)i, col);
  return v ? (char *)v : (char *)"";
  
}

int64_t postgres__row__row_hyget_hyint(int64_t rows, int64_t i, const char * colname) {
        #include <libpq-fe.h>
  #include <stdlib.h>
  PGresult *res = (PGresult *)(intptr_t)rows;
  int col = PQfnumber(res, (const char *)colname);
  if (col < 0) return 0;
  if (PQgetisnull(res, (int)i, col)) return 0;
  const char *v = PQgetvalue(res, (int)i, col);
  return v ? (int64_t)atoll(v) : 0;
  
}

int64_t postgres__row__col_hycount(int64_t rows) {
        #include <libpq-fe.h>
  return (int64_t)PQnfields((PGresult *)(intptr_t)rows);
  
}

const char * postgres__row__col_hyname(int64_t rows, int64_t j) {
        #include <libpq-fe.h>
  const char *n = PQfname((PGresult *)(intptr_t)rows, (int)j);
  return n ? (char *)n : (char *)"";
  
}


