/* generated by tur (phase 2) */
#include "postgres__notify.h"

static void * postgres__notify____ok(int64_t);
static void * postgres__notify____err(int64_t);
static const char * postgres__notify___un_unlisten_hysql(const char *);
static const char * postgres__notify___un_ununlisten_hysql(const char *);
static int64_t postgres__notify___un_unpq_hyexec_hyraw(int64_t, const char *);
static int64_t postgres__notify___un_unpq_hyconsume_hyinput(int64_t);
static int64_t postgres__notify___un_unpq_hynotifies(int64_t);
void * postgres__notify__notify_hylisten(int64_t, const char *);
void * postgres__notify__notify_hyunlisten(int64_t, const char *);
void * postgres__notify__notify_hypoll(int64_t);
const char * postgres__notify__notification_hychannel(int64_t);
const char * postgres__notify__notification_hypayload(int64_t);

static void * postgres__notify____ok(int64_t v) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = true; r->ok_val = v; r->err_val = 0; return r;
  
}

static void * postgres__notify____err(int64_t e) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = false; r->ok_val = 0; r->err_val = e; return r;
  
}

static const char * postgres__notify___un_unlisten_hysql(const char * channel) {
        #include <stdlib.h>
  #include <string.h>
  const char *prefix = "LISTEN ";
  size_t plen = strlen(prefix);
  size_t clen = strlen((const char *)channel);
  char *buf = (char *)malloc(plen + clen + 1);
  memcpy(buf, prefix, plen);
  memcpy(buf + plen, (const char *)channel, clen);
  buf[plen + clen] = '\0';
  return buf;
  
}

static const char * postgres__notify___un_ununlisten_hysql(const char * channel) {
        #include <stdlib.h>
  #include <string.h>
  const char *prefix = "UNLISTEN ";
  size_t plen = strlen(prefix);
  size_t clen = strlen((const char *)channel);
  char *buf = (char *)malloc(plen + clen + 1);
  memcpy(buf, prefix, plen);
  memcpy(buf + plen, (const char *)channel, clen);
  buf[plen + clen] = '\0';
  return buf;
  
}

static int64_t postgres__notify___un_unpq_hyexec_hyraw(int64_t conn, const char * sql) {
        #include <libpq-fe.h>
  PGresult *res = PQexec((PGconn *)(intptr_t)conn, (const char *)sql);
  if (!res) return 0;
  ExecStatusType st = PQresultStatus(res);
  PQclear(res);
  return (st == PGRES_COMMAND_OK || st == PGRES_TUPLES_OK) ? 1 : 0;
  
}

static int64_t postgres__notify___un_unpq_hyconsume_hyinput(int64_t conn) {
        #include <libpq-fe.h>
  return (int64_t)PQconsumeInput((PGconn *)(intptr_t)conn);
  
}

static int64_t postgres__notify___un_unpq_hynotifies(int64_t conn) {
        #include <libpq-fe.h>
  PGnotify *n = PQnotifies((PGconn *)(intptr_t)conn);
  return (int64_t)(intptr_t)n;
  
}

void * postgres__notify__notify_hylisten(int64_t conn, const char * channel) {
        void * __t0;
        {
            const char * sql_23 = postgres__notify___un_unlisten_hysql(channel);
            (void)sql_23;
            int64_t rc_24 = postgres__notify___un_unpq_hyexec_hyraw(conn, sql_23);
            (void)rc_24;
            void * __t1;
            if ((rc_24) != (INT64_C(0))) {
                __t1 = postgres__notify____ok(INT64_C(0));
            } else {
                __t1 = postgres__notify____err(INT64_C(0));
            }
            __t0 = __t1;
        }
        return __t0;
}

void * postgres__notify__notify_hyunlisten(int64_t conn, const char * channel) {
        void * __t2;
        {
            const char * sql_27 = postgres__notify___un_ununlisten_hysql(channel);
            (void)sql_27;
            int64_t rc_28 = postgres__notify___un_unpq_hyexec_hyraw(conn, sql_27);
            (void)rc_28;
            void * __t3;
            if ((rc_28) != (INT64_C(0))) {
                __t3 = postgres__notify____ok(INT64_C(0));
            } else {
                __t3 = postgres__notify____err(INT64_C(0));
            }
            __t2 = __t3;
        }
        return __t2;
}

void * postgres__notify__notify_hypoll(int64_t conn) {
        void * __t4;
        {
            int64_t ci_30 = postgres__notify___un_unpq_hyconsume_hyinput(conn);
            (void)ci_30;
            void * __t5;
            if ((ci_30) == (INT64_C(0))) {
                __t5 = postgres__notify____err(INT64_C(0));
            } else {
                __t5 = postgres__notify____ok(postgres__notify___un_unpq_hynotifies(conn));
            }
            __t4 = __t5;
        }
        return __t4;
}

const char * postgres__notify__notification_hychannel(int64_t n) {
        #include <libpq-fe.h>
  PGnotify *notif = (PGnotify *)(intptr_t)n;
  return notif ? (char *)notif->relname : (char *)"";
  
}

const char * postgres__notify__notification_hypayload(int64_t n) {
        #include <libpq-fe.h>
  PGnotify *notif = (PGnotify *)(intptr_t)n;
  if (!notif) return (char *)"";
  return notif->extra ? (char *)notif->extra : (char *)"";
  
}


