/* generated by tur (phase 2) */
#include "postgres__db.h"

static void * postgres__db____ok(int64_t);
static void * postgres__db____err(int64_t);
static bool postgres__db___un_unok_qu(void *);
static int64_t postgres__db___un_unok_hyval(void *);
static int64_t postgres__db____nil();
static int64_t postgres__db____cons(int64_t, int64_t);
static int64_t postgres__db___un_unparams_hycount(int64_t);
static int64_t postgres__db___un_unparams_hyvalues(int64_t, int64_t);
static int64_t postgres__db___un_unpq_hyconnect_hyraw(const char *);
static void postgres__db___un_unpq_hyfinish_hyraw(int64_t);
static int64_t postgres__db___un_unpq_hyexec_hyraw(int64_t, const char *);
static int64_t postgres__db___un_unpq_hyquery_hyraw(int64_t, const char *);
static int64_t postgres__db___un_unpq_hyquery_hyparams_hyraw(int64_t, const char *, int64_t, int64_t);
void * postgres__db__db_hyconnect(const char *);
void * postgres__db__db_hyclose(int64_t);
void * postgres__db__db_hyexec(int64_t, const char *);
void * postgres__db__db_hyquery(int64_t, const char *);
void * postgres__db__db_hyquery_hyparams(int64_t, const char *, int64_t);
void * postgres__db__db_hybegin(int64_t);
void * postgres__db__db_hycommit(int64_t);
void * postgres__db__db_hyrollback(int64_t);

static void * postgres__db____ok(int64_t v) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = true; r->ok_val = v; r->err_val = 0; return r;
  
}

static void * postgres__db____err(int64_t e) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = false; r->ok_val = 0; r->err_val = e; return r;
  
}

static bool postgres__db___un_unok_qu(void * r) {
        struct { bool is_ok; int64_t ok_val; int64_t err_val; } *res = (void *)r;
  return res != NULL && res->is_ok;
  
}

static int64_t postgres__db___un_unok_hyval(void * r) {
        struct { bool is_ok; int64_t ok_val; int64_t err_val; } *res = (void *)r;
  return res->ok_val;
  
}

static int64_t postgres__db____nil() {
        return 0;
  
}

static int64_t postgres__db____cons(int64_t v, int64_t n) {
        #include <stdlib.h>
  struct { int64_t value; int64_t next; } *cell = malloc(sizeof(*cell));
  cell->value = v; cell->next = n;
  return (int64_t)(intptr_t)cell;
  
}

static int64_t postgres__db___un_unparams_hycount(int64_t params) {
        struct { int64_t value; int64_t next; } *cell =
      (struct { int64_t value; int64_t next; } *)(intptr_t)params;
  int64_t n = 0;
  while (cell) { n++; cell = (struct { int64_t value; int64_t next; } *)(intptr_t)cell->next; }
  return n;
  
}

static int64_t postgres__db___un_unparams_hyvalues(int64_t params, int64_t n) {
        #include <stdlib.h>
  struct __pgcons { int64_t value; int64_t next; };
  const char **arr = (const char **)malloc((size_t)n * sizeof(const char *));
  struct __pgcons *cell = (struct __pgcons *)(intptr_t)params;
  for (int64_t i = 0; i < n && cell; i++) {
    arr[i] = (const char *)(intptr_t)cell->value;
    cell = (struct __pgcons *)(intptr_t)cell->next;
  }
  return (int64_t)(intptr_t)arr;
  
}

static int64_t postgres__db___un_unpq_hyconnect_hyraw(const char * connstr) {
        #include <libpq-fe.h>
  PGconn *conn = PQconnectdb((const char *)connstr);
  if (!conn || PQstatus(conn) != CONNECTION_OK) {
    if (conn) PQfinish(conn);
    return 0;
  }
  return (int64_t)(intptr_t)conn;
  
}

static void postgres__db___un_unpq_hyfinish_hyraw(int64_t conn) {
        #include <libpq-fe.h>
  PQfinish((PGconn *)(intptr_t)conn);
  
}

static int64_t postgres__db___un_unpq_hyexec_hyraw(int64_t conn, const char * sql) {
        #include <libpq-fe.h>
  PGresult *res = PQexec((PGconn *)(intptr_t)conn, (const char *)sql);
  if (!res) return 0;
  ExecStatusType st = PQresultStatus(res);
  PQclear(res);
  return (st == PGRES_COMMAND_OK || st == PGRES_TUPLES_OK) ? 1 : 0;
  
}

static int64_t postgres__db___un_unpq_hyquery_hyraw(int64_t conn, const char * sql) {
        #include <libpq-fe.h>
  PGresult *res = PQexec((PGconn *)(intptr_t)conn, (const char *)sql);
  if (!res) return 0;
  if (PQresultStatus(res) != PGRES_TUPLES_OK) { PQclear(res); return 0; }
  return (int64_t)(intptr_t)res;
  
}

static int64_t postgres__db___un_unpq_hyquery_hyparams_hyraw(int64_t conn, const char * sql, int64_t paramValues, int64_t nparams) {
        #include <libpq-fe.h>
  const char **vals = (const char **)(intptr_t)paramValues;
  PGresult *res = PQexecParams((PGconn *)(intptr_t)conn,
                               (const char *)sql,
                               (int)nparams,
                               NULL, vals, NULL, NULL, 0);
  if (!res) return 0;
  if (PQresultStatus(res) != PGRES_TUPLES_OK) { PQclear(res); return 0; }
  return (int64_t)(intptr_t)res;
  
}

void * postgres__db__db_hyconnect(const char * connstr) {
        void * __t0;
        {
            int64_t raw_42 = postgres__db___un_unpq_hyconnect_hyraw(connstr);
            (void)raw_42;
            void * __t1;
            if ((raw_42) != (INT64_C(0))) {
                __t1 = postgres__db____ok(raw_42);
            } else {
                __t1 = postgres__db____err(INT64_C(0));
            }
            __t0 = __t1;
        }
        return __t0;
}

void * postgres__db__db_hyclose(int64_t conn) {
        postgres__db___un_unpq_hyfinish_hyraw(conn);
        void * __t2;
        __t2 = postgres__db____ok(INT64_C(0));
        return __t2;
}

void * postgres__db__db_hyexec(int64_t conn, const char * sql) {
        void * __t3;
        {
            int64_t rc_46 = postgres__db___un_unpq_hyexec_hyraw(conn, sql);
            (void)rc_46;
            void * __t4;
            if ((rc_46) != (INT64_C(0))) {
                __t4 = postgres__db____ok(INT64_C(0));
            } else {
                __t4 = postgres__db____err(INT64_C(0));
            }
            __t3 = __t4;
        }
        return __t3;
}

void * postgres__db__db_hyquery(int64_t conn, const char * sql) {
        void * __t5;
        {
            int64_t raw_49 = postgres__db___un_unpq_hyquery_hyraw(conn, sql);
            (void)raw_49;
            void * __t6;
            if ((raw_49) != (INT64_C(0))) {
                __t6 = postgres__db____ok(raw_49);
            } else {
                __t6 = postgres__db____err(INT64_C(0));
            }
            __t5 = __t6;
        }
        return __t5;
}

void * postgres__db__db_hyquery_hyparams(int64_t conn, const char * sql, int64_t params) {
        void * __t7;
        {
            int64_t n_53 = postgres__db___un_unparams_hycount(params);
            (void)n_53;
            int64_t vals_54 = postgres__db___un_unparams_hyvalues(params, n_53);
            (void)vals_54;
            int64_t raw_55 = postgres__db___un_unpq_hyquery_hyparams_hyraw(conn, sql, vals_54, n_53);
            (void)raw_55;
            void * __t8;
            if ((raw_55) != (INT64_C(0))) {
                __t8 = postgres__db____ok(raw_55);
            } else {
                __t8 = postgres__db____err(INT64_C(0));
            }
            __t7 = __t8;
        }
        return __t7;
}

void * postgres__db__db_hybegin(int64_t conn) {
        return postgres__db__db_hyexec(conn, "BEGIN");
}

void * postgres__db__db_hycommit(int64_t conn) {
        return postgres__db__db_hyexec(conn, "COMMIT");
}

void * postgres__db__db_hyrollback(int64_t conn) {
        return postgres__db__db_hyexec(conn, "ROLLBACK");
}


