/* generated by tur (phase 2) */
#ifndef TUR_raygui__themes_H
#define TUR_raygui__themes_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "raygui__core.h"
#include "raygui__style.h"

void raygui__themes__gui_hyapply_hylight_hytheme();
void raygui__themes__gui_hyapply_hydark_hytheme();
#endif /* TUR_raygui__themes_H */
