/* generated by tur (phase 2) */
#include "raygui__themes.h"

void raygui__themes__gui_hyapply_hylight_hytheme();
void raygui__themes__gui_hyapply_hydark_hytheme();

void raygui__themes__gui_hyapply_hylight_hytheme() {
        raygui__core__gui_hyload_hystyle_hydefault();
}

void raygui__themes__gui_hyapply_hydark_hytheme() {
        raygui__core__gui_hyload_hystyle_hydefault();
        raygui__core__gui_hyset_hystyle(RAYGUI_unDEFAULT_24, RAYGUI_unBORDER_unCOLOR_unNORMAL_40, INT64_C(1515870975));
        raygui__core__gui_hyset_hystyle(RAYGUI_unDEFAULT_24, RAYGUI_unBORDER_unCOLOR_unFOCUSED_43, INT64_C(2358021375));
        raygui__core__gui_hyset_hystyle(RAYGUI_unDEFAULT_24, RAYGUI_unBORDER_unCOLOR_unPRESSED_46, INT64_C(3031741695));
        raygui__core__gui_hyset_hystyle(RAYGUI_unDEFAULT_24, RAYGUI_unBORDER_unCOLOR_unDISABLED_49, INT64_C(1010580735));
        raygui__core__gui_hyset_hystyle(RAYGUI_unDEFAULT_24, RAYGUI_unBASE_unCOLOR_unNORMAL_41, INT64_C(505290495));
        raygui__core__gui_hyset_hystyle(RAYGUI_unDEFAULT_24, RAYGUI_unBASE_unCOLOR_unFOCUSED_44, INT64_C(757935615));
        raygui__core__gui_hyset_hystyle(RAYGUI_unDEFAULT_24, RAYGUI_unBASE_unCOLOR_unPRESSED_47, INT64_C(1212696831));
        raygui__core__gui_hyset_hystyle(RAYGUI_unDEFAULT_24, RAYGUI_unBASE_unCOLOR_unDISABLED_50, INT64_C(336860415));
        raygui__core__gui_hyset_hystyle(RAYGUI_unDEFAULT_24, RAYGUI_unTEXT_unCOLOR_unNORMAL_42, INT64_C(3368601855));
        raygui__core__gui_hyset_hystyle(RAYGUI_unDEFAULT_24, RAYGUI_unTEXT_unCOLOR_unFOCUSED_45, INT64_C(3705462015));
        raygui__core__gui_hyset_hystyle(RAYGUI_unDEFAULT_24, RAYGUI_unTEXT_unCOLOR_unPRESSED_48, INT64_C(4294967295));
        raygui__core__gui_hyset_hystyle(RAYGUI_unDEFAULT_24, RAYGUI_unTEXT_unCOLOR_unDISABLED_51, INT64_C(1616929023));
}


