/* generated by tur (phase 2) */
#ifndef TUR_raygui__core_H
#define TUR_raygui__core_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void raygui__core__gui_hyenable();
void raygui__core__gui_hydisable();
void raygui__core__gui_hylock();
void raygui__core__gui_hyunlock();
int64_t raygui__core__gui_hyis_hylocked();
void raygui__core__gui_hyset_hyalpha(double);
void raygui__core__gui_hyset_hystate(int64_t);
int64_t raygui__core__gui_hyget_hystate();
void raygui__core__gui_hyset_hyfont(int64_t);
int64_t raygui__core__gui_hyget_hyfont();
void raygui__core__gui_hyset_hystyle(int64_t, int64_t, int64_t);
int64_t raygui__core__gui_hyget_hystyle(int64_t, int64_t);
void raygui__core__gui_hyload_hystyle(const char *);
void raygui__core__gui_hyload_hystyle_hydefault();
#endif /* TUR_raygui__core_H */
