/* generated by tur (phase 2) */
#ifndef TUR_raygui__rect_H
#define TUR_raygui__rect_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

Rect raygui__rect__rect(double, double, double, double);
#endif /* TUR_raygui__rect_H */
