/* generated by tur (phase 2) */
#ifndef TUR_raygui__controls_H
#define TUR_raygui__controls_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "raygui__rect.h"

int64_t raygui__controls__make_hytext_hybuf(int64_t);
void raygui__controls__free_hytext_hybuf(int64_t);
const char * raygui__controls__text_hybuf_hy_gtcstr(int64_t);
void raygui__controls__gui_hylabel(Rect, const char *);
int64_t raygui__controls__gui_hybutton(Rect, const char *);
int64_t raygui__controls__gui_hylabel_hybutton(Rect, const char *);
int64_t raygui__controls__gui_hytoggle(Rect, const char *, int64_t);
int64_t raygui__controls__gui_hytoggle_hygroup(Rect, const char *, int64_t);
int64_t raygui__controls__gui_hycheck_hybox(Rect, const char *, int64_t);
double raygui__controls__gui_hyslider(Rect, const char *, const char *, double, double, double);
double raygui__controls__gui_hyslider_hybar(Rect, const char *, const char *, double, double, double);
double raygui__controls__gui_hyprogress_hybar(Rect, const char *, const char *, double, double, double);
int64_t raygui__controls__gui_hytext_hybox(Rect, int64_t, int64_t, int64_t);
int64_t raygui__controls__gui_hytext_hybox_hymulti(Rect, int64_t, int64_t, int64_t);
int64_t raygui__controls__gui_hyspinner(Rect, const char *, int64_t, int64_t, int64_t, int64_t);
int64_t raygui__controls__gui_hyvalue_hybox(Rect, const char *, int64_t, int64_t, int64_t, int64_t);
int64_t raygui__controls__gui_hycombo_hybox(Rect, const char *, int64_t);
int64_t raygui__controls__gui_hydropdown_hybox(Rect, const char *, int64_t, int64_t);
int64_t raygui__controls__gui_hylist_hyview(Rect, const char *, int64_t, int64_t);
int64_t raygui__controls__gui_hylist_hyview_hyex(Rect, const char *, int64_t, int64_t, int64_t, int64_t);
int64_t raygui__controls__gui_hycolor_hypicker(Rect, const char *, int64_t);
double raygui__controls__gui_hycolor_hybar_hyalpha(Rect, const char *, double);
double raygui__controls__gui_hycolor_hybar_hyhue(Rect, const char *, double);
int64_t raygui__controls__gui_hymessage_hybox(Rect, const char *, const char *, const char *);
int64_t raygui__controls__gui_hytext_hyinput_hybox(Rect, const char *, const char *, const char *, int64_t, int64_t, int64_t);
int64_t raygui__controls__gui_hygrid(Rect, const char *, double, int64_t);
#endif /* TUR_raygui__controls_H */
