/* generated by tur (phase 2) */
#ifndef TUR_plot__point_H
#define TUR_plot__point_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "plot__core.h"

int64_t plot__point__points(int64_t, int64_t, const char *);
int64_t plot__point__error_hybars(int64_t, int64_t, int64_t, const char *);
int64_t plot__point__vector_hyfield(int64_t, double, double, double, double, int64_t, int64_t, int64_t, const char *);
int64_t plot__point__arrows(int64_t, int64_t, const char *);
#endif /* TUR_plot__point_H */
