/* generated by tur (phase 2) */
#ifndef TUR_plot__line_H
#define TUR_plot__line_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "plot__core.h"

int64_t plot__line__function(int64_t, double, double, int64_t, int64_t, const char *);
int64_t plot__line__lines(int64_t, int64_t, const char *);
int64_t plot__line__parametric(int64_t, double, double, int64_t, int64_t, const char *);
int64_t plot__line__polar(int64_t, double, double, int64_t, int64_t, const char *);
int64_t plot__line__inverse(int64_t, double, double, int64_t, int64_t, const char *);
int64_t plot__line__density(int64_t, double, int64_t, int64_t, const char *);
#endif /* TUR_plot__line_H */
