/* generated by tur (phase 2) */
#ifndef TUR_plot__style_H
#define TUR_plot__style_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int64_t plot__style__line_hystyle(int64_t, double, int64_t, double);
int64_t plot__style__point_hystyle(int64_t, int64_t, int64_t, double, double);
int64_t plot__style__fill_hystyle(int64_t, double, int64_t, double);
int64_t plot__style__plot_hyopts(int64_t, int64_t, const char *, const char *, const char *, double, double, double, double, int64_t);
int64_t plot__style__plot_hyopts_hywidth(int64_t);
int64_t plot__style__plot_hyopts_hyheight(int64_t);
int64_t plot__style__default_hyline_hystyle();
int64_t plot__style__default_hypoint_hystyle();
int64_t plot__style__default_hyfill_hystyle();
int64_t plot__style__default_hyplot_hyopts();
int64_t plot__style__dash_hysolid();
int64_t plot__style__dash_hydash();
int64_t plot__style__dash_hydot();
int64_t plot__style__dash_hydash_hydot();
int64_t plot__style__sym_hycircle();
int64_t plot__style__sym_hysquare();
int64_t plot__style__sym_hytriangle();
int64_t plot__style__sym_hycross();
int64_t plot__style__sym_hyplus();
int64_t plot__style__sym_hydiamond();
int64_t plot__style__palette_hysize();
int64_t plot__style__palette_hycolor(int64_t);
int64_t plot__style__color_hyseq(int64_t, int64_t, int64_t);
#endif /* TUR_plot__style_H */
