/* generated by tur (phase 2) */
#ifndef TUR_plot__area_H
#define TUR_plot__area_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "plot__core.h"

int64_t plot__area__rectangles(int64_t, int64_t, const char *);
int64_t plot__area__area_hyhistogram(int64_t, int64_t, const char *);
int64_t plot__area__discrete_hyhistogram(int64_t, int64_t, int64_t, const char *);
int64_t plot__area__stacked_hyhistogram(int64_t, int64_t, int64_t, int64_t);
#endif /* TUR_plot__area_H */
