/* generated by tur (phase 2) */
#include "plot__area.h"

int64_t plot__area__rectangles(int64_t, int64_t, const char *);
int64_t plot__area__area_hyhistogram(int64_t, int64_t, const char *);
int64_t plot__area__discrete_hyhistogram(int64_t, int64_t, int64_t, const char *);
int64_t plot__area__stacked_hyhistogram(int64_t, int64_t, int64_t, int64_t);

int64_t plot__area__rectangles(int64_t rects, int64_t fill, const char * label) {
        return plot__core___un_unmake_hyrenderer(INT64_C(50), fill, INT64_C(0), rects, INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), label, "");
}

int64_t plot__area__area_hyhistogram(int64_t bars, int64_t fill_styles, const char * label) {
        return plot__core___un_unmake_hyrenderer(INT64_C(51), INT64_C(0), INT64_C(0), bars, fill_styles, INT64_C(0), INT64_C(0), INT64_C(0), label, "");
}

int64_t plot__area__discrete_hyhistogram(int64_t bars, int64_t fill, int64_t invert, const char * label) {
        return plot__core___un_unrenderer_hyints(plot__core___un_unmake_hyrenderer(INT64_C(52), fill, INT64_C(0), bars, bars, INT64_C(0), INT64_C(0), INT64_C(0), label, ""), invert, INT64_C(0), INT64_C(0), INT64_C(0));
}

int64_t plot__area__stacked_hyhistogram(int64_t groups, int64_t fills, int64_t labels, int64_t invert) {
        return plot__core___un_unrenderer_hyints(plot__core___un_unmake_hyrenderer(INT64_C(53), INT64_C(0), INT64_C(0), groups, groups, fills, labels, INT64_C(0), "", ""), invert, INT64_C(0), INT64_C(0), INT64_C(0));
}


