/* generated by tur (phase 2) */
#ifndef TUR_plot__tick_H
#define TUR_plot__tick_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

const char * plot__tick__format_hytick(double, int64_t);
int64_t plot__tick__linear_hyticks(double, double, int64_t);
int64_t plot__tick__log_hyticks(double, double);
int64_t plot__tick__linear_hytick_hylabels(double, double, int64_t);
int64_t plot__tick__log_hytick_hylabels(double, double);
#endif /* TUR_plot__tick_H */
