/* generated by tur (phase 2) */
#ifndef TUR_plot__core_H
#define TUR_plot__core_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "plot__style.h"

bool plot__core___un_unok_qu(void *);
int64_t plot__core___un_unok_hyval(void *);
int64_t plot__core___un_unerr_hyval(void *);
int64_t plot__core___un_unmake_hyrenderer(int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, const char *, const char *);
int64_t plot__core___un_unrenderer_hyfloats(int64_t, double, double, double, double, double, double);
int64_t plot__core___un_unrenderer_hyints(int64_t, int64_t, int64_t, int64_t, int64_t);
int64_t plot__core___un_unrenderer_hybounds(int64_t, double, double, double, double);
void * plot__core___un_unsurface_hycreate(int64_t, int64_t);
void plot__core___un_unsurface_hydestroy(int64_t);
void * plot__core___un_unsurface_hywrite_hypng(int64_t, const char *);
void * plot__core___un_uncanvas_hycreate(int64_t);
void plot__core___un_uncanvas_hydestroy(int64_t);
int64_t plot__core___un_unsurface_hywidth(int64_t);
int64_t plot__core___un_unsurface_hyheight(int64_t);
int64_t plot__core___un_unsurface_hypixel_hybyte(int64_t, int64_t, int64_t, int64_t);
int64_t plot__core___un_uncount_hynon_hybackground(int64_t, int64_t, int64_t, int64_t, int64_t);
bool plot__core___un_unpixel_hyis_hybackground_qu(int64_t, int64_t, int64_t);
void plot__core___un_unplot_hysample_hyadaptive(int64_t, int64_t, double, double, double, double, int64_t, int64_t, int64_t, int64_t, int64_t);
void * plot__core__plot_hyinto_hycanvas(int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t);
void * plot__core__plot(int64_t, int64_t);
void * plot__core__plot_hywrite_hypng(int64_t, int64_t, const char *);
#endif /* TUR_plot__core_H */
