/* generated by tur (phase 2) */
#include "plot__decor.h"

static double plot__decor____nan();
int64_t plot__decor__x_hyaxis();
int64_t plot__decor__y_hyaxis();
int64_t plot__decor__axes();
int64_t plot__decor__x_hytick_hylines();
int64_t plot__decor__y_hytick_hylines();
int64_t plot__decor__tick_hygrid();
int64_t plot__decor__hrule_hystyled(double, int64_t);
int64_t plot__decor__hrule(double);
int64_t plot__decor__vrule_hystyled(double, int64_t);
int64_t plot__decor__vrule(double);
int64_t plot__decor__point_hylabel_hystyled(double, double, const char *, int64_t, int64_t);
int64_t plot__decor__point_hylabel(double, double, const char *, int64_t);

static double plot__decor____nan() {
        return 0.0 / 0.0; 
}

int64_t plot__decor__x_hyaxis() {
        return plot__core___un_unmake_hyrenderer(INT64_C(1), INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), "", "");
}

int64_t plot__decor__y_hyaxis() {
        return plot__core___un_unmake_hyrenderer(INT64_C(2), INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), "", "");
}

int64_t plot__decor__axes() {
        return plot__core___un_unmake_hyrenderer(INT64_C(3), INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), "", "");
}

int64_t plot__decor__x_hytick_hylines() {
        return plot__core___un_unmake_hyrenderer(INT64_C(4), INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), "", "");
}

int64_t plot__decor__y_hytick_hylines() {
        return plot__core___un_unmake_hyrenderer(INT64_C(5), INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), "", "");
}

int64_t plot__decor__tick_hygrid() {
        return plot__core___un_unmake_hyrenderer(INT64_C(6), INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), "", "");
}

int64_t plot__decor__hrule_hystyled(double y, int64_t style) {
        int64_t __t0;
        {
            int64_t r_201 = plot__core___un_unmake_hyrenderer(INT64_C(7), style, INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), "", "");
            (void)r_201;
            __t0 = plot__core___un_unrenderer_hybounds(plot__core___un_unrenderer_hyfloats(r_201, y, 0.0, 0.0, 0.0, 0.0, 0.0), plot__decor____nan(), plot__decor____nan(), y, y);
        }
        return __t0;
}

int64_t plot__decor__hrule(double y) {
        return plot__decor__hrule_hystyled(y, plot__style__default_hyline_hystyle());
}

int64_t plot__decor__vrule_hystyled(double x, int64_t style) {
        int64_t __t1;
        {
            int64_t r_205 = plot__core___un_unmake_hyrenderer(INT64_C(8), style, INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), "", "");
            (void)r_205;
            __t1 = plot__core___un_unrenderer_hybounds(plot__core___un_unrenderer_hyfloats(r_205, x, 0.0, 0.0, 0.0, 0.0, 0.0), x, x, plot__decor____nan(), plot__decor____nan());
        }
        return __t1;
}

int64_t plot__decor__vrule(double x) {
        return plot__decor__vrule_hystyled(x, plot__style__default_hyline_hystyle());
}

int64_t plot__decor__point_hylabel_hystyled(double x, double y, const char * text, int64_t anchor, int64_t style) {
        return plot__core___un_unrenderer_hybounds(plot__core___un_unrenderer_hyfloats(plot__core___un_unmake_hyrenderer(INT64_C(9), style, INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), "", text), x, y, 0.0, 0.0, 0.0, 0.0), x, x, y, y);
}

int64_t plot__decor__point_hylabel(double x, double y, const char * text, int64_t anchor) {
        return plot__decor__point_hylabel_hystyled(x, y, text, anchor, plot__style__default_hyline_hystyle());
}


