/* generated by tur (phase 2) */
#include "plot__line.h"

static double plot__line____nan();
int64_t plot__line__function(int64_t, double, double, int64_t, int64_t, const char *);
int64_t plot__line__lines(int64_t, int64_t, const char *);
int64_t plot__line__parametric(int64_t, double, double, int64_t, int64_t, const char *);
int64_t plot__line__polar(int64_t, double, double, int64_t, int64_t, const char *);
int64_t plot__line__inverse(int64_t, double, double, int64_t, int64_t, const char *);
int64_t plot__line__density(int64_t, double, int64_t, int64_t, const char *);

static double plot__line____nan() {
        return 0.0 / 0.0; 
}

int64_t plot__line__function(int64_t f, double x_min, double x_max, int64_t samples, int64_t style, const char * label) {
        return plot__core___un_unrenderer_hybounds(plot__core___un_unrenderer_hyints(plot__core___un_unrenderer_hyfloats(plot__core___un_unmake_hyrenderer(INT64_C(21), style, INT64_C(0), f, INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), label, ""), x_min, x_max, 0.0, 0.0, 0.0, 0.0), samples, INT64_C(0), INT64_C(0), INT64_C(0)), x_min, x_max, plot__line____nan(), plot__line____nan());
}

int64_t plot__line__lines(int64_t vs, int64_t style, const char * label) {
        return plot__core___un_unmake_hyrenderer(INT64_C(20), style, INT64_C(0), vs, INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), label, "");
}

int64_t plot__line__parametric(int64_t f, double t_min, double t_max, int64_t samples, int64_t style, const char * label) {
        return plot__core___un_unrenderer_hyints(plot__core___un_unrenderer_hyfloats(plot__core___un_unmake_hyrenderer(INT64_C(22), style, INT64_C(0), f, INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), label, ""), t_min, t_max, 0.0, 0.0, 0.0, 0.0), samples, INT64_C(0), INT64_C(0), INT64_C(0));
}

int64_t plot__line__polar(int64_t f, double theta_min, double theta_max, int64_t samples, int64_t style, const char * label) {
        return plot__core___un_unrenderer_hyints(plot__core___un_unrenderer_hyfloats(plot__core___un_unmake_hyrenderer(INT64_C(23), style, INT64_C(0), f, INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), label, ""), theta_min, theta_max, 0.0, 0.0, 0.0, 0.0), samples, INT64_C(0), INT64_C(0), INT64_C(0));
}

int64_t plot__line__inverse(int64_t f, double y_min, double y_max, int64_t samples, int64_t style, const char * label) {
        return plot__core___un_unrenderer_hyints(plot__core___un_unrenderer_hyfloats(plot__core___un_unmake_hyrenderer(INT64_C(24), style, INT64_C(0), f, INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), label, ""), y_min, y_max, 0.0, 0.0, 0.0, 0.0), samples, INT64_C(0), INT64_C(0), INT64_C(0));
}

int64_t plot__line__density(int64_t vs, double bandwidth, int64_t samples, int64_t style, const char * label) {
        return plot__core___un_unrenderer_hyints(plot__core___un_unrenderer_hyfloats(plot__core___un_unmake_hyrenderer(INT64_C(25), style, INT64_C(0), vs, INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), label, ""), bandwidth, 0.0, 0.0, 0.0, 0.0, 0.0), samples, INT64_C(0), INT64_C(0), INT64_C(0));
}


