/* generated by tur (phase 2) */
#include "plot__style.h"

static double plot__style____nan();
static const char * plot__style___un_unnull_hycstr();
int64_t plot__style__line_hystyle(int64_t, double, int64_t, double);
int64_t plot__style__point_hystyle(int64_t, int64_t, int64_t, double, double);
int64_t plot__style__fill_hystyle(int64_t, double, int64_t, double);
int64_t plot__style__plot_hyopts(int64_t, int64_t, const char *, const char *, const char *, double, double, double, double, int64_t);
int64_t plot__style__plot_hyopts_hywidth(int64_t);
int64_t plot__style__plot_hyopts_hyheight(int64_t);
int64_t plot__style__default_hyline_hystyle();
int64_t plot__style__default_hypoint_hystyle();
int64_t plot__style__default_hyfill_hystyle();
int64_t plot__style__default_hyplot_hyopts();
int64_t plot__style__dash_hysolid();
int64_t plot__style__dash_hydash();
int64_t plot__style__dash_hydot();
int64_t plot__style__dash_hydash_hydot();
int64_t plot__style__sym_hycircle();
int64_t plot__style__sym_hysquare();
int64_t plot__style__sym_hytriangle();
int64_t plot__style__sym_hycross();
int64_t plot__style__sym_hyplus();
int64_t plot__style__sym_hydiamond();
int64_t plot__style__palette_hysize();
int64_t plot__style__palette_hycolor(int64_t);
int64_t plot__style__color_hyseq(int64_t, int64_t, int64_t);

static double plot__style____nan() {
        return 0.0 / 0.0;
    
}

static const char * plot__style___un_unnull_hycstr() {
        return (char *)(intptr_t)0;
    
}

int64_t plot__style__line_hystyle(int64_t color, double width, int64_t dash, double alpha) {
        typedef struct { int64_t color; double width; int64_t dash; double alpha; } LineStyle;
    LineStyle *s = malloc(sizeof(*s));
    s->color = color; s->width = width; s->dash = dash; s->alpha = alpha;
    return (int64_t)(intptr_t)s;
    
}

int64_t plot__style__point_hystyle(int64_t color, int64_t fill_color, int64_t sym, double size, double alpha) {
        typedef struct { int64_t color; int64_t fill_color; int64_t sym; double size; double alpha; } PointStyle;
    PointStyle *s = malloc(sizeof(*s));
    s->color = color; s->fill_color = fill_color; s->sym = sym; s->size = size; s->alpha = alpha;
    return (int64_t)(intptr_t)s;
    
}

int64_t plot__style__fill_hystyle(int64_t color, double alpha, int64_t line_color, double line_width) {
        typedef struct { int64_t color; double alpha; int64_t line_color; double line_width; } FillStyle;
    FillStyle *s = malloc(sizeof(*s));
    s->color = color; s->alpha = alpha; s->line_color = line_color; s->line_width = line_width;
    return (int64_t)(intptr_t)s;
    
}

int64_t plot__style__plot_hyopts(int64_t width, int64_t height, const char * title, const char * x_label, const char * y_label, double x_min, double x_max, double y_min, double y_max, int64_t legend_pos) {
        typedef struct {
      int64_t width; int64_t height;
      char *title; char *x_label; char *y_label;
      double x_min; double x_max; double y_min; double y_max;
      int64_t legend_pos;
    } PlotOpts;
    PlotOpts *o = malloc(sizeof(*o));
    o->width = width; o->height = height;
    o->title = (char *)(intptr_t)title;
    o->x_label = (char *)(intptr_t)x_label;
    o->y_label = (char *)(intptr_t)y_label;
    o->x_min = x_min; o->x_max = x_max; o->y_min = y_min; o->y_max = y_max;
    o->legend_pos = legend_pos;
    return (int64_t)(intptr_t)o;
    
}

int64_t plot__style__plot_hyopts_hywidth(int64_t opts) {
        typedef struct {
      int64_t width; int64_t height;
      char *title; char *x_label; char *y_label;
      double x_min; double x_max; double y_min; double y_max;
      int64_t legend_pos;
    } PlotOpts;
    return opts ? ((PlotOpts *)(intptr_t)opts)->width : 0;
    
}

int64_t plot__style__plot_hyopts_hyheight(int64_t opts) {
        typedef struct {
      int64_t width; int64_t height;
      char *title; char *x_label; char *y_label;
      double x_min; double x_max; double y_min; double y_max;
      int64_t legend_pos;
    } PlotOpts;
    return opts ? ((PlotOpts *)(intptr_t)opts)->height : 0;
    
}

int64_t plot__style__default_hyline_hystyle() {
        return plot__style__line_hystyle(INT64_C(-1), 0.0, INT64_C(0), 0.0);
}

int64_t plot__style__default_hypoint_hystyle() {
        return plot__style__point_hystyle(INT64_C(-1), INT64_C(-1), INT64_C(0), 0.0, 0.0);
}

int64_t plot__style__default_hyfill_hystyle() {
        return plot__style__fill_hystyle(INT64_C(-1), 0.0, INT64_C(-1), 0.0);
}

int64_t plot__style__default_hyplot_hyopts() {
        return plot__style__plot_hyopts(INT64_C(0), INT64_C(0), plot__style___un_unnull_hycstr(), plot__style___un_unnull_hycstr(), plot__style___un_unnull_hycstr(), plot__style____nan(), plot__style____nan(), plot__style____nan(), plot__style____nan(), INT64_C(1));
}

int64_t plot__style__dash_hysolid() {
        return INT64_C(0);
}

int64_t plot__style__dash_hydash() {
        return INT64_C(1);
}

int64_t plot__style__dash_hydot() {
        return INT64_C(2);
}

int64_t plot__style__dash_hydash_hydot() {
        return INT64_C(3);
}

int64_t plot__style__sym_hycircle() {
        return INT64_C(0);
}

int64_t plot__style__sym_hysquare() {
        return INT64_C(1);
}

int64_t plot__style__sym_hytriangle() {
        return INT64_C(2);
}

int64_t plot__style__sym_hycross() {
        return INT64_C(3);
}

int64_t plot__style__sym_hyplus() {
        return INT64_C(4);
}

int64_t plot__style__sym_hydiamond() {
        return INT64_C(5);
}

int64_t plot__style__palette_hysize() {
        return INT64_C(8);
}

int64_t plot__style__palette_hycolor(int64_t idx) {
        #include <stdlib.h>
    #include <stdint.h>
    typedef struct { int64_t head; int64_t tail; } Cons;
    static const int palette[8][3] = {
      {31, 119, 180}, {214, 39, 40}, {44, 160, 44}, {255, 127, 14},
      {148, 103, 189}, {140, 86, 75}, {227, 119, 194}, {127, 127, 127}
    };
    int i = (int)(idx % 8);
    if (i < 0) i += 8;
    Cons *c3 = (Cons *)malloc(sizeof(*c3));
    Cons *c2 = (Cons *)malloc(sizeof(*c2));
    Cons *c1 = (Cons *)malloc(sizeof(*c1));
    c3->head = palette[i][2]; c3->tail = 0;
    c2->head = palette[i][1]; c2->tail = (int64_t)(intptr_t)c3;
    c1->head = palette[i][0]; c1->tail = (int64_t)(intptr_t)c2;
    return (int64_t)(intptr_t)c1;
    
}

int64_t plot__style__color_hyseq(int64_t start_idx, int64_t end_idx, int64_t n) {
        #include <stdlib.h>
    #include <stdint.h>
    typedef struct { int64_t head; int64_t tail; } Cons;
    static const double palette[8][3] = {
      {31, 119, 180}, {214, 39, 40}, {44, 160, 44}, {255, 127, 14},
      {148, 103, 189}, {140, 86, 75}, {227, 119, 194}, {127, 127, 127}
    };
    int si = (int)(start_idx % 8), ei = (int)(end_idx % 8);
    if (si < 0) si += 8;
    if (ei < 0) ei += 8;
    if (n <= 0) return 0;
    int64_t out = 0;
    for (int i = n - 1; i >= 0; i--) {
      double t = (n == 1) ? 0.0 : (double)i / (double)(n - 1);
      double r = palette[si][0] + (palette[ei][0] - palette[si][0]) * t;
      double g = palette[si][1] + (palette[ei][1] - palette[si][1]) * t;
      double b = palette[si][2] + (palette[ei][2] - palette[si][2]) * t;
      int best = 0;
      double bestd = 1e300;
      for (int p = 0; p < 8; p++) {
        double dr = palette[p][0] - r;
        double dg = palette[p][1] - g;
        double db = palette[p][2] - b;
        double d = dr * dr + dg * dg + db * db;
        if (d < bestd) { bestd = d; best = p; }
      }
      Cons *cell = (Cons *)malloc(sizeof(*cell));
      cell->head = best;
      cell->tail = out;
      out = (int64_t)(intptr_t)cell;
    }
    return out;
    
}


