/* generated by tur (phase 2) */
#ifndef TUR_plot__contour_H
#define TUR_plot__contour_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "plot__core.h"

int64_t plot__contour__isoline(int64_t, double, double, double, double, int64_t, double, int64_t, const char *);
int64_t plot__contour__contours(int64_t, double, double, double, double, int64_t, int64_t, int64_t, const char *);
int64_t plot__contour__contour_hyintervals(int64_t, double, double, double, double, int64_t, int64_t, int64_t, const char *);
int64_t plot__contour__color_hyfield(int64_t, double, double, double, double, int64_t, double);
#endif /* TUR_plot__contour_H */
