/* generated by tur (phase 2) */
#include "plot__contour.h"

int64_t plot__contour__isoline(int64_t, double, double, double, double, int64_t, double, int64_t, const char *);
int64_t plot__contour__contours(int64_t, double, double, double, double, int64_t, int64_t, int64_t, const char *);
int64_t plot__contour__contour_hyintervals(int64_t, double, double, double, double, int64_t, int64_t, int64_t, const char *);
int64_t plot__contour__color_hyfield(int64_t, double, double, double, double, int64_t, double);

int64_t plot__contour__isoline(int64_t f, double x_min, double x_max, double y_min, double y_max, int64_t samples, double level, int64_t style, const char * label) {
        return plot__core___un_unrenderer_hybounds(plot__core___un_unrenderer_hyints(plot__core___un_unrenderer_hyfloats(plot__core___un_unmake_hyrenderer(INT64_C(60), style, INT64_C(0), f, INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), label, ""), x_min, x_max, y_min, y_max, level, level), samples, INT64_C(0), INT64_C(0), INT64_C(0)), x_min, x_max, y_min, y_max);
}

int64_t plot__contour__contours(int64_t f, double x_min, double x_max, double y_min, double y_max, int64_t samples, int64_t n, int64_t styles, const char * label) {
        return plot__core___un_unrenderer_hybounds(plot__core___un_unrenderer_hyints(plot__core___un_unrenderer_hyfloats(plot__core___un_unmake_hyrenderer(INT64_C(61), styles, INT64_C(0), f, INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), label, ""), x_min, x_max, y_min, y_max, 0.0, 0.0), samples, n, INT64_C(0), INT64_C(0)), x_min, x_max, y_min, y_max);
}

int64_t plot__contour__contour_hyintervals(int64_t f, double x_min, double x_max, double y_min, double y_max, int64_t samples, int64_t n, int64_t fills, const char * label) {
        return plot__core___un_unrenderer_hybounds(plot__core___un_unrenderer_hyints(plot__core___un_unrenderer_hyfloats(plot__core___un_unmake_hyrenderer(INT64_C(62), fills, INT64_C(0), f, INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), label, ""), x_min, x_max, y_min, y_max, 0.0, 1.0), samples, n, INT64_C(0), INT64_C(0)), x_min, x_max, y_min, y_max);
}

int64_t plot__contour__color_hyfield(int64_t f, double x_min, double x_max, double y_min, double y_max, int64_t samples, double alpha) {
        return plot__core___un_unrenderer_hybounds(plot__core___un_unrenderer_hyints(plot__core___un_unrenderer_hyfloats(plot__core___un_unmake_hyrenderer(INT64_C(63), INT64_C(0), INT64_C(0), f, INT64_C(0), INT64_C(0), INT64_C(0), INT64_C(0), "", ""), x_min, x_max, y_min, y_max, alpha, 0.0), samples, INT64_C(0), INT64_C(0), INT64_C(0)), x_min, x_max, y_min, y_max);
}


