/* generated by tur (phase 2) */
#ifndef TUR_plot__decor_H
#define TUR_plot__decor_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "plot__core.h"
#include "plot__style.h"

int64_t plot__decor__x_hyaxis();
int64_t plot__decor__y_hyaxis();
int64_t plot__decor__axes();
int64_t plot__decor__x_hytick_hylines();
int64_t plot__decor__y_hytick_hylines();
int64_t plot__decor__tick_hygrid();
int64_t plot__decor__hrule_hystyled(double, int64_t);
int64_t plot__decor__hrule(double);
int64_t plot__decor__vrule_hystyled(double, int64_t);
int64_t plot__decor__vrule(double);
int64_t plot__decor__point_hylabel_hystyled(double, double, const char *, int64_t, int64_t);
int64_t plot__decor__point_hylabel(double, double, const char *, int64_t);
#endif /* TUR_plot__decor_H */
