/* generated by tur (phase 2) */
#include "plot__interval.h"

static double plot__interval____nan();
int64_t plot__interval__function_hyinterval(int64_t, int64_t, double, double, int64_t, int64_t, int64_t, const char *);
int64_t plot__interval__lines_hyinterval(int64_t, int64_t, int64_t, int64_t, const char *);
int64_t plot__interval__parametric_hyinterval(int64_t, int64_t, double, double, int64_t, int64_t, int64_t, const char *);
int64_t plot__interval__polar_hyinterval(int64_t, int64_t, double, double, int64_t, int64_t, int64_t, const char *);

static double plot__interval____nan() {
        return 0.0 / 0.0; 
}

int64_t plot__interval__function_hyinterval(int64_t f1, int64_t f2, double x_min, double x_max, int64_t samples, int64_t fill, int64_t style, const char * label) {
        return plot__core___un_unrenderer_hybounds(plot__core___un_unrenderer_hyints(plot__core___un_unrenderer_hyfloats(plot__core___un_unmake_hyrenderer(INT64_C(40), fill, style, f1, f2, INT64_C(0), INT64_C(0), INT64_C(0), label, ""), x_min, x_max, 0.0, 0.0, 0.0, 0.0), samples, INT64_C(0), INT64_C(0), INT64_C(0)), x_min, x_max, plot__interval____nan(), plot__interval____nan());
}

int64_t plot__interval__lines_hyinterval(int64_t vs1, int64_t vs2, int64_t fill, int64_t style, const char * label) {
        return plot__core___un_unmake_hyrenderer(INT64_C(41), fill, style, vs1, vs2, INT64_C(0), INT64_C(0), INT64_C(0), label, "");
}

int64_t plot__interval__parametric_hyinterval(int64_t f1, int64_t f2, double t_min, double t_max, int64_t samples, int64_t fill, int64_t style, const char * label) {
        return plot__core___un_unrenderer_hyints(plot__core___un_unrenderer_hyfloats(plot__core___un_unmake_hyrenderer(INT64_C(42), fill, style, f1, f2, INT64_C(0), INT64_C(0), INT64_C(0), label, ""), t_min, t_max, 0.0, 0.0, 0.0, 0.0), samples, INT64_C(0), INT64_C(0), INT64_C(0));
}

int64_t plot__interval__polar_hyinterval(int64_t f1, int64_t f2, double theta_min, double theta_max, int64_t samples, int64_t fill, int64_t style, const char * label) {
        return plot__core___un_unrenderer_hyints(plot__core___un_unrenderer_hyfloats(plot__core___un_unmake_hyrenderer(INT64_C(43), fill, style, f1, f2, INT64_C(0), INT64_C(0), INT64_C(0), label, ""), theta_min, theta_max, 0.0, 0.0, 0.0, 0.0), samples, INT64_C(0), INT64_C(0), INT64_C(0));
}


