/* generated by tur (phase 2) */
#ifndef TUR_plutovg__canvas_H
#define TUR_plutovg__canvas_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void * plutovg__canvas__canvas_hycreate(int64_t);
void plutovg__canvas__canvas_hydestroy(int64_t);
void plutovg__canvas__canvas_hyset_hysource_hycolor(int64_t, double, double, double, double);
void plutovg__canvas__canvas_hyfill_hyrect(int64_t, double, double, double, double);
void plutovg__canvas__canvas_hymove_hyto(int64_t, double, double);
void plutovg__canvas__canvas_hyline_hyto(int64_t, double, double);
void plutovg__canvas__canvas_hyquad_hyto(int64_t, double, double, double, double);
void plutovg__canvas__canvas_hycubic_hyto(int64_t, double, double, double, double, double, double);
void plutovg__canvas__canvas_hyclose_hypath(int64_t);
void plutovg__canvas__canvas_hyrect(int64_t, double, double, double, double);
void plutovg__canvas__canvas_hyellipse(int64_t, double, double, double, double);
void plutovg__canvas__canvas_hycircle(int64_t, double, double, double);
void plutovg__canvas__canvas_hyfill(int64_t);
void plutovg__canvas__canvas_hystroke(int64_t);
void plutovg__canvas__canvas_hyclip(int64_t);
void plutovg__canvas__canvas_hyadd_hypath(int64_t, int64_t);
void plutovg__canvas__canvas_hyfill_hypath(int64_t, int64_t);
void plutovg__canvas__canvas_hystroke_hypath(int64_t, int64_t);
void plutovg__canvas__canvas_hysave(int64_t);
void plutovg__canvas__canvas_hyrestore(int64_t);
void plutovg__canvas__canvas_hytranslate(int64_t, double, double);
void plutovg__canvas__canvas_hyscale(int64_t, double, double);
void plutovg__canvas__canvas_hyrotate(int64_t, double);
void plutovg__canvas__canvas_hytransform(int64_t, double, double, double, double, double, double);
void plutovg__canvas__canvas_hyreset_hytransform(int64_t);
void plutovg__canvas__canvas_hyset_hyline_hywidth(int64_t, double);
void plutovg__canvas__canvas_hyset_hyline_hycap(int64_t, const char *);
void plutovg__canvas__canvas_hyset_hyline_hyjoin(int64_t, const char *);
void plutovg__canvas__canvas_hyset_hymiter_hylimit(int64_t, double);
void * plutovg__canvas__dash_hyarray_hycreate();
void plutovg__canvas__dash_hyarray_hyadd(int64_t, double);
int64_t plutovg__canvas__dash_hyarray_hycount(int64_t);
void plutovg__canvas__dash_hyarray_hydestroy(int64_t);
void plutovg__canvas__canvas_hyset_hydash_hyoffset(int64_t, double);
void plutovg__canvas__canvas_hyset_hydash_hyarray(int64_t, int64_t);
void plutovg__canvas__canvas_hyset_hyfill_hyrule(int64_t, const char *);
void plutovg__canvas__canvas_hyset_hyoperator(int64_t, const char *);
void plutovg__canvas__canvas_hyset_hyopacity(int64_t, double);
void plutovg__canvas__canvas_hyarc(int64_t, double, double, double, double, double);
void plutovg__canvas__canvas_hyarc_hyto(int64_t, double, double, double, bool, bool, double, double);
void plutovg__canvas__canvas_hyround_hyrect(int64_t, double, double, double, double, double, double);
void plutovg__canvas__canvas_hydraw_hyimage(int64_t, int64_t, double, double, double, double);
#endif /* TUR_plutovg__canvas_H */
