/* generated by tur (phase 2) */
#ifndef TUR_plutovg__font_H
#define TUR_plutovg__font_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void * plutovg__font__font_hyface_hyload_hyfrom_hyfile(const char *, int64_t);
void * plutovg__font__font_hyface_hyload_hyfrom_hydata(const char *, int64_t, int64_t);
void plutovg__font__font_hyface_hydestroy(int64_t);
double plutovg__font__font_hyface_hyascent(int64_t, double);
double plutovg__font__font_hyface_hydescent(int64_t, double);
double plutovg__font__font_hyface_hyline_hygap(int64_t, double);
void * plutovg__font__font_hyface_hytext_hyextents(int64_t, double, const char *);
void * plutovg__font__font_hycache_hycreate();
void plutovg__font__font_hycache_hydestroy(int64_t);
void * plutovg__font__font_hycache_hyadd_hyfile(int64_t, const char *);
void * plutovg__font__font_hycache_hyload_hysystem(int64_t);
void * plutovg__font__font_hycache_hyget(int64_t, const char *, const char *, double);
void plutovg__font__canvas_hyset_hyfont_hyface(int64_t, int64_t);
void plutovg__font__canvas_hyset_hyfont_hysize(int64_t, double);
void plutovg__font__canvas_hyset_hyfont(int64_t, int64_t, double);
void plutovg__font__canvas_hyfill_hytext(int64_t, const char *, const char *, double, double);
void plutovg__font__canvas_hystroke_hytext(int64_t, const char *, const char *, double, double);
void * plutovg__font__canvas_hytext_hyextents(int64_t, const char *, const char *);
#endif /* TUR_plutovg__font_H */
