/* generated by tur (phase 2) */
#ifndef TUR_plutovg__surface_H
#define TUR_plutovg__surface_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void * plutovg__surface__surface_hycreate(int64_t, int64_t);
void * plutovg__surface__surface_hycreate_hyfrom_hydata(const char *, int64_t, int64_t, int64_t);
void plutovg__surface__surface_hydestroy(int64_t);
int64_t plutovg__surface__surface_hywidth(int64_t);
int64_t plutovg__surface__surface_hyheight(int64_t);
int64_t plutovg__surface__surface_hystride(int64_t);
const char * plutovg__surface__surface_hydata(int64_t);
void * plutovg__surface__surface_hywrite_hypng(int64_t, const char *);
void * plutovg__surface__surface_hywrite_hyjpeg(int64_t, const char *, int64_t);
#endif /* TUR_plutovg__surface_H */
