/* generated by tur (phase 2) */
#include "plutovg__path.h"

static void * plutovg__path____ok(int64_t);
static void * plutovg__path____err(int64_t);
void * plutovg__path__path_hycreate();
void plutovg__path__path_hydestroy(int64_t);
void plutovg__path__path_hymove_hyto(int64_t, double, double);
void plutovg__path__path_hyline_hyto(int64_t, double, double);
void plutovg__path__path_hyquad_hyto(int64_t, double, double, double, double);
void plutovg__path__path_hycubic_hyto(int64_t, double, double, double, double, double, double);
void plutovg__path__path_hyarc_hyto(int64_t, double, double, double, bool, bool, double, double);
void plutovg__path__path_hyclose(int64_t);
void plutovg__path__path_hyadd_hyrect(int64_t, double, double, double, double);
void plutovg__path__path_hyadd_hyround_hyrect(int64_t, double, double, double, double, double, double);
void plutovg__path__path_hyadd_hyellipse(int64_t, double, double, double, double);
void plutovg__path__path_hyadd_hycircle(int64_t, double, double, double);
void plutovg__path__path_hyadd_hyarc(int64_t, double, double, double, double, double);
void * plutovg__path__path_hyclone(int64_t);
void * plutovg__path__path_hyclone_hyflatten(int64_t);
void * plutovg__path__path_hyclone_hydashed(int64_t, double, int64_t);
void * plutovg__path__path_hyparse(int64_t, const char *);
void * plutovg__path__path_hyextents(int64_t);
double plutovg__path__path_hylength(int64_t);
void plutovg__path__rect_hydestroy(int64_t);
double plutovg__path__rect_hyx(int64_t);
double plutovg__path__rect_hyy(int64_t);
double plutovg__path__rect_hyw(int64_t);
double plutovg__path__rect_hyh(int64_t);

static void * plutovg__path____ok(int64_t v) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = true; r->ok_val = v; r->err_val = 0; return r;
  
}

static void * plutovg__path____err(int64_t e) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = false; r->ok_val = 0; r->err_val = e; return r;
  
}

void * plutovg__path__path_hycreate() {
        #include <stdlib.h>
  #include <plutovg.h>
  plutovg_path_t *p = plutovg_path_create();
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  if (!p) { r->is_ok = false; r->ok_val = 0; r->err_val = 0; return r; }
  r->is_ok = true; r->ok_val = (int64_t)(intptr_t)p; r->err_val = 0;
  return r;
  
}

void plutovg__path__path_hydestroy(int64_t p) {
        #include <plutovg.h>
  if (p) plutovg_path_destroy((plutovg_path_t *)(intptr_t)p);
  
}

void plutovg__path__path_hymove_hyto(int64_t p, double x, double y) {
        #include <plutovg.h>
  plutovg_path_move_to((plutovg_path_t *)(intptr_t)p, (float)x, (float)y);
  
}

void plutovg__path__path_hyline_hyto(int64_t p, double x, double y) {
        #include <plutovg.h>
  plutovg_path_line_to((plutovg_path_t *)(intptr_t)p, (float)x, (float)y);
  
}

void plutovg__path__path_hyquad_hyto(int64_t p, double x1, double y1, double x, double y) {
        #include <plutovg.h>
  plutovg_path_quad_to((plutovg_path_t *)(intptr_t)p,
                       (float)x1, (float)y1, (float)x, (float)y);
  
}

void plutovg__path__path_hycubic_hyto(int64_t p, double x1, double y1, double x2, double y2, double x, double y) {
        #include <plutovg.h>
  plutovg_path_cubic_to((plutovg_path_t *)(intptr_t)p,
                        (float)x1, (float)y1,
                        (float)x2, (float)y2,
                        (float)x,  (float)y);
  
}

void plutovg__path__path_hyarc_hyto(int64_t p, double rx, double ry, double rotation, bool large_arc_qu, bool sweep_qu, double x, double y) {
        #include <plutovg.h>
  plutovg_path_arc_to((plutovg_path_t *)(intptr_t)p,
                      (float)rx, (float)ry, (float)rotation,
                      large_arc, sweep,
                      (float)x, (float)y);
  
}

void plutovg__path__path_hyclose(int64_t p) {
        #include <plutovg.h>
  plutovg_path_close((plutovg_path_t *)(intptr_t)p);
  
}

void plutovg__path__path_hyadd_hyrect(int64_t p, double x, double y, double w, double h) {
        #include <plutovg.h>
  plutovg_path_add_rect((plutovg_path_t *)(intptr_t)p,
                        (float)x, (float)y, (float)w, (float)h);
  
}

void plutovg__path__path_hyadd_hyround_hyrect(int64_t p, double x, double y, double w, double h, double rx, double ry) {
        #include <plutovg.h>
  plutovg_path_add_round_rect((plutovg_path_t *)(intptr_t)p,
                              (float)x, (float)y, (float)w, (float)h,
                              (float)rx, (float)ry);
  
}

void plutovg__path__path_hyadd_hyellipse(int64_t p, double cx, double cy, double rx, double ry) {
        #include <plutovg.h>
  plutovg_path_add_ellipse((plutovg_path_t *)(intptr_t)p,
                           (float)cx, (float)cy,
                           (float)rx, (float)ry);
  
}

void plutovg__path__path_hyadd_hycircle(int64_t p, double cx, double cy, double r) {
        #include <plutovg.h>
  plutovg_path_add_circle((plutovg_path_t *)(intptr_t)p,
                          (float)cx, (float)cy, (float)r);
  
}

void plutovg__path__path_hyadd_hyarc(int64_t p, double cx, double cy, double r, double start_angle, double sweep_angle) {
        #include <plutovg.h>
  plutovg_path_add_arc((plutovg_path_t *)(intptr_t)p,
                       (float)cx, (float)cy, (float)r,
                       (float)start_angle, (float)sweep_angle,
                       false);
  
}

void * plutovg__path__path_hyclone(int64_t p) {
        #include <stdlib.h>
  #include <plutovg.h>
  plutovg_path_t *c = plutovg_path_clone((plutovg_path_t *)(intptr_t)p);
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  if (!c) { r->is_ok = false; r->ok_val = 0; r->err_val = 0; return r; }
  r->is_ok = true; r->ok_val = (int64_t)(intptr_t)c; r->err_val = 0;
  return r;
  
}

void * plutovg__path__path_hyclone_hyflatten(int64_t p) {
        #include <stdlib.h>
  #include <plutovg.h>
  plutovg_path_t *c = plutovg_path_clone_flatten((plutovg_path_t *)(intptr_t)p);
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  if (!c) { r->is_ok = false; r->ok_val = 0; r->err_val = 0; return r; }
  r->is_ok = true; r->ok_val = (int64_t)(intptr_t)c; r->err_val = 0;
  return r;
  
}

void * plutovg__path__path_hyclone_hydashed(int64_t p, double offset, int64_t dashes) {
        #include <stdlib.h>
  #include <plutovg.h>
  char *buf = (char *)(intptr_t)dashes;
  int n = buf ? ((int *)buf)[1] : 0;
  const float *arr = buf ? (const float *)(buf + sizeof(int) * 2) : NULL;
  plutovg_path_t *c = plutovg_path_clone_dashed(
      (const plutovg_path_t *)(intptr_t)p,
      (float)offset, arr, n);
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  if (!c) { r->is_ok = false; r->ok_val = 0; r->err_val = 0; return r; }
  r->is_ok = true; r->ok_val = (int64_t)(intptr_t)c; r->err_val = 0;
  return r;
  
}

void * plutovg__path__path_hyparse(int64_t p, const char * svg) {
        #include <stdlib.h>
  #include <string.h>
  #include <plutovg.h>
  bool ok = plutovg_path_parse((plutovg_path_t *)(intptr_t)p,
                               (const char *)(intptr_t)svg, -1);
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = ok; r->ok_val = 0; r->err_val = ok ? 0 : 1;
  return r;
  
}

void * plutovg__path__path_hyextents(int64_t p) {
        #include <stdlib.h>
  #include <plutovg.h>
  plutovg_rect_t ext;
  plutovg_path_extents((plutovg_path_t *)(intptr_t)p, &ext, /*tight=*/false);
  float *out = malloc(sizeof(float) * 4);
  out[0] = ext.x; out[1] = ext.y; out[2] = ext.w; out[3] = ext.h;
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = true; r->ok_val = (int64_t)(intptr_t)out; r->err_val = 0;
  return r;
  
}

double plutovg__path__path_hylength(int64_t p) {
        #include <plutovg.h>
  return (double)plutovg_path_length((plutovg_path_t *)(intptr_t)p);
  
}

void plutovg__path__rect_hydestroy(int64_t box) {
        #include <stdlib.h>
  if (box) free((void *)(intptr_t)box);
  
}

double plutovg__path__rect_hyx(int64_t box) {
        return (double)((float *)(intptr_t)box)[0];
  
}

double plutovg__path__rect_hyy(int64_t box) {
        return (double)((float *)(intptr_t)box)[1];
  
}

double plutovg__path__rect_hyw(int64_t box) {
        return (double)((float *)(intptr_t)box)[2];
  
}

double plutovg__path__rect_hyh(int64_t box) {
        return (double)((float *)(intptr_t)box)[3];
  
}


