/* generated by tur (phase 2) */
#include "test__assert.h"

bool test__assert__assert_hyeq(int64_t, int64_t);
bool test__assert__assert_hyne(int64_t, int64_t);
bool test__assert__assert_hytrue(bool);
bool test__assert__assert_hyfalse(bool);
bool test__assert__assert_hysome(int64_t);
bool test__assert__assert_hynone(int64_t);
bool test__assert__assert_hyok(int64_t);
bool test__assert__assert_hyerr(int64_t);

bool test__assert__assert_hyeq(int64_t expected, int64_t actual) {
        bool __t0;
        if ((expected) == (actual)) {
            __t0 = true;
        } else {
            puts("  FAIL assert-eq: expected");
            printf("%lld\n", (long long)(expected));
            puts("  got");
            printf("%lld\n", (long long)(actual));
            bool __t1;
            __t1 = false;
            __t0 = __t1;
        }
        return __t0;
}

bool test__assert__assert_hyne(int64_t a, int64_t b) {
        bool __t2;
        if ((a) != (b)) {
            __t2 = true;
        } else {
            puts("  FAIL assert-ne: expected values to differ, both");
            printf("%lld\n", (long long)(a));
            bool __t3;
            __t3 = false;
            __t2 = __t3;
        }
        return __t2;
}

bool test__assert__assert_hytrue(bool x) {
        bool __t4;
        if (x) {
            __t4 = true;
        } else {
            puts("  FAIL assert-true: expected true, got false");
            bool __t5;
            __t5 = false;
            __t4 = __t5;
        }
        return __t4;
}

bool test__assert__assert_hyfalse(bool x) {
        bool __t6;
        if (!(x)) {
            __t6 = true;
        } else {
            puts("  FAIL assert-false: expected false, got true");
            bool __t7;
            __t7 = false;
            __t6 = __t7;
        }
        return __t6;
}

bool test__assert__assert_hysome(int64_t o) {
        #include <stdio.h>
  #include <stdint.h>
  if (!o) { printf("  FAIL assert-some: expected some, got none (null)\n"); return 0; }
  struct { int64_t is_some; int64_t value; } *opt =
      (void*)(intptr_t)o;
  if (opt->is_some) return 1;
  printf("  FAIL assert-some: expected some, got none\n"); return 0;
  
}

bool test__assert__assert_hynone(int64_t o) {
        #include <stdio.h>
  #include <stdint.h>
  if (!o) return 1;
  struct { int64_t is_some; int64_t value; } *opt =
      (void*)(intptr_t)o;
  if (!opt->is_some) return 1;
  printf("  FAIL assert-none: expected none, got some\n"); return 0;
  
}

bool test__assert__assert_hyok(int64_t r) {
        #include <stdio.h>
  #include <stdint.h>
  if (!r) { printf("  FAIL assert-ok: got null result\n"); return 0; }
  struct { int64_t is_ok; int64_t ok_val; int64_t err_val; } *res =
      (void*)(intptr_t)r;
  if (res->is_ok) return 1;
  printf("  FAIL assert-ok: expected ok, got err\n"); return 0;
  
}

bool test__assert__assert_hyerr(int64_t r) {
        #include <stdio.h>
  #include <stdint.h>
  if (!r) { printf("  FAIL assert-err: got null result\n"); return 0; }
  struct { int64_t is_ok; int64_t ok_val; int64_t err_val; } *res =
      (void*)(intptr_t)r;
  if (!res->is_ok) return 1;
  printf("  FAIL assert-err: expected err, got ok\n"); return 0;
  
}


