/* generated by tur (phase 2) */
#ifndef TUR_test__suite_H
#define TUR_test__suite_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int64_t test__suite____ts(int64_t);
void test__suite___un_unit_hyprint(int64_t, const char *, bool);
void test__suite___un_undesc_hyprint(const char *);
bool test__suite__it(const char *, bool);
#endif /* TUR_test__suite_H */
