/* generated by tur (phase 2) */
#include "test__suite.h"

int64_t test__suite____ts(int64_t);
void test__suite___un_unit_hyprint(int64_t, const char *, bool);
void test__suite___un_undesc_hyprint(const char *);
bool test__suite__it(const char *, bool);

int64_t test__suite____ts(int64_t op) {
        static int64_t pass = 0, fail = 0, n = 0;
  switch ((int)op) {
    case 0: return pass;
    case 1: pass++; n++; return n;
    case 2: return fail;
    case 3: fail++; n++; return n;
    case 4: return n;
    default: return 0;
  }
  
}

void test__suite___un_unit_hyprint(int64_t n, const char * desc, bool result) {
        #include <stdio.h>
  if (result)
    printf("ok %lld - %s\n", (long long)n, desc);
  else
    printf("not ok %lld - %s\n", (long long)n, desc);
  
}

void test__suite___un_undesc_hyprint(const char * name) {
        #include <stdio.h>
  printf("# %s\n", name);
  
}

bool test__suite__it(const char * desc, bool result) {
        bool __t0;
        {
            int64_t __t1;
            if (result) {
                __t1 = test__suite____ts(INT64_C(1));
            } else {
                __t1 = test__suite____ts(INT64_C(3));
            }
            int64_t n_12 = __t1;
            (void)n_12;
            test__suite___un_unit_hyprint(n_12, desc, result);
            bool __t2;
            __t2 = result;
            __t0 = __t2;
        }
        return __t0;
}


