/* generated by tur (phase 2) */
#include "test__runner.h"

static void test__runner___un_unrunner_hyprint(int64_t, int64_t, int64_t);
void test__runner__run_hyall();

static void test__runner___un_unrunner_hyprint(int64_t n, int64_t p, int64_t f) {
        #include <stdio.h>
  printf("1..%lld\n", (long long)n);
  if (f == 0)
    fprintf(stderr, "# All %lld tests passed.\n", (long long)p);
  else
    fprintf(stderr, "# %lld passed, %lld failed.\n",
            (long long)p, (long long)f);
  
}

void test__runner__run_hyall() {
        test__runner___un_unrunner_hyprint(test__suite____ts(INT64_C(4)), test__suite____ts(INT64_C(0)), test__suite____ts(INT64_C(2)));
}


