/* generated by tur (phase 2) */
#ifndef TUR_rtmidi__in_H
#define TUR_rtmidi__in_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void * rtmidi__in__midi_hyin_hyopen(int64_t, int64_t, const char *);
void * rtmidi__in__midi_hyin_hyopen_hyvirtual(int64_t, const char *);
void rtmidi__in__midi_hyin_hyclose(int64_t);
void rtmidi__in__midi_hyin_hyset_hycallback(int64_t, int64_t);
void rtmidi__in__midi_hyin_hycancel_hycallback(int64_t);
void rtmidi__in__midi_hyin_hyignore_hytypes(int64_t, bool, bool, bool);
#endif /* TUR_rtmidi__in_H */
