/* generated by tur (phase 2) */
#ifndef TUR_rtmidi__core_H
#define TUR_rtmidi__core_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void * rtmidi__core__midi_hyin_hynew(const char *);
void * rtmidi__core__midi_hyout_hynew(const char *);
void rtmidi__core__midi_hyin_hyfree(int64_t);
void rtmidi__core__midi_hyout_hyfree(int64_t);
int64_t rtmidi__core__midi_hyin_hyport_hycount(int64_t);
int64_t rtmidi__core__midi_hyout_hyport_hycount(int64_t);
const char * rtmidi__core__midi_hyin_hyport_hyname(int64_t, int64_t);
const char * rtmidi__core__midi_hyout_hyport_hyname(int64_t, int64_t);
#endif /* TUR_rtmidi__core_H */
