/* generated by tur (phase 2) */
#include "rtmidi__out.h"

static void * rtmidi__out____ok(int64_t);
static void * rtmidi__out____err(int64_t);
void * rtmidi__out__midi_out_open(int64_t, int64_t, const char *);
void * rtmidi__out__midi_out_open_virtual(int64_t, const char *);
void rtmidi__out__midi_out_close(int64_t);
void * rtmidi__out__midi_out_send(int64_t, const char *, int64_t);

static void * rtmidi__out____ok(int64_t v) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = true; r->ok_val = v; r->err_val = 0; return r;
  
}

static void * rtmidi__out____err(int64_t e) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = false; r->ok_val = 0; r->err_val = e; return r;
  
}

void * rtmidi__out__midi_out_open(int64_t mo, int64_t i, const char * name) {
        #include <stdlib.h>
  #include <rtmidi/rtmidi_c.h>
  rtmidi_open_port((RtMidiPtr)(intptr_t)mo, (unsigned int)i, (const char*)name);
  RtMidiPtr ptr = (RtMidiPtr)(intptr_t)mo;
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  if (ptr->ok) { r->is_ok = true;  r->ok_val = 0; r->err_val = 0; }
  else         { r->is_ok = false; r->ok_val = 0; r->err_val = 0; }
  return r;
  
}

void * rtmidi__out__midi_out_open_virtual(int64_t mo, const char * name) {
        #include <stdlib.h>
  #include <rtmidi/rtmidi_c.h>
  rtmidi_open_virtual_port((RtMidiPtr)(intptr_t)mo, (const char*)name);
  RtMidiPtr ptr = (RtMidiPtr)(intptr_t)mo;
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  if (ptr->ok) { r->is_ok = true;  r->ok_val = 0; r->err_val = 0; }
  else         { r->is_ok = false; r->ok_val = 0; r->err_val = 0; }
  return r;
  
}

void rtmidi__out__midi_out_close(int64_t mo) {
        #include <rtmidi/rtmidi_c.h>
  rtmidi_close_port((RtMidiPtr)(intptr_t)mo);
  
}

void * rtmidi__out__midi_out_send(int64_t mo, const char * bytes, int64_t len) {
        #include <stdlib.h>
  #include <rtmidi/rtmidi_c.h>
  int rc = rtmidi_out_send_message((RtMidiOutPtr)(intptr_t)mo,
                                   (const unsigned char*)bytes,
                                   (size_t)len);
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  if (rc == 0) { r->is_ok = true;  r->ok_val = 0; r->err_val = 0; }
  else         { r->is_ok = false; r->ok_val = 0; r->err_val = 0; }
  return r;
  
}


