/* generated by tur (phase 2) */
#include "rtmidi__core.h"

static void * rtmidi__core____ok(int64_t);
static void * rtmidi__core____err(int64_t);
static int64_t rtmidi__core____parse_midi_api(const char *);
void * rtmidi__core__midi_in_new(const char *);
void * rtmidi__core__midi_out_new(const char *);
void rtmidi__core__midi_in_free(int64_t);
void rtmidi__core__midi_out_free(int64_t);
int64_t rtmidi__core__midi_in_port_count(int64_t);
int64_t rtmidi__core__midi_out_port_count(int64_t);
const char * rtmidi__core__midi_in_port_name(int64_t, int64_t);
const char * rtmidi__core__midi_out_port_name(int64_t, int64_t);

static void * rtmidi__core____ok(int64_t v) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = true; r->ok_val = v; r->err_val = 0; return r;
  
}

static void * rtmidi__core____err(int64_t e) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = false; r->ok_val = 0; r->err_val = e; return r;
  
}

static int64_t rtmidi__core____parse_midi_api(const char * api) {
        #include <string.h>
  #include <rtmidi/rtmidi_c.h>
  rtmidi_api_t api_val = RTMIDI_API_UNSPECIFIED;
  if (strcmp((const char*)api, ":alsa") == 0)       api_val = RTMIDI_API_LINUX_ALSA;
  else if (strcmp((const char*)api, ":core-midi") == 0) api_val = RTMIDI_API_MACOSX_CORE;
  else if (strcmp((const char*)api, ":winmm") == 0) api_val = RTMIDI_API_WINDOWS_MM;
  else if (strcmp((const char*)api, ":jack") == 0)  api_val = RTMIDI_API_UNIX_JACK;
  else if (strcmp((const char*)api, ":dummy") == 0) api_val = RTMIDI_API_DUMMY;
  return (int64_t)api_val;
  
}

void * rtmidi__core__midi_in_new(const char * api) {
        #include <stdlib.h>
  #include <rtmidi/rtmidi_c.h>
  rtmidi_api_t api_val = (rtmidi_api_t)(__parse_midi_api(api));
  RtMidiInPtr mi = rtmidi_in_create(api_val, "Turmeric", 100);
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  if (mi != NULL && mi->ok) {
    r->is_ok = true; r->ok_val = (int64_t)(intptr_t)mi; r->err_val = 0;
  } else {
    if (mi) rtmidi_in_free(mi);
    r->is_ok = false; r->ok_val = 0; r->err_val = 0;
  }
  return r;
  
}

void * rtmidi__core__midi_out_new(const char * api) {
        #include <stdlib.h>
  #include <rtmidi/rtmidi_c.h>
  rtmidi_api_t api_val = (rtmidi_api_t)(__parse_midi_api(api));
  RtMidiOutPtr mo = rtmidi_out_create(api_val, "Turmeric");
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  if (mo != NULL && mo->ok) {
    r->is_ok = true; r->ok_val = (int64_t)(intptr_t)mo; r->err_val = 0;
  } else {
    if (mo) rtmidi_out_free(mo);
    r->is_ok = false; r->ok_val = 0; r->err_val = 0;
  }
  return r;
  
}

void rtmidi__core__midi_in_free(int64_t mi) {
        #include <rtmidi/rtmidi_c.h>
  rtmidi_in_free((RtMidiInPtr)(intptr_t)mi);
  
}

void rtmidi__core__midi_out_free(int64_t mo) {
        #include <rtmidi/rtmidi_c.h>
  rtmidi_out_free((RtMidiOutPtr)(intptr_t)mo);
  
}

int64_t rtmidi__core__midi_in_port_count(int64_t mi) {
        #include <rtmidi/rtmidi_c.h>
  return (int64_t)rtmidi_get_port_count((RtMidiPtr)(intptr_t)mi);
  
}

int64_t rtmidi__core__midi_out_port_count(int64_t mo) {
        #include <rtmidi/rtmidi_c.h>
  return (int64_t)rtmidi_get_port_count((RtMidiPtr)(intptr_t)mo);
  
}

const char * rtmidi__core__midi_in_port_name(int64_t mi, int64_t i) {
        #include <rtmidi/rtmidi_c.h>
  int len = 0;
  return (char*)rtmidi_get_port_name((RtMidiPtr)(intptr_t)mi, (unsigned int)i, NULL, &len);
  
}

const char * rtmidi__core__midi_out_port_name(int64_t mo, int64_t i) {
        #include <rtmidi/rtmidi_c.h>
  int len = 0;
  return (char*)rtmidi_get_port_name((RtMidiPtr)(intptr_t)mo, (unsigned int)i, NULL, &len);
  
}


