/* generated by tur (phase 2) */
#include "rtmidi__msg.h"

int64_t rtmidi__msg__msg_note_on(int64_t, int64_t, int64_t);
int64_t rtmidi__msg__msg_note_off(int64_t, int64_t, int64_t);
int64_t rtmidi__msg__msg_control_change(int64_t, int64_t, int64_t);
int64_t rtmidi__msg__msg_program_change(int64_t, int64_t);
int64_t rtmidi__msg__msg_pitch_bend(int64_t, int64_t, int64_t);
int64_t rtmidi__msg__msg_aftertouch(int64_t, int64_t);
int64_t rtmidi__msg__msg_poly_aftertouch(int64_t, int64_t, int64_t);
int64_t rtmidi__msg__msg_sysex(const char *, int64_t);
int64_t rtmidi__msg__msg_status(int64_t);
int64_t rtmidi__msg__msg_channel(int64_t);
int64_t rtmidi__msg__msg_data1(int64_t);
int64_t rtmidi__msg__msg_data2(int64_t);
const char * rtmidi__msg__msg_bytes(int64_t);
int64_t rtmidi__msg__msg_len(int64_t);
void rtmidi__msg__msg_free(int64_t);

int64_t rtmidi__msg__msg_note_on(int64_t channel, int64_t note, int64_t velocity) {
        #include <stdlib.h>
  struct __midi_msg { unsigned char *bytes; int len; };
  struct __midi_msg *m = (struct __midi_msg*)malloc(sizeof(struct __midi_msg));
  m->bytes = (unsigned char*)malloc(3);
  m->bytes[0] = (unsigned char)(0x90 | (channel & 0x0F));
  m->bytes[1] = (unsigned char)(note     & 0x7F);
  m->bytes[2] = (unsigned char)(velocity & 0x7F);
  m->len = 3;
  return (int64_t)(intptr_t)m;
  
}

int64_t rtmidi__msg__msg_note_off(int64_t channel, int64_t note, int64_t velocity) {
        #include <stdlib.h>
  struct __midi_msg { unsigned char *bytes; int len; };
  struct __midi_msg *m = (struct __midi_msg*)malloc(sizeof(struct __midi_msg));
  m->bytes = (unsigned char*)malloc(3);
  m->bytes[0] = (unsigned char)(0x80 | (channel & 0x0F));
  m->bytes[1] = (unsigned char)(note     & 0x7F);
  m->bytes[2] = (unsigned char)(velocity & 0x7F);
  m->len = 3;
  return (int64_t)(intptr_t)m;
  
}

int64_t rtmidi__msg__msg_control_change(int64_t channel, int64_t cc, int64_t value) {
        #include <stdlib.h>
  struct __midi_msg { unsigned char *bytes; int len; };
  struct __midi_msg *m = (struct __midi_msg*)malloc(sizeof(struct __midi_msg));
  m->bytes = (unsigned char*)malloc(3);
  m->bytes[0] = (unsigned char)(0xB0 | (channel & 0x0F));
  m->bytes[1] = (unsigned char)(cc    & 0x7F);
  m->bytes[2] = (unsigned char)(value & 0x7F);
  m->len = 3;
  return (int64_t)(intptr_t)m;
  
}

int64_t rtmidi__msg__msg_program_change(int64_t channel, int64_t program) {
        #include <stdlib.h>
  struct __midi_msg { unsigned char *bytes; int len; };
  struct __midi_msg *m = (struct __midi_msg*)malloc(sizeof(struct __midi_msg));
  m->bytes = (unsigned char*)malloc(2);
  m->bytes[0] = (unsigned char)(0xC0 | (channel & 0x0F));
  m->bytes[1] = (unsigned char)(program & 0x7F);
  m->len = 2;
  return (int64_t)(intptr_t)m;
  
}

int64_t rtmidi__msg__msg_pitch_bend(int64_t channel, int64_t lsb, int64_t msb) {
        #include <stdlib.h>
  struct __midi_msg { unsigned char *bytes; int len; };
  struct __midi_msg *m = (struct __midi_msg*)malloc(sizeof(struct __midi_msg));
  m->bytes = (unsigned char*)malloc(3);
  m->bytes[0] = (unsigned char)(0xE0 | (channel & 0x0F));
  m->bytes[1] = (unsigned char)(lsb & 0x7F);
  m->bytes[2] = (unsigned char)(msb & 0x7F);
  m->len = 3;
  return (int64_t)(intptr_t)m;
  
}

int64_t rtmidi__msg__msg_aftertouch(int64_t channel, int64_t pressure) {
        #include <stdlib.h>
  struct __midi_msg { unsigned char *bytes; int len; };
  struct __midi_msg *m = (struct __midi_msg*)malloc(sizeof(struct __midi_msg));
  m->bytes = (unsigned char*)malloc(2);
  m->bytes[0] = (unsigned char)(0xD0 | (channel & 0x0F));
  m->bytes[1] = (unsigned char)(pressure & 0x7F);
  m->len = 2;
  return (int64_t)(intptr_t)m;
  
}

int64_t rtmidi__msg__msg_poly_aftertouch(int64_t channel, int64_t note, int64_t pressure) {
        #include <stdlib.h>
  struct __midi_msg { unsigned char *bytes; int len; };
  struct __midi_msg *m = (struct __midi_msg*)malloc(sizeof(struct __midi_msg));
  m->bytes = (unsigned char*)malloc(3);
  m->bytes[0] = (unsigned char)(0xA0 | (channel & 0x0F));
  m->bytes[1] = (unsigned char)(note     & 0x7F);
  m->bytes[2] = (unsigned char)(pressure & 0x7F);
  m->len = 3;
  return (int64_t)(intptr_t)m;
  
}

int64_t rtmidi__msg__msg_sysex(const char * bytes, int64_t len) {
        #include <stdlib.h>
  #include <string.h>
  struct __midi_msg { unsigned char *bytes; int len; };
  struct __midi_msg *m = (struct __midi_msg*)malloc(sizeof(struct __midi_msg));
  int total = (int)len + 2;
  m->bytes = (unsigned char*)malloc((size_t)total);
  m->bytes[0] = 0xF0;
  memcpy(m->bytes + 1, (const void*)bytes, (size_t)len);
  m->bytes[total - 1] = 0xF7;
  m->len = total;
  return (int64_t)(intptr_t)m;
  
}

int64_t rtmidi__msg__msg_status(int64_t m) {
        struct __midi_msg { unsigned char *bytes; int len; };
  return (int64_t)(((struct __midi_msg*)(intptr_t)m)->bytes[0] & 0xF0);
  
}

int64_t rtmidi__msg__msg_channel(int64_t m) {
        struct __midi_msg { unsigned char *bytes; int len; };
  return (int64_t)(((struct __midi_msg*)(intptr_t)m)->bytes[0] & 0x0F);
  
}

int64_t rtmidi__msg__msg_data1(int64_t m) {
        struct __midi_msg { unsigned char *bytes; int len; };
  return (int64_t)(((struct __midi_msg*)(intptr_t)m)->bytes[1]);
  
}

int64_t rtmidi__msg__msg_data2(int64_t m) {
        struct __midi_msg { unsigned char *bytes; int len; };
  return (int64_t)(((struct __midi_msg*)(intptr_t)m)->bytes[2]);
  
}

const char * rtmidi__msg__msg_bytes(int64_t m) {
        struct __midi_msg { unsigned char *bytes; int len; };
  return (char*)((struct __midi_msg*)(intptr_t)m)->bytes;
  
}

int64_t rtmidi__msg__msg_len(int64_t m) {
        struct __midi_msg { unsigned char *bytes; int len; };
  return (int64_t)((struct __midi_msg*)(intptr_t)m)->len;
  
}

void rtmidi__msg__msg_free(int64_t m) {
        #include <stdlib.h>
  struct __midi_msg { unsigned char *bytes; int len; };
  struct __midi_msg *msg = (struct __midi_msg*)(intptr_t)m;
  free(msg->bytes);
  free(msg);
  
}


