/* generated by tur (phase 2) */
#ifndef TUR_rtmidi__core_H
#define TUR_rtmidi__core_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void * rtmidi__core__midi_in_new(const char *);
void * rtmidi__core__midi_out_new(const char *);
void rtmidi__core__midi_in_free(int64_t);
void rtmidi__core__midi_out_free(int64_t);
int64_t rtmidi__core__midi_in_port_count(int64_t);
int64_t rtmidi__core__midi_out_port_count(int64_t);
const char * rtmidi__core__midi_in_port_name(int64_t, int64_t);
const char * rtmidi__core__midi_out_port_name(int64_t, int64_t);
#endif /* TUR_rtmidi__core_H */
