/* generated by tur (phase 2) */
#ifndef TUR_rtmidi__out_H
#define TUR_rtmidi__out_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void * rtmidi__out__midi_out_open(int64_t, int64_t, const char *);
void * rtmidi__out__midi_out_open_virtual(int64_t, const char *);
void rtmidi__out__midi_out_close(int64_t);
void * rtmidi__out__midi_out_send(int64_t, const char *, int64_t);
#endif /* TUR_rtmidi__out_H */
