/* generated by tur (phase 2) */
#ifndef TUR_rtaudio__core_H
#define TUR_rtaudio__core_H

#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void * rtaudio__core__audio_hynew(const char *);
void rtaudio__core__audio_hyfree(int64_t);
const char * rtaudio__core__audio_hyapi(int64_t);
#endif /* TUR_rtaudio__core_H */
