/* generated by tur (phase 2) */
#include "rtaudio__devices.h"

static int64_t rtaudio__devices____nil();
static int64_t rtaudio__devices____cons(int64_t, int64_t);
int64_t rtaudio__devices__device_hycount(int64_t);
int64_t rtaudio__devices__device_hyinfo(int64_t, int64_t);
const char * rtaudio__devices__device_hyinfo_hyname(int64_t);
int64_t rtaudio__devices__device_hyinfo_hyoutput_hychans(int64_t);
int64_t rtaudio__devices__device_hyinfo_hyinput_hychans(int64_t);
int64_t rtaudio__devices__device_hyinfo_hysample_hyrates(int64_t);
int64_t rtaudio__devices__device_hydefault_hyoutput(int64_t);
int64_t rtaudio__devices__device_hydefault_hyinput(int64_t);
void rtaudio__devices__device_hyinfo_hyfree(int64_t);

static int64_t rtaudio__devices____nil() {
        return 0;
  
}

static int64_t rtaudio__devices____cons(int64_t v, int64_t n) {
        #include <stdlib.h>
  struct { int64_t value; int64_t next; } *cell = malloc(sizeof(*cell));
  cell->value = v; cell->next = n;
  return (int64_t)(intptr_t)cell;
  
}

int64_t rtaudio__devices__device_hycount(int64_t a) {
        #include <rtaudio/rtaudio_c.h>
  return (int64_t)rtaudio_device_count((rtaudio_t)(intptr_t)a);
  
}

int64_t rtaudio__devices__device_hyinfo(int64_t a, int64_t id) {
        #include <stdlib.h>
  #include <string.h>
  #include <rtaudio/rtaudio_c.h>
  struct __dev_info {
    char         *name;
    unsigned int  output_chans;
    unsigned int  input_chans;
    int64_t       sample_rates;
  };
  rtaudio_device_info_t info = rtaudio_get_device_info((rtaudio_t)(intptr_t)a, (unsigned int)id);
  struct __dev_info *di = (struct __dev_info*)malloc(sizeof(struct __dev_info));
  di->name         = strdup(info.name);
  di->output_chans = info.output_channels;
  di->input_chans  = info.input_channels;
  int64_t rates = 0;
  for (unsigned int i = info.num_sample_rates; i-- > 0;) {
    struct { int64_t value; int64_t next; } *cell = malloc(sizeof(*cell));
    cell->value = (int64_t)info.sample_rates[i];
    cell->next  = rates;
    rates = (int64_t)(intptr_t)cell;
  }
  di->sample_rates = rates;
  return (int64_t)(intptr_t)di;
  
}

const char * rtaudio__devices__device_hyinfo_hyname(int64_t di) {
        struct __dev_info { char *name; unsigned int output_chans; unsigned int input_chans; int64_t sample_rates; };
  return ((struct __dev_info*)(intptr_t)di)->name;
  
}

int64_t rtaudio__devices__device_hyinfo_hyoutput_hychans(int64_t di) {
        struct __dev_info { char *name; unsigned int output_chans; unsigned int input_chans; int64_t sample_rates; };
  return (int64_t)((struct __dev_info*)(intptr_t)di)->output_chans;
  
}

int64_t rtaudio__devices__device_hyinfo_hyinput_hychans(int64_t di) {
        struct __dev_info { char *name; unsigned int output_chans; unsigned int input_chans; int64_t sample_rates; };
  return (int64_t)((struct __dev_info*)(intptr_t)di)->input_chans;
  
}

int64_t rtaudio__devices__device_hyinfo_hysample_hyrates(int64_t di) {
        struct __dev_info { char *name; unsigned int output_chans; unsigned int input_chans; int64_t sample_rates; };
  return ((struct __dev_info*)(intptr_t)di)->sample_rates;
  
}

int64_t rtaudio__devices__device_hydefault_hyoutput(int64_t a) {
        #include <rtaudio/rtaudio_c.h>
  return (int64_t)rtaudio_get_default_output_device((rtaudio_t)(intptr_t)a);
  
}

int64_t rtaudio__devices__device_hydefault_hyinput(int64_t a) {
        #include <rtaudio/rtaudio_c.h>
  return (int64_t)rtaudio_get_default_input_device((rtaudio_t)(intptr_t)a);
  
}

void rtaudio__devices__device_hyinfo_hyfree(int64_t di) {
        #include <stdlib.h>
  struct __dev_info { char *name; unsigned int output_chans; unsigned int input_chans; int64_t sample_rates; };
  struct __dev_info *d = (struct __dev_info*)(intptr_t)di;
  free(d->name);
  struct { int64_t value; int64_t next; } *cell =
      (struct { int64_t value; int64_t next; } *)(intptr_t)d->sample_rates;
  while (cell) {
    struct { int64_t value; int64_t next; } *next =
        (struct { int64_t value; int64_t next; } *)(intptr_t)cell->next;
    free(cell);
    cell = next;
  }
  free(d);
  
}


