/* generated by tur (phase 2) */
#include "rtaudio__stream.h"

static void * rtaudio__stream____ok(int64_t);
static void * rtaudio__stream____err(int64_t);
void * rtaudio__stream__stream_hyopen(int64_t, int64_t, int64_t, int64_t, int64_t, const char *, int64_t, int64_t, int64_t);
void * rtaudio__stream__stream_hystart(int64_t);
void rtaudio__stream__stream_hystop(int64_t);
void rtaudio__stream__stream_hyclose(int64_t);
int64_t rtaudio__stream__stream_hylatency(int64_t);
int64_t rtaudio__stream__stream_hysample_hyrate(int64_t);

static void * rtaudio__stream____ok(int64_t v) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = true; r->ok_val = v; r->err_val = 0; return r;
  
}

static void * rtaudio__stream____err(int64_t e) {
        #include <stdlib.h>
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  r->is_ok = false; r->ok_val = 0; r->err_val = e; return r;
  
}

void * rtaudio__stream__stream_hyopen(int64_t a, int64_t out_device, int64_t out_chans, int64_t in_device, int64_t in_chans, const char * format, int64_t sample_rate, int64_t buf_frames, int64_t callback) {
        #include <stdlib.h>
  #include <string.h>
  #include <rtaudio/rtaudio_c.h>
  rtaudio_format_t fmt = RTAUDIO_FORMAT_FLOAT32;
  if (strcmp((const char*)format, ":int16") == 0)        fmt = RTAUDIO_FORMAT_SINT16;
  else if (strcmp((const char*)format, ":int32") == 0)   fmt = RTAUDIO_FORMAT_SINT32;
  else if (strcmp((const char*)format, ":float32") == 0) fmt = RTAUDIO_FORMAT_FLOAT32;
  else if (strcmp((const char*)format, ":float64") == 0) fmt = RTAUDIO_FORMAT_FLOAT64;
  rtaudio_stream_parameters_t out_params;
  rtaudio_stream_parameters_t in_params;
  rtaudio_stream_parameters_t *out_ptr = NULL;
  rtaudio_stream_parameters_t *in_ptr  = NULL;
  if (out_chans > 0) {
    out_params.device_id    = (unsigned int)out_device;
    out_params.num_channels = (unsigned int)out_chans;
    out_params.first_channel = 0;
    out_ptr = &out_params;
  }
  if (in_chans > 0) {
    in_params.device_id    = (unsigned int)in_device;
    in_params.num_channels = (unsigned int)in_chans;
    in_params.first_channel = 0;
    in_ptr = &in_params;
  }
  unsigned int frames = (unsigned int)buf_frames;
  int rc = rtaudio_open_stream((rtaudio_t)(intptr_t)a,
                               out_ptr, in_ptr,
                               fmt, (unsigned int)sample_rate,
                               &frames,
                               (rtaudio_cb_t)(intptr_t)callback,
                               NULL, NULL, NULL);
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  if (rc == 0) { r->is_ok = true;  r->ok_val = 0; r->err_val = 0; }
  else         { r->is_ok = false; r->ok_val = 0; r->err_val = 0; }
  return r;
  
}

void * rtaudio__stream__stream_hystart(int64_t a) {
        #include <stdlib.h>
  #include <rtaudio/rtaudio_c.h>
  int rc = rtaudio_start_stream((rtaudio_t)(intptr_t)a);
  struct { bool is_ok; int64_t ok_val; int64_t err_val; } *r = malloc(sizeof(*r));
  if (rc == 0) { r->is_ok = true;  r->ok_val = 0; r->err_val = 0; }
  else         { r->is_ok = false; r->ok_val = 0; r->err_val = 0; }
  return r;
  
}

void rtaudio__stream__stream_hystop(int64_t a) {
        #include <rtaudio/rtaudio_c.h>
  rtaudio_stop_stream((rtaudio_t)(intptr_t)a);
  
}

void rtaudio__stream__stream_hyclose(int64_t a) {
        #include <rtaudio/rtaudio_c.h>
  rtaudio_close_stream((rtaudio_t)(intptr_t)a);
  
}

int64_t rtaudio__stream__stream_hylatency(int64_t a) {
        #include <rtaudio/rtaudio_c.h>
  return (int64_t)rtaudio_get_stream_latency((rtaudio_t)(intptr_t)a);
  
}

int64_t rtaudio__stream__stream_hysample_hyrate(int64_t a) {
        #include <rtaudio/rtaudio_c.h>
  return (int64_t)rtaudio_get_stream_sample_rate((rtaudio_t)(intptr_t)a);
  
}


